### ISSUE TITLE
view query generates only one result 

### ISSUE THREAD

**Issue by yechongbo** [pouchdb/pouchdb#3782] opened 2015-05-02 17:49 UTC
Hi,

I am working on a cordova project with msopentech websql as the sqlite plugin and pouch 3.4.0 as the data access. The problem I am facing right now is, when querying views, it retrieves only single result even there are multiple documents with given doc id in database. Really don't understand what's going on under the hood. Please advise, thank you!

**Comment by nolanlawson** [comment] 2015-05-02 18:29
Have you tried not using the SQLite Plugin? It's shown some instability recently and isn't currently passing the PouchDB test suite...

**Comment by yechongbo** [comment] 2015-05-02 18:39
yes, it works perfectly without SQLite Plugin.

**Comment by nolanlawson** [comment] 2015-05-02 22:35
This is a bug on the SQLite Plugin then. Gonna resolve as a duplicate of https://github.com/litehelpers/Cordova-sqlite-storage/issues/255

**Comment by nolanlawson** [comment] 2015-05-02 22:35
BTW which phone were you testing on? iOS or Android, and which version?

**Closed by nolanlawson** 2015-05-02 22:35 UTC

**Comment by yechongbo** [comment] 2015-05-03 03:41
it's windows store app actually, it works just fine on iOS and Android so far. After inspecting the database file, i found that this problem is caused by incorrect number of documents in doc store table of automatically generated database for view index. it stores only a single record for same doc id emitted by view. by comparing with android, which i think is correct, it does store multiple records for same doc id with different json content, and the only difference is the column data type for doc id, which is blob on android and string on windows. need to figure out how could this happen. 

Thanks for the reply

**Comment by front-a-little** [comment] 2015-06-02 06:58
Were you able to fix it on windows store app ?

**Comment by yechongbo** [comment] 2015-06-02 12:23
somehow fixed, not by code itself, but to make sure the views are emitted with unique key for any single document. after that, query view documents by both startKey and endKey.
