### ISSUE TITLE
indexed_db_went_bad

### ISSUE THREAD

**Issue by bsuyog16** [pouchdb/pouchdb#7027] opened 2018-01-19 07:21 UTC
### Issue
I am using db.putAttachment(fileId, fileName, fileBlob, fileType)  API of pouchdb to put attachment . It is working on chrome browser without any error but when I am running on android device. Its giving error.

```

    this.db.putAttachment(fileId, fileName, fileBlob, fileType).then(function (result) {
      console.log("result", result);
    }).catch(function (err) {
      console.log(err);
    });

  // fileName and fileType variables values I am fetching from fileBlob only
   // here is my fileBlob object:
    File(108255) { name: "imageArticle_0zcz.jpg", lastModified: 1515824411531, lastModifiedDate: Sat Jan 13 2018 11: 50: 11 GMT + 0530(IST), webkitRelativePath: "", size: 108255, … }
    lastModified:1515824411531
    lastModifiedDate:Sat Jan 13 2018 11: 50: 11 GMT + 0530(IST) { }
    name:"imageArticle_0zcz.jpg"
    size:108255
    type:"image/jpeg"
    webkitRelativePath:""
    __proto__:File
```

Error:
`CustomPouchError {status: 500, name: "indexed_db_went_bad", message: "unknown", error: true, reason: "DataError", …}
`
### Info
- Environment: Node => 8.9.3 , Ionic =>3.19.0
- Platform: Android
- Adapter: IndexedDB
- Server: PouchDB 

### Reproduce

test.html 
```

<ion-content padding>
  <ion-list>
    <ion-label >Attach file</ion-label>
    <ion-item>
      <input type="file" (change)="handleFileSelect($event)">
    </ion-item>
  </ion-list>

  <ion-row>
    <ion-col>
      <button ion-button class="btn-primary-color" block tappable icon-left (click)="setNoteDetails()">
    <ion-icon name="checkmark"></ion-icon> Add Note
      </button>
    </ion-col>
  </ion-row>
</ion-content>
```

test.ts

 ```
 private filetype;
  private fileName;
  private blobFile;
  	
 handleFileSelect(evt) {
   var files = evt.target.files;
   this.blobFile = files[0];
   console.log("file ",this.blobFile);
   this.filetype = files[0].type;
   this.fileName = files[0].name;
 }

 setNoteDetails() {
    this.db.putAttachment("test", this.fileName, this.blobFile, this.fileType).then(function (result) {
      console.log("result", result);
    }).catch(function (err) {
      console.log(err);
    });
 }
```

You can build an apk in debug mode and test it in android device. While debugging using chrome browser chrome:// inspect you will see error in console.

Kindly help.

**Comment by daleharvey** [comment] 2018-01-21 13:57
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/6985, they seem to have the same problem of attachments on android which I cant reproduce, if you could reply in there it would be great thanks

**Closed by daleharvey** 2018-01-21 13:57 UTC
