### ISSUE TITLE
IDB DOMException apparently not caused by destroy()

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3802] opened 2015-05-06 12:17 UTC
Another interesting data point:

```
Uncaught (in promise) DOMException: 
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. {message: "Failed to execute 'transaction' on 'IDBDatabase': 
The database connection is closing.", name: "InvalidStateError", code: 11, 
stack: "Error: Failed to execute 'transaction' on 'IDBData…ss (http://x.example.com/jav.js:352:56)", INDEX_SIZE_ERR: 1…}n.openTransactionSafely @ pouchdb-3.3.1.min.js:7e._get @ pouchdb-3.3.1.min.js:8(anonymous function) @ pouchdb-3.3.1.min.js:7(anonymous function) @ pouchdb-3.3.1.min.js:10(anonymous function) @ pouchdb-3.3.1.min.js:10(anonymous function) @ pouchdb-3.3.1.min.js:10(anonymous function) @ pouchdb-3.3.1.min.js:10(anonymous function) @ pouchdb-3.3.1.min.js:10$.ajax.success @ jav.js:352j @ jquery.js:3094k.fireWith @ jquery.js:3206x @ jquery.js:8259k.cors.a.crossDomain.send.b @ jquery.js:8600
```

Apparently the author managed to reproduce this in Chrome without using `destroy()`. See [this SO question](http://stackoverflow.com/questions/30069878/pouchdb-transaction-error/30076385#30076385) for details.

**Comment by nolanlawson** [comment] 2015-05-06 12:17
Tried to repro in Chrome 42 and could not ^.

**Comment by fma-technologies** [comment] 2015-05-07 02:27
@nolanlawson Thank you very much for your reply on SO. As requested I have supplied a live test case to reproduce (though the problem is very intermittent). I have just sent you an e-mail.

**Comment by andru** [comment] 2015-05-08 22:32
FYI I'm also hitting this without using `destroy()`, but so far I've not been able to reproduce a test case outside of the context of my application.  Once it happens, I get this message for every `put`.

**Comment by nolanlawson** [comment] 2015-05-09 00:26
@andru Do you only see it in Chrome as well? Never seen this reported in Firefox so far.

**Comment by andru** [comment] 2015-05-10 09:24
I've not happened upon it during testing in Firefox, but since I do most of my dev work with Chrome the odds are skewed. I'll switch to Firefox DE for a while.

**Comment by daleharvey** [comment] 2015-11-14 01:17
Few months, hasnt been reported and cant reproduce, closing some of these old ones out, please reopen if there is indication this is still a bug

**Closed by daleharvey** 2015-11-14 01:17 UTC
Labels: bug

**Comment by jamesmfriedman** [comment] 2021-08-05 03:52
This bug is killing me years later in production, and I'm running out of ideas.

Sentry is filling up with these errors on mobile devices, but I never see them locally myself. The failures appear to happen at random times with no clear indication as to what is causing them.

I've found lots of mentions of this issue in other threads unrelated to PouchDB, but in all cases people seemed pretty desperate. The best info I've gotten is hard restarting the app. Once this error is hit, there is NO recovering from it. Pouch will refuse to do anything with that local database. I can even create a new PouchDB locally with the same name (presuming it uses a new indexedDb request under the hood) and it will continue to fail.

**Comment by dheimoz** [comment] 2021-08-05 19:12
hey @jamesmfriedman, so this exact error is happening with the latest Pouchdb version?
Thanks
