### ISSUE TITLE
There was not enough remaining storage space in Cordova App

### ISSUE THREAD

**Issue by ScreenDriver** [pouchdb/pouchdb#3505] opened 2015-02-05 15:58 UTC
I am using Apache Cordova to build my app. I installed PouchDB and, as explained [here],(http://pouchdb.com/adapters.html) added the SQLite Plugin.
New instances of PouchDB will be created with 

```javascript
new PouchDB('myDB', {adapter: 'websql', size: 10});
```

Unfortunately I get a error if I made some batch (bulk) inserts:
 
```"there was not enough remaining storage space, or the storage quota was reached and the user declined to allow more space"```

I can increase the limit how much I like, it seems to be ignored. I've tested it with a some mock JSON objects with the same size. The first inserts run fine and then when I reach the limit I get this error message. If I increase the size, nothing happens and I still get immediately this exception.

Could it be that the size parameter will be ignored? Or does PouchDB don't use the natively installed SQLite Plugin?

**Comment by nolanlawson** [comment] 2015-02-05 17:06
So it sounds like PouchDB is not actually using the SQLite plugin. You should never see that kind of error if you are using the SQLite plugin.

Another thing is that the `size` parameter is totally ignored if you are using the SQLite plugin. It's only for WebSQL.

Unfortunately it's kind of hard to tell what PouchDB is actually using (open issue somewhere...), but if you use the non-minified code, and then search for `sqlitePlugin`, and set a breakpoint, you should be able to see if PouchDB is actually using the SQLite Plugin. Another way is to check that `window.sqlitePlugin` is actually defined **before** you load PouchDB (so be sure to include the plugin in your `index.html` first).

Another tool: I just created a [PouchDB Cordova guide](https://github.com/nolanlawson/pouchdb-phonegap-cordova) which contains a sample app that actually uses the SQLite plugin (I checked!). So you can compare your code against that and see if it's working.

**Comment by ScreenDriver** [comment] 2015-02-06 10:25
Thank you for your help but I don't get it. I did everything explained [here](https://github.com/nolanlawson/pouchdb-phonegap-cordova) but still the same.
 
```window.sqlitePlugin``` is defined **before** I use PouchDB

the script order is ok
```html
<script src="cordova.js"></script>
<script src="bower_components/pouchdb/dist/pouchdb.js"></script>
```
I added following code
```javascript
var openDBFunction = (typeof navigator !== 'undefined' &&
      navigator.sqlitePlugin &&
      navigator.sqlitePlugin.openDatabase) ?
    navigator.sqlitePlugin.openDatabase.bind(navigator.sqlitePlugin) :
      (typeof sqlitePlugin !== 'undefined' && sqlitePlugin.openDatabase) ?
    sqlitePlugin.openDatabase.bind(sqlitePlugin) :
      (typeof openDatabase !== 'undefined') ?
    openDatabase :
    null;

console.log(navigator.sqlitePlugin);
console.log(typeof sqlitePlugin !== 'undefined');
console.log(typeof openDatabase !== 'undefined');
```
the output is
```javascript
undefined
false
true
```
I think the problem is that PouchDB is not waiting for the ```ondeviceready``` event. I can not find anything in the PouchDB source code that is related to the deviceready event. The code above runs immediately when ```pouchdb.js``` is loaded. It should however run when the device is ready.

By the way: your sample [sample application](https://github.com/nolanlawson/pouchdb-cordova-hello-world-with-sqlite-plugin) does have the same issue: I inserted a lot of data in your ```var websql = new PouchDB('websqlpouch', {adapter: 'websql'});``` and after some time I get the same storage exception.

**Comment by nolanlawson** [comment] 2015-02-06 16:01
Crap, it seems like there's a bug then where we're not actually using the SQLite Plugin because we're not waiting for the onDeviceReady event. Thanks for bringing this up.

**Comment by nolanlawson** [comment] 2015-02-06 16:02
probably this was introduced by me during some refactoring, and of course we didn't notice because the SQLite plugin is not tested by Travis >_<

**Comment by nolanlawson** [comment] 2015-02-06 16:04
As a workaround, you can do:

```js
window.addEventListener('ondeviceready', function () {
  // only load PouchDB when cordova is fully ready
  var script = document.createElement('script');
  script.src ='bower_components/pouchdb/dist/pouchdb.js';
  document.body.appendChild(script);
});
```

**Comment by nolanlawson** [comment] 2015-02-06 16:06
Oh OK, I see the problem. In our integration tests, we explicitly wait for the `'deviceready'` event before doing anything. So I guess we should update the docs?

**Comment by nolanlawson** [comment] 2015-02-06 16:08
FWIW I don't think this can be solved within PouchDB itself, because the websql adapter's `valid()` function is synchronous. So we can't wait for `deviceready`.

**Comment by jfspencer** [comment] 2015-02-06 17:44
Using Ionic/Cordova SQLite plugin I did load testing with pouch using 3.2.0 at the end of December, I could bulk add 100K without error. The sqlite db reached sizes around 1.4GB. my only limitation was the number of docs I could add at one time (100K was about the limit).

Testing again with 3.3.0 I am not able to get the db to go past 50MB . At that size I can restart the app and do one off adds but it silently fails after that, no success or error response. In both tests I did not use the size: x parameter when creating the db.

**Comment by nolanlawson** [comment] 2015-02-06 19:25
Yeah I think the issue is that it's not actually using the SQLite plugin. See my comments above.

**Comment by nolanlawson** [comment] 2015-02-07 16:58
jfspencer: yeah, we introduced a bug since 3.2.0 where we didn't actually use the SQLite Plugin. My bad. In the meantime you can use this [prerelease version](https://raw.githubusercontent.com/nolanlawson/pouchdb-cordova-hello-world-with-sqlite-plugin/6cb705660ba023b6a21a5f0e33d155d85a95d634/www/js/pouchdb-3.3.1-prerelease.js).

**Comment by jfspencer** [comment] 2015-02-07 17:27
@nolanlawson Thanks! I will update to the prerelease.

**Comment by daleharvey** [comment] 2015-02-07 20:45
Fixed in https://github.com/pouchdb/pouchdb/commit/7a7ee7d1dcad2ddfb79baaf4bc00b7d3551df8c4

**Closed by daleharvey** 2015-02-07 20:45 UTC

**Comment by irvins** [comment] 2017-10-06 17:04
I get this error and im using the latest (6.2) version of pouch. 

I see this post is 2 years old and nothing newer references the bug.  

I must have screwed something up big time.   I place my cordova.js before i include my pouch. 

ERROR WRITING TO A DB
status: 500
name: web_sql_went_bad
message: unknown
reason: there was not enough remaining storage space, or the storage quota was reached and the user declined to allow more space
db.type() is deprecated and will be removed in a future version of PouchDB

this is how i start off the app

var db  = new PouchDB(dbname, {iosDatabaseLocation: 'default', auto_compaction: true, adapter: 'cordova-sqlite'});
        if (!db.adapter) {
            console.log("no adapter");
          db = new PouchDB(dbname);
        }
        return db;

any help would be appreciated.
