### ISSUE TITLE
Is it allowed to update the _conflicts array?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5771] opened 2016-10-14 11:45 UTC
I would like to do something like:

```javascript
  _upsert (localDoc) {
    return this.db
      .get(localDoc._id)
      .then(remoteDoc => deepEquals(fromDoc(localDoc), fromDoc(remoteDoc))
        ? remoteDoc._rev
        : this.db
            .put({
              ...localDoc,
              _conflicts: [remoteDoc._rev, ...(remoteDoc._conflicts || [])],
              _rev: remoteDoc._rev
            })
            .catch(err => {
              if (err.status !== 409) {
                throw err
              }
              return this._upsert(localDoc)
            })
      )
  }
```

In order to let my conflict resolution daemon handle any document conflicts. Is there anything inherently wrong with this?

**Comment by daleharvey** [comment] 2016-10-14 15:12
Closing as dupe of https://github.com/pouchdb/pouchdb/issues/5772

**Closed by daleharvey** 2016-10-14 15:12 UTC
