### ISSUE TITLE
Filtered replication ignores _deleted docs

### ISSUE THREAD

**Issue by sphaso** [pouchdb/pouchdb#3578] opened 2015-02-27 13:18 UTC
Hi.            
I'm facing a weird issue using PouchDB 3.3.0. Basically when I set filtered replication using a ddoc the onChange doesn't immediately trigger at load time (but it does without filters!). I have to ctrl+R and then I finally see something.

This is my setup (with the filter parameters commented). I'm not sure if this is a bug or just dumbness on my part. I've seen a PR vaguely related to filtered replication so I thought I'd ask.

```javascript
localDB.sync(remoteDB, {
                        live: true,
                        retry: true
                })
            .changes({
            continuous: true,
            //filter: 'app/by_user',
            //query_params: { agente: agent },
            onChange: function(change){
                $rootScope.$apply(function(){
                    localDB.get(change.id, function(err, doc){
                        console.log("change detected!");
                        if(!change.deleted){
                            $rootScope.$apply(function(){
                                if(err) console.log(err);
                                else {
                                    console.log("broadcast");
                                    $rootScope.$broadcast('upsert', doc);
                                }
                            });
                        }
                        else if(change.deleted){
                            $rootScope.$apply(function(){
                                $rootScope.$broadcast('delete', {_id: change.id});
                            });
                        }
                    });
                });
            }
        });
```

**Comment by nolanlawson** [comment] 2015-02-28 06:20
You can do `include_docs: true` on changes to avoid having to fetch the `doc`.

There's probably a bug with filtered replication. I'll try to look into it when I get a chance!

Another tip: if you are using filtered replication to try to do user security, [you might be doing it wrong](https://github.com/nolanlawson/pouchdb-authentication#couchdb-authentication-recipes), because users can actually still read each other's documents. See that link for details.

**Comment by sphaso** [comment] 2015-02-28 09:28
Thanks for the tip about user security, but the filter is more of a usability solution. It might become a nice workaroud if we can't fix this in time and I get enough HD space.

I'm not sure about the exact behavior of include_docs. From the docs it looks like it actually includes conflicts and attachments, not really my case. Does it ignore filter? (will I have to filter client side? that's not really an option).

**Comment by nolanlawson** [comment] 2015-02-28 14:13
You also need to set `conflicts: true, attachments: true` in order to get conflicts and attachments. :)

You shouldn't need to filter client-side. I'll try to fix this bug.

**Comment by nolanlawson** [comment] 2015-02-28 15:48
Ah okay, I remember now. This is a documentation issue. I've updated the PouchDB web site with a recent fix for the documentation. Now it says:

> `options.view`: Specify a view function (i.e. `'design_doc_name/view_name'`) to act as a filter. Documents counted as "passed" for a view filter if a map function emits at least one record for them. Note: `options.filter` must be set to `'_view'` for this option to work.

Let me know if that helps.

**Comment by nolanlawson** [comment] 2015-02-28 16:08
Oh, and you're also going to need to use the nightly until we release the next one, because there's a fix for filtered replication with ddocs: http://pouchtest.com/nightly

**Comment by sphaso** [comment] 2015-02-28 21:19
Thank you, I'l have a chance to test on Monday. I should also specify that I'm not using a view, but an actual filter. So I don't really have a map\reduce, just a boring function(req, doc) in the ddoc.

**Comment by sphaso** [comment] 2015-03-02 11:57
Back with some news.
I've tried the solution you've proposed by:
- using the nightly (0a523ed)
- changing my "change" options into:

```Javascript
localDB.changes({
            continuous: true,
            view: 'app/by_user',
            filter: '_view',
            query_params: { agente: agent },
```

Outcome: I can see the indexedDB being populated but onChange doesn't trigger, even after repeated ctrl+R.
In case you want to see my ddoc:

```Javascript
{
   "_id": "_design/app",
   "_rev": "1-d5c42302b756548440134e2755aab03d",
   "filters": {
       "by_user": "function(doc, req) { if(doc.Agents && doc.Agents.indexOf(req.query.agente) > -1){ return true; } return false; }"
   }
}
```

**Comment by sphaso** [comment] 2015-03-03 09:12
Day three.
Yesterday I debugged the nightly source the whole day. I've started to have doubts on my setup. Reread the docs for the Nth time and I rewrote it:

```Javascript
   localDB.sync(remoteDB, {
                        live: true,
                        retry: true,
            continuous: true,
            filter: 'app/by_user',
            query_params: { "agente": agent }
        }).on('change', function(change){
                console.log("change detected!");
                $rootScope.$apply(function(){
                    localDB.get(change.id, function(err, doc){
                        if(!change.deleted){
                            $rootScope.$apply(function(){
                                if(err) console.log(err);
                                else {
                                    console.log("broadcast");
                                    $rootScope.$broadcast('upsert', doc);
                                }
                            });
                        }
                        else if(change.deleted){
                            $rootScope.$apply(function(){
                                $rootScope.$broadcast('delete', {_id: change.id});
                            });
                        }
                    });
                });
        });
```

Outcome:
now the IndexedDB is getting populated according to the filter (before I had some documents that shouldn't have passed the filter). However! localDB.get() is throwing an exception which wasn't showing before:

```
CustomPouchError {status: 400, name: "invalid_id", message: "_id field must contain a string", error: true, toString: function}
```

But but but... my docs _id is not a string! I'll give you an example _id: "PDV297858"
After a while things start to get funny in the console:

```Javascript
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.pouchdb.js:9266 EventEmitter.addListenerpouchdb.js:9298 EventEmitter.oncepouchdb.homebrew.js:7308 Replication.readypouchdb.js:7370 replicatepouchdb.homebrew.js:7263 (anonymous function)
```

Increasing the batches_limit option seems to change nothing in this regard.

**Comment by nolanlawson** [comment] 2015-03-03 13:05
So what was the issue?

**Comment by sphaso** [comment] 2015-03-03 13:14
That's a good question. I think that the main issue is that I was running ".changes" on the local (indexedDB) instead of the remote DB.
That sounds like a very derp moment on my part, yet it was working fine until I needed to add a filter. I still believe my above code can (or must) be improved. Why would I have to register a "change" on localDB and then other changes events on remoteDB?

**Comment by nolanlawson** [comment] 2015-03-03 15:35
The EventEmitter thing is a known issue. It's just a warning, and should be harmless.

As for why it's "crashing," that sounds very bad. :( What are you seeing? And are you still using IndexedDB?

**Comment by sphaso** [comment] 2015-03-03 15:44
I am: CouchDB on the server-side, PouchDB default adapter (IndexedDB) client-side. I'm also using LocalStorage to store one key-value pair. The are now two crashes cases:
- one proper crash (seems to have disappeared for now, with no change in code, wot?) is when the sync starts. The app simply exits. When I re-open it it goes back to the first page as if nothing happened (the sync is on the second page)
- one "weird" crash. Sync is fine. I load the app the first time, enter username, it syncs, I see stuff. Yay. I close it, reopen it... white screen of death. From the console I see that it's syncing and everything seems to be running normal. Still investigating this one.

I'd be surprised if the second issue is related to Pouch, but it might have something to do with the way I'm instructing the sync. What do you think about the code I pasted? I'll repaste here for comfort:

```Javascript
localDB.sync(remoteDB, {
            live: true,
            retry: true,
            filter: 'app/by_user',
            query_params: { "agente": agent }
        })
        .on('change', function(result){
                console.log("change");
                result.change.docs.forEach(function(change) {
                    $rootScope.$apply(function(){
                        $rootScope.$broadcast('upsert', change);
                    });
                });
        });

        remoteDB.changes({
                    continuous: true,
                    filter: 'app/by_user',
                    query_params: { "agente": agent }
                })
               .on('create', function(info){
                            console.log("create");
                            $rootScope.$apply(function(){
                                localDB.get(info.id, function(err, doc){                                                                                                 $rootScope.$apply(function(){
                                        if(err) console.log(err);
                                        else {
                                            $rootScope.$broadcast('upsert', doc);
                                        }
                                    });
                                });
                            });
                        })
                 .on('update', function(info){
                    console.log("update");
                    $rootScope.$apply(function(){
                        localDB.get(info.id, function(err, doc){                                                                                                 $rootScope.$apply(function(){
                                if(err) console.log(err);
                                else {
                                    $rootScope.$broadcast('upsert', doc);
                                }
                            });
                        });
                    });
                })
                 .on('delete', function(info){
                    console.log("delete");
                    $rootScope.$apply(function(){
                            $rootScope.$broadcast('delete', {_id: info.id});
                        });
                });
```
Thank you for your help so far. I'm pretty green to the whole stack (Couch, ionic, cordova...) so don't assume I'm not making any silly mistake.

**Comment by nolanlawson** [comment] 2015-03-03 16:33
Hmm, your code looks okay to me, although all the `$rootScope.apply` may be slowing it down. You might want to look into the pattern discussed in [this blog post](http://pouchdb.com/2015/02/28/efficiently-managing-ui-state-in-pouchdb.html) for a more efficient method.

**Comment by sphaso** [comment] 2015-03-04 08:07
Nolan, at this point I must admit I'm utterly confused. Some of the questions running through my mind:
- why do I need to listen to changes from both databases? If Pouch is automagically syncing in the background, I should be able to do everything by just listening to changes on the local DB (like you're doing in the blog post you kindly linked)
- why was my initial code OK before I had the bright idea to add filters? I was simply listening to changes on the localDB, the only problem was that "onChange" was not triggering at startup. After a ctrl+R I was able to listen to changes from both ends without a problem
- "onChange" property and ".on('change'" seems to return two different objects, the latter doesn't have a "deleted" field like the former. The blog post seem to suggest otherwise

Ultimately, do you agree there is a bug with server-side filtering and that my code is more of a workaround than a proper implementation?

**Comment by nolanlawson** [comment] 2015-03-04 13:05
There is no `on('delete')` even that I'm aware of. Did you try the toy example in the blog post, and compare that against your own app? The toy app is definitely using the `deleted` property.

**Comment by sphaso** [comment] 2015-03-04 13:14
I'm consulting the docs, at this page: http://pouchdb.com/api.html#changes I read:

```
In addition to the 'change' event, any change will also emit a 'create', 'update', or 'delete' event.
```

Is that incorrect?

My current code is:

```Javascript
localDB.sync(remoteDB, {
            live: true,
            retry: true,
            filter: 'app/by_user',
            query_params: { "agente": agent }
        })
        .on('change', function(result){
                console.log("change!");
                result.change.docs.forEach(function(change) {
                    $rootScope.$apply(function(){
                        $rootScope.$broadcast('upsert', change);
                    });
                });
        });
```
As you can see from the (working) code, "result" is not returning a single change but something like this:

{
   change: { docs: ... the docs that changed }
   direction: "pull"
}

The "deleted" field is nowhere to be seen. Is the code wrong? The use of .on('change',... seems identical to the examples in your "toy app" in the blog post.

**Comment by nolanlawson** [comment] 2015-03-04 14:26
Yeah okay, I totally forgot about that. We should probably get rid of those events, because it's kind of confusing. All you need is the `'change'` event.

The toy app is correctly consuming `'change'` events and responding based on whether they are deleted, updated, or created. You can set a breakpoint inside of the toy app to see that `change.deleted` is indeed set. I'm not sure what else to tell you... :/

**Comment by sphaso** [comment] 2015-03-04 14:30
At this point what worries is me is not if there's a deleted field or not, but that the event is not triggering if I delete a document server-side :\

**Comment by nolanlawson** [comment] 2015-03-04 14:39
Do you have a live test case to reproduce?

**Comment by nolanlawson** [comment] 2015-03-04 14:44
Oh wait, yeah, that was a bug in 3.3.0. You should upgrade to 3.3.1.

**Comment by sphaso** [comment] 2015-03-04 14:56
I'm using v3.3.1. I only wish I could provide a live example, unfortunately the CouchDB instance is on the company dev server.
I feel like we're back to square one. This works as expected:

```Javascript
        localDB.sync(remoteDB, {
            live: true,
            retry: true
        });

        localDB.changes({
                    continuous: true,
                    include_docs: true
                }).on('change', function(change){
                    console.log(change);
                    if(change.deleted){
                        console.log("deleted!");
                    }
                    else {
                            $rootScope.$apply(function(){
                                $rootScope.$broadcast('upsert', change.doc);
                            });
                    }
                });
```

However this whole issue is about filtering server-side, if I try to do this, two things happen:
- I need to ctrl+R to start the replication
- The filter gets ignored (that's why you suggested using the nightly?)

```Javascript
        localDB.sync(remoteDB, {
            live: true,
            retry: true,
            filter: 'app/by_user',
            query_params: { "agente": agent }
        });
 
        localDB.changes({
                    continuous: true,
                    include_docs: true,
                    filter: 'app/by_user',
                    query_params: { "agente": agent }
                }).on('change', function(change){
                    console.log(change);
                    if(change.deleted){
                        console.log("deleted!");
                    }
                    else {
                            $rootScope.$apply(function(){
                                $rootScope.$broadcast('upsert', change.doc);
                            });
                    }
                });

```

**Comment by nolanlawson** [comment] 2015-03-04 15:27
Hmm, so you only need to filter client-side? You know, when you filter client side, you might as well just do it all in-memory inside your `'change'` listener. There is no performance benefit to using filter/query_params/etc. for local stuff, as I say in that blog post.

Otherwise, you can try changing your filter ddoc to:

```js
{
   "_id": "_design/app",
   "_rev": "1-d5c42302b756548440134e2755aab03d",
   "filters": {
       "by_user": "function(doc, req) { debugger; if(doc.Agents && doc.Agents.indexOf(req.query.agente) > -1){ return true; } return false; }"
   }
}
```

Then open up a debugger and see what your filter function is doing.

**Comment by sphaso** [comment] 2015-03-04 15:33
I need to filter server-side. I don't see any difference between my current ddoc and the one you provided? Anyway, the ddoc is working fine since I'm able to see the correct response with this code:

```Javascript
localDB.sync(remoteDB, {
            live: true,
            retry: true,
            filter: 'app/by_user',
            query_params: { "agente": agent }
        })
        .on('change', function(result){
                console.log("change!");
                result.change.docs.forEach(function(change) {
                    $rootScope.$apply(function(){
                        $rootScope.$broadcast('upsert', change);
                    });
                });
        });
```

The issues I see are:
- onChange is not triggering if a document is deleted on the server AND sync is using a filter
- when on('change') is attached to changes AND sync is using a filter I need to ctrl+R to trigger the event
- when on('change') is attached to sync I see a different response from the one I'd see if it was attached to changes

**Comment by nolanlawson** [comment] 2015-03-04 15:47
`sync()` does not support filter/query_params/etc.

I admit this is really tough to debug without a working reproducible test. :/ You don't need to share your entire codebase; just the smallest possible test to reproduce what you are seeing.

**Comment by sphaso** [comment] 2015-03-04 15:52
I'm really puzzled. The above code works besides for the delete issue, so somehow the filter is working?

I don't have a problem sharing the codebase, the issue I see is that I wouldn't know how to have you access our development server DB and I don't have a CouchDB instance on the cloud (do you have one?). At this point I'm fairly certain that the issue is with ddocs so just testing with local PouchDB instances wouldn't make much sense.

**Comment by nolanlawson** [comment] 2015-03-04 16:23
Maybe your filter function throws an error if the doc is deleted? I admit I'm not sure what filter functions do in the case of deleted docs.

**Comment by sphaso** [comment] 2015-03-04 16:35
I've setup a cloud DB and a plnkr. I've sent you all the references by email.

**Comment by sphaso** [comment] 2015-03-05 08:28
I'm closing the issue. To recap:
- One of the issues (filtered replication simply not using the filter as expected) was very well fixed with v3.3.1
- The remaining issue is with deleted documents. Nolan had the great idea that maybe deleted documents don't pass the filter. To add to that I've also noticed that when I remove the value that would make the filter pass (e.g. the agent code in the list of agents linked to the doc), "changes" doesn't trigger

I wanted to see if this was PouchDB-side or CouchDB-side. It didn't take long, by curling I see that it is indeed the expected behavior of CouchDB.

Thanks again for spending the time to work this through.

**Comment by nolanlawson** [comment] 2015-03-05 13:01
Interesting, so when you do filtered changes, deleted documents just don't show up at all? Is that what surprised you?

**Comment by sphaso** [comment] 2015-03-05 13:10
Yes, this is very surprising and problematic. How are you supposed to replicate this deletion on the local DB then?        
What I'm trying: 
on each pause get all the local docs, query the remoteDB (remoteDB.get(id..)) then if 404 do localDB.remove. The problem now is that localDB.remove(id) is throwing 404 on documents that I can see are on the IndexedDB. I guess it's because it cannot see the doc on the remote when it tries to sync? Will working directly with the IndexedDB API break anything in Pouch?

**Comment by nolanlawson** [comment] 2015-03-05 13:25
You shouldn't need to do the sync manually yourself. And yes, working directly with IndexedDB is bad news; don't do it. :)

It doesn't sound correct to me that filters would skip deleted docs, since you're right that that would break replication. This sounds like a bug in PouchDB maybe.

When I get a chance (maybe this weekend) I can try to have a look at your live example and see what's going on. Else if you could write a unit test in [test.replication.js](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js) that reproduces the issue (see [this test](https://github.com/pouchdb/pouchdb/blob/00dd0cb164031cc246f6a1e76cb9154a02eb7278/tests/integration/test.replication.js#L1367-L1399) for a similar one, that would get us one step closer to fixing it. The nice thing about that test suite is that it will test all combinations of local and remote, so it's easy to isolate whether a problem is at the CouchDB level or PouchDB level.

**Comment by sphaso** [comment] 2015-03-05 13:36
I'll see if I can write a UT. Should I issue a PR for it? How would you test for someone deleting a document on the server? (without using Pouch, hopefully this won't be an issue).
My plnkr unfortunately is broken since my Iris Couch is giving 404. If you have a CouchDB server you can easily swap the URL to test.

**Comment by nolanlawson** [comment] 2015-03-05 16:25
If you read the TESTING.md, it will explain how to run the tests. If you want to test in Node, it's as simple as `npm install && npm test`; if you want to test in the browser, do `npm install && npm run dev`, and then it will give you a URL to open in your browser. Then you can use `?grep=mytestname` to filter your test.

In that test, you could do a `db.remove()` on the remote database in order to simulate someone deleting a doc on the remote server. And yes, a PR would be lovely. :) Even if it's failing, opening up a PR so we can see the difference would be very helpful.

**Comment by sphaso** [comment] 2015-03-05 21:33
Thanks for all the info. I think my UT should in fact fail, there is no point in making it otherwise :) 

I'm trying to setup a dev environment for Pouch on my Arch box. I synced my fork to the lastest upstream/master and ran npm install && npm test. Unfortunately one test is failing and I can't figure out why. The test in question is:
test.replicate.js-local-http Test basic events
Uncaught RangeError: port should be > 0 and < 65536: 0
(stack references the request node_module)

I see from the test code that it's trying to replicate 0.0.0.0:0. Well, that's not > 0 :) I guess the test in question was supposed to catch it and have the test pass as a result, but it seems this is not the case.
I see that the latest build is green on this side. Do you have any idea what might be causing this?

**Comment by daleharvey** [comment] 2015-04-03 11:42
Fixed in https://github.com/pouchdb/pouchdb/commit/725185a09d6173db6802d685fe9c2c36a222e1fb

**Closed by daleharvey** 2015-04-03 11:42 UTC
Labels: help wanted

**Comment by raymatos** [comment] 2015-12-02 06:31
Sorry to reopen this, but im having a similar issue

```
db.changes({
					live: true,
					since: 'now',
					include_docs: true,
					filter: '_view',
					view: collectionName + '/collection'
				}).on('change', function (change) {
			    if (change.deleted) {
			      // change.id holds the deleted id
			      _internalDelete(change);
			    } else { // updated/inserted
			      // change.doc holds the new doc
			      _internalAddEdit(change.doc);
			    }
			  }).on('error', logger.error);
```


By adding a filter and view deleted documents are not being catched in the change event.  However if i were to remove the filter then it works.

**Comment by sphaso** [comment] 2015-12-02 08:12
Just so we're on the same page: 
- are you deleting the docs by updating the "_deleted" field?
- are your design docs both on the client and the server?

There are a few caveats I described at the end of [this post](http://pouchdb.com/2015/04/05/filtered-replication.html) but I haven't upgraded to v5 since writing it.

**Comment by raymatos** [comment] 2015-12-02 09:25
I'm deleting the doc via the db.remove(doc) call.




Design docs live on both local and remote.  I'm deleting from the local.



—

**Comment by sphaso** [comment] 2015-12-02 12:25
From the documentation I gather that ```remove``` doesn't update the "_deleted" field. I suggest you try updating the doc with the field "_deleted: true" in order to delete your documents. This is usually the way in filtered replication. Please note that this will not purge the documents from the store.

**Comment by raymatos** [comment] 2015-12-03 15:59
That worked.  However documents are still in the store.

**Comment by sphaso** [comment] 2015-12-03 16:26
Glad it worked! Purging is not supported by PouchDB as of yet, see issue #802

**Comment by raymatos** [comment] 2015-12-03 16:30
BTW according to the pouchDb docs, ```remove()``` should be adding an _deleted attribute to the doc.  

http://pouchdb.com/guides/updating-deleting.html

**Comment by jamesmfriedman** [comment] 2019-01-03 23:06
I know I'm a few years late to this issue, but it does definitely appear to still be an issue.

To break it down:
If you are using filtered replication, both remove, and put _deleted: true do not replicate.

Any ideas?

**Comment by jamesmfriedman** [comment] 2019-01-03 23:14
Interestingly enough, this fails filtered replication

```
db.put({_id, _deleted:true})
```

but this works

```
db.bulkDocs([{_id, _deleted:true}])
```
