### ISSUE TITLE
Database has a global failure DOMException

### ISSUE THREAD

**Issue by jpcastro4** [pouchdb/pouchdb#7291] opened 2018-05-23 13:24 UTC
### Issue
Database has a global failure DOMException

The error began to appear when I did a full Clear Storage in my application. From there request new PouchDb I get the error

![image](https://user-images.githubusercontent.com/29064473/40426659-0502c8de-5e72-11e8-8bea-4e42156b7e03.png)

### Info
- Environment: (Cordova/browser/hybrid app/etc.)
- Platform: (Chrome/iOS/Android/)
- Adapter: (IndexedDB)
 

### Reproduce

Make a debug on local emulation on the computer I have identified missing data that is not rebuilt after clear storage

Compare

debug in app
![image](https://user-images.githubusercontent.com/29064473/40426802-5ec152c8-5e72-11e8-9854-79ecff9b6b87.png)

debug in my pc

![image](https://user-images.githubusercontent.com/29064473/40426849-75989416-5e72-11e8-922d-ce0719d32d99.png)

After this incident I can not reverse the situation.

**Comment by daleharvey** [comment] 2018-05-23 14:35
Sorry I dont really understand the report / what you expect to happen. If you could reproduce and list the steps that lead to it being broken with http://pouchdb-bug-helper.glitch.me/ it would be extremely useful

I can see that in the app its being served from `file://`, I know that browsers generally have a hard time doing things right when using webapis from the file system, if you cant reproduce the steps with chrome + http://pouchdb-bug-helper.glitch.me/ or say fairly specifically what pouchdb is handling wrong then its likely a bug that needs to be fixed by cordova / whatever is being used to serve it from the filesystem

**Comment by daleharvey** [comment] 2018-05-31 08:18
Need more info to debug preferably in a browser, looks like you are seeing it work on the pc and fail on the app so whatever app wrapper you are using, cordova etc probably needs looked into

**Closed by daleharvey** 2018-05-31 08:18 UTC

**Comment by manukieli** [comment] 2018-06-06 18:18
Hi,
I've the same error on some smartphone with Android and Chrome.
The error is not in all smartphone.
The snapshot of the console error is from a mobile conecting to USB to PC and with remote devices debug.
![error_pouchdb](https://user-images.githubusercontent.com/14294794/41057056-4fbef29e-69c6-11e8-9d11-2e8fbfc93419.jpg)

**Comment by owaishanif786** [comment] 2018-10-09 20:02
I have same error as @manukieli  have. only chrome have this problem. firefox working fine

**Comment by petersobolev** [comment] 2019-01-30 16:51
Same error ("Database has a global failure DOMException") at line "console[method].apply(console, args);" while running sync() inside worker (worker implemented via blob).

Chrome 71.0.3578.98 (Official Build) (64-bit) / Win7
No problem in FireFox /Win7 however.

It usually appears before some db sync errors. For example:
-------
pouchdb-7.0.0.js:2526 Database has a global failure DOMException
guardedConsole @ pouchdb-7.0.0.js:2526
idb.onabort @ pouchdb-7.0.0.js:8326
pouchdb-7.0.0.js:3538 Uncaught Error: Unable to resolve latest revision for id ItemNote_111, rev 1-fe2d140756c6b98d2b4f2de20484f1f6
    at latest (pouchdb-7.0.0.js:3538)
    at IDBRequest.txn.objectStore.get.onsuccess (pouchdb-7.0.0.js:7976)

**Comment by lmj0011** [comment] 2019-08-08 07:36
For those that have stumbled here because their Chrome extension gave this error, try restarting your computer and reproducing. (as cliche that may sound, it made this go away for me)
