### ISSUE TITLE
Cannot set property '_rev' of undefined calling allDocs

### ISSUE THREAD

**Issue by yawhide** [pouchdb/pouchdb#4936] opened 2016-02-29 22:11 UTC
Not sure how I got this to happen, but I am calling an allDocs where some keys to documents have `deleted` set to true and others dont and `include_docs = true`

here is the stack trace i get from nodejs

```
/Users/yawhide/workspace/diamond/baymax/node_modules/pouchdb/lib/index.js:7686
            doc.doc._rev = doc.value.rev;
                         ^

TypeError: Cannot set property '_rev' of undefined
    at allDocsInner (/Users/yawhide/workspace/diamond/baymax/node_modules/pouchdb/lib/index.js:7686:26)
    at /Users/yawhide/workspace/diamond/baymax/node_modules/pouchdb/lib/index.js:7714:13
    at /Users/yawhide/workspace/diamond/baymax/node_modules/level-sublevel/shell.js:101:15
    at /Users/yawhide/workspace/diamond/baymax/node_modules/level-sublevel/nut.js:120:19
```
I put some console.logs around that area of the code. The code indeed does try to set _rev on undefined. The reason why doc.doc is undefined is because we set it to whatever `stores.bySeqStore.get` returns (and it returns and err, which is `[NotFoundError: Key not found in database]` and an undefined `data`)

is this just a bug on your end? I dont think I am using your api incorrectly

EDIT: here is my api call:
```
db.allDocs({ include_docs: true, keys: ['some id'] })
```

**Comment by nolanlawson** [comment] 2016-03-02 14:16
Hm, is the device running out of space? What version of Chrome are you using?

**Comment by yawhide** [comment] 2016-03-02 17:33
its happening on node.js v4.3.1, pouch version 5.1 and 5.2.1

**Comment by yawhide** [comment] 2016-03-02 18:19
I have plenty of space on my hard drive.
I am not using chrome, I am using the npm module.

**Comment by nolanlawson** [comment] 2016-03-03 15:42
If you can find a test to reproduce, that would be very helpful. I think this has come up before, but nobody could figure out how to reproduce it. :/

**Comment by daleharvey** [comment] 2016-06-08 09:14
This looks exactly the same bug as https://github.com/pouchdb/pouchdb/issues/5309, closing as a dupe as that one has a PR in progress

**Closed by daleharvey** 2016-06-08 09:14 UTC
Labels: bug, needs reproducing

**Comment by yawhide** [comment] 2016-06-08 14:01
i got so excited for a second thinking you guys fixed it haha

**Comment by ngrj** [comment] 2017-11-16 15:25
Hi, thanks for the awesome work on pouchdb,
I've a node webkit application which is installed around few hundred places, almost every other day one of the clients application faces these issue, we have to delete the local pouch database and replicate the same database to use it. Re replicating the database fixes the issue. But since I've very large amount of docs these does not seem to be a ideal solution. So, I tried debugging the issue. Here are the things I've found out from my debugging: 

- If you call allDocs with option include_docs True, it will raise the above issue

- If you call allDocs without include_docs, it won't raise the issue, so it led me to believe that some doc content must be missing , so I called allDocs with include_docs:false and then for every id I've received I called db.get() and I found a Id for which I've recieved a 404 error instead of doc. 
`Object {status: 404, name: "not_found", message: "missing", error: true}`
I thought the temporary fix is to just purge that document and let it replicate from server but I don't seem to find a way to purge document. So, I tried db.remove, my doc revision id was 12-something and after db.remove it went to 10-something instead of 13-something but even after deleting I get the same issue and if I delete it this time , the rev id will be 14-something and the problem gets resolved.
