### ISSUE TITLE
Corrupt indexeddb data can replicate back to server

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3942] opened 2015-06-08 12:44 UTC
I'm opening a new issue based on https://github.com/pouchdb/pouchdb/issues/3932. The old issue devolved into a lot of personal attacks and comments on those personal attacks, so it's not helpful to continue the conversation over there.

I suspect that by not using `revpos` correctly, our replicator somehow gets CouchDB into a state where it starts replicating documents without their attachments. I have [a test case](https://gist.github.com/nolanlawson/f0dd3e35ba908df691bb) that shows PouchDB 3.6.0 saving the attachments with `revpos: undefined` and `revpos: 0`, but I cannot reproduce the case where the attachment data is actually lost.

@kxepal @rnewson This is one of the most serious bugs PouchDB has faced, but I'm kind of at a loss to figure out how to attack it. Is there any way you can think of that a malignant replicator could misuse `revpos` in order to convince CouchDB to just completely drop attachments? According to the reporter of #3932, the attachments started looking like:

```
"css/ptm55f-webfont.ttf": {
   "digest": "md5-SbEzACAvJcCFxzHSFvq0IQ==",
   "content_type": "application/octet-stream",
   "data": ""
  }
```

But I cannot reproduce.

**Comment by nolanlawson** [comment] 2015-06-08 12:49
OK, here's [a slightly different attempt](https://gist.github.com/nolanlawson/a980820bd7e75d1fcf2b). In this case, I can get CouchDB to save an attachment, and it ends up with `revpos: 0`, even though the `1-` revision *does not actually contain the attachment*. (It's contained in `2-`.) Is it possible that this could cause the attachments to get lost somehow?

**Comment by nolanlawson** [comment] 2015-06-08 12:53
Hm, even if I use CouchDB's replicator to replicate that document to another database, the attachment is still there.

**Comment by nolanlawson** [comment] 2015-06-08 12:57
Ditto for compaction. The attachment is still there, even though `revpos` is wrong.

**Comment by kxepal** [comment] 2015-06-08 13:44
There is no magic behind revpos: if you remember `_revisions` field of documents (`GET /db/doc?revs=true`) then it's the value for `start` field inside that object.

Undefined or `0` revpos are also [fine case](https://github.com/apache/couchdb-couch/blob/master/src/couch_att.erl#L385-L395) - it's not an issue.

**Comment by rnewson** [comment] 2015-06-08 22:53
`revpos` goes hand in hand with `atts_since`. The goal being to optimize replication by not having to transfer the bytes of attachments already present on the target.

If you aren't returning a revpos value (or are always returning 0) then I don't think it can be the cause of the reported data loss. pouchdb also doesn't use the `atts_since` request parameter, I infer?

couchdb will send a stub instead of the attachment if the revpos is lower than `atts_since`.

To cause data loss through this mechanism I think it would be necessary to send an `atts_since` request parameter that is too high and to then save the resultant stub as if it were not a stub (i.e, record the name and md5 but not record a body (since the "data" attribute would not be present).

**Comment by daleharvey** [comment] 2015-06-08 23:06
We never actually use `atts_since` or `revpos` in our replicator, they can only be fields that may get transferred, the only way we fetch docs is via https://github.com/pouchdb/pouchdb/blob/master/lib/replicate/getDocs.js#L31 or https://github.com/pouchdb/pouchdb/blob/master/lib/replicate/getDocs.js#L70, so given the symptoms it seems like there must be some way that we are fetching a doc that has missing attachment information / stubs and we are assuming it has data

**Comment by nolanlawson** [comment] 2015-06-09 12:13
@rnewson @kxepal That makes sense, thanks! What if, though, the user is mixing CouchDB replication with PouchDB replication? Is there some combination where CouchDB's replicator will use `atts_since` and fail to send the attachment data?

**Comment by kxepal** [comment] 2015-06-09 12:25
@nolanlawson `atts_since` is only used against source database, so CouchDB cannot query PouchDB database with such parameter (while we're speaking about in-browser use case). And even if, `atts_since` is an optimization to not replicate all the attachments for every revision, but only those which were actually changed. So PouchDB behavior here should be like CouchDB one in pre-0.11 era.

**Comment by nolanlawson** [comment] 2015-06-09 14:36
@kxepal What I mean is this:

1) User replicates from PouchDB to CouchDB (and back again, or whatever)
2) Docs with invalid `revpos: 0` are stored in CouchDB (as demonstrated in my test case)
3) User replicates from CouchDB to another CouchDB
4) What happens...?

**Comment by daleharvey** [comment] 2015-06-11 23:30
Another data point on irc

```enquora> updating PouchDB from 3.5 to 3.6, replication from remote of documents with attachments is failing in all browsers. I notice PouchDB is issuing a GET with a URL like    blob:http://mydomain.com/documentID```

I dont know how we can possibly be constructing urls like that, but it sounds like it could definitely cause this type of issue

**Comment by enquora** [comment] 2015-06-11 23:33
a source code search hasn't returned anything that shows such a URL being constructed, but it most certainly is happening. fwiw, Safari is showing a different but seemingly related failure mode.

**Comment by nolanlawson** [comment] 2015-06-12 03:24
@enquora Can you please provide any more information than that? A live test or some kind of description of what you were doing with the data and how the data was lost?

I have been trying really hard to reproduce this (worked all weekend on it, also see https://github.com/pouchdb/pouchdb/pull/3957), and I'm not getting any closer. In https://github.com/pouchdb/pouchdb/pull/3957 I've even got a test where it actually upgrades from 3.5.0 to the latest version, with partial replications in-between, and I still cannot reproduce.

Please try to reproduce if you can. It could be some particular combination of factors - e.g. whether or not you are putting the attachments in base64 format or Blob format, whether you are using `put()` or `putAttachment`, whether or not you are replicating between CouchDBs, whether you are replicating to Couch or from Couch, how many revisions the document has, how many documents you are storing, how many attachments you are storing, how many *unique attachments* you are storing...

I would really like to track down this bug, but right now it is just frustratingly difficult. :(

My ideal test would look like this:

* `index1.html` using PouchDB 3.5.0, doing something with a local database and replicating to a remote CouchDB (could be `127.0.0.1:5984`, doesn't matter).
* `index2.html` using PouchDB 3.6.0, interacting with the same data, doing what it is that causes the data loss.

Steps to reproduce would be: open `index1.html`, then open `index2.html`. Could somebody please write a test that accomplishes this?

**Comment by nolanlawson** [comment] 2015-06-12 05:37
I'm starting to think we should roll back to 3.5.0, if nobody is able to reproduce this and fix it soon.

**Comment by nolanlawson** [comment] 2015-06-12 05:52
another data point:

> we patch all incoming requests with the two application/json headers - I found this necessary in the past. I originally wondered if that had anything to do with this. Have just begun experimenting

Uploads are now `multipart/related` rather than `application/json`. Wonder if this has anything to do with that. It would explain why I cannot reproduce, if the only way to reproduce is to have a server proxy that expects json.

**Comment by nolanlawson** [comment] 2015-06-12 06:16
I think `blob:http://mysite.com` is a red herring. That's most likely just IDB checking for blob support. If you see an empty blob of type `image/png`, then that's what that is.

**Comment by daleharvey** [comment] 2015-06-12 19:30
Ok I think I have found this, as mentioned on irc it seems to be related to the proxy, I am seeing failures that look very similiar by editing `node_modules/corsproxy/bin/corsproxy.js` and adding 

```
    req.headers['content-type'] = 'application/json';
    req.url = path;
    return proxy.proxyRequest(req, res, target);
```

with that change I am seeing http://127.0.0.1:8000/tests/integration/?grep=3932 fail and with some similiar symptoms to the report (body: {}  digest: "md5-B0UGSRi0lpPMpk1rahPSig==")

**Comment by daleharvey** [comment] 2015-06-13 23:43
So @ermouth is talking directly to couch and still seeing this, not certain its the same bug although @enquora if you force application/json headers it will almost definitely break things. @ermouth is gonna try to share the database he is using to reproduce

**Comment by daleharvey** [comment] 2015-06-16 00:34
So the root cause of the corruption is still unknown and there is likely not a lot we can do about that, however we should have checks in place to ensure corrupt data does not get replicated back to the server, working on a test for that now

**Comment by daleharvey** [comment] 2015-09-27 00:29
Actually disagreeing with my earlier self, we dont work directly on the filesystem we run against databases that are high level themselves, checking the corruption of the data is an expensive operation and is entirely different for each type of storage that is used. If we find any issues of data corruption they should be filed against the underlying store. Closing since we havent got anywhere with finding what the original corruption is but please open a new bug if theres any indication that this is still an issue

**Closed by daleharvey** 2015-09-27 00:29 UTC
