### ISSUE TITLE
Weird error "bad collationIndex or unexpectedly reached end of input: '_'"

### ISSUE THREAD

**Issue by jacargentina** [pouchdb/pouchdb#3421] opened 2015-01-20 20:08 UTC
Following code makes querying views throw the error 

**bad collationIndex or unexpectedly reached end of input: '_'**

```javascript
var PouchDB = require('pouchdb');
var PouchDB_defaults = PouchDB.defaults({
  prefix: __dirname + '/databases/'
});
var db = new PouchDB_defaults({name: 'testing'});
db.put({
    _id: '_design/list',
    views: {
      all: {
        map: function(doc) {
          emit(doc._id);
        }.toString()
      },
      byBase: {
        map: function(doc) {
          if (doc.Base) {
            emit([doc.Base, doc._id]);
          }
        }.toString()
      }
    }
  })
  .then(function(response) {
    console.log('design put response: ', response);
    db.put({
        _id: 'TESTING',
        name: 'hello'
      })
      .then(function() {
        db.query('list/all', {
            include_docs: true,
            descending: true,
            limit: 20
          })
          .then(function(response) {
            console.log('query response ', response);
          })
          .catch(function(err) {
            console.log('ERROR ', err);
          })
      });
  });
```

Problem is solved by calling the constructor with: 

```javascript
var db = new PouchDB_defaults('testing');
```
Would be nice to show an error when calling with {name: ' ... '} if its a wrong call ?

@nolanlawson

**Comment by nolanlawson** [comment] 2015-01-20 20:55
seems related to PouchDB.defaults with the prefix.

**Comment by nolanlawson** [comment] 2015-01-24 20:26
@jacargentina do you have a live test case? Cannot figure out how this is happening.

**Comment by jacargentina** [comment] 2015-02-03 18:02
Just create a new directory "testing" and put inside this:


**package.json**
```javascript
{
  "name": "issue-3421",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "rm databases -Rf && mkdir databases && node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "pouchdb": "^3.3.0"
  }
}
```
and this

**index.js**
```javascript
var PouchDB = require('pouchdb');
var PouchDB_defaults = PouchDB.defaults({
  prefix: __dirname + '/databases/'
});
var db = new PouchDB_defaults({name: 'testing'});
db.put({
    _id: '_design/list',
    views: {
      all: {
        map: function(doc) {
          emit(doc._id);
        }.toString()
      },
      byBase: {
        map: function(doc) {
          if (doc.Base) {
            emit([doc.Base, doc._id]);
          }
        }.toString()
      }
    }
  })
  .then(function(response) {
    console.log('design put response: ', response);
    db.put({
        _id: 'TESTING',
        name: 'hello'
      })
      .then(function() {
        db.query('list/all', {
            include_docs: true,
            descending: true,
            limit: 20
          })
          .then(function(response) {
            console.log('query response ', response);
          })
          .catch(function(err) {
            console.log('ERROR ', err);
          })
      });
  });
```

Then do:
```bash
npm install && npm test
```

**Comment by jacargentina** [comment] 2015-02-03 18:03
The output of doing that on my Fedora 21, Node v0.10.33 is:

````bash
npm test

> issue-3421@1.0.0 test /home/..../javascript/issue-3421
> rm databases -Rf && mkdir databases && node index.js

design put response:  { ok: true,
  id: '_design/list',
  rev: '1-67ee043e96cd98edd3b7021915453545' }
ERROR  [Error: bad collationIndex or unexpectedly reached end of input: _]
```

**Comment by nolanlawson** [comment] 2015-02-05 17:15
OK cool, I will try to look into this when I get a chance.

**Comment by mlegenhausen** [comment] 2015-04-30 10:51
+1 any progress on that issue?

**Comment by mlegenhausen** [comment] 2015-04-30 11:06
Found the problem, you need to define `startKey` and `endKey` (if you use decending you need to switch the values) or even your design docs will be proceed by the map reduce function which leads to this error.

**Comment by nolanlawson** [comment] 2015-04-30 11:15
Hm, it actually appears to me that this was caused by https://github.com/pouchdb/pouchdb/issues/3741. I recall seeing this error when I used `new PouchDB({name: 'foo'})`, and I see @jacargentina using that pattern above.

So this should be fixed in master; anyone who want to try it out can download it from the nightly build: http://pouchtest.com/nightly

**Closed by nolanlawson** 2015-04-30 11:15 UTC
