### ISSUE TITLE
PouchDB fails to use the SQLite plugin when reopening the DB

### ISSUE THREAD

**Issue by jamesjacobs** [pouchdb/pouchdb#4990] opened 2016-03-23 08:11 UTC
Hi, I'm writing an Ionic app that uses PouchDB and the SQLite plugin. I have a Angular factory that returns methods for creating the pouchDB and basic CRUD functions:

```
.factory('PouchdbFactory', ['$q', function ($q) {

        var db,
            codes = [];

        var initDB = function() {
            db = new PouchDB('codes', {adapter: 'websql', auto_compaction: true, location: 2}); // location should be 2
            // Listen for changes on the database
            db.changes({ live: true, since: 'now', include_docs: true}).on('change', onDatabaseChange);

            db.info().then(console.log.bind(console));
        }

       ...etc...
```

I call the `initDB()` function in my main ionic `.run()` block. This all works fine and creates the DB using the SQLite plugin - `db.info().then(console.log.bind(console));` reports `sqllite-plugin: true`

I added a second factory, which is used to periodically get the PouchDB data and recalculate some values. Within that factory I inject the first factory and call `initDB()` again (which I believed would open the existing DB). Everything works as intended however `db.info().then(console.log.bind(console));` now logs `sqllite-plugin: false`. Here's the second factory:

```
.factory('OtpFactory', ['$rootScope', '$interval', '$localstorage', 'PouchdbFactory',  function($rootScope, $interval, $localstorage, PouchdbFactory) {

        var otpCodes,
            globalTimerPromise,
            totpObj = new TOTP();

        // this breaks sqllite plugin (db.info().then(console.log.bind(console)); returns sqllite_plugin: false )
        PouchdbFactory.initDB();

        PouchdbFactory.getAllCodes().then(function(codes) {
            otpCodes = codes;
        });
```

I'm still new to Angular so hopefully this is not down to error or the structure I'm using. I could create the DB in Global scope or $rootScope but why does calling the initDB method break the plugin use?

**Comment by nolanlawson** [comment] 2016-03-24 16:29
Hm, is `window.sqlitePlugin` still attached when you re-create the PouchDB? Without stepping through the code it's hard to tell what's going on, but if you can set a debug breakpoint around [these lines](https://github.com/pouchdb/pouchdb/blob/194ea5dd52d4e46aa1068a13f1b6a7c5a05b82a2/src/adapters/websql/createOpenDBFunction-browser.js#L3-L18) you may be able to help us debug it.

**Comment by jamesjacobs** [comment] 2016-03-27 19:21
Hi @nolanlawson thanks for the reply, your help would be awesome. I added a debugger and also a breakpoint to `createOpenDBFunction()` and can confirm when the second `PouchdbFactory.initDB();` is present `sqlitePlugin` is undefined. When I remove the second `PouchdbFactory.initDB();` everything works as it should and `sqlitePlugin` is defined.

If it helps, when only one is present I get a lot more console outputs too, from both PouchDB - for example:

```2016-03-27 19:59:52.171 HelloCordova[13470:80889] pouchdb:api codes +0ms info``` 

and also SQL plugin itself:

```
2016-03-27 19:59:52.041 HelloCordova[13470:80889] Initializing SQLitePlugin
2016-03-27 19:59:52.041 HelloCordova[13470:80889] Initializing SQLitePlugin
2016-03-27 19:59:52.042 HelloCordova[13470:80889] Detected docs path: /Users/XXX/Library/Developer/CoreSimulator/Devices/C026ED9B-BE2C-44A0-9EF6-BC17CFEBE09D/data/Containers/Data/Application/7B2DD9E9-F115-43B8-AF32-A04EECA868EF/Documents
2016-03-27 19:59:52.042 HelloCordova[13470:80889] Detected Library path: /Users/XXX/Library/Developer/CoreSimulator/Devices/C026ED9B-BE2C-44A0-9EF6-BC17CFEBE09D/data/Containers/Data/Application/7B2DD9E9-F115-43B8-AF32-A04EECA868EF/Library
2016-03-27 19:59:52.042 HelloCordova[13470:80889] no cloud sync at path: /Users/XXX/Library/Developer/CoreSimulator/Devices/C026ED9B-BE2C-44A0-9EF6-BC17CFEBE09D/data/Containers/Data/Application/7B2DD9E9-F115-43B8-AF32-A04EECA868EF/Library/LocalDatabase
2016-03-27 19:59:52.042 HelloCordova[13470:80954] open full db path: /Users/XXX/Library/Developer/CoreSimulator/Devices/C026ED9B-BE2C-44A0-9EF6-BC17CFEBE09D/data/Containers/Data/Application/7B2DD9E9-F115-43B8-AF32-A04EECA868EF/Library/LocalDatabase/_pouch_codes
2016-03-27 19:59:52.044 HelloCordova[13470:80954] Good news: SQLite is thread safe! 
```

I can publish a test app on github if it help? Grateful of any advice as this is a blocker for me (although I'm going to try setting the DB as a global). Thanks

**Comment by nolanlawson** [comment] 2016-03-28 16:19
That's really weird - is the SQLite Plugin removing itself from `window` somehow? PouchDB is definitely not doing that, but maybe the SQLite Plugin is.

Also FYI: the SQLite Plugin has zero value in an Android application. It is slower, buggier, and harder to manage than native WebSQL or IndexedDB. It's only useful on iOS when you want to exceed storage limits, or in rare cases where you want a prepopulated DB, etc.

**Comment by jamesjacobs** [comment] 2016-03-28 18:41
I'm not sure how debug that or what could be causing it... I've followed all the tutorials and docs I could find.

The only reason I'm using the SQLite plugin is to persist data as I've had issues with cordova apps wiping local storage on app store updates or when device memory is low (especially on iOS). Can Pouch save data to a json file, similar to lokijs? 

I've been trying to get the plugin working nicely with Pouch for over a month now. :(

**Comment by nolanlawson** [comment] 2016-03-29 05:48
I understand your pain with the SQLite Plugin. Unfortunately LocalStorage/IndexedDB/WebSQL do not enjoy wide browser support, and browsers randomly deleting data is a big problem. The [durable storage API](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/Md2SYtNazVU) is meant to fix that.

I don't mean to chastise anyone for using the SQLite Plugin; just to offer other options. If you can provide a test to reproduce for this particular bug, that would help us enormously in tracking it down.

**Comment by nolanlawson** [comment] 2016-05-03 01:22
I've added the "needs reproducing" label to this bug; please provide a test case to reproduce and we will try to help.

**Comment by daleharvey** [comment] 2016-06-08 11:50
So without STR we cant fix this, particularly on a mostly unsupported platform where it looks like it may not actually be our issue. 

If you can give us steps to reproduce that show this is an error in pouchdb we can fix, please reopen or file a new bug but closing for now. thanks

**Closed by daleharvey** 2016-06-08 11:50 UTC
Labels: bug, needs reproducing
