### ISSUE TITLE
Live sync vs browser reload

### ISSUE THREAD

**Issue by czb** [pouchdb/pouchdb#4442] opened 2015-10-09 05:14 UTC
I have the following code:

    o.db.sync(o.remoteURL + dbName, { live: true, retry: true }).then(function (e, s) {
    });

Sometimes when I reload the browser and always when `browser-sync` reloads the browser, an exception is thrown in `EventEmitter.prototype.emit` in `Change` with message `Database encountered an unknown error`.

If I am right then the error originates in `api._changes` -> `ajax` to `_changes` url.

Should not the error go to `e` in `then` function?

EDIT:

I have traced down the error to `getChanges` function:

    var changes = src.changes(changesOpts)
          .on('change', onChange);

If I change the code to

    var changes = src.changes(changesOpts, function (e) {
    }).on('change', onChange);

Then the error is caught and not thrown. Is that a bug that the error is not caught by a callback function?

**Comment by nolanlawson** [comment] 2015-10-09 14:46
I think the issue is that typically folks do not use the promise style when they are doing live/retry (see the docs for some examples: http://pouchdb.com/api.html#replication

That said, this sounds like a bug we would like to track. Do you have a test case to reproduce?

**Comment by czb** [comment] 2015-10-15 05:31
I have changed the code into

    .on('error', function(error) {
      throwError(error);
    });

But I still observe the error. I can get rid of the error only when in pouchdb.js I change

    var changes = src.changes(changesOpts)
      .on('change', onChange);

into

    var changes = src.changes(changesOpts, function (e) {})
      .on('change', onChange);

It is PouchDB 4.0.3 that I use.

**Comment by nolanlawson** [comment] 2015-10-17 16:23
Can you provide more details about the error you're seeing? Which browser are you using? Also a live example would be best. :)

**Comment by czb** [comment] 2015-10-20 07:04
You can try to login as username: demo and password|: demo

https://brocon2.ekj.dk/projects/brosyn/

Then open Developer Tools (F12) in Chrome. Then go to the menu in the right. Click on Log out.

If you are lucky enough, you will get the uncaught Database encountered an unknown error.

In source code, app.js line:

    o.oldSync = o.db.sync(o.remoteURL + dbName, { live: true, retry: true }).on('change', function (info) {

probably triggers the error

**Comment by nolanlawson** [comment] 2015-11-21 19:04
Hi @czb, I tried out your app, and I am seeing this in the console:

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://brocon2.ekj.dk' is therefore not allowed access.
```

This means you need to enable CORS on the CouchDB. Please refer to http://pouchdb.com/errors.html#no_access_control_allow_origin_header for more info. Closing, please reopen if it's still an issue.

**Closed by nolanlawson** 2015-11-21 19:04 UTC
Labels: enhancement
