### ISSUE TITLE
pouchdb-server failure - 3963 length property on stubs 

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4227] opened 2015-08-29 23:40 UTC
Failing locally in both chrome + fx, no idea why we dont see it on travis, possibly version issue

**Comment by nolanlawson** [comment] 2015-08-30 13:44
Feel like I've seen this before, but not been able to track it down.

**Comment by nolanlawson** [comment] 2015-08-30 15:38
Cannot repro on my machine; which version of express-pouchdb/pouchdb-server/pouchdb are you using?

**Comment by daleharvey** [comment] 2015-08-30 17:19
This is with a fresh `npm install`, express-pouchdb@0.14.2, pouchdb-server@0.6.6 master `$ GREP=3963 SERVER=pouchdb-server npm test` fails

**Comment by nolanlawson** [comment] 2015-08-30 18:43
Try upgrading? I'm on pouchdb-server@0.9.0 and I cannot reproduce at all. I'm also on Linux Mint, though.

**Comment by nolanlawson** [comment] 2015-08-30 18:55
Okay, I can repro

**Comment by nolanlawson** [comment] 2015-08-30 18:59
Yup, so what's happening is that the version of pouchdb-server that's getting installed (0.6.6) is using an old version of PouchDB (3.6.0) that has this length bug.

The reason you're not seeing this bug in Travis is because Travis runs [a script](https://github.com/pouchdb/pouchdb/blob/ac56d71cac049fd026ee1e8918bcb82d31192018/bin/run-test.sh#L8-L120 to link pouchdb-server's version of pouchdb to the current workspace version. 

This will be fixed if you update pouchdb-server or when https://github.com/pouchdb/pouchdb/pull/4232 lands.

**Comment by nolanlawson** [comment] 2015-08-30 19:00
As a side note, I think it is weird, but apparently certain versions of npm will resolve e.g. `^0.6.0` only to `0.6.6` and not `0.9.0`. It seems to have different behavior for pre-1.0 versions.

**Closed by nolanlawson** 2015-08-30 19:00 UTC

**Comment by marten-de-vries** [comment] 2015-08-30 19:19
@nolanlawson True. It's about time to release 1.0 for ``express-pouchdb`` & ``pouchdb-server``. Let's just do it with the next npm publish.

**Comment by nolanlawson** [comment] 2015-08-30 19:50
:+1:
