### ISSUE TITLE
Reference Error when importing in angular project

### ISSUE THREAD

**Issue by MTschannett** [pouchdb/pouchdb#7299] opened 2018-05-27 18:54 UTC
### Issue
When using PouchDB with Angular 6 a ReferenceError gets thrown.

The error message: 
```
ERROR Error: Uncaught (in promise): ReferenceError: process is not defined
ReferenceError: process is not defined
```
I don't know if i have imported pouchdb incorrectly (I followed the documentation for this). 
https://pouchdb.com/guides/setup-pouchdb.html#typescript

My current workaround is to monkey-patch the window variable with the process package from nodejs
Before this was done in the angular-cli, but I think this shouldn't be done when something isn't used in a node environment.

Current workaround code:
```
import process from 'process';
(window as any).process = process
```

If help is wanted to for this issue i would be happy to help (after some getting started help:))

### Info
- Environment: browser
- Platform: Chrome
- Adapter:  default
- Server: Couchdb

### Reproduce
Clone this repository: https://github.com/MTschannett/pouchdb-reproduction
run `npm install` to install the dependecies and then `ng serve` to serve the app.

For testing PouchDB and CouchDb i have a local CouchDB server running.

**Comment by daleharvey** [comment] 2018-05-27 19:51
Duplicate of https://github.com/pouchdb/pouchdb/issues/7263, basically it looks like angular tries to build pouchdb itself without doing our browser switches, would love help getting it fixed as I don't use angular myself, I think it should be using our built version, not sure we should be shipping our sources at all

**Closed by daleharvey** 2018-05-27 19:51 UTC
