### ISSUE TITLE
New Issue found 8.0.0

### ISSUE THREAD

**Issue by ishaiavrahami** [pouchdb/pouchdb#8591] opened 2023-01-30 09:01 UTC
### Issue
Upgrated from 7.3.1 and got an issue with emit
Write the description of the issue here

### Info
- Environment: (vue,js)
- Platform: (Chrome)
- Adapter: (none)
- Server: (CouchDB)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

<img width="566" alt="Screenshot 2023-01-30 at 11 00 24 AM" src="https://user-images.githubusercontent.com/33962719/215432550-0b52ddc3-62cf-47f7-9139-1105a4fa4db5.png">

<img width="275" alt="Screenshot 2023-01-30 at 11 00 27 AM" src="https://user-images.githubusercontent.com/33962719/215432556-bae540b6-3001-4373-bef4-9ae75161b322.png">

**Comment by garethbowen** [comment] 2023-01-30 21:38
Looks like a duplicate of #8581

**Comment by AlbaHerrerias** [comment] 2023-02-09 11:30
Yes, it looks like a duplicate. Fixed in https://github.com/pouchdb/pouchdb/pull/8583 and released in 8.0.1

**Closed by AlbaHerrerias** 2023-02-09 11:30 UTC
