### ISSUE TITLE
Pouchdb 7 doesn't work anymore with pouchdb-authentication

### ISSUE THREAD

**Issue by jbrun** [pouchdb/pouchdb#7355] opened 2018-06-26 07:48 UTC
Context
After updated from pouchdb 6.4.2 to 7.0.0 I have some troubles with authentication.
This code works fine before.
```
this._pouchDB = new PouchDB(this._pouchDbName);
this._remotePouchDB = new PouchDB(remoteCouchDBAddress, {skip_setup: true});
this._remotePouchDB.logIn(login, password).then(function (response) {
      self._pouchDB.replicate.from(self._remotePouchDB).on('complete', function (info) {
          ...
      }
}
```
After upgrading, the login phase works already well but when I replicate from, I have an 401 error :
{error: "unauthorized", reason: "one of _design, _reader is required for this request", status: 401, name: "unauthorized", message: "one of _design, _reader is required for this request"}

Your Environment
Version of PouchDB Authentication: 1.1.3
Version of PouchDB: 7.0.0
Platform name and version: Chrome
Operating System and version: Windows
Server: Cloudant

**Comment by ptitjes** [comment] 2018-06-26 08:36
Hi @jbrun. It is useless to open two issues. Let's handle the work on `pouchdb-authentication` in the issue you created there : https://github.com/pouchdb-community/pouchdb-authentication/issues/239.

As I just told you there, I have a work-in-progress : https://github.com/pouchdb-community/pouchdb-authentication/pull/238. It is working correctly on Node.js but I fail to have the `whatwg-fetch` polyfills to work in the browser tests. If you have any idea how to fix this, please contribute.

@daleharvey Would you mind to close this issue as a duplicate of https://github.com/pouchdb-community/pouchdb-authentication/issues/239 ? Thanks.

**Closed** 2018-06-26 08:56 UTC

**Comment by jbrun** [comment] 2018-06-26 08:57
Sorry I didn't know where was the problem.
I close this one
Duplicate of #pouchdb-community/pouchdb-authentication#239

**Comment by ptitjes** [comment] 2018-06-26 09:17
Thanks @jbrun !
