### ISSUE TITLE
Attachments loss

### ISSUE THREAD

**Issue by ermouth** [pouchdb/pouchdb#3961] opened 2015-06-13 06:08 UTC
On https://github.com/pouchdb/pouchdb/issues/3932, https://github.com/pouchdb/pouchdb/issues/3942.

__UPD. Disregard the post__, both fix and reason seem to be invalid :( More info in comments.

Seems that issue takes place in, at least, 3.2.1 and 3.3.1 and, possibly, 3.6.0 (did not test) because:
* timeout in ajax module is too short (1e4 hardcoded, smth around 1e6 look more reasonable)
* remote DB can have several docs with large atts (tens of megabytes) and fetching them induces timeout
* this case is somehow incorrectly handled
* doc is saved with original md5, but zero-length attachment(s).

If all above is correct it seems that Pouch never checks if attachment received from remote source is consistent to its digest.

As for 3.2.1 there was enough to increase timeout. For general fix I think it‘s reasonable to re-hash received data and revisit timeout handler.

Also this case shows why browser tests with CouchDB on `localhost` better be avoided. Virtual loop in general has much wider bandwidth capacity than any real end-user network.

I can reproduce it in all browsers with remote DB that contains several docs with large attachments. Please let me know if you also can. No code example since case is very specific to network conditions and DB, sorry.

Seems that https://github.com/pouchdb/pouchdb/issues/3932 could not be reproduced, even repeating steps provided exactly, because my remote DB had several large docs and my network is nearly always very busy.

To note – general practice to avoid this kind of issues is to have a test for each numeric constant inside the code, as well as for assumption under each particular constant.

**Comment by ermouth** [comment] 2015-06-13 13:08
In 3.6.0 situation seem to be more complex, still investigating.

**Comment by ermouth** [comment] 2015-06-14 08:47
All below is for Chrome.

I went down to IDB level and what I see is that Blobs can be fetched well with direct transactions, they have correct type, correct size, but I can not read these Blobs using FileReader. Any available method (readAsArrayBuffer, asBinaryString, asDataUrl, asText) – all fail with error "NotFound".

Code, that fetches attach, looks like this (think it‘s correct):

``` javascript
var res, req = indexedDB.open('_pouch_dbname');
req.onsuccess = function(e) {
  var db = e.target.result;
  db.transaction(["attach-store"], "readonly")
  .objectStore("attach-store")
  .get("md5-SBwxEsOQ1mwFXc3DLe4YSQ==")
  .onsuccess = function(e) {
  	console.log(res = e.target.result)	
  }
};
```
`res.blob` now must be valid Blob.

Blob itself remains sliceable, but slices are also unreadable.

All sympthoms remain the same to https://github.com/pouchdb/pouchdb/issues/3932 – I kill DB, create it, replicate from remote, see all files with attaches using Pouch, then close tab, wait a little, reopen it, replicate to and from again (NB: doing nothing in Futon) – and see zero-length attaches using Pouch.

Somewhere inbetween Pouch index engine works, but don‘t think it changes anything, since, as I understand, views have own DBs.

Until I close tab, everything is fine. I cannot even imagine what it can be. Even checked if my SSDs started to degrade – but found no errors.

The only specialty is that entire IDB (all objectStores) is quite large – about 1/2Gb. Also one of docs replicated is large JSON (~20Mb) and large attach (also ~20Mb).

All steps were performed manually, without any proxy shims or helpers. Sympthoms are same in 3.2.1 and 3.6.0.

Seems like situation somehow related to https://codereview.chromium.org/865013002

As for Opera and FF – very likely that issues I assumed to be same sympthoms, were just aborted replication and too optimistic test, assuming that replication finished succesfully.

Going to provide .couch with source DB – to allow repro.

**Comment by ermouth** [comment] 2015-06-14 12:11
It seems, that disabling Blobs for Chrome very likely solves the problem completely, at least for 3.2.1. Built custom 3.2.1 where `blobSupportPromise` always resolves to `false` in Chrome – and can not reproduce loss after several retries.

**Comment by nolanlawson** [comment] 2015-06-14 14:16
That's weird. The FileReader bug in Chrome should be fixed as of Chrome 43. It was [this Chromium issue](https://code.google.com/p/chromium/issues/detail?id=447836), and you can test it yourself. In at least that test case, it passes for me on Chrome 43.

Could it be that you had Blobs inserted into IndexedDB using an older version of Pouch (where we didn't detect the Chrome bug) and an older version of Chrome (where the bug wasn't fixed)?

BTW Opera will not teach us much, because they use the same engine as Chrome.

**Comment by ermouth** [comment] 2015-06-14 14:35
@nolanlawson as I know that bug was not applicable to Mac – and I use Mac, and Blobs were inserted by 3.2.1 yesterday last time. So it‘s very likely that bug is new.
But you know Chrome team nearly sweared several times before, that IDB is now stable – nevertheless new bugs were discovered each time they said everything is ~ok.
Going to send you and Dale .couch tomorrow if you feel you still interested in dissection of the bug.

**Comment by nolanlawson** [comment] 2015-06-14 14:53
@ermouth I'd be more interested in seeing an HTML test to reproduce, if this is indeed a Chrome bug. I wouldn't be surprised if they had another one. And yeah, I am testing on Mac as well.

It sounds like you're discovered a lot of bugs, but the big one (attachment loss) should be fixed by https://github.com/pouchdb/pouchdb/pull/3964. Please let me know if that resolves the attachment loss, or if the Chrome bug is also causing it.

**Comment by ermouth** [comment] 2015-06-14 15:33
@nolanlawson Reading the code I discovered a lot of optimistic assumptions, missing typechecks and possible edge cases, that may induce bugs. For example potential race was discovered without real bug, just walking through code.
Can prepare kinda explication of most noticeable moments if you interested. Like
`2487-2488 Presence of .stub does not mean we have no .data, and presence of .data::String and .content_type::String without .digest means we can just forget about .stub`
`3697 Presence of metastore does not mean integrity of the DB`
But do not think you‘re interested in this kind of stuff.

And, yeah, I‘ll try to prepare standalone HTML with repro of Blob bug – but it will be shipped with forked 3.2.1 with timeouts increased, or you just can‘t replicate-in 20Mb docs.

**Comment by nolanlawson** [comment] 2015-06-14 19:27
>  Reading the code I discovered a lot of optimistic assumptions, missing typechecks and possible edge cases, that may induce bugs.

Pull requests are welcome. :) Please fix bugs when you see them, even if you can't find a test! Sometimes we can determine the test given the fix.

> Presence of .stub does not mean we have no .data, and presence of .data::String and .content_type::String without .digest means we can just forget about .stub

Actually CouchDB gives this guarantee; it's just PouchDB that has screwed it up in the past. Hence we assume it everywhere except in the tests.

> And, yeah, I‘ll try to prepare standalone HTML with repro of Blob bug – but it will be shipped with forked 3.2.1 with timeouts increased

That's fine, but keep in mind the 3.2.1 doesn't have the Chrome fix (it came in 3.3.0, as I read through the release notes, see https://github.com/pouchdb/pouchdb/issues/3369 for details), so if you are using an old version of Chrome (pre-43), it will have the blob bug and there's nothing we can do about it. What version of Chrome are you using?

**Comment by nolanlawson** [comment] 2015-06-15 01:53
@ermouth Which version of CouchDB are you using?

**Comment by ermouth** [comment] 2015-06-15 08:34
@nolanlawson CouchDB 1.6.1, Chrome 43.

**Comment by ermouth** [comment] 2015-06-15 15:55
@nolanlawson @daleharvey I have something like a repro – but it works only both on my Mac and my Air. My collegues see non-zero values after running the second part.

To run the test:
* Please, open http://cloudwall.me/pouchdb/blobbug2.html and follow instructions. 
* After first part finished (in about 2-3 minutes) successfully, please close tab, 
* wait a little, 
* open second part. See URL of the second part in the first part description.

In the second part I see this http://jquerymy.com/pouchdb/blobfail6.png, but my collegues see valid numbers. 

I see valid numbers, only when I run test from other domain.

We also sorted out large DB as possible reason – one of my collegues has 1.8Gb IBD and see non-zeroes.

Any clues?

**Comment by daleharvey** [comment] 2015-06-15 18:01
Hrm, I am seeing non zero values in Chrome 43, if its only you that seems to be able to replicate this, could you send me your copies of 

```
~/Library/Application\ Support/Google/Chrome/Default/IndexedDB/http_cloudwall.me_0.indexeddb.leveldb
~/Library/Application\ Support/Google/Chrome/Default/IndexedDB/http_cloudwall.me_0.indexeddb.blob
```

? I am gonna try pinging a google engineer on this too

**Comment by daleharvey** [comment] 2015-06-15 18:04
I am also going to take a shot at corrupting data internally and see if I can get it to replicate those corruptions

**Comment by ermouth** [comment] 2015-06-15 19:29
@daleharvey sent you a link with short description of Mac where loss takes place.

Intriguing, that file in .blob/ folder has zero length o_O

**Comment by nolanlawson** [comment] 2015-06-15 20:05
@ermouth Hm, are you clearing out Chrome before re-running the test? (This browser extension is awesome: https://chrome.google.com/webstore/detail/clearbrowserdata/apehfighfmpoieeniallefdeibodgmmb) Have you tried other versions of Chrome (Canary/Chromium)?

**Comment by ermouth** [comment] 2015-06-15 20:44
@nolanlawson Thanks for extension – looks nice!

I‘m not clearing out anything since I assume that any DB is intended to persist data in the wild. Don‘t think that creating special sterile conditions is good for real-life part of testset. Another point is that wiping out can kill the bug that seems to be of very precious and rear specie :) 

About Chromium/Canary – I haven‘t tried.

**Comment by daleharvey** [comment] 2015-06-15 21:05
Yeh while you are the only person that can reproduce this I would be wary of clearing out data, can you continually run that test and see the failing condition? it sounds since nobody else can reproduce with your exact steps that it must be due to corrupt local data, going to retry with your profile data now

**Comment by daleharvey** [comment] 2015-06-15 21:10
Ugh nope, getting non zero lengths using your profile data too

**Comment by ermouth** [comment] 2015-06-15 21:32
@daleharvey I see this sympthom not only for cloudwall.me domain, but also for the domain where I have main working set. So I‘ll try tomorrow to wipe out everything local related to cloudwall.me.

> can you continually run that test and see the failing condition?

I‘ve tried many times, result is always the same, without exeption. Can even share screen via skype to let you see how it looks like.

So now I definitely need to sort out IDB as a reason. What the heck is the reason? What else can be the reason?

**Comment by ermouth** [comment] 2015-06-15 22:27
Recorded screencast https://youtu.be/JtxMadpPlT4

**Comment by ermouth** [comment] 2015-06-15 23:24
Extension did not help. 
Checked disk on restart and found this http://jquerymy.com/pouchdb/diskerrors.jpg 
Disk repair also did not help, but deletion of abovementioned folders helped – now can not reproduce. At least I have screencast :)

Closing. Thanks for help, deeply sorry for time spent.

**Comment by daleharvey** [comment] 2015-06-16 00:33
So from the symptoms it seems like somehow idb has got into a state where it can corrupt all attachment data since it works after you wipe that folder. I was hoping I could reproduce with your profile data but I guess just having the data in place isnt enough, something would need to have been applied (or I cant just chuck some profile data in there and assume the same state), the single zero length blob in that folder is definitely suspect @ermouth Can I share your profile data with an engineer from google? they have been helpful with fixing idb bugs before.

Given this, I think we can do a few things, we cant do a whole lot if indexeddb below us is corrupt, but we should be able to detect and prevent completely corrupt data from replicating ie we shouldnt be replicating a bunch of empty attachments, may need to checksum attachments or something. We can reused https://github.com/pouchdb/pouchdb/issues/3942 for this.

Then there is https://github.com/pouchdb/pouchdb/issues/3963 which has a fix

And there is https://github.com/pouchdb/pouchdb/issues/3962 which can be fixed by https://github.com/pouchdb/pouchdb/pull/3964

I think this was a bit of a perfect storm of different issues, with these 3 things in place we should be better protected from it happening again

**Comment by daleharvey** [comment] 2015-06-16 00:35
Also going to reopen this to track the corrupt attachments issue with chrome

**Comment by ermouth** [comment] 2015-06-16 01:02
Yes, you can share. Dump from cloudwall contains no sensitive information, that is not SHA256-encrypted.

For me it‘s much more likely, that the reason is degraded SSDs (but I‘m not sure, since have no deep knowledge on the topic). Both machines that had the bug, has SSDs, and both IDBs (I mean IDBs for two domains), where bug was noticed, were extremely heavily used day and night for months. Both machines nearly always are on, and have tabs with cloudwall opened. So I suspect SSD.

Disk checks I performed on running OS although did not show any problems (that is strange), I had to restart machines with Cmd-R and run disk utility to see faults on both FS. I did it, when understood that no more reasons can exist, but filesystem fault.

I also plan to change cloudwall code to prevent zero-length attaches from saving – it was the reason they could spread. First I read docs with them, then saved – and they leaked to Couch and then, eventually, to S3. You can see how it looks, opening https://cloudwall.smileupps.com/blobbugsample/142731838701xkwbk0ra for example. DB I provided as sample in repro, is a clone of not fully repaired build of cloudwall.

> may need to checksum attachments

You can hardcode md5 of zero-length and compare it with attach digest if attach itself has zero-length. If digest saved differs from `md5-cCkGbCesb17xjWYNV0GXmg==`, file is corrupted.

Again, thanks a lot for patience and help, and deepest apologize for my rudeness and pressure. Although Pouch have some errors, data loss per se definitely was not induced by Pouch.

**Comment by nolanlawson** [comment] 2015-06-16 01:34
@ermouth It's okay, no hard feelings. IndexedDB is still a young technology, and our goal with PouchDB is to push the limits, so that we can move the web forward. We've had plenty of growing pains, and I've lost count of the number of bugs I've filed on the various browsers.

I do think @inexorabletash at Google would be very interested in these results, although we should probably compile them into a succinct bug report and file it on Chromium. Can you confirm that this data was created exclusively in Chrome 43? Or was some of it created in <=42 and then updated to 43?

Thanks again for all your effort to catalog these bugs and provided reproducible tests; it is deeply appreciated.

**Comment by ermouth** [comment] 2015-06-16 01:45
> Can you confirm that this data was created exclusively in Chrome 43? Or was some of it created in <=42 and then updated to 43?

As I can recollect, those data, at least _pouch_ardsk DB, was created not later than October 2014.

**Comment by ermouth** [comment] 2015-06-16 09:57
As for iMac SSD degradation does not seem to be an answer. Just found this in logs:
```
/dev/rdisk2: ** Checking catalog file.
/dev/rdisk2:    Incorrect block count for file 000000000000000e.db
/dev/rdisk2:    (It should be 245 instead of 6150)
/dev/rdisk2:    Incorrect block count for file 0000000000000016.db
/dev/rdisk2:    (It should be 44 instead of 6515)
/dev/rdisk2: ** Checking multi-linked files.
/dev/rdisk2: ** Checking catalog hierarchy.
/dev/rdisk2: ** Checking extended attributes file.
/dev/rdisk2: ** Checking volume bitmap.
/dev/rdisk2:    Volume bitmap needs minor repair for orphaned blocks
/dev/rdisk2: ** Checking volume information.
/dev/rdisk2:    Invalid volume free block count
```
AFAIK rdisk2 for iMac fusion drive is conventional HDD, not SSD. Also was absolutely sure fsck can not write logs when checks disks on reboot.

**Comment by ermouth** [comment] 2015-06-16 10:51
As for MB Air – it‘s definitely SSD degradation. http://jquerymy.com/pouchdb/diskerrors-air.jpg
Short translation: “Can‘t repair using Disk Utility, so backup, format and repair from backup”.

**Comment by kxepal** [comment] 2015-06-16 12:22
> You can hardcode md5 of zero-length and compare it with attach digest if attach itself has zero-length. If digest saved differs from md5-cCkGbCesb17xjWYNV0GXmg==, file is corrupted.

Digest for zero-length attachment is `md5-1B2M2Y8AsgTpgAmY7PhCfg==`. But idea is good.

**Comment by ermouth** [comment] 2015-06-16 12:28
@kxepal opening this https://cloudwall.smileupps.com/blobbugsample/142731838701xkwbk0ra and scrolling down to bottom I see, that zero-length attachments all have digest `md5-cCkGbCesb17xjWYNV0GXmg==`, not `...Cfg==`. Also I see this in my local CouchDB. 

How can it happen?

**Comment by kxepal** [comment] 2015-06-16 12:34
@ermouth gzip encoding I guess:

```
{
    "_id": "test",
    "_rev": "3-061a44969eac46d0d7b15b8563ba9ac0",
    "_attachments": {
        "zero.txt": {
            "content_type": "text/plain",
            "revpos": 3,
            "digest": "md5-cCkGbCesb17xjWYNV0GXmg==",
            "length": 0,
            "stub": true,
            "encoding": "gzip",
            "encoded_length": 20
        },
        "zero": {
            "content_type": "application/octet-stream",
            "revpos": 2,
            "digest": "md5-1B2M2Y8AsgTpgAmY7PhCfg==",
            "length": 0,
            "stub": true
        }
    }
}```

**Comment by ermouth** [comment] 2015-06-16 12:44
@kxepal WOW! Thank you, didn‘t know about it. Two questions:
* How do you obtain this kind of stats?
* Doesn‘t it mean, that digests are useless for checking integrity of received and unpacked attachment during replication?

**Comment by kxepal** [comment] 2015-06-16 12:58
@ermouth 

> How do you obtain this kind of stats?

That information returns when document is requested with `?atts_encoding_info=true` request parameter. If attachment MIME type is defined in [compressible types](http://docs.couchdb.org/en/1.6.1/config/misc.html#attachments/compressible_types) then it content automagically becomes compressed with gzip and this parameter reveals that fact.

> Doesn‘t it mean, that digests are useless for checking integrity of received and unpacked attachment during replication?

Technically, yes, but since only gzip compression type is supported and since it has limited amount of compression levels, it wouldn't be hard to maintain list of hashes against empty content. More generic solution could be also to decode gzip header, extract compression level and match with the related digest to not iterate over all possible values (but not sure if this would be faster/simpler).

Till the time when browsers will support more interesting compression methods, like snappy, some more solid solution will be found to detect attachment corruption, so as temporary workaround it's fine, imho.

**Comment by nolanlawson** [comment] 2015-06-16 13:57
> Doesn‘t it mean, that digests are useless for checking integrity of received and unpacked attachment during replication?

Yeah, Couch and Pouch will actually evaluate the digests differently sometimes, due to differences in Erlang, browser, even operating system. Basically the browser can only trust the checksum for checksums it itself has generated.

**Comment by kxepal** [comment] 2015-06-16 14:20
@nolanlawson For digest, [there are no](https://github.com/apache/couchdb-couch/blob/master/src/couch_att.erl#L447-L450) specific Erlang bits. I guess, compression was the root of those differences, but only. It's hard to produce different digests using the same algorithms for the same data unless there is bug in their implementation (:

**Comment by nolanlawson** [comment] 2015-06-18 03:44
@kxepal It only occurs with strings (`content_type: plain/text`). It definitely happens, though, and we work around it in the unit tests, e.g. [these lines](https://github.com/pouchdb/pouchdb/blob/5ef48cd7af94302fa074ddc2b8bb736c7151d448/tests/integration/test.attachments.js#L1194-L1200).

**Comment by ermouth** [comment] 2015-06-18 09:30
@nolanlawson Couldn‘t it be somehow related with BOM?

**Comment by daleharvey** [comment] 2015-06-22 04:09
So the issue of ensuring we dont read out and certainly dont replicate corrupt data is being tracked in https://github.com/pouchdb/pouchdb/issues/3942

**Closed by daleharvey** 2015-06-22 04:09 UTC
