### ISSUE TITLE
React Native Compatibility

### ISSUE THREAD

**Issue by siuying** [pouchdb/pouchdb#4755] opened 2016-01-07 09:50 UTC
Consider last issue about this (#3787) is some time ago, I figured React Native have changed a lot. 

At this point I just want to include PouchDB as a CouchBase lite client. When I try to include it with vanilla React native, I get follow error on compile time:

```
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module request from /Users/siuying/workspace/parchment/electron-parchment/node_modules/pouchdb/lib/deps/ajax/ajaxCore.js: Invalid directory /Users/node_modules/lib/deps/ajax/request-browser.js
```

I think its because the ``package.json``:

``
"browser": {
    ...
    "request": "./lib/deps/ajax/request-browser.js"
  }
``

and react native packager cannot find the file. Any idea how I could workaround this issue?

**Comment by nickcolley** [comment] 2016-01-07 10:03
The upcoming release of PouchDB changes a few things regarding the build process so this might be fixed when that lands. (Which should be soon)

https://github.com/pouchdb/pouchdb/issues/4700

**Comment by siuying** [comment] 2016-01-07 10:08
Thanks, I'll try using head from pouchdb/pouchdb to see if it work

**Comment by siuying** [comment] 2016-01-07 15:04
Cannot get it work using ``git+https`` or ``pouchdb/pouchdb`` in the pouchdb entry in package.json, it just cant found the module. Will wait for next release and see.

**Comment by carbureted** [comment] 2016-01-09 08:21
I just got pouchdb running on react-native locally with sqlite3 as a storage engine, albeit more than a little hackily! Check it out. For requiring pouchdb, var PouchDB = require('./node_modules/pouchdb/dist/pouchdb.min.js') *seems* okay-ish.

https://gist.github.com/carbureted/88d207ddfc9d2157902f

**Comment by carbureted** [comment] 2016-01-22 03:02
For anyone interested in pouch/react-native, check out the module I just made - https://github.com/carbureted/react-native-pouchdb/. The only necessary change to pouchdb core was detecting react-native and using fetch instead of xhr in request-browser.js. Would this be appropriate to submit as a pull request, or is it too niche?

```
function isReactNative() {
  try {
    return navigator.product == "ReactNative"
  }
  catch(e) {
    return false
  }
}

var hasXhr = testXhr();

function ajax$1(options, callback) {
  if ((hasXhr || options.xhr) && !isReactNative()) {
    return xhRequest(options, callback);
  } else {
    return fetchRequest(options, callback);
  }
}
```

**Comment by daleharvey** [comment] 2016-01-22 08:14
would 

```
function isReactNative() { 
  return 'product' in navigator && navigator.product === 'ReactNative';
}
```
work? 

would like to avoid the try catch if we can, but either way would be happy to accept this in core, ideally we would be able to get this tested in ci but hand tested for early patches is ok

**Comment by nolanlawson** [comment] 2016-01-23 14:58
Correct me if I'm wrong, but it sounds like the issue is that React Native has a buggy implementation of XHR, but a non-buggy implementation of `fetch()`. (Neither are provided by JSCore AFAIK.)

So why should the fix be to work around the buggy implementation? Couldn't we do them a favor and fix their XHR instead? I'm not eager to put in hacks to PouchDB core to work around bugs in another library, that could be more easily fixed by opening a PR on the other library.

BTW another solution to this problem is to just

```js
var oldXHR = XMLHttpRequest;
delete XMLHttpRequest;
// load pouchdb
XMLHttpRequest = oldXHR;
```

Alternatively, we could try preferring `fetch()` to XHR, but IIRC there were issues with that stemming from buggy browser implementations of `fetch()` (which are not so easily fixed by a PR, heh).

**Comment by abuisman** [comment] 2016-03-23 22:00
So I just tried pouchdb in react-native 0.19 and I am surprised to see it working. So `npm install pouchdb` and `var PouchDB = require('pouchdb');`. 

My code:

````
process.nextTick = setImmediate; //Crucial part it seems
var db = new PouchDB('my_database');

var sync = PouchDB.sync('kittydb3', 'http://myUrl', {
  live: true,
  retry: true
})

db.allDocs({include_docs: true}).then(function(docs){
  console.info('docs', docs);
})
````

I ran some basic create, fetch and syncs with remote database, stopped the app and started again and got the docs again, etc.

Could someone confirm please?

As you can see you will have to add `process.nextTick = setImmediate;` as a polyfill as per https://github.com/spencercarli/meteor-todos-react-native/blob/master/ReactNativeTodos/app/config/db/lib/process.polyfill.js

What I am wondering though is whether adding https://github.com/tradle/asyncstorage-down wouldn't solve the issue as well. I am however unsure about how to add it as an adapter when initializing pouchdb. Could someone show me the code to do so?

**Comment by carbureted** [comment] 2016-03-23 22:40
Nice! Have you tried running it without the debug tools on? 

Something I noticed is that the react-native javascript environment seems to gain some browser APIs not implemented in the production environment while the dev tools are on (I assume it's the side effect of some hack to get it talking with Chrome but haven't looked into it at all, just shimmed whatever I needed). For instance, the last time I checked JavaScriptCore doesn't have btoa, which was causing pouch to crash.

**Comment by abuisman** [comment] 2016-03-24 11:11
@carbureted What would I need to do in order to run without the debug tools? Is it enough to disable them in the cmd+d menu? 'disable chrome debugging' or would I have to do more?

Also, can you, or anyone else for that matter, tell me what code I need to use in order to have 'asyncstorage-down' available as an adapter and use it with pouch?

**Comment by nolanlawson** [comment] 2016-03-24 16:27
I started working on an adapter implementation here, however it is unfinished: https://github.com/nolanlawson/pouchdb-async-storage. It may point you in the right direction, though.

**Comment by carbureted** [comment] 2016-03-25 22:46
@abuisman The steps for building for production are [here](https://facebook.github.io/react-native/docs/debugging.html#debugging-react-native-apps). For asyncstorage-down, I assume you're talking about this - https://github.com/tradle/asyncstorage-down. I haven't used it, so I can't tell you exactly what you'll need to do to get it working.

**Comment by stockulus** [comment] 2016-04-25 17:30
I got PouchDB finally running on react-native with AsyncStorage.

Polyfill I needed + some Packages:
```js
global.Buffer = global.Buffer || require('buffer').Buffer;
process.version = process.version || 'react-native';
process.nextTick = process.nextTick || ((func) => setTimeout(func, 0));
```
[AsyncDownAdapter](https://www.npmjs.com/package/pouchdb-asyncstorage-down)

I'll continue to work on this, get it tested automatic + do Performance tests.
Feedback welcome Twitter @stockulus

**Comment by renato** [comment] 2016-04-26 03:40
@nolanlawson Are these comments still true?

"one thing is React Native's AsyncStorage is very very unsuitable for any heavy access or large amounts of key/values" https://github.com/pouchdb/pouchdb/issues/3787#issuecomment-100830713

"asyncstorage-down is also a pretty inefficient usage even of AsyncStorage, because it's based on localstorage-down, which has no key iteration and thus keeps all keys in memory" https://github.com/pouchdb/pouchdb/issues/3787#issuecomment-100928752

I just found https://github.com/couchbaselabs/react-native-couchbase-lite, I've never used it but I'm considering it as it uses the native versions of Couchbase Lite exposed in a JS API.

**Comment by nolanlawson** [comment] 2016-04-26 05:26
Those statements are still true. Hence why I'm looking now into solving this problem using [the node-websql approach](https://github.com/nolanlawson/node-websql#custom-sqlite3-bindings) instead. As for Couchbase Lite, I really don't know much about it.

**Comment by nolanlawson** [comment] 2016-05-20 00:06
I'm going to close this, because this can be handled outside of PouchDB core, especially once the monorepo/subpackages rewrite is out. Then anyone will be able to write custom PouchDB adapters and easily include them as plugins. (In fact you can already do this today, but the monorepo will make it a bit easier.)

**Closed by nolanlawson** 2016-05-20 00:06 UTC
Labels: bug
