### ISSUE TITLE
Help Needed: Generic PouchDB adapter <-> Cordova Plugin Interface

### ISSUE THREAD

**Issue by jfspencer** [pouchdb/pouchdb#7013] opened 2018-01-16 05:11 UTC
### Info
- Environment: hybrid app
- Platform: iOS/Android
- Adapter: New Generic Cordova Plugin Adapter

### Want to write a generic pouchDB adapter that hooks into the Cordova plugin interface
I would like to use pouchDB, but I want to pair it with native datastores other than sqlite. I have looked through the existing adapters but am having a hard time separating the storage implementation from the common pouchDB adapter interface. All I am looking for here is a Cordova plugin that complies as a pouchDB adapter, this adapter would just be hooks to the Cordova plugin. The datastore implementation would be written on the native layer. 

If I can get this working, I would be writing adapters for Realm and Couchbase Lite2.

would it be fairly easy for one of the adapter maintainers to write a blank pouch adapter to hook into?

If not I would like to help as much as possible. Some help documenting the api footprint would be greatly appreciated, things like

- what does pouchDB do/need on initialization
- what is the general I/O behavior of the adapter layer
- is this the complete API, and what are pouchDB data structure requirements for each
    - api._meta
    - api._remote
    - api._id
    - api._bulkDocs
    - api._get
    - api._getAttachment
    - api._info
    - api._allDocs
    - api._changes
    - api._close
    - api._getRevisionTree
    - api._doCompaction
    - api._getLocal
    - api._putLocal
    - api._removeLocal
    - api._destroy

**Comment by daleharvey** [comment] 2018-01-18 14:30
So the last adapter written was the indexeddb one https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-adapter-indexeddb

Writing a new.adapter I would copy and.paste that and switch out the implementations where indexeddb is used.

**Comment by daleharvey** [comment] 2018-01-18 14:32
For the questions, would use the code as reference but pouch doesn't need adapters to do anything on construction, the io is just callbacks (would love to switch to promises, big job for small benefit though)

**Comment by jfspencer** [comment] 2018-01-19 02:27
Thanks. I'll start on indexeddb.

**Comment by daleharvey** [comment] 2018-01-19 06:04
Ok cool, not a bug so closing this out but if you have more questions feel free to post them here or the mailing list

**Closed by daleharvey** 2018-01-19 06:04 UTC
