### ISSUE TITLE
Duplicate "replication" docs in Pouch 3.3.1

### ISSUE THREAD

**Issue by hakan1111** [pouchdb/pouchdb#3673] opened 2015-03-30 07:43 UTC
Hi,
we are running your excellent Pouch db in a setup where we replicate continuously from local Pouch db to Couch db. Recently we have found a strange issue which we can not understand, nor reproduce, but it has happened now a few times. 
The issue is that we find 2 "replication" documents in Pouch - ie, the "replication" doc is the one that keeps track of the current checkpoint (last_seq) number (example "_local/jUrbH_ICrwKZ4EeRFEqheg==". 
There might be a connection to a "409" error message that we are seeing in connection to this, ie when Pouch does "PUT _local/jUrbH_ICrwKZ4EeRFEqheg==" to Couch then there is a 409 response.

Can you think of any case when this could happen? We are kind of clueless here...

**Comment by hakan1111** [comment] 2015-03-30 07:51
![pouch_checkpoint](https://cloud.githubusercontent.com/assets/11521724/6892190/38b3b8cc-d6c2-11e4-86aa-89b753afb52b.png)

Attaching a screen-shot to clarify

**Comment by nolanlawson** [comment] 2015-04-12 16:28
The 409 error message is normal, but what's not normal is two different checkpoint docs being written. If you have a live test case to reproduce that would be wonderful; else I am stumped as to how this could be happening, unless somehow you are actually replicating from two remote DBs or you subtly change the options when you replicate (e.g. changing the filter).

**Comment by hakan1111** [comment] 2015-04-12 20:28
Hi Nolan, and thanks for the answer.
I am sorry to say that I can not reproduce this, but will keep looking and get back with more info if I have it.
BR /Håkan

**Comment by daleharvey** [comment] 2015-07-22 12:41
Unable to reproduce, very possible a filter issue but closing out, please reopen if you can still see any issues we need to look into

**Closed by daleharvey** 2015-07-22 12:41 UTC
