### ISSUE TITLE
Feature request: support for Cloudant Query

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#2422] opened 2014-06-26 00:51 UTC
Cloudant just introduced an awesome new query system very similar to MongoDB. It would be very nice to also have this functionality build into a PouchDB plugin.

https://docs.cloudant.com/api/cloudant-query.html

**Comment by slawo** [comment] 2015-01-19 14:03
this would be ++good

**Comment by nolanlawson** [comment] 2015-01-19 15:40
Progress is being made: https://github.com/nolanlawson/pouchdb-indexes

**Comment by nickcolley** [comment] 2015-01-20 21:25
:balloon: so excite

**Comment by nolanlawson** [comment] 2015-01-25 22:49
pouchdb-find 0.1.0 is out: https://github.com/nolanlawson/pouchdb-find

**Comment by nickcolley** [comment] 2015-01-25 23:27
Looking sweeet!

**Comment by colinskow** [comment] 2015-01-26 08:03
It's a late Christmas present!!! Thanks Nolan, can't wait to play with it.

**Comment by daleharvey** [comment] 2015-07-07 12:14
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/3538, it works, we can start the discussion about it being in core :)

**Closed by daleharvey** 2015-07-07 12:14 UTC
