### ISSUE TITLE
changes() leaks memory

### ISSUE THREAD

**Issue by cztomsik** [pouchdb/pouchdb#6502] opened 2017-05-15 12:15 UTC
Any `changes()` call without `return_docs: false` leaks memory

It seems that `return_docs` is effective even for http connections unlike from what is mentioned in the docs:
> Is available for non-http databases and defaults to true

### Reproduce
```
const db = new PouchDB('http://127.0.0.1:5984/skimdb')

db.changes({
  include_docs: true,
  batch_size: 1000
}).on('change', (c) => {
  // doesnt matter
})
```

What happens is that it will "slow down" after first ~50 000 seqs - because of excessive memory usage (few seconds and it's hundreds MBs). I am not sure if it relates to any existing issue so I am creating new one.

This might be resolved by:
1. updating docs (along with examples)
2. making `return_docs: false` default for http databases

**Comment by vvo** [comment] 2017-05-15 17:37
Just stumbled on this too, we have been facing a memory leak on https://github.com/algolia/npm-search and have been searching for it a bit.

I will use this `return_docs: false` and see what happens. The docs says `[return_docs] Is available for non-http databases and defaults to true`.

We are using the http adapter, but strangely the code of the http adapter sets return_docs to true by default, see https://github.com/pouchdb/pouchdb/blob/d483bdf78a295b71cb43419d285b0eed2fcf360d/packages/node_modules/pouchdb-adapter-http/src/index.js#L777

Not sure this as anything to do with our leak but will try.

**Comment by Haroenv** [comment] 2017-05-16 07:41
This did fix our memory leak, so maybe `return_docs` should always be `false` by default.

**Comment by vvo** [comment] 2017-05-16 07:50
> maybe return_docs should always be false by default.

Yes in the http couch adapter, will wait for a more knowledgeable person to confirm this.

**Comment by vvo** [comment] 2017-05-22 08:26
@willholley If you need more insights let us know, for now this is mostly a documentation issue. The doc says that if you are only using a http layer or DB then you are fine, changes will not leak. But that's not the case because the actual http pouchdb layer sets returnDocs: true by default.

**Comment by willholley** [comment] 2017-05-22 08:43
thanks @vvo - will do

**Comment by daleharvey** [comment] 2017-06-24 09:10
So yup the documentation is wrong here, however we should not be setting different defaults for http or not, we should fix the documentation for whether this option is available for http adapters

Seperately we could change the default for all adapters to returnDocs = false, or more drastically remove the option for `returnDocs` at all and require any changes listeners to collect their own results

**Comment by cztomsik** [comment] 2017-06-24 09:55
just fixing docs is fine :)

**Comment by vvo** [comment] 2017-06-24 13:29
The documentation is wrong on two aspects: we say that the http adapter is not using returnDocs and that's it's false by default.

You can passe returnDocs when using an http adapter and it's true by default.

**Comment by jareware** [comment] 2017-08-03 08:51
FWIW, we just spent a long time wondering where our memory is being retained in a long-running process perusing `changes()` and think this is the cause. +1 for:

> or more drastically remove the option for returnDocs at all and require any changes listeners to collect their own results

Anecdotally, I didn't even know you can use the `complete` event for collecting your results, and have always collected them myself in `change`. :)

**Comment by alxndrsn** [comment] 2018-02-26 09:49
Documentation still needs updating.

**Comment by daleharvey** [comment] 2018-04-04 10:58
ok got a fix for this up, return_docs defaults to true unless opts.live = true, then it default is false, updated the document to match reality as well - https://github.com/pouchdb/pouchdb/pull/7211

**Closed** 2018-04-04 14:45 UTC
