### ISSUE TITLE
Browser modal authentication window raised on normal detection 401 during sync with Cloudant

### ISSUE THREAD

**Issue by tdupard** [pouchdb/pouchdb#4748] opened 2016-01-06 18:11 UTC
A modal authentication window is raised by the browser on "normal detection" 401 during sync with Cloudant.

I get the reason for the 401 from the log (see below message), but is there a way to suppress the modal window? If the window is cancelled away the sync happens normally.

"The above 401 is totally normal. PouchDB is just detecting if the remote supports the _bulk_get API."

Tested on: FF 43, IE Edge, Chrome 47

**Comment by daleharvey** [comment] 2016-01-06 18:16
Is your cloudant instance password protected? if you check the log do we not sent the correct credentials when checking for `bulk_get`?

**Comment by tdupard** [comment] 2016-01-06 18:28
That is correct, I can see the
   "Authorization: Basic ZDY2NDllMTItNmXXXXXX...." header in the other requests, like '_changes' but not in the '_bulk_get' request.

**Comment by daleharvey** [comment] 2016-01-06 18:32
How do you set the credentials, in the constructor or on the actual request?

**Comment by tdupard** [comment] 2016-01-06 18:37
I am passing the url with credentials embedded to the constructor:

var remoteCouch = 'https://XXXX:XXXXX.cloudant.com/' + dbName;

var sync = PouchDB.sync(dbName, remoteCouch, {
		  live: true,
		  retry: true
		}

**Comment by daleharvey** [comment] 2016-01-06 18:45
That is very strange, they should definitely be passed into that call then, taking a look, cheers for the follow up info

**Comment by twitwi** [comment] 2016-01-09 19:22
I observe the same problem in the same context (syncing to cloudant with credentials in the URL).

Also, I'm not sure it is totally related but when the same application is deployed on android using ionic (with the same cloudant sync), it also fails at subsequent synchronization. I didn't dig more on this one.

**Comment by willholley** [comment] 2016-01-09 20:17
I thought it was expected that we don't sent authorization to _bulk_get with Cloudant because the preflight response does not allow it (see https://github.com/pouchdb/pouchdb/issues/4613)? I still wouldn't expect a model dialog. @tdupard are you able to share your Cloudant username / raise a support ticket so I can check the logs on our side?

**Comment by tdupard** [comment] 2016-01-09 20:55
@willholley, sure, what is the best to do that? Do you want me to send my credentials to your Gmail?  But the authentication window is consistent across FF, Chrome and IE so far. My Cloudant creds were created in Bluemix if it maters...

**Comment by daleharvey** [comment] 2016-01-09 20:56
If we arent sending credentials then it seems like it has to be a bug on the pouch side, I was certain I fixed all of them but I will take another look

**Comment by willholley** [comment] 2016-01-09 21:13
hmm. To be clear, Cloudant omits "authorization" from "Access-Control-Allow-Headers" when a preflight request is made to an endpoint that doesn't exist (i.e. _bulk_get). The client is doing the correct thing by not sending an "authorization" header in the subsequent request.

**Comment by willholley** [comment] 2016-01-09 21:13
possibly this is a bug on the Cloudant side but I haven't seen it cause problems until now.

**Comment by willholley** [comment] 2016-01-09 21:16
@tdupard can you open a ticket directly with the Cloudant team with an email to support@cloudant.com? Be sure to include your database URL. You can email me the ticket number if you like, else I'll keep an eye out for it.

**Comment by tdupard** [comment] 2016-01-09 21:36
@willholley will do, thanks.
Thanks for the quick follow up @daleharvey.

**Comment by tdupard** [comment] 2016-01-09 21:55
In the mean time is there a way to suppress the check for _bulk_get the PouchDb Synch() method's options?
I am not sure if it is checking for efficiency purpose but I am replicating a very small set of docs of very small size. Just wondering.

**Comment by willholley** [comment] 2016-01-10 09:33
ok - I'm able to reproduce this. It seems that we send a 'WWW-Authenticate:Basic realm="Cloudant Private Database"' header in the 401 response to _bulk_get, causing the browser to prompt for credentials. I'll see if we can suppress this.

**Comment by willholley** [comment] 2016-01-10 09:48
as a short term fix, I wonder if we're better off detecting Cloudant / older CouchDB versions with db.info to shortcut the _bulk_get test?

**Comment by daleharvey** [comment] 2016-02-04 10:30
It is sounding like this is fixed and cloudant will have `bulk_get` soon as a bonus, so closing out

**Closed by daleharvey** 2016-02-04 10:30 UTC
Labels: bug
