### ISSUE TITLE
Existing events don't allow to monitor the status of replication while { live: true }

### ISSUE THREAD

**Issue by acelot** [pouchdb/pouchdb#3507] opened 2015-02-06 03:44 UTC
I want to implement a simple synchronization status indicator with the following states:

1. **Active** (spinning refresh icon) – when PouchDB is getting changes or downloading attachments.
2. **Paused** (check icon) – when PouchDB is idle and waiting changes from both sides.
3. **Stopped** (stop icon) – when sync is cancelled.
4. **Error** (exclamation icon) – when something went wrong.

At this time PouchDB 3.3.0 firing `pause` event even though it downloading attachments. I may not be right, but it seems to me that the `pause` event should be fired when all the active downloads are finished.

Another question is it how to detect that local changes are synced?

**Comment by daleharvey** [comment] 2015-02-06 22:52
@acelot as you listed is exactly how it should behave, you mention attachments, is there any chance you have a reproducible case? there are some known issues with these events and would like to get them drilled down

**Comment by acelot** [comment] 2015-02-07 13:00
@daleharvey I'm preparing an example. I'll let you know ASAP.

**Comment by daleharvey** [comment] 2015-08-04 20:31
we have quite a few open bugs on this, so gonna close this as dupe

**Closed by daleharvey** 2015-08-04 20:31 UTC
