### ISSUE TITLE
.query() bug when updating documents

### ISSUE THREAD

**Issue by bgold0** [pouchdb/pouchdb#7293] opened 2018-05-24 17:06 UTC
### Issue
`.query()` function is not returning what it is supposed to. If I do `allDocs()` it works as designed. I've destroyed the database and done this over and over again with the same result.

### Info
- Environment: **react-native**
- Platform: **iOS**
- Adapter: **asyncstorage**
- Server: **pouchDB / cloudant**

### Reproduce

Let's say I have these three documents:

	{ "_id": "11111", "type": "template", "name": "person" }
	{ "_id": "22222", "type": "template", "name": "place" }
	{ "_id": "33333", "type": "template", "name": "thing" }

I have a cloud database and then I have a device with pouchDB syncing from that database.

These are the steps that I do:

1. I sync both databases together. So now I have the most recent versions of this document on my device.
2. I run the below query and I get back all three templates like so:

**Code**
    
    var template_obj = {};

    return device_db.query('filters/templates')
    .then((templates) => {
		for (let t of templates.rows) templates_obj[t.id] = true;
		return templates_obj;
	});

**filters/templates**

    function (doc) {
      if(doc.type == "template")
        emit(doc._id);
    }

**return**
    
    {"11111": true, "22222": true, "33333": true}

3. I update template: person on cloud. And then I update it again. So 2 revisions have gone by without syncing to my device.

4. I sync with my device.
5. Now when I run the same query and I only get back the document I edited. Which is weird because I haven't touched any of the other documents. The same view returns the expected results on the cloud but not on the device.

**return**
    
    {"11111": true}

6. If I do the following code however, all templates come back as normal and the same `_rev` from the cloud show up on the device. Meaning the sync was successful and view is getting confused.

**new code**

    return device_db.allDocs({conflicts: true})
	.then((data) => {
	    for (let d of data.rows) {
	        if(d.doc.type == "template") {
	        	templates_obj[d.doc._id] = true;
	        }
	    }
	    return templates_obj;
	 }).catch((err) => {
		console.log(JSON.stringify(err));
	})

I'm starting to believe this is a bug because if I destroy my database and do these steps again, I can reproduce this issue.

**Comment by EternalDeiwos** [comment] 2018-06-02 15:22
Also experiencing something similar to this.

What's weird is that it happily allows me to query the database (with indices etc.) after my initialisation steps (which include calls to `db.put({ ... })`); but when I make changes afterward then I only get the doc that I just made changes to.

The docs are definitely still in the database because `db.allDocs()` still works as intended.

**Comment by greenais** [comment] 2018-07-01 10:51
The same here - only the first doc is showed up in query.
With only difference that I don't replicate docs from CouchDB (as doc_ids filter doesn't work, I still have no idea why - filed an issue in pouchdb-react-native) - but getting them one-by-one from CouchDB and saving locally.

Moreover - in some cases .query() throws a really weird "Document update conflict" error - on single query call, no other in parallel/pending. How is it even possible?

### Info
- Environment: "pouchdb-react-native": "6.4.1"
- Platform: Android
- Adapter: asyncstorage
- Server: CouchDB 2.1.1

**Comment by greenais** [comment] 2018-07-15 06:45
I can confirm that after manaul combining latest PDB plugins queries work as expected, no issues.
No outdated pouchdb-react-native is needed, like this:

```
import PouchDB from 'pouchdb-core';
PouchDB
.plugin(require('pouchdb-adapter-asyncstorage').default)
.plugin(require('pouchdb-adapter-http'))
.plugin(require('pouchdb-mapreduce'))
.plugin(require('pouchdb-replication'))
.plugin(require('pouchdb-authentication'));
const localDB = new PouchDB(localDBname, {adapter: 'asyncstorage', auto_compaction: true});

```

**Comment by EternalDeiwos** [comment] 2018-07-15 10:12
My problem still persists, although rather than what is described in the OP of this issue, mine is more similar to #7188 or #7219 (the same underlying problem -- the issues were merged to this one).

Was there something done in the 7.0 pre-release that would fix this problem? I've been looking at commit logs and don't see anything in particular.

**Comment by daleharvey** [comment] 2018-07-15 10:16
I doubt it, its a strange sounding bug and seems like one we have tests for, if you could make a reproduction on https://pouchdb-bug-helper.glitch.me/ it would make it a lot easier to fix

**Comment by EternalDeiwos** [comment] 2018-07-15 10:32
@daleharvey I recall trying @warrenbell's snippet in #7219 to confirm about a month or so ago.

I'll try reproducing the problem and reporting here sometime, unless someone beats me to it. I'm not sure when I'll get to it.

Just a thought: I've noticed that all of the related issues filed have been about react-native. It could be something on that end. Before I try reproduce the problem using your glitch.me link, I'll update my RN and try again.

**Comment by greenais** [comment] 2018-07-15 10:44
I guess it could be a bit unrelevant to make examples in V8 JS browser environments - as RN JS engine is JavaScriptCore + Babel on top of code.
Probably it will be a good try to test same code in small React web app + webpack/babel, but I'm still not sure that it could 100% represent RN environment - as it will be browser and V8 engine.

**Comment by pt7892** [comment] 2018-07-30 08:59
Any updates about this issue? Also facing the same problem using with react native.

**Comment by greenais** [comment] 2018-07-30 14:18
I doublechecked - in browser environments (I tried Chrome, FF, Opera, even IE, not Safari - I don't have Mac) everything works as expected, no issues: after update changes from CDB - views bring up proper set of docs, not just last changed one only. 
.query() is broken only in RN environment, based on JavaScriptCore. 
AFAIK Safari is based on JSC as well, so probably devs could check it against Safari as first possible step to sort out the root of issues?
It seems like something is being messed in pouchdb-mapreduce plugin under JSC, but only PDB devs could tell what to check there..
So we (RN people) are waiting in hope (taking, off cause, into account that PDB wasn't intended to work in RN environment, browsers and node only were claimed). But RN is quite fast expanding market so let's hope it will be considered.

**Comment by bgold0** [comment] 2018-07-30 14:20
For anyone looking for an alternative, I've completely abandoned the `.query()` and moved onto `.find()` which works without any issues so far.

**Comment by greenais** [comment] 2018-07-30 14:50
@bgold0, thank you.
In return - here is how I replaced already outdated (in terms of consisting PDB modules) pouchdb-react-native:

```
import PouchDB from 'pouchdb-core';
PouchDB
.plugin(require('pouchdb-adapter-asyncstorage').default)
.plugin(require('pouchdb-adapter-http'))
.plugin(require('pouchdb-mapreduce'))
.plugin(require('pouchdb-replication'))
.plugin(require('pouchdb-authentication'));

const localDB = new PouchDB(localDBname, {adapter: 'asyncstorage', auto_compaction: true});


```

**Comment by daleharvey** [comment] 2018-07-30 15:09
Cheers for the update, feel free to carry on dicussing in here but closing out as fairly  certain if its only showing up in react-native environments, its not a pouchdb bug, thanks

**Closed by daleharvey** 2018-07-30 15:09 UTC

**Comment by greenais** [comment] 2018-07-30 17:10
RN wasn't considered. Pity.

**Comment by greenais** [comment] 2018-08-07 21:02
@bgold0,
I played around with pouchdb-find and found that it works quite unstable - suddenly it stops to bring up any results, docs array is empty.

```
localDB.createIndex({
	index: {fields: ['doctype', 'cityID', 'date']},
	ddoc: 'cityDayIndex',
	name: 'cityDayIndex'
    })
	
localDB.find({
      use_index: 'cityDayIndex',
      selector: {doctype: 'Event', cityID: cityID, date: date}
	  })
```
First for two fields it worked, once I added third field - it stopped, zero lenght array.
deleteIndex brings some error but getIndexes shows that index seems to be deleted (probably not completely as docs say "Delete an index, remove any orphaned design documents, and clean up any leftover data on disk").
Rebuilding RN/recreating index for 2-3-4 fields sometimes bring it back to work but, again, suddenly it stops showing results with no reasons. And I can't figure out why to get some workround.

Did you experience something similar, any clue, perhaps?

**Comment by bgold0** [comment] 2018-08-07 21:19
@greenais I think your syntax is wrong. Try this:

	db.find({
	    selector:{
	        "$and": [ {doctype: 'Event'},{cityID: cityID},{date: date} ]
	    }
	})

**Comment by greenais** [comment] 2018-08-07 21:47
@bgold0 
hm, according to docs they are equivalent
[https://pouchdb.com/api.html#query_index](https://pouchdb.com/api.html#query_index)

I've just rebuided RN from scratch using your example syntax - now it works. For how long - that's the question...
So you had no similar issues with find, right?

**Comment by DaveWelling** [comment] 2018-12-27 14:36
@daleharvey Hi Dale, I'd like to try to submit a PR for this issue if I can figure it out.  I realize it isn't a problem with pouchdb so much as react native, but if I can find a way to make it work without disrupting the pouchdb code, that might be a boon for both communities.
I'm having trouble just tracking down where indexes are updated when a put occurs.  If you can just give me a push in the right direction, I would be super grateful.  
It seems unlikely to be in the adapter as I've been using the SQL lite adapter while others appear to have been using the asyncstorage adapter.

**Comment by garrensmith** [comment] 2018-12-27 14:45
Hi David, take a look in the abstract-mapreduce section. That probably would be a decent place to start.


________________________________

**Comment by DaveWelling** [comment] 2018-12-27 21:53
I turns out this IS a problem in BOTH adapters (sqllite (which uses the old pouchdb-adapter-websql-core)  and [asyncstoreage](https://github.com/stockulus/pouchdb-react-native/blob/master/packages/pouchdb-adapter-asyncstorage/src/all_docs.js)).  Essentially, what is happening is that neither adapter supports the 'key' option in allDocs.  This means that when this lookup criteria is passed in, it is ignored and all records are returned.
As a result, abstract-mapreduce will not work correctly when updating the index.  Specifically, it fails at line 494 of getKeyValueDocs -- returning all docs instead of those with the keys passed in.
In my case, I was able to find a different adapter for SqlLite that works.
If you come to this thread with the same problem, I've created a [PR](https://github.com/kkbhav/pouchdb-adapters-rn/pull/2) for some minor problems in the [pouchdb-adapters-rn](https://github.com/kkbhav/pouchdb-adapters-rn) repository to fix a few minor problems which will prevent you using it.  If the PR isn't merged for whatever reason, you can just use my [fork](https://github.com/DaveWelling/pouchdb-adapters-rn/tree/bug/updateDocsAndReference).

**Comment by chichilatte** [comment] 2019-03-29 14:58
For anyone still suffering this problem, i used @badbod99's pouchdb expo example to get it working...
https://github.com/badbod99/pouchdb-expo-example

My project was raw React Native, not expo, but it was pretty trivial job, took about 10 mins.

The idea is to dump `pouchdb-react-native` and use the original `pouchdb` modules.
And also to dump `pouchdb-adapter-react-native-sqlite` and use a custom sqlite adapter (it's in the repo)

Note: This is for sqlite dbs only, no good for asyncstorage (tho writing a little adapter might be easy)

**Comment by craftzdog** [comment] 2019-04-03 06:02
I published `pouchdb-adapter-react-native-sqlite@2.0.0` which depends on `pouchdb-adapter-websql-core@7.0.0`.
I confirmed it resolved the issue on RN@0.59.
Thanks @DaveWelling!

**Comment by greenais** [comment] 2019-04-04 07:53
@craftzdog 
Just to be sure: I just checked your repo - it still in Prerequisites depends on buggy pouchdb-react-native, does your adapter resolve the "lost docs after update" issue on top of pouchdb-react-native@next? Or it's intended to work with core PDB, like:
import PouchDB from 'pouchdb-core'
...and then al new sqlite adapter stuff?

**Comment by craftzdog** [comment] 2019-04-04 13:44
I'm not using `pouchdb-react-native` anymore.
Read this blogpost: https://dev.to/craftzdog/hacking-pouchdb-to-use-on-react-native-1gjh

**Comment by greenais** [comment] 2019-04-05 07:04
Oh, great! I just noticed it there on https://github.com/craftzdog/pouchdb-adapter-react-native-sqlite - that's why was the question
Thank you for your great job!
We definitely need to spread this good news across devs

**Comment by daviesdoclc** [comment] 2019-07-30 14:07
I'm having this same issue with pouchdb-find using the cordova-plugin-sqlite-2 adapter.  It works fine on a desktop browser, but within my iOS app, once I've done an update to an item, only that item gets returned in future queries.  Not putting an index on the documents seems to solve it for me, but then I suspect it's not benefitting.
