### ISSUE TITLE
Retry live replication when disconnected

### ISSUE THREAD

**Issue by moneppo** [pouchdb/pouchdb#2768] opened 2014-09-15 15:20 UTC
Right now if a live replication fails, it dies. This means for apps that want to work consistently in an environment with intermittent internet connectivity, we have to relaunch the replication based on our own heuristic.

It would be great to have an option to have pouchdb back off when replication fails rather than fail outright. Originally I thought pouch could respond to the online/offline events but those aren't well implemented. Perhaps a better feature would simply be to include a retry time option, and if there is a failure, pouch could automatically retry after the interval has passed.

**Comment by daleharvey** [comment] 2015-01-17 21:33
So I already have the bug number in the PR pointed to the other bug, so cross referencing as these are mostly duplicate bugs, closing as dupe of https://github.com/pouchdb/pouchdb/issues/966

**Closed by daleharvey** 2015-01-17 21:33 UTC
