### ISSUE TITLE
Add heartbeat to Ajax requester options

### ISSUE THREAD

**Issue by amkonieczka** [pouchdb/pouchdb#4263] opened 2015-09-03 21:31 UTC
```javascript
var db = new PouchDB('http://example.com/dbname', {
    ajax: {
        timeout: 120000,
        heartbeat: 300000
    }
});
```

**Comment by nickcolley** [comment] 2015-09-04 08:42
Hey @amkonieczka !

Thanks for the issue, can you describe what kind of use case you'd want this option for?

**Comment by daleharvey** [comment] 2015-09-04 11:13
A heartbeat is something supported by CouchDB, its used when you open a polling connection to couchdb change, after a while that connection will be killed if there is no activity so you can define a heartbeat where couch will send some empty data down the line purely to maintain the connection.

I believe we had problems with long lived connection even with a heartbeat in some browsers so our timeout is below the time a connection would get killed, but it would be fairly easy / safe to just support this option anyway, it only applies to the http adapter and it only needs to pass through the option

**Comment by nickcolley** [comment] 2015-09-04 11:16
Neat, Good a first timer then?

http://wiki.apache.org/couchdb/HTTP_database_API#Changes

**Comment by daleharvey** [comment] 2015-09-04 11:18
Yup definitely

**Comment by nickcolley** [comment] 2015-09-04 11:21
https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/http/index.js#L785

**Comment by daleharvey** [comment] 2015-10-04 11:35
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/2982, just away to implement heartbeat, but likely not as `ajax` options but as one specifically to changes, since its a changes option

**Closed by daleharvey** 2015-10-04 11:35 UTC
Labels: enhancement
