### ISSUE TITLE
install error in node.js v8.1.4

### ISSUE THREAD

**Issue by c941010623** [pouchdb/pouchdb#6622] opened 2017-07-16 10:56 UTC
have error
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mofunti/.npm/_logs/2017-07-16T10_55_06_593Z-debug.log

**Comment by c941010623** [comment] 2017-07-16 11:36
leveldown@1.5.0 will npm install error

**Comment by c941010623** [comment] 2017-07-16 14:48
I find the problem 
When Node.js bee is 8.0.0 or up
The pouchdb will install error
But node v 7.10.1 will work good
Why? Not npm problem, I have test
v7.10.1+npm 5.3.0 will ok
Only Node.js v8.0.0～v8.1.3 will not install

**Comment by willholley** [comment] 2017-07-17 13:53
https://github.com/Level/leveldown/pull/366 suggests prebuilt packages for leveldown are only available for version `1.7.1` and up.

**Comment by willholley** [comment] 2017-07-17 17:10
@c941010623 I can't reproduce this problem with pouchdb master and node v8.1.4.

**Comment by c941010623** [comment] 2017-07-20 05:55
prebuild info spawn args   '-Goutput_dir=.' ]
prebuild verb ok 
prebuild verb command build []
prebuild verb build type Release
prebuild verb architecture x64
prebuild verb node dev dir /Users/mofunti/Google 雲端硬碟/Api_Server/node_modules/leveldown/8.2.0
prebuild verb `which` succeeded for `make` /usr/bin/make
prebuild info spawn make
prebuild info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/builder.o
clang: error: no such file or directory: '雲端硬碟/Api_Server/node_modules/leveldown/8.2.0/include/node'
clang: error: no such file or directory: '雲端硬碟/Api_Server/node_modules/leveldown/8.2.0/src'
clang: error: no such file or directory: '雲端硬碟/Api_Server/node_modules/leveldown/8.2.0/deps/uv/include'
clang: error: no such file or directory: '雲端硬碟/Api_Server/node_modules/leveldown/8.2.0/deps/v8/include'
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/builder.o] Error 1
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/Users/mofunti/Google 雲端硬碟/Api_Server/node_modules/node-gyp/lib/build.js:258:23)
prebuild ERR! stack     at emitTwo (events.js:125:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:213:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/Users/mofunti/Google 雲端硬碟/Api_Server/node_modules/node-gyp/lib/build.js:258:23)
prebuild ERR! build     at emitTwo (events.js:125:13)
prebuild ERR! build     at ChildProcess.emit (events.js:213:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mofunti/.npm/_logs/2017-07-20T05_51_42_481Z-debug.log

still have install error in node.js v8.2.0

**Comment by artin-phares** [comment] 2017-07-23 11:56
@willholley 

> suggests prebuilt packages for leveldown are only available for version 1.7.1 and up

yep, currently pouchdb references leveldown@1.5.0 which does not have prebuild available anymore.    

installation logic cannot find prebuild, then starts compilation from source and fail.  
it forces me to install python, visual studio c++ (wat?), then fly to the mars and return with the ring of power.

so, can you update leveldown? :)

**Comment by willholley** [comment] 2017-07-24 08:50
leveldown updated in master as per #6551

**Comment by artin-phares** [comment] 2017-07-24 09:03
Cool! Looking forward for next npm release.

**Comment by daleharvey** [comment] 2017-07-24 10:05
Closed as part of https://github.com/pouchdb/pouchdb/issues/6551

**Closed by daleharvey** 2017-07-24 10:05 UTC

**Comment by maiharun98444** [comment] 2017-11-30 13:17
@c941010623 - You got solution for this problem? Even i am facing the same issue.

**Comment by artin-phares** [comment] 2017-11-30 13:33
@maiharun98444  

I was tired to wait for next version of `pouchdb` with new `leveldown@1.7.2` and just asked people from `leveldown` to make a prebuild of `leveldown@1.5.0` for my environment.  And they kindly did that https://github.com/Level/leveldown/issues/393.

If it happens that `leveldown@1.5.0` does not have prebuild for your environment you can try the same.

**Comment by maiharun98444** [comment] 2017-11-30 14:35
@c941010623  Thank you for the quick help. Will try the same
