### ISSUE TITLE
Handling xhr.response===null (iOS http adapter)

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#5486] opened 2016-07-19 19:23 UTC
### Environment (Node.js/browser/hybrid app/etc.)

Browser

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

iOS Safari in Simulator

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

Fruitdown

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB 1.6

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

```
[Error] Failed to load resource: The request timed out. (10|png, line 0)
[Error] TypeError: Attempted to assign to readonly property.
	onreadystatechange (vendor-2144b83d0afea292420d69ea120a5a7d.js:88096)
```

![image](https://cloud.githubusercontent.com/assets/2558804/16963340/4665b18a-4df6-11e6-93e4-32da907be158.png)

which points to https://github.com/pouchdb/pouchdb/blob/ce73b62428d61225e23fa7c1515767b64bdd3eb9/packages/pouchdb-ajax/src/request-browser.js#L221

It seems it is not allowed to write to `error.status` in iOS Safari.

**Comment by daleharvey** [comment] 2016-07-20 13:44
hrm, this seems to work in normal safari, will try on an emuator, you got a specific version for the demo? it would also be useful to know if the error comes from `new Error` or JSON.parse, either way it seems very strange, a plain js object certainly should be fine and if its `new Error` then the `err.code = ` seems like it should be the one that is throwing

**Comment by ssured** [comment] 2016-07-20 14:59
All is well in iOS 9.3 / iPad2 simulator:
![image](https://cloud.githubusercontent.com/assets/2558804/16990768/938f12be-4e99-11e6-9fa6-73a3a1f54c05.png)

And then in an iOS 9.3.2 iPad Air 1 device, connected by USB:
![image](https://cloud.githubusercontent.com/assets/2558804/16990947/2f3cd00c-4e9a-11e6-8fc7-c84a12d43d7b.png)

However I do see these errors popping up in Rollbar. These events popped up while researching the sync of 200+ attachments on Safari. The highlighted line is where the error comes from. I have +- 100 occurrences, all on Mobile Safari.

**Comment by nolanlawson** [comment] 2016-07-20 15:44
@ssured This would be interesting to test in Chrome and in Safari 10, in order to get a second opinion. I'm not sure whether it's a bug in Safari IndexedDB, in FruitDOWN, or in PouchDB, but if you test in a few different browsers that gives us a clue.

**Comment by nolanlawson** [comment] 2016-07-20 15:47
Oh wait I see, it's because of assigning a status to the error. Yeah, what Dale said.

**Comment by ssured** [comment] 2016-07-21 15:13
Hmmm, pretty weird, I get `TypeError: Cannot set property 'status' of 'null'` on this codepath just now in Chrome on OSX, idb, 4.5.3:

![image](https://cloud.githubusercontent.com/assets/2558804/17027120/ed29e834-4f62-11e6-89ff-d487646407c1.png)

Where `xhr` looks like

![image](https://cloud.githubusercontent.com/assets/2558804/17027150/0f79d692-4f63-11e6-90a7-4e98467d0dee.png)

It is not related to this bug on iOS, see below. It seems `xhr.response === null` exists in a real browser, should I open a new issue for this? This is the only time I've seen this error, it annoys me to open so many tickets without a test / proper reproduction path.

![image](https://cloud.githubusercontent.com/assets/2558804/17027350/cf0a5aae-4f63-11e6-8c62-8e5fa407a294.png)

**Comment by daleharvey** [comment] 2016-07-21 16:22
Yeh without a reproduction path bugs arent that useful, I think its good to carry on investigating here and can split it out if we find separately reproducable bugs

**Comment by daleharvey** [comment] 2016-07-21 16:25
however `JSON.parse(null) === null`, so there is definitely a problem there, ill see if I can get something to hit this path

**Comment by ssured** [comment] 2016-07-21 18:43
The setup of my app makes it quite hard to reproduce issues, but quite easy to trigger them. There's a local DB (idb/websql/fruitdown) syncing to a remote HTTP CouchDB. If the app is online then it sends requests for data to both the online and offline db with a `Promise.race` call. Whatever is first, is then used as an answer. This usage of almost all available PouchDB library code triggers some errors, such as the one above. Still most goes exceptionally well, which is awesome and thanks to your hard work. My hopes are to find some issues and get my error logger down to 0 issues.

**Comment by ssured** [comment] 2016-07-22 15:34
Caught an exception today. What happens is that there is an error in the xhr object, which has `xhr.response === null`:

![image](https://cloud.githubusercontent.com/assets/2558804/17062197/30112a0c-5032-11e6-8994-f842c2ef2176.png)

`InvalidStateError: DOM Exception 11` is something to look into, I don't have the time now (it's end of day here at the office).

Patch is available in my PR: #5491 

I hope this can be merged in asap, but still what remains is why this is exactly happening.

**Comment by ssured** [comment] 2016-07-22 15:39
Hit something possibly related on iOS: 

`TypeError: undefined is not an object (evaluating 'response.headers')`

on: https://github.com/pouchdb/pouchdb/blob/d31bf170ccfa54ca58e6afd43fe9f496e639e1a9/packages/pouchdb-ajax/src/ajaxCore.js#L72 , sadly I do not have a stacktrace.

It seems it's unsafe to rely on the format of `xhr.response`

**Comment by ssured** [comment] 2016-07-22 18:47
Searching on GitHub for InvalidStateError yields some interesting results. https://github.com/search?l=JavaScript&q=INVALID_STATE_ERR&ref=searchresults&state=closed&type=Issues&utf8=%E2%9C%93 It seems accessing status and other properties is sensitive to ordering.

One last observation is that all the errors have `xhr.responseType==='arraybuffer'`, these are probably requests for attachments (binary).

**Comment by ssured** [comment] 2016-07-23 07:16
My daily error log looks like this:

```
Daily Summary for SnagTracker.com

2016-07-22 08:00 - 2016-07-23 08:00
Production

Error

62 occurrences: https://rollbar.com/ssured/SnagTracker.com/items/120/
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Status: Active

15 occurrences: https://rollbar.com/ssured/SnagTracker.com/items/302/
TypeError: Attempted to assign to readonly property.
Status: Active

10 occurrences: https://rollbar.com/ssured/SnagTracker.com/items/303/
Error: once called more than once
Status: Active

5 occurrences: https://rollbar.com/ssured/SnagTracker.com/items/304/
TypeError: undefined is not an object (evaluating 'response.headers')
Status: Active
```

These errors seem related to me. I'll close the other topic and rename this

**Comment by ssured** [comment] 2016-07-23 08:30
Temporary workaround for Safari users is setting both `options.batch_size=1` and `options.batches_limit=1`. This lets the sync finish for me.

**Comment by nolanlawson** [comment] 2016-07-27 15:15
Do you think a pull request adding a check for `typeof response.headers !== 'undefined'` would work here? Forcing everyone down to a batch size of 1 just to avoid hitting a certain code path does not seem like a good permanent solution.

**Comment by daleharvey** [comment] 2016-08-02 12:06
Fixed in https://github.com/pouchdb/pouchdb/commit/2e50ae0ea4ff97ad1b3d0f22d0fc9b4cdc1fdc37

**Closed by daleharvey** 2016-08-02 12:06 UTC
Labels: bug, needs reproducing
