### ISSUE TITLE
Improve Replication Events when Live=true

### ISSUE THREAD

**Issue by ng-** [pouchdb/pouchdb#4266] opened 2015-09-04 03:17 UTC
I currently create a new database and start "live" syncing it right after a user logs in.  I only want to show them the logged-in page once all the data is *initially* synced to avoid showing incomplete data. Of course I think Feature: Replication progress #4089 will help with detecting the initial sync, but I think the events could be improved (or maybe just better documented).

I am fairly new to PouchDB so please let me know if I am doing this wrong, but I am having a lot of trouble detecting when this initial sync occurs when live = true.  My experience is building my first app and reading through https://github.com/pouchdb/pouchdb/issues/1916.  This seems like it should be a common use case, so was hoping the API would be straightforward, however

```local.sync(remote,  {live:true, retry:true}).once('paused', login)``` never gets called (bug?)
```local.sync(remote,  {live:true, retry:true}).on('paused', login)``` gets called lots of times (by design)
```local.sync(remote,  {live:true, retry:true}).on('complete', login)``` never gets called (by design)
```local.sync(remote,  {live:true, retry:true}).then(login)``` never gets called (not documented)

The closest I have been able to do is 
 ```
new Promise(function(resolve) {       
      remote[name].sync(local[name], {live:true, retry:true}).on('paused', resolve)
})
```
However the above code still has the problem that it is getting called prematurely some of the time, so that login is getting called before all the data has been replicated locally, showing an incomplete page.

**Comment by daleharvey** [comment] 2015-09-04 11:17
So there are open bugs with the paused events not being fired or sometimes too many times and working on fixing them. However I think for your case things would be much more reliable if you did not use live replication for the initial sync, can you do:
```
local.sync(remote, {retry: true}).then(function() { 
  local.sync(remote, {live: true, retry: true});
  // show login
});
```
?

**Comment by ng-** [comment] 2015-09-04 17:24
Great idea Dale, thanks!

**Comment by daleharvey** [comment] 2015-09-04 19:51
I am gonna close this as a dupe of https://github.com/pouchdb/pouchdb/issues/4251 and https://github.com/pouchdb/pouchdb/issues/3852, feel free to ask if you have more questions, but those cover the same issues

**Closed by daleharvey** 2015-09-04 19:51 UTC
