### ISSUE TITLE
401 unauthorized firing 'complete' instead of 'error' or 'denied'

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#4276] opened 2015-09-05 08:09 UTC
I want my app to send the user back to the login screen when a live replication fails due to a 401 unauthorized response.

Based on your documentation: "In a live replication, only cancelling the replication should trigger this [complete] event." I would expect this to be handled by either 'error' or 'denied'.

With the 'complete' event, I have to iterate through the errors on both 'push' and 'pull' properties to tell if an unauthorized occurred... more complicated than it should be.

**Comment by daleharvey** [comment] 2015-09-05 09:59
Can you describe the situation a little more? I believe this may be due to the fact that replication can reject writes with a 401 and replication will carry on by design, people may have a `validate_doc_update` to do per document authorisation which will reject some writes but not others.

You mentioned the denied event, that is supposed to be fired in this situation are you not seeing it? a 'denied' event isnt a completion one and the complete event will still fire after denied does

**Comment by colinskow** [comment] 2015-09-05 10:35
As a security feature, when a user logs out I remove them from the _security doc of their database. This means that replication will fail with `401 unauthorized` on any other sessions that user has opened (intended behavior). This sets off the 'complete' event and nothing else.

In contrast, a validate_doc_update failure should result in `403 forbidden` and replication continues.

I am listening for the 'denied' event but it does not fire in the case of `401 unauthorized`. Although I am using PouchDB 4.0.0 because 4.0.1 hasn't been firing events at all.

**Comment by colinskow** [comment] 2015-09-10 13:25
So I did a bit of further testing. When PouchDB live replication receives an `unauthorized` or `forbidden` error from the process of attempting to find or write a checkpoint (`/_local`) then replication is terminated and the `complete` event is fired. This seems like rational behavior because CouchDB doesn't like the credentials. Although based on your documentation, it should be firing the `error` event instead.

When a normal `validate_doc_update` fails with `unauthorized` or `forbidden` then the `denied` event correctly fires and replication continues.

**Comment by colinskow** [comment] 2015-09-11 16:35
By the way, here is the source code that I'm working on that sets up 3-way sync and tracks events...
https://github.com/colinskow/ng-pouch-mirror

**Comment by daleharvey** [comment] 2015-09-26 13:43
@colinskow It seems like you are wanting to get your bugs fixed fairly quickly and fixing them yourself, so thanks :), and leaving these here in case you are looking to take a look at this (or anyone else)

https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.retry.js#L543 Is a test that overrides the `ajax` handler so you can customise whatever you want to return, this should hopefully help in generating a test for this condition.

We dont trigger `denied` on checkpoint failures and seems like 50 / 50 on whether we should, but we definitely should be firing the error event if a replication fails due to a bunch of 401s, and I think thats the case that this bug should focus on. most of that code is handled @ https://github.com/pouchdb/pouchdb/blob/master/lib/replicate/replicate.js#L58

**Comment by daleharvey** [comment] 2015-10-03 16:02
So I wrote a test for this, however fixing it is tricky, we have some not so perfect state handling code in the replicator so I may need to do a few refactorings before getting to the fix

https://gist.github.com/daleharvey/09d273f5d8502c8aa37a

**Comment by nolanlawson** [comment] 2015-10-04 14:07
Leaving this open unless @daleharvey thinks 31cdcf8993924414d13f0d3df080d60220ba2b87 solves the original issue.

**Comment by daleharvey** [comment] 2015-10-04 14:15
Yup this fixes the issue, previously `complete` was getting fired because we werent tracking the cancelled state properly, test ensures we do now

**Comment by srikanth235** [comment] 2016-04-22 08:47
I just wanted to check whether this fix has gone into latest i.e. 5.3.2 release. I'm still seeing the same error in 5.3.2.

**Comment by nolanlawson** [comment] 2016-04-23 16:44
Reopening since apparently 31cdcf8  doesn't solve the issue.

**Comment by daleharvey** [comment] 2016-06-02 08:08
@srikanth235 do you have any further information on the issue you are seeing? we identified the bug and landed the fix with a passing test so if you are seeing something related broken it would help to know exactly what that was. Thanks

**Comment by coderroggie** [comment] 2016-06-17 18:24
So, I guess I'm not clear as to what should happen when my session with couchdb expires as it relates to a live sync that is currently happening.  Should that only fire the "complete" event or should it also fire an "error" event?  I'm not sure that the docs are completely clear there.  Or I missed something in the docs...

**Comment by colinskow** [comment] 2016-06-18 00:39
@coderroggie that should fire the "denied" event.

**Comment by daleharvey** [comment] 2016-06-19 00:12
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/5172

**Closed by daleharvey** 2016-06-19 00:12 UTC
Labels: bug
