### ISSUE TITLE
Multiple requests on PouchDB sync

### ISSUE THREAD

**Issue by todotresde** [pouchdb/pouchdb#4975] opened 2016-03-14 11:57 UTC
I am using PouchDB 5.3 with Couchbase Sync Gateway 1.2, with the sync function. It works without any problem when I use a small set of records (20 .. 50). But I have problems when I use 3K, because the first time that try to synchronize, it has around 17K request to the server.

This is the configuration with this problem:

```
this.sync = function(remoteDatabase, onComplete, onError) {
    database.sync(remoteDatabase, {
        live: true,
        retry: false
    }).on('change', function(change) {
        // yo, something changed!
        console.log("Sync Change");
    }).on('paused', function(info) {
        // replication was paused, usually because of a lost connection
        console.log("Sync Paused");
        if (onComplete)
            onComplete();
    }).on('active', function(info) {
        // replication was resumed 
        console.log("Sync Active");
    }).on('error', function(err) {
        // totally unhandled error (shouldn't happen)
        console.log("Sync Error", err);
        if (onError)
            onError();
    }).on('complete', function(info) {
        console.log("Sync Complete");
    }).then(function(info) {
        console.log("Sync Complete");
    });
}
```

Also, it is not possible to detect when this 17k requests are done.

If I set the live method to false, it only has around of 3k requests, but after that, it is not possible to sync when some changes is made on any of both sides.

This are the set of repeated requests (with differents uuids)

```
http://...._bulk_docs?_nonce=1457702282722
http://...._bulk_docs?_nonce=1457702282722
http://....._revs_diff?_nonce=1457702282818
http://....._revs_diff?_nonce=1457702282818
http://....._local/EhRrzqajjvWCiEqNXBk87A%3D%3D?
http://....._local/EhRrzqajjvWCiEqNXBk87A%3D%3D?

```
Any idea about how to prevent this 17k requests??

And if this is mandatory to do, any idea about how to detect once is finished?

**Comment by provedotit** [comment] 2016-03-18 18:36
To add to this - I watched the requests comparing 5.2 to 5.3.1 and 5.3.1 had about 3x the requests. I'm not sure what changed to cause this.

I replicate from a remote to local (~10k docs) and I sync with another remote (~800 docs)

Regarding detecting when done, I use info() to get the doc count on the remote and then periodically check the local doc count and compare. I use this to show % complete to the user.

**Comment by nolanlawson** [comment] 2016-03-19 22:16
If Couchbase Sync Gateway ever implements the `_bulk_get` method, then we can potentially use that and reduce the number of requests. Alternatively, you can play with the `batch_size` and `batches_limit` options.

Although I'm very surprised that your 17k requests are mostly _bulk_docs, _revs_diff, and _local. I would expect to see a lot more regular document GETs.

**Comment by provedotit** [comment] 2016-03-20 03:42
@nolanlawson The original poster had 17k requests.

I have about 1100k requests on 5.2 but on 5.3.1 I get around 4k requests with bulk_docs, revs_diff. 
Any idea why I would have more requests on 5.3.1 for an initial sync?

**Comment by nolanlawson** [comment] 2016-03-20 13:03
I don't know; that's more a question for the Couchbase team. Keep in mind that we don't test against Couchbase in CI, only against CouchDB and PouchDB Server. So Couchbase support is mostly maintained by Couchbase themselves.

**Comment by todotresde** [comment] 2016-03-21 10:52
Thanks for your reply!

So @nolanlawson , if I sync against CouchDB, I should have only 3K , and not 17K requests?

**Comment by nolanlawson** [comment] 2016-03-24 16:35
@todotresde I'm really not sure exactly how many you'll see without testing. My hunch is that CouchDB 2 or PouchDB Server will generate the fewest number of requests, due to the new _bulk_get API.

**Comment by willholley** [comment] 2016-03-26 10:51
Couchbase Sync Gateway has a [_bulk_get](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/sync-gateway/rest-api/database/post-bulk-get/index.html) endpoint but the response type is `multipart-mixed` which I expect means it doesn't work with PouchDB.

**Comment by nolanlawson** [comment] 2016-05-03 01:26
Closing because I believe this issue is mostly about `_bulk_get`. Please try your code against a server with `_bulk_get`, e.g. PouchDB Server. If that doesn't fix the issue, then it's a true bug with PouchDB. Else the problem is either in CSG or with the fact that CSG ought to implement `_bulk_get` per the new CouchDB replication spec (i.e. support `application/json` and not multipart-mixed, which Pouch does not and cannot support due to browser limitations).

**Closed by nolanlawson** 2016-05-03 01:26 UTC
