### ISSUE TITLE
Doc Suggestion: Dealing with race conditions in conflict resolution

### ISSUE THREAD

**Issue by kuza55** [pouchdb/pouchdb#4145] opened 2015-08-10 22:12 UTC
I've read the existing threads on PouchDB conflict resolution such as http://stackoverflow.com/questions/27193171/resolve-pouch-couch-db/27198922

And I feel like no-one is really talking about the possibility of getting race conditions when dealing with conflicts.

The flow for dealing with conflicts seems to be:

a) Detect conflicts in client code
b) Get conflicting revisions
c) Resolve conflict and write the result to the db
d) Delete the resolved conflict

In particular, no-one seems to mention the possibility of two clients attempt step c) at the same time,  where it seems like we'd end up with conflicting resolutions, and one of them would get written down as a conflict that needed to be resolved itself.

I was thinking through this myself and it seemed like the sanest way to deal with this is to simply add a marker to doc revisions that are conflict resolution revisions, and if we see any conflicts that have that marker, we should just ignore them (so that we don't have to deal with recursively dealing with them).

There's still a race condition possible if you somehow end up with c) and d) accepted locally, but then c) fails when syncing, but d) succeeds before anyone else manages to merge the revision. Though I'm struggling to come up with a series of events that would actually lead to that.

In any case, it would be nice if the documentation explained what the right way of handling this case was.

**Comment by daleharvey** [comment] 2015-08-10 23:07
So in this scenario currently if you have 2 resolvers, they will race until one wins which isnt ideal. I didnt particularly understand this case until it was explained to me, but the correct solution will be to use deterministic revisions, that way the 2 clients can resolve the conflict and as long as they resolve them in the same way, they will generate the same document that will not end up in another conflict

Theres a bug open for it @ https://github.com/pouchdb/pouchdb/issues/2451, it shouldnt be too large a change

**Comment by kuza55** [comment] 2015-08-11 00:12
Ah, thanks for the pointer!

That seem like a great solution for a lot of cases, though the requirement to produce deterministic results from merges might make cross-language sync trickier (e.g. android app using couchbase lite and pouchdb, especially if you try and do anything tricky in there), and would have issues if I ever try to update the merging strategy.

Is there another approach people are using while that bug remains unsolved, or are they just not worrying about it due to it being a low probability event?

**Comment by nolanlawson** [comment] 2015-08-11 02:20
Thank you for the interesting writeup; I admit the possibility had never occurred to me.

It's worth pointing out that this problem only occurs in a system where you need to both 1) delete one conflict, and 2) write another conflict on top of the previously winning revision. For conflict resolution strategies that only involve deleting one conflict or the other, this shouldn't come up (although in PouchDB, you could indeed commit two conflicting deletions, but the end result would be the same since neither one would be considered "winning," and therefore not a conflict. But obviously that doesn't cover every strategy.

In the case of PouchDB, it seems like we would benefit a lot from at least coordinating with Cloudant Sync/Couchbase Mobile and coming up with a deterministic revision scheme. Unfortunately we can't borrow CouchDB's, because it's based on some idiosyncrasies of Erlang strings.

**Comment by nolanlawson** [comment] 2015-08-11 02:27
Also I would love to introduce deterministic revisions, but man, it is definitely going to be a performance drag. :grimacing: Traversing the entire doc object, sorting keys, recursion... hoo boy.

**Comment by nolanlawson** [comment] 2015-08-11 02:50
I kind of like the idea of just `md5(require('json-stable-stringify')(doc))` as a simple first implementation. Could always be rewritten later for better perf: https://www.npmjs.com/package/json-stable-stringify

**Comment by daleharvey** [comment] 2015-08-11 12:21
@kuza55 also the other alternative (as mentioned on twitter) is to do a read resolver, add {conflicts: true} to any read request you do and merge the documents in code

Closing this out as a dupe of https://github.com/pouchdb/pouchdb/issues/2451, but feel free to carry on the conversation, cheers

**Closed by daleharvey** 2015-08-11 12:21 UTC

**Comment by kuza55** [comment] 2015-08-12 05:47
I don't think resolving conflicts on reads as opposed to writes resolves this. My initial comments were actually about the case where you resolve conflicts on reads, and I think they're still applicable.

I guess, unless you're recommending leaving the conflicts in the db, and not writing the merged results at all? Which seems like it would just cause performance to degrade over time.

**Comment by nolanlawson** [comment] 2015-08-12 13:11
I think what @daleharvey is saying is that until #2451 gets resolved, your best bet is to resolve conflicts on reads. Which is not ideal, but trust me; it doesn't change the performance implications at all. No matter what, PouchDB/CouchDB are going to replicate all the leaf nodes (even deleted ones), and as for operations on the winning revisions (e.g. `allDocs()` or `get()`), the number of revisions will not affect the performance characteristics.

**Comment by CatchSandeepVaid** [comment] 2017-10-05 09:22
What if there are more than 2 DB's involved. Consider the following scenario where i want to show a message to user (on mobile)  when a doc having conflict is synced to his pouchdb (by reading docs after sync). 
a) User1 uses Mobile1 (Pouch DB1), there is a CouchDB & User2 uses Mobile2(Pouch DB2)
b) Assuming PouchDB1 & PouchDB2 syncs a document from CouchDB and now both has version 1-x
c) Both updated the document offline, so PouchDB1 has 2-x while PouchDB2 has 2-y
d) PouchDB1 syncs with couchdb and hence couchdb now has 2-x
![image](https://user-images.githubusercontent.com/6469422/31219600-7d17f552-a9db-11e7-9e64-6d9ad9e30fff.png)
e) PouchDb2 syncs with couchdb. After sync, client code reads the synced docs and detects a conflict. It resolves the conflict by removing conflicted rev (2-Y) and putting a new rev on top of latest(2-x) which results in rev 3-y and 3-T1(tombstone) respectively. **PouchDB2 immediately syncs with CouchDB again so that couchdb gets 3-Y & 3-T1.**
![image](https://user-images.githubusercontent.com/6469422/31219829-24ed18f2-a9dc-11e7-8b8f-620aa517a591.png)

![image](https://user-images.githubusercontent.com/6469422/31220009-bab74e52-a9dc-11e7-8a8e-6eaf8c212d07.png)





f) PouchDB1 syncs with couchdb and gets 3-Y.

Issues:
1) Race condition at step e)
2) Many syncs (at step e) when conflicts frequency increases.

Is this approach correct and how to resolve the issues?

**Comment by MrGurns** [comment] 2018-04-24 16:36
@subscribing I'm having a similar issue to @CatchSandeepVaid
