### ISSUE TITLE
'active' and 'paused' events not firing during live replication PouchDB 4.0.1

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#4275] opened 2015-09-05 08:00 UTC
I upgraded from 4.0.0 to 4.0.1 and the 'active' and 'paused' events stopped firing on live two-way sync between a memory adaptor and HTTP adaptor. I downgraded back to 4.0.0 and they started working again. Tested with Safari 8.0.8 and Chrome 45 on OS X Yosemite.

**Comment by daleharvey** [comment] 2015-09-05 10:01
Yup we are looking into this, going to make as a dupe of https://github.com/pouchdb/pouchdb/issues/4251 since that has the start of tests attached, cheers

**Closed by daleharvey** 2015-09-05 10:01 UTC
