### ISSUE TITLE
Ajax throws misleading error message when timeouting + Replication is impossible after first error

### ISSUE THREAD

**Issue by acdcjunior** [pouchdb/pouchdb#3210] opened 2014-12-17 21:52 UTC
Hey there! I'm reporting two very related problems that unfortunately happened to me at the same time. Depending on what, if anything, will be done, this probably should be divided into two more issues, but I'm not the one to decide that :)

This is somehow related to #2562.

Timeouts throwing `405`/`Method Not Allowed` error
-

As initially mentioned in #2982, every since I begun using PouchDB (two weeks now), I'd get the error below intermittently:

    r {message: undefined, status: 405, statusText: "Method Not Allowed", name: "unknown_error"…}

It would happen on ordinary `GET`s, `PUT`s, during replication, anywhere, every now and then.

The error message sent me in a quest to solve a CORS problem, and I searched everywhere for it. In the end, I (think I) found the cause: [this function](https://github.com/pouchdb/pouchdb/blob/master/lib/deps/ajax-browser.js#L208) sets a timeout of 10s and aborts Ajax requests. All in all, having a timeout is OK, but, as said, the problem is that when it aborts, the error message thrown hints that this is a CORS error, when it is not.

A "fix" would be to have the error message inform that it was a timeout (that is, when that `abortReq` is executed).

Remote DB "unreplicable" after first timeout during replication
-

Now, to make matters worse, my timeouts also happened during replication. I used something very similar to the backoff replication code [as shown in the guides](http://pouchdb.com/guides/replication.html):

```javascript
var timeout = 5000;
var backoff = 2;
function retryReplication() {
  localDB.sync.to(remoteDB, {live: true}).on('change', function (change) {
    // yo, something changed!
    timeout = 5000; // reset
  }).on('error', function (err) {
    setTimeout(function () {
      timeout *= backoff;
      retryReplication();
    }, timeout);
  })));
}
```
<sub>(It has some extra `)`s in there, and in other snippets as well. It is so simple, I'd fix it, can I just fork, commit and PR?).</sub>

The thing is that when an Ajax call timed out (that is, took more than 10s without responding), the replication would fail. Up to here, all OK. The real problem is that subsequent attempts to replicate (that is, to execute `retryReplication()`) would throw the `405` error right away (with no HTTP request being initiated at all). It is like the `remoteDB` became "poisoned" after the first timeout (plus the error message always being 405...).

To have it back working, I had to recreate the remote DB, something like:

```javascript
var remoteDBUrl = "http://example.com/docs";
var remoteDB = new PouchDB(remoteDBUrl);
//...
var timeout = 5000;
var backoff = 2;
function retryReplication() {
  localDB.sync.to(remoteDB, {live: true}).on('change', function (change) {
    // yo, something changed!
    timeout = 5000; // reset
  }).on('error', function (err) {
    setTimeout(function () {
      timeout *= backoff;
      // added the line below! recreating the remote db as the previous was bricked
      remoteDB = new PouchDB(remoteDBUrl);
      retryReplication();
    }, timeout);
  });
}
```

And that's it. Btw, great tool.

**Comment by nolanlawson** [comment] 2015-02-19 12:34
We've heavily rewritten `ajax-browser.js` since this was filed. Can you re-test? Or provide a working reproducible test case?

**Comment by acdcjunior** [comment] 2015-02-19 16:31
Sure! The application those problems happened is still running (with the workaround of recreating the remote DB everytime it timeouts).

Should I attempt to replicate both problems (the timeout showing "Method Not Allowed" message + failed replication "poisoning" the DB) or do you mean one of those specifically?

The version I should re-test is 3.3.1, right? (I'm asking if I have to build a version from the sources.)

**Comment by nolanlawson** [comment] 2015-02-19 16:39
3.3.1 is fine. And ultimately what would be best is a live reproducible test case - i.e. a site I can go to, where I just press a button or something and it shows the error. :)  Thanks!

**Comment by daleharvey** [comment] 2015-07-22 12:37
We also have retry: true and various change, so yup please reopen if you are still having issues, but should be fixed

**Closed by daleharvey** 2015-07-22 12:37 UTC

**Comment by acdcjunior** [comment] 2015-07-22 12:41
Yeah. I actually ended up changing the source code to extend the Ajax timeout value.

When I get the chance to work on the app where we had these problems, I will test and, if the problem persists, will, as you said, reopen this.

For now the project (shouldn't be a surprise) is stuck with that version, but it should be updated as soon as we get the chance.
