### ISSUE TITLE
Unkown error during authentication

### ISSUE THREAD

**Issue by csysmans** [pouchdb/pouchdb#4175] opened 2015-08-18 09:58 UTC
I'm using PouchDB 4.0. To test the credentials to a remote CouchDB server, I use the following code:
```
testCredentials: function(credentials, callback){
        var remoteDb = new PouchDB('http://X.X.X.X/dbName', {
            auth: {
                username: credentials.username,
                password: credentials.password
            }
        });

        remoteDb.info(function(err, info) {
            if (err) { 
                if(err.status == 401)
                    callback("unauthorized");
                else {
                    console.log(err); 
                    callback("error");
                }
            } else {
                callback("success");
            }
        });
}
```

When I pass invalid credentials (e.g. existing user but invalid password), I see a 401 error returned inside the CouchDB log file. However, PouchDb always returns the following 500 error:
```
{"status":500,"name":"unknown_error","message":"Database encountered an unknown error","error":true}
```
The same problem occurs when using the pouchdb-authentication plugin.
This code worked perfectly in previous versions of PouchDB.

**Comment by bucktaylor** [comment] 2015-08-19 00:18
I'm getting a similar problem using pouchdb-authentication plugin and filed an issue in that projects git repository. Are you using SSL by any chance?

I've spent over 2 days trying to figure this out....

I can get in no problems using HTTP, but if I try with HTTPS I get the status 500 error. I can also log in using HTTPS in futon, but not with pouchdb.

**Comment by nolanlawson** [comment] 2015-08-19 02:40
Can you provide more information? Like a screenshot or error log or the HTTP error returned? "Database encountered an unknown error" is what PouchDB says when it stops due to some other error, so it would be most helpful to see that error.

Also steps to reproduce would be extremely helpful. :)

**Comment by bucktaylor** [comment] 2015-08-19 16:12
Hi Nolan,

I made you a user in my DB. Here is a tiny app to test: http://www.hvac-rebate.com/App/pouchdb/index.html using both http and https.

When I step through the code, it shows no response code (0) from my server over https. I'm wondering if the request is even being sent by pouchDB using the "https" adapter?

You should also be able to log in at: https://www.hvac-rebate.com:6984/_utils/ (peak into the code for your username and password). this DB is still in dev mode, so feel free to trash it as needed.

**Comment by calvinmetcalf** [comment] 2015-08-19 17:10
I bet this is cors related.

**Comment by csysmans** [comment] 2015-08-19 17:30
I do not use HTTPS and I still have the problem. 
CORS is enabled.

**Comment by willholley** [comment] 2015-08-21 13:37
just tested this using the sample app provided above (modifying the password so it fails) and I get an error:

    Unathorized username or password. 
     ***Error: 
    {"status":401,"name":"unauthorized","message":"Name or password is incorrect."}

looks correct?

**Comment by willholley** [comment] 2015-08-21 13:46
I think the issue may be related to self-signed https certificates. Visiting https://www.hvac-rebate.com:6984/_utils/ presents me with an insecure site warning because the certificate is not trusted. If I click through this and proceed, executing the PouchDB test in another browser tab works.

**Comment by bucktaylor** [comment] 2015-08-21 14:20
Hi Will, yes, it is a self-signed certificate. Hopefully this isn't the issue.

The browser warning is a browser feature, and shouldn't be interfering with this process, otherwise I would expect the same warning in my test app - which is not currently happening, however it may be how pouch is handling the warning - I just don't know yet.

The self-signed certificate works in couch and also appears to work in pouch if I use the direct IP address of the server inside my firewall. If I access it from outside the firewall using the public domain name, it fails (as provided in my test app link above). This is the behavior that is confounding me.

I am in the process of trying to run through the code and compare it to jquery.couch which is what works in futon.

**Comment by willholley** [comment] 2015-08-21 14:40
@bucktaylor I'm pretty sure it's the issue. In Chrome, I see a net::ERR_INSECURE_RESPONSE - the browser blocks the request to an insecure HTTPS resource from an HTTP resource. You could work around it by hosting the PouchDB application over HTTPS using the same cert, forcing the user to accept it. I can only assume that CouchDB doesn't care about the invalid cert (which is probably reasonable behaviour for a database but not for a web browser).

**Comment by bucktaylor** [comment] 2015-08-21 15:38
Perhaps, but like I said, if I use the internal IP address it works fine (same response in browser). Fails when using the external IP address.
________________________________

**Comment by csysmans** [comment] 2015-08-21 15:40
As I said before, I'm not using HTTPS and i still get the same error.
However, I'm using PouchDB from within a Cordova application.

**Comment by willholley** [comment] 2015-08-21 15:49
@csysmans I think these issues are orthogonal. PouchDB returning a 500 error just means "unknown error". @nolanlawson perhaps we should consider changing this so we can differentiate between client-side and server-side errors?

**Comment by willholley** [comment] 2015-08-21 15:50
@bucktaylor can you capture the network trace as a HAR when it fails (using Chrome dev tools)?

**Comment by bucktaylor** [comment] 2015-08-21 17:17
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2015-08-21T17:09:45.999Z",
        "id": "page_1",
        "title": "http://www.hvac-rebate.com/App/pouchdb/index.html",
        "pageTimings": {
          "onContentLoad": 878.5149999894202,
          "onLoad": 876.3819999294356
        }
      }
    ],
    "entries": [
      {
        "startedDateTime": "2015-08-21T17:09:45.999Z",
        "time": 104.69199996441603,
        "request": {
          "method": "GET",
          "url": "http://www.hvac-rebate.com/App/pouchdb/index.html",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Host",
              "value": "www.hvac-rebate.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 400,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 21 Aug 2015 17:09:34 GMT"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Last-Modified",
              "value": "Wed, 19 Aug 2015 15:27:08 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.10 (Ubuntu)"
            },
            {
              "name": "ETag",
              "value": "\"3d1-51dabaaf65525-gzip\""
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "Content-Type",
              "value": "text/html"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Accept-Ranges",
              "value": "bytes"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=100"
            },
            {
              "name": "Content-Length",
              "value": "433"
            }
          ],
          "cookies": [],
          "content": {
            "size": 977,
            "mimeType": "text/html",
            "compression": 544
          },
          "redirectURL": "",
          "headersSize": 337,
          "bodySize": 433,
          "_transferSize": 770
        },
        "cache": {},
        "timings": {
          "blocked": 0.856999889947474,
          "dns": -1,
          "connect": -1,
          "send": 0.24700001813471606,
          "wait": 102.48700005467981,
          "receive": 1.101000001654029,
          "ssl": -1
        },
        "connection": "314",
        "pageref": "page_1"
      },
      {
        "startedDateTime": "2015-08-21T17:09:46.167Z",
        "time": 533.4179999772459,
        "request": {
          "method": "GET",
          "url": "http://www.hvac-rebate.com/App/pouchdb/Scripts/jquery-1.6.4.js",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Referer",
              "value": "http://www.hvac-rebate.com/App/pouchdb/index.html"
            },
            {
              "name": "Host",
              "value": "www.hvac-rebate.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 372,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 21 Aug 2015 17:09:35 GMT"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Last-Modified",
              "value": "Wed, 19 Aug 2015 14:11:27 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.10 (Ubuntu)"
            },
            {
              "name": "ETag",
              "value": "\"3a24f-51daa9c4b422d-gzip\""
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "Content-Type",
              "value": "application/javascript"
            },
            {
              "name": "Transfer-Encoding",
              "value": "chunked"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Accept-Ranges",
              "value": "bytes"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=99"
            }
          ],
          "cookies": [],
          "content": {
            "size": 238159,
            "mimeType": "application/javascript",
            "compression": 169394
          },
          "redirectURL": "",
          "headersSize": 358,
          "bodySize": 68765,
          "_transferSize": 69123
        },
        "cache": {},
        "timings": {
          "blocked": 4.28799993824214,
          "dns": -1,
          "connect": -1,
          "send": 0.2760000061243799,
          "wait": 145.51300008315548,
          "receive": 383.34099994972394,
          "ssl": -1
        },
        "connection": "314",
        "pageref": "page_1"
      },
      {
        "startedDateTime": "2015-08-21T17:09:46.168Z",
        "time": 588.298000046052,
        "request": {
          "method": "GET",
          "url": "http://www.hvac-rebate.com/App/pouchdb/Scripts/pouchdb-4.0.0.js",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Referer",
              "value": "http://www.hvac-rebate.com/App/pouchdb/index.html"
            },
            {
              "name": "Host",
              "value": "www.hvac-rebate.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 373,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 21 Aug 2015 17:09:35 GMT"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Last-Modified",
              "value": "Tue, 18 Aug 2015 16:52:10 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.10 (Ubuntu)"
            },
            {
              "name": "ETag",
              "value": "\"5d45b-51d98bd38d15e-gzip\""
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "Content-Type",
              "value": "application/javascript"
            },
            {
              "name": "Transfer-Encoding",
              "value": "chunked"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Accept-Ranges",
              "value": "bytes"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=100"
            }
          ],
          "cookies": [],
          "content": {
            "size": 382043,
            "mimeType": "application/javascript",
            "compression": 284756
          },
          "redirectURL": "",
          "headersSize": 359,
          "bodySize": 97287,
          "_transferSize": 97646
        },
        "cache": {},
        "timings": {
          "blocked": 4.68500005081296,
          "dns": -1,
          "connect": -1,
          "send": 0.3690000157803306,
          "wait": 144.3019999423997,
          "receive": 438.9420000370591,
          "ssl": -1
        },
        "connection": "313",
        "pageref": "page_1"
      },
      {
        "startedDateTime": "2015-08-21T17:09:46.168Z",
        "time": 487.7139999298379,
        "request": {
          "method": "GET",
          "url": "http://www.hvac-rebate.com/App/pouchdb/Scripts/pouchdb.authentication.js",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Referer",
              "value": "http://www.hvac-rebate.com/App/pouchdb/index.html"
            },
            {
              "name": "Host",
              "value": "www.hvac-rebate.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 382,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 21 Aug 2015 17:09:35 GMT"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Last-Modified",
              "value": "Wed, 19 Aug 2015 00:11:05 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.10 (Ubuntu)"
            },
            {
              "name": "ETag",
              "value": "\"2167c-51d9edeed4c0b-gzip\""
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "Content-Type",
              "value": "application/javascript"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Accept-Ranges",
              "value": "bytes"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=100"
            },
            {
              "name": "Content-Length",
              "value": "35938"
            }
          ],
          "cookies": [],
          "content": {
            "size": 136828,
            "mimeType": "application/javascript",
            "compression": 100890
          },
          "redirectURL": "",
          "headersSize": 354,
          "bodySize": 35938,
          "_transferSize": 36292
        },
        "cache": {},
        "timings": {
          "blocked": 2.70399998407811,
          "dns": 0.020000035874550015,
          "connect": 130.36799989640735,
          "send": 0.09700004011398278,
          "wait": 224.32200005278003,
          "receive": 130.20299992058386,
          "ssl": -1
        },
        "connection": "335",
        "pageref": "page_1"
      },
      {
        "startedDateTime": "2015-08-21T17:09:46.169Z",
        "time": 343.5130000580102,
        "request": {
          "method": "GET",
          "url": "http://www.hvac-rebate.com/App/pouchdb/Scripts/main.js",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Referer",
              "value": "http://www.hvac-rebate.com/App/pouchdb/index.html"
            },
            {
              "name": "Host",
              "value": "www.hvac-rebate.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 364,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 21 Aug 2015 17:09:35 GMT"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Last-Modified",
              "value": "Wed, 19 Aug 2015 15:52:48 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.10 (Ubuntu)"
            },
            {
              "name": "ETag",
              "value": "\"909-51dac06c4bcb5-gzip\""
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "Content-Type",
              "value": "application/javascript"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Accept-Ranges",
              "value": "bytes"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=100"
            },
            {
              "name": "Content-Length",
              "value": "668"
            }
          ],
          "cookies": [],
          "content": {
            "size": 2313,
            "mimeType": "application/javascript",
            "compression": 1645
          },
          "redirectURL": "",
          "headersSize": 350,
          "bodySize": 668,
          "_transferSize": 1018
        },
        "cache": {},
        "timings": {
          "blocked": 3.63900000229478,
          "dns": 0.02799998037516982,
          "connect": 128.67100001312804,
          "send": 0.06300001405202238,
          "wait": 209.54599999822597,
          "receive": 1.566000049934246,
          "ssl": -1
        },
        "connection": "338",
        "pageref": "page_1"
      },
      {
        "startedDateTime": "2015-08-21T17:09:46.932Z",
        "time": 93.50800001993775,
        "request": {
          "method": "GET",
          "url": "http://www.hvac-rebate.com/favicon.ico",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Referer",
              "value": "http://www.hvac-rebate.com/App/pouchdb/index.html"
            },
            {
              "name": "Host",
              "value": "www.hvac-rebate.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 348,
          "bodySize": 0
        },
        "response": {
          "status": 404,
          "statusText": "Not Found",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 21 Aug 2015 17:09:35 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.10 (Ubuntu)"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=99"
            },
            {
              "name": "Content-Length",
              "value": "290"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=iso-8859-1"
            }
          ],
          "cookies": [],
          "content": {
            "size": 290,
            "mimeType": "text/html",
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 216,
          "bodySize": 290,
          "_transferSize": 506
        },
        "cache": {},
        "timings": {
          "blocked": 0.6460000295192,
          "dns": -1,
          "connect": -1,
          "send": 0.15500001609325398,
          "wait": 91.52599994558845,
          "receive": 1.1810000287368467,
          "ssl": -1
        },
        "connection": "313",
        "pageref": "page_1"
      },
      {
        "startedDateTime": "2015-08-21T17:09:52.505Z",
        "time": 0,
        "request": {
          "method": "OPTIONS",
          "url": "https://www.hvac-rebate.com:6984/_session",
          "httpVersion": "unknown",
          "headers": [
            {
              "name": "Access-Control-Request-Method",
              "value": "POST"
            },
            {
              "name": "Origin",
              "value": "http://www.hvac-rebate.com"
            },
            {
              "name": "Referer",
              "value": "http://www.hvac-rebate.com/App/pouchdb/index.html"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
            },
            {
              "name": "Access-Control-Request-Headers",
              "value": "accept, content-type"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "unknown",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_INSECURE_RESPONSE"
        },
        "cache": {},
        "timings": {
          "blocked": -1,
          "dns": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "ssl": -1
        },
        "pageref": "page_1"
      }
    ]
  }
}

**Comment by bucktaylor** [comment] 2015-08-21 17:23
Here is HTTP:

{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2015-08-21T17:19:34.240Z",
        "id": "page_2",
        "title": "http://www.hvac-rebate.com/App/pouchdb/index.html",
        "pageTimings": {
          "onContentLoad": 976.1040000012144,
          "onLoad": 975.8140000049025
        }
      }
    ],
    "entries": [
      {
        "startedDateTime": "2015-08-21T17:22:20.887Z",
        "time": 254.96900000143796,
        "request": {
          "method": "POST",
          "url": "http://www.hvac-rebate.com:5984/_session",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Origin",
              "value": "http://www.hvac-rebate.com"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Host",
              "value": "www.hvac-rebate.com:5984"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Accept",
              "value": "application/json"
            },
            {
              "name": "Referer",
              "value": "http://www.hvac-rebate.com/App/pouchdb/index.html"
            },
            {
              "name": "Cookie",
              "value": "AuthSession="
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "54"
            }
          ],
          "queryString": [],
          "cookies": [
            {
              "name": "AuthSession",
              "value": "",
              "expires": null,
              "httpOnly": false,
              "secure": false
            }
          ],
          "headersSize": 468,
          "bodySize": 54,
          "postData": {
            "mimeType": "application/json",
            "text": "{\"name\":\"nolanlawson\",\"password\":\"iFramedRogerRabbit\"}"
          }
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 21 Aug 2015 17:22:09 GMT"
            },
            {
              "name": "Server",
              "value": "CouchDB/1.6.0 (Erlang OTP/17)"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Access-Control-Allow-Origin",
              "value": "http://www.hvac-rebate.com"
            },
            {
              "name": "Access-Control-Expose-Headers",
              "value": "Cache-Control, Content-Type, Server"
            },
            {
              "name": "Cache-Control",
              "value": "must-revalidate"
            },
            {
              "name": "Access-Control-Allow-Credentials",
              "value": "true"
            },
            {
              "name": "Set-Cookie",
              "value": "AuthSession=bm9sYW5sYXdzb246NTVENzVFNDE6j1kVJ63PfUoeCK_T86USmbzJndA; Version=1; Path=/; HttpOnly"
            },
            {
              "name": "Content-Length",
              "value": "52"
            }
          ],
          "cookies": [
            {
              "name": "AuthSession",
              "value": "bm9sYW5sYXdzb246NTVENzVFNDE6j1kVJ63PfUoeCK_T86USmbzJndA",
              "path": "/",
              "expires": null,
              "httpOnly": true,
              "secure": false
            }
          ],
          "content": {
            "size": 52,
            "mimeType": "application/json",
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 454,
          "bodySize": 52,
          "_transferSize": 506
        },
        "cache": {},
        "timings": {
          "blocked": 0.870999996550381,
          "dns": -1,
          "connect": -1,
          "send": 0.322000007145109,
          "wait": 120.60500006191451,
          "receive": 133.17099993582798,
          "ssl": -1
        },
        "connection": "1212",
        "pageref": "page_2"
      }
    ]
  }
}

**Comment by bucktaylor** [comment] 2015-08-21 17:23
Here is HTTPS:

{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2015-08-21T17:19:34.241Z",
        "id": "page_2",
        "title": "http://www.hvac-rebate.com/App/pouchdb/index.html",
        "pageTimings": {
          "onContentLoad": 976.1040000012144,
          "onLoad": 975.8140000049025
        }
      }
    ],
    "entries": [
      {
        "startedDateTime": "2015-08-21T17:23:20.293Z",
        "time": 0,
        "request": {
          "method": "OPTIONS",
          "url": "https://www.hvac-rebate.com:6984/_session",
          "httpVersion": "unknown",
          "headers": [
            {
              "name": "Access-Control-Request-Method",
              "value": "POST"
            },
            {
              "name": "Origin",
              "value": "http://www.hvac-rebate.com"
            },
            {
              "name": "Referer",
              "value": "http://www.hvac-rebate.com/App/pouchdb/index.html"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
            },
            {
              "name": "Access-Control-Request-Headers",
              "value": "accept, content-type"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "unknown",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_INSECURE_RESPONSE"
        },
        "cache": {},
        "timings": {
          "blocked": -1,
          "dns": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "ssl": -1
        },
        "pageref": "page_2"
      }
    ]
  }
}

**Comment by bucktaylor** [comment] 2015-08-21 17:31
@csysmans how does it test before you compile in a cordova app?

**Comment by bucktaylor** [comment] 2015-08-21 17:44
@willholley is the HTTPS request not supposed to send authentication information like HTTP?

**Comment by willholley** [comment] 2015-08-23 08:08
@bucktaylor - from the HTTPS trace you can see that the browser is raising "net::ERR_INSECURE_RESPONSE" because it doesn't trust the self-signed certificate. I'd suggest that the quick fix is to add the certificate to your root certificates store or obtain a trusted certificate.

**Comment by bucktaylor** [comment] 2015-08-25 20:36
OK - so here's an update:

1). @willholley : Using a trusted Certificate does work in IE, Chrome, Mozilla. (IMMEDIATE SOLUTION)

2). If I authenticate first in http, then https works in Chrome, but I couldn't get it to work in IE or Mozilla. Sometimes if you open up another tab in the same browser, and open "https://www.hvac-rebate.com:6984/_session" by clicking through the warning it will also work (allows the browser to set the authentication cookie).

3). I set up my own CA and signed the certificates with the CA, however this still produces the same warning in all the browsers with one exception, using my own CA allowed https to work in Edge. It seems Edge is doing something different with the CA chain in this situation.

@daleharvey : although I would like to be able to use self-signed certificates as an option - perhaps this is not really a bug but rather something that needs enhancement (providing it is possible to detect and deal with the various browsers response to SSL/TLS messages/errors)?

Thanks everyone for your feedback.

**Comment by daleharvey** [comment] 2015-10-06 21:38
So SSL / TLS errors are way below the pouchdb stack and there isnt going to be anything we can do to improve them so closing this out, cheers for the help getting it identified

**Closed by daleharvey** 2015-10-06 21:38 UTC
Labels: enhancement
