### ISSUE TITLE
CustomPouchError does not copy all properties from the original Error

### ISSUE THREAD

**Issue by flimzy** [pouchdb/pouchdb#7886] opened 2019-08-19 21:19 UTC
### Issue
I've noticed occasional errors during replication, which have no description. After some debugging, I've narrowed it down to the [createError()](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-errors/src/index.js#L46) function.

I've only been able to reproduce the error condition under heavy load, so I don't know how to provide a reliable reproduction case, programatically.

It seems that under load, Pouch receives an error from Fetch, which isn't properly propagated by `createError()`. I've added the following debug code to the function to demonstrate:

```
function createError(error, reason) {
    console.log("in createError");
    console.log(error);
  function CustomPouchError(reason) {
      console.log("in CustomPouchError");
      console.log("reason = "+reason);
    // inherit error properties from our parent error manually
    // so as to allow proper JSON parsing.
    /* jshint ignore:start */
    for (var p in error) {
      if (typeof error[p] !== 'function') {
          console.log("setting "+p);
        this[p] = error[p];
    } else {
        console.log("not setting"+p);
    }
    }
    /* jshint ignore:end */
    if (reason !== undefined) {
      this.reason = reason;
    }
  }
  CustomPouchError.prototype = PouchError.prototype;
  var x = new CustomPouchError(reason);
  console.log("x");
  console.log(x);
  return x;
}
```

Then when running in my high-load situation, I see the following on the console:

![screenshot](https://user-images.githubusercontent.com/8555063/63300025-82385d80-c2d7-11e9-8c94-5d4c277dde38.png)

I would expect "Failed to fetch" to have been propagated to the final error.

Observed with Chrome 73.0.3683.75 and PouchDB 7.1.1.

**Comment by flimzy** [comment] 2019-10-20 12:43
ping

**Comment by dreamair** [comment] 2019-11-20 08:11
It doesn't seem to "eat" the error, but it misses to propagate the properties of the cause error. Some Error properties are not enumerable for some reason I couldn't find (https://esdiscuss.org/topic/should-error-message-be-enumerable). So the for-in-error does not work for example the properties 'message', 'name' or 'stack' and important information gets lost.

**Comment by flimzy** [comment] 2020-01-19 09:59
ping

**Comment by flimzy** [comment] 2020-03-19 11:13
> It doesn't seem to "eat" the error, but it misses to propagate the properties of the cause error. Some Error properties are not enumerable for some reason I couldn't find (https://esdiscuss.org/topic/should-error-message-be-enumerable). So the for-in-error does not work for example the properties 'message', 'name' or 'stack' and important information gets lost.

Is a solution apparent to you? I don't mind creating a PR, but it wasn't clear to me how to proceed.

**Comment by dreamair** [comment] 2020-03-20 11:24
Sorry, I've lost track of this issue. For my situation I've had a quick-fix of replacing the for-in-error with 
```
for (var p of ['message', 'stack', 'name']) {
      if (p in error && typeof error[p] !== 'function') {
        this[p] = error[p];
      }
}
```
For a more generic approach it's probably better to use something like
```
var obj = error
while (obj) {
	for (var p of Object.getOwnPropertyNames(obj)) {
		if (typeof obj[p] !== 'function') {
			this[p] = obj[p];
		}
	}
	obj = Object.getPrototypeOf(obj)
}
```
This should work better than the existing for-in-error even without testing. But some unit tests with real-life errors might be nice....

**Comment by garethbowen** [comment] 2020-05-17 21:08
This is now fixed in `master`.

**Closed by garethbowen** 2020-05-17 21:08 UTC
