### ISSUE TITLE
Use leveldown-prebuilt to speed up install for node?

### ISSUE THREAD

**Issue by slaskis** [pouchdb/pouchdb#3981] opened 2015-06-18 09:16 UTC
I'm using pouchdb currently in both node and client but I'm not using the leveldb adapter. But it still insists on building that excruciatingly slow dependency. 

Any thoughts on using https://www.npmjs.com/package/leveldown-prebuilt instead to make it faster for node installs? 

Or perhaps only load that adapter if leveldb is installed? I realize it's a minor inconvenience but with that clear in the install instructions of just a very friendly deprecation message if that adapters is attempted I think it could be fine.

Cheers!

**Comment by daleharvey** [comment] 2015-06-18 09:57
Yeh I tried leveldown-prebuilt previously and it failed tests, but worth trying again. 

One idea has been to split into `pouchdb-http` `pouchdb-level` etc, with people having the ability to switch to their own level adapter or to just be using a http client we definitely would like it, but it is definitely fiddly between the configurable adapters, level-alt etc

**Comment by nolanlawson** [comment] 2015-06-18 12:32
I think we would need to make Node a build target instead of source code (so then we could build `pouchdb-without-leveldb`), which may become necessary anyway if we switch to Babel. But we're a long way off from that for now.

**Comment by slaskis** [comment] 2015-06-18 19:45
Actually I just read this on their github:

> leveldown (>= 1.2.2) now supports prebuilds so you shouldn't have to use this fork anymore

So maybe just updating leveldown will do it?

**Comment by slaskis** [comment] 2015-06-18 19:57
Trying it now I see that the tests get stuck on `testUtils.cleanup` where the destroy callback is never called. 

So I guess it's more work than just updating :/ But at least the npm install was fast! ;)

**Comment by daleharvey** [comment] 2015-06-18 20:08
Yeh this has come up, there are breaking changes that will need migration - https://github.com/pouchdb/pouchdb/issues/3873

**Comment by daleharvey** [comment] 2015-06-22 04:07
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/3873, hopefully we can get it done soon

**Closed by daleharvey** 2015-06-22 04:07 UTC
