### ISSUE TITLE
infinite error loop with _bulk_get. (5.1.0)

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#4546] opened 2015-11-05 16:15 UTC
Hello, On Safari (with Ionic Cordova - PouchDB 5.1.0 - CLOUDANT) I encounter this error : 

[Error] Failed to load resource: request body stream exhausted (_bulk_get, line 0)
https://myapp-cloudant.com/mydb/_bulk_get?revs=true&attachments=true

I don't have any issue on Chrome. And CORS is activated on Backend side ( Cloudant).

```
2015-11-05 17:14:23.494 myapp[4057:34894] WARN: PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
2015-11-05 17:14:24.102 myapp[4057:34894] Sync replicate resumed - user went back online 
2015-11-05 17:14:24.534 myapp[4057:34894] WARN: PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
2015-11-05 17:14:24.535 myapp[4057:34894]  Sync onPause {"status":500,"name":"unknown_error","message":"Database encountered an unknown error"}
2015-11-05 17:14:25.725 myapp[4057:34894] WARN: PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
2015-11-05 17:14:26.250 myapp[4057:34894] Sync replicate resumed - user went back online 
2015-11-05 17:14:27.200 myapp[4057:34894] WARN: PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
2015-11-05 17:14:27.203 myapp[4057:34894]  Sync onPause {"status":500,"name":"unknown_error","message":"Database encountered an unknown error"}
2015-11-05 17:14:28.431 myapp[4057:34894] WARN: PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
2015-11-05 17:14:28.955 myapp[4057:34894] Sync replicate resumed - user went back online 
2015-11-05 17:14:29.471 myapp[4057:34894] WARN: PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
2015-11-05 17:14:29.474 myapp[4057:34894]  Sync onPause {"status":500,"name":"unknown_error","message":"Database encountered an unknown error"}
```

```

console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
https://myapp.cloudant.com/myDB/_bulk_get?revs=true&attachments=trueFailed to load resource: request body stream exhausted
console-via-logger.js:173 Sync onPause 
PouchError
console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
console-via-logger.js:173Sync replicate resumed - user went back online 
console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
https://myapp.cloudant.com/myDB/_bulk_get?revs=true&attachments=trueFailed to load resource: request body stream exhausted
console-via-logger.js:173 Sync onPause 
PouchError
console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
console-via-logger.js:173Sync replicate resumed - user went back online 
console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
https://myapp.cloudant.com/myDB/_bulk_get?revs=true&attachments=trueFailed to load resource: request body stream exhausted
console-via-logger.js:173 Sync onPause 
PouchError
console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
console-via-logger.js:173Sync replicate resumed - user went back online 
console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
https://myapp.cloudant.com/myDB/_bulk_get?revs=true&attachments=trueFailed to load resource: request body stream exhausted
console-via-logger.js:173 Sync onPause 
PouchError
console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
console-via-logger.js:173Sync replicate resumed - user went back online 
console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
https://myapp.cloudant.com/myDB/_bulk_get?revs=true&attachments=trueFailed to load resource: request body stream exhausted
console-via-logger.js:173 Sync onPause 
PouchError
console-via-logger.js:173PouchDB: the remote database may not have CORS enabled.If not please enable CORS
```

**Comment by nickcolley** [comment] 2015-11-05 16:20
Hey @ronyrun,

What version of PouchDB are you using?

Also if you have a snippet to reproduce that'd be great.

**Comment by ronyrun** [comment] 2015-11-05 16:23
Hey @nickcolley  
  "name": "pouchdb",
  "version": "5.1.0",

**Comment by ronyrun** [comment] 2015-11-05 16:26
OK no more loop with the 5.0.0 version.

**Comment by ronyrun** [comment] 2015-11-05 16:30
It's working fine on Chrome with the 5.1.0 version.

**Comment by ronyrun** [comment] 2015-11-05 16:42
Correction, it's not working on Chrome as well, I have a popup with " authentication Required"

**Comment by nolanlawson** [comment] 2015-11-05 17:18
Does this only occur with Cloudant, or does it occur with CouchDB as well? Also please go into the Network tab and find the error that Cloudant is sending back, so we know what error PouchDB is not correctly handling.

**Comment by ronyrun** [comment] 2015-11-05 17:27
OK nolan, currently, I don't Have any couchDB server available right now.
let me get the network error from cloudant.

**Comment by daleharvey** [comment] 2015-11-05 17:31
Yeh would be interested if you are getting a 5XX error, if so may be a dupe of https://github.com/pouchdb/pouchdb/issues/4542

**Comment by ronyrun** [comment] 2015-11-05 17:46
I have issue also on the db.change call.
But on Safari Inspector, the network I don't find a proper way to get the errors...

**Comment by ronyrun** [comment] 2015-11-05 17:49
Sync onPause {"status":500,"name":"unknown_error","message":"Database encountered an unknown error"}

**Comment by daleharvey** [comment] 2015-11-08 10:10
Yup definitely, dupe of https://github.com/pouchdb/pouchdb/issues/4542

**Closed by daleharvey** 2015-11-08 10:10 UTC

**Comment by ronyrun** [comment] 2015-11-08 10:21
Hello Dale, thank you for your concern on this issue.
Thank all of you you for your work!
