### ISSUE TITLE
Having a variable called URL kills PouchDB

### ISSUE THREAD

**Issue by glynnbird** [pouchdb/pouchdb#4014] opened 2015-06-30 07:18 UTC
I had code like this:

```js
var URL = "https://myurl.cloudant.com/mydb";
var db = new PouchDB("mydb");
db.replicate.from(URL);
```

and PouchDB died with `Uncaught TypeError: URL.createObjectURL is not a function`

This is th the code in `checkBlobSupport` that fails

```js
...
        var storedBlob = e.target.result;
        var url = URL.createObjectURL(storedBlob);
...
```

If I change my variable name to avoid the clash with "URL", then it everything works as expected e.g.
```js
var U = "https://myurl.cloudant.com/mydb";
var db = new PouchDB("mydb");
db.replicate.from(U);
```

**Comment by daleharvey** [comment] 2015-06-30 12:58
lol nice, `window.URL` doesnt help either, I know there are different ways to define global properties to not be overridable, maybe have to file as a browser bug

**Comment by Ginden** [comment] 2015-06-30 20:40
Fun fact - this code also kills PouchDB:
```
Array.shift = null;
```

Solution: do not create variables in global scope, because you risk a conflict between native browser object/function and user-defined.

**Comment by glynnbird** [comment] 2015-06-30 20:56
Yes indeed. I thought at first it was PouchDB not being careful enough with variable scope, but I didn't appreciate it was https://developer.mozilla.org/en-US/docs/Web/API/URL I was killing. ;)

**Comment by Ginden** [comment] 2015-06-30 20:58
It's good idea to never pollute global scope. ;)

**Comment by ermouth** [comment] 2015-06-30 21:39
@daleharvey Seems it‘s not a bug. To protect code from that kind of overloads good approach is to copy references to system globals into local closure vars on start. Like:
``` javascript
(function Pouchstart (Window) {
  // Init goes here
  var URL = Window.URL, localStorage = Window.localStorage // an so on
// Code goes here
})(window);
```
At least this reduces risk – no guarantee they are not broken when Pouch starts. But if they are untouched on start, Pouch shouldn‘t not break when someone redefines `window.URL` later.

**Comment by daleharvey** [comment] 2015-07-06 16:53
Yeh that would work but its more code to fix the very rare case of things being redefined after the fact, this happens with all dom globals (indexeddb etc) I talked to the dom team at firefox and theres basically no fix except possible future support for modules, so closing this out

**Closed by daleharvey** 2015-07-06 16:53 UTC

**Comment by Ginden** [comment] 2015-07-07 08:24
It's possible to avoid any clash if only `document.__proto__.__proto__.createElement` wasn't overwriten.
`window.document` is not possible to be overwriten (`Object.getOwnPropertyDescriptor(window, 'document')`).
So we can do:
`document.createElement('iframe')
...
iframe.contentWindow.URL; // fully functional object
`
Anyway - it's heavy fix for rare problem.

**Comment by nolanlawson** [comment] 2015-07-18 18:58
Also it is dangerous to start looking for `window` because then you might break NW.js (which we still need to test in CI, long story).
