### ISSUE TITLE
Cache ddoc views and filters for performance

### ISSUE THREAD

**Issue by garethbowen** [pouchdb/pouchdb#4867] opened 2016-02-03 21:05 UTC
Querying persistent views [first gets and parses the ddoc](https://github.com/pouchdb/pouchdb/blob/master/src/mapreduce/index.js#L887) to get the view implementation. With a large ddoc such as  a complex couchapp this can be slow, for example with my 9MB ddoc this was taking around 1 second. Because the ddoc is parsed for each query request it quickly becomes a performance bottleneck.

I wrote a dirty dirty patch to implement a `views` cache which greatly improves the performance of my app.

Other areas of the code also query the ddoc for `views` and `filters` properties and so would also benefit from this change.

My proposal is to cache the `views` and `filters` on the db object and then listen for changes to the ddoc to invalidate the cache.

**Comment by garethbowen** [comment] 2016-02-03 21:06
If this approach is acceptable I'm happy to help out with a PR for it.

**Comment by nolanlawson** [comment] 2016-02-05 13:38
I think this sounds like a reasonable fix, especially if it can be done in such a way that guards against odd edge cases like e.g. updating the ddoc. We already heavily cache inside of map/reduce, but it would make sense to go one step further and cache the ddoc itself as well.

If you open up a PR, it will run the tests against the full map/reduce test suite, and we can confirm that the fix works. I'd be happy to see your PR! :)

**Comment by daleharvey** [comment] 2016-02-19 10:32
Fixed in https://github.com/pouchdb/pouchdb/commit/0ddeae6b6c44fa12b83c5348df6947e3ce28c28c

**Closed by daleharvey** 2016-02-19 10:32 UTC

**Comment by nolanlawson** [comment] 2016-05-03 02:22
In retrospect I think this PR might have been merged too eagerly. Looking over the code now, I see several issues:

- adds undocumented `getView()` and `getFilter()` to the API, which could confuse users. These should at least be `_`-prefixed.
- no evidence that this speeds anything up, or by how much
- adds another dependency between mapreduce and pouchdb core, making it harder to untangle them (if we ever will)

In #5118 this commit has actually been accused of creating a performance _regression_. So I really think we need to re-evaluate this PR and determine whether it's worth the maintenance cost and the potential performance cost.

**Comment by nolanlawson** [comment] 2016-05-03 02:28
There's another fundamental problem with this PR, which is that it's not actually safe to cache DDocs in-memory and use that to determine whether or not an update is required. Hence why you have to do the `changes()` request for every ddoc `get()`.

It seems like if anything, this PR addresses the problem of having an enormous ddoc (e.g. one that is 9MB - why such a large DDoc?), whereas it introduces new performance problems due to:

1. having to do `changes()` for every map/reduce request, and
2. adding a new `Promise` to the async chain, thus increasing the number of ticks

I think without any evidence that this improves anything, I would strongly be in favor of reverting.

**Comment by daleharvey** [comment] 2016-05-03 14:24
> (e.g. one that is 9MB - why such a large DDoc?)

Its fairly common in couchapps to store the entire application in the design doc, including all the binary assets (js / css / html / images etc) so 9MB isnt actually surprisingly big, however a large amount of that should likely be attachment data which doesnt need resolved when picking up the view code

**Comment by garethbowen** [comment] 2016-05-03 20:24
> however a large amount of that should likely be attachment data which doesnt need resolved when picking up the view code

The bulk of the issue is that kanso (couchapp builder) inlines things such as node modules and app settings instead of using an attachment or a separate doc. This means the parser has to do a lot of work to find the views. It's difficult to know how many other people will face the same issue.

I'm planning workaround the issue by reducing the size of the ddoc in pouch by plucking the minimal set of properties into a client side ddoc, and pulling out the app settings into a separate doc.

**Comment by nolanlawson** [comment] 2016-05-06 15:46
That sounds like a good compromise; sorry there's no good solution here that fits all use cases. FWIW native secondary indexes will probably fix the case for smaller DDocs and then we can revisit what we do for larger DDocs.
