### ISSUE TITLE
destroy() race condition causing IndexedDB to hang

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3415] opened 2015-01-20 00:16 UTC
Still haven't tracked this down, but opening up an issue so it doesn't fall through the cracks.

I've managed to get IndexedDB in a state where it just doesn't respond in Chrome after a few tests. Seems to be related to `stale: update_after` in map/reduce causing some parallelism. Weirdly, the tests complete when the Dev Tools are open, so we may have another Heiseinbug on our hands.

https://github.com/pouchdb/pouchdb/pull/3414 does not fix this particular bug.

**Comment by nolanlawson** [comment] 2015-01-20 00:20
Oh okay, in both Firefox and Chrome it gets stuck around 93%. Live demo: http://bl.ocks.org/nolanlawson/dc5d9d1f2de083963689

**Comment by nolanlawson** [comment] 2015-01-20 00:21
Cannot repro in Safari.

**Comment by nolanlawson** [comment] 2015-01-20 15:44
Cannot repro in IE. Also cannot repro in Firefox anymore; maybe it was a fluke.

**Comment by daleharvey** [comment] 2015-01-21 14:51
Hmm, I am sure there is some problem with https://github.com/pouchdb/pouchdb/blob/master/lib/constructor.js#L118 interfering with the task queue

**Comment by nolanlawson** [comment] 2015-01-21 15:48
Hmmm, I'm kinda convinced it's an IDB bug, else why would it work in WebSQL/Level?

**Comment by daleharvey** [comment] 2015-01-21 15:52
I think we may have different bugs

**Comment by nolanlawson** [comment] 2015-01-22 17:14
I can occasionally repro in Firefox 35. It's very inconsistent though.

**Comment by nolanlawson** [comment] 2015-01-22 17:19
OK, Chrome is saying `Unhandled promise rejection` with stacktrace;

```
"Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Error (native)
    at startTransaction (http://bl.ocks.org/nolanlawson/raw/dc5d9d1f2de083963689/test-bundle.js:19678:15)
    ...
```

The line throwing an error is [this one](https://github.com/pouchdb/pouchdb/blob/ada62f35b7fa1badab9dcf8e9b50689dc13e4000/lib/adapters/idb/idb-bulk-docs.js#L63).

So I think we need two fixes:

1) Whenever `idb.transaction` is called, convert a sync error into an async error
2) Mapreduce should catch errors and do something smart if the database is closing

**Comment by nolanlawson** [comment] 2015-01-23 16:52
OK, I get it. The issue is that `idb.transaction` throws a sync error from within a function that is not a promise, so it doesn't call `reject`.

**Comment by nolanlawson** [comment] 2015-01-24 15:28
Man, I have seriously tried every way I can think of to repro this. I am able to reproduce it in the new pouchdb-find repo, but only occasionally.

**Comment by nolanlawson** [comment] 2015-02-03 14:05
This got reported by a user in the wild. We should probably track it down:

    Hi everyone, I'm getting an error (DOMException 11) after perform a call to the "query" method, do anyone know the reason and/or how to fix it?
    the detailed error is: (DOMException) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

**Comment by nolanlawson** [comment] 2015-02-07 18:54
duplicate of #3277

**Comment by bedney** [comment] 2015-02-19 01:33
I'm seeing this error consistently (i.e. 100% of the time) when doing a 'remove' with both an '_id' and a '_rev'.

The error text is exactly the same as above.

Any thoughts on fix or ETA of fix?

Thanks!

**Comment by nolanlawson** [comment] 2015-02-19 02:14
@bedney Are you destroying the database? And yeah, a live example to reproduce would be superb.

**Comment by bedney** [comment] 2015-02-19 02:51
I am not. I'm deleting a single document with an `_id` and `_rev` using `remove`. I get the `_rev` first by doing a `get`. Note that I'm not using the Promises interface, but old-style callbacks. So, to paraphrase, it's like this:

```js
testDb = new PouchDB('pouch_test');
testDb.put({_id:'author_info',body:{firstName: 'Bill', lastName: 'Edney'}});
testDb.get({_id:'author_info'}, function (err,data) {
    testDb.remove({_id:'author_info', _rev: data._rev}, function(err,data) {
    // error occurs here.
}
});
```
I can get you a live example of this if you'd like - pressed for time right now.

**Comment by nolanlawson** [comment] 2015-02-19 03:23
I'm not able to repro your error (here's [a block](http://bl.ocks.org/nolanlawson/9d0cb6b01457940aa785)), but your code doesn't seem quite right, because you're doing the `put` and the `get` simultaneously, introducing race conditions. What you probably want is:

```js
testDb.put({_id:'author_info',body:{firstName: 'Bill', lastName: 'Edney'}}, function (err) {
  testDb.get({_id:'author_info'}, function (err,data) {
      testDb.remove({_id:'author_info', _rev: data._rev}, function(err,data) {
      // error occurs here.
    });
  });
});
```

I'm guessing that the IndexedDB error itself is a red herring and is caused by a synchronous error being thrown in user code, resulting in IndexedDB closing down.

**Comment by bedney** [comment] 2015-02-19 04:05
@nolanlawson - Wow, well I feel stupid... I knew I needed to do that for the get/remove pair... sorry for wasting your time and thanks for the tip. That fixed this for me.

Unfortunately, that doesn't give you a good test case - sorry :-(.

**Comment by nolanlawson** [comment] 2015-02-19 12:22
It's okay; I'm starting to get an idea of what's going on here. :) Thanks for reporting.

**Comment by doublerebel** [comment] 2015-03-19 23:57
I've run into this just now, reliably reproducible on Chrome.  I do a destroy, where within the callback I create a new database of the same name.  This is because #802 is still open and I have no other way to purge documents.

I'm trying to use a setTimeout to get around the race condition but so far not even 100ms is sufficient.  Thanks for your work, PouchDB is otherwise awesome.

**Comment by nolanlawson** [comment] 2015-03-20 05:07
Currently you should be able to work around this by waiting for any `db.query()`s to complete. I.e. if you have any design documents with map/reduce functions inside of them, just query them all (with `limit:0`) and wait for them to finish.

If you are not using `query()` and you're still running into this, then I would be very surprised. Is that the case?

**Comment by doublerebel** [comment] 2015-03-21 19:27
@nolanlawson Thanks for the suggestions.  It turned out there was an error in recreating the database, and since I wasn't passing a callback or listening for the error from the Create Database promise, I didn't see the error.

Therefore it's more related to #1715 -- nearly all async cases are documented except for Create Database.  Perhaps a callback should be recommended to avoid #1940?  Listening for the error in the callback is working great for us, but I know the trend is to prefer Promises over callbacks.

**Comment by agozie** [comment] 2015-08-15 04:36
Just got this 
`Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`

The happens constantly with `query`.

**Comment by nolanlawson** [comment] 2015-08-15 15:29
@agozie Currently the workaround is to be sure that the secondary index is up-to-date before destroying. E.g. you can simply do

```js
db.query('some_ddoc/some_view', {limit: 1}).then(function () {
  return db.destroy();
});
```

**Comment by agozie** [comment] 2015-08-15 18:51
@nolanlawson I didn't destroy the db, I refreshed and got that error. Destroying the db afterwards failed to correct it. I had to manually delete db, and it was ok.

**Comment by tohagan** [comment] 2015-11-19 08:40
Got this one today with PouchDB v5.0.0 while running inside my debugger.  
      Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

* `startChanges()` is calling `abortReplication()` 

I create a `var db = PouchDB('x')`, call `db.destroy()` and then db.sync(dbRemote, ...)
I'm wishing that there was a way to do `db.create()` to ensure that I can safely call  `db.sync()` 

**Stack Trace:**

	    at Error (native)
	    at exports.openTransactionSafely (http://localhost:9876/absoluteD:/Projects/MyApp/src/client/bower_components/pouchdb/dist/pouchdb.js:3889:16)
	    at PouchDB.api._getLocal (http://localhost:9876/absoluteD:/Projects/MyAppsrc/client/bower_components/pouchdb/dist/pouchdb.js:3317:21)
	    at PouchDB.<anonymous> (http://localhost:9876/absoluteD:/Projects/MyApp/src/client/bower_components/pouchdb/dist/pouchdb.js:504:17)
	    at PouchDB.<anonymous> (http://localhost:9876/absoluteD:/Projects/MyApp/src/client/bower_components/pouchdb/dist/pouchdb.js:11217:21)
	    at PouchDB.<anonymous> (http://localhost:9876/absoluteD:/Projects/MyApp/src/client/bower_components/pouchdb/dist/pouchdb.js:11279:18)
	    at http://localhost:9876/absoluteD:/Projects/MyApp/src/client/bower_components/pouchdb/dist/pouchdb.js:8357:21
	    at PouchDB.<anonymous> (http://localhost:9876/absoluteD:/Projects/MyApp/src/client/bower_components/pouchdb/dist/pouchdb.js:8344:19)
	    at PouchDB.get (http://localhost:9876/absoluteD:/Projects/MyApp/src/client/bower_components/pouchdb/dist/pouchdb.js:11279:18)
	    at Checkpointer.getCheckpoint (http://localhost:9876/absoluteD:/Projects/MyApp/src/client/bower_components/pouchdb/dist/pouchdb.js:9887:22)

**Comment by jpike88** [comment] 2015-12-19 11:31
This code causes an issue in Chrome.

Why are race condition issues still an issue at this point?

```
templateDB.destroy().then(function(response) {
                    var templateDB = pouchDB('templates', {
                        size: 100,
                        auto_compaction: true
                    });

                    storeTemplateData(result.data);

                }).catch(function(err) {
                    // do it anyway
                    storeTemplateData(result.data);
                });

**Comment by daleharvey** [comment] 2015-12-19 11:55
For the same reason scope errors are :) programming is hard.

You are defining `templateDb` to the inner scope of the destroy function, `storeTemplateData` is seeing the old destroyed `templateDb` thats available to the outer scope, not the newly create instance, if you replace the `var templateDB =` with just `templateDB = ` you should be fine.

Just a note that we are pretty serious about making sure PouchDB is a welcoming and friendly place to contribute (see: https://github.com/pouchdb/pouchdb/blob/master/CODE_OF_CONDUCT.md), Very happy to reply to your issues but if you could keep that in mind when posting again it would be great. Thanks

**Comment by jpike88** [comment] 2015-12-19 12:00
It works in Safari, OS X, and even IE10. It shouldn't matter that I'm redeclaring the database, or that I'm using var or not. Chrome support in pouchDB is clearly the issue here.

**Comment by daleharvey** [comment] 2015-12-19 12:19
It does matter that you are redeclaring it, in our current api we require a valid and current instance in order to be able to write to the database, we are possibly looking at changing that but it is what is required currently. https://github.com/pouchdb/pouchdb/issues/4339 has more details about that issue. 

In OSX is likely works because webSQL doesnt have the concept of closing or deleting a database and the old reference is still valid, ie10 if it does indeed still work then it seems like it would have to be a bug in the implementation compared to both firefox and chrome, who both have the same behaviour @ http://paste.pouchdb.com/paste/14ldhn/

**Comment by drunksaint** [comment] 2016-02-25 11:49
i'm facing the same issue when i destroy the database and on complete, immediately recreate a database with the same name.

**Comment by nickcolley** [comment] 2016-02-25 12:15
@drunksaint can you try a nightly build and see if your error is still present? http://pouchtest.com/nightly/index.html

If it is, can you post the code so we can reproduce the issue?

Thanks :)

**Comment by drunksaint** [comment] 2016-02-25 12:34
i have 2 pages (say, a.html and b.html)
basically what i'm doing is:

in a.html,
pouch = new PouchDB('x');
couch = new PouchDB('couchserver/whatever');
sync couch and pouch.

sometime down the line (in a.html) i do
pouch.destroy().then(function(){
   window.location.href = "b.html";
}

b.html does some very simple stuff (non-pouch related) and goes back to a.html, which creates the same pouchdb 'x' and tries to sync from a different couchdb (couchserver/whateverelse). this is when the error occurs in my experience.

i'm not sure if the different couch server is relevant though.

**Comment by soitgoes** [comment] 2016-04-11 02:23
I ran into this exception in Chrome.
```
Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Error (native)
```

 My scenario went something like this.

```
db.destroy().then(function (){
   db = new PouchDB('test');
   db.put(...);
});
```

After replacing that with ..
```
db.destroy().then(function (){
   new PouchDB('test').then(function (tmpDb){
     db = tmpDb;
     db.put(...);
  });
});
```
I had good results.

Maybe the documentation could clear up that a promise is returned from the ctor.  I didn't realize that from the API or the examples.

**Comment by nolanlawson** [comment] 2016-04-17 21:39
This API (`new PouchDB('test').then(...)`) is actually quasi-deprecated, which is why we removed it from the docs. If it fixes your issue, then that's kind of troubling, but I would guess it's because of a race condition under the hood with IndexedDB.

Normally this problem can be worked around my just making sure that you don't try to access the database at the same time that you're `destroy()`ing it, or in the case of map/reduce, to make sure that your `query()`s have completed before `destroy()`ing.

**Comment by daleharvey** [comment] 2016-06-19 10:52
I have a test for this https://gist.github.com/daleharvey/5ac88ac0bfb3732bb6a42ed806b269c3

**Comment by daleharvey** [comment] 2016-06-19 11:10
ok so this is actually mostly ok, it may be in that previous versions we hung at this point, however the test shows that while the console will show 

```
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
```

The error is propogated via `.catch` on the query, users can handle it appropriately. Its possible we could provide a clearer message, however given that we want to pass through errors as much as possible and that deleting the data you are currently querying is an edge case that makes it fairly clear something is going to error I think its ok

**Comment by daleharvey** [comment] 2016-06-19 11:19
It is only ok in the browser however, in node it does hang

**Comment by daleharvey** [comment] 2016-06-19 19:42
So I tried out a fix for this, unfortunately its not going to be simple, right now on any database call we could have potentially deleted the store, in that case the call simple hangs, no error callback or error thrown, not sure if this is a leveldown or a sublevel issue, we could wrap every call but thats messy and we always miss some (we have already tried dealing with it in that way, both in the level adapter and the same with the replicator. 

I think a better fix could be done in alignment with https://github.com/pouchdb/pouchdb/issues/3224, the browser shouldnt however have this problem

**Comment by daleharvey** [comment] 2016-06-19 20:03
Alternatively we can figure out where this is happening, `level` is not supposed to hang in this way

```
> var db = require('level')('/tmp/xyz'); db.close(function () { db.get('whatever', function (err) { console.log(err) }) })
undefined
> [ReadError: Database is not open]
```

So not sure if leveldown or sublevel

**Comment by daleharvey** [comment] 2016-06-19 20:59
Anyone know leveldown / sublevel better than I do, so the call @ https://github.com/pouchdb/pouchdb/blob/master/packages/pouchdb-adapter-leveldb-core/src/index.js#L1328 hangs, trying to figure out where it is supposed to go to, I expected https://github.com/pouchdb/sublevel-pouchdb/blob/master/lib/shell.js#L82 but thats not printing out anything

**Comment by nolanlawson** [comment] 2016-06-19 23:05
If there's a failing test I'm happy to look into this. I'd like to fix it
on our end rather than the level end because ideally I'd like to neither
throw an error nor hang.

**Comment by daleharvey** [comment] 2016-06-19 23:24
The test is in a branch @ https://github.com/pouchdb/pouchdb/tree/3415, GREP=3415 to run it 

The bug is in level or sublevel, we are calling `.get` / `.put` and it hangs, it should callback with an error when the database is closed, we can work around it somewhat as we do with our current `isClosed()` calls, but that is messy, hard to test and in the end not really sufficient, if the database gets closed after we call `.get` / `.put` etc then we are still going to be in the same position, we need level to correctly report the error (which it does in basic testing)

**Comment by anowak** [comment] 2016-11-23 13:12
For the sake of completeness (one of the commenters reported seeing this error without destroying the database), we also see the 'database is closing' error with Pouch 5.4.5 and Chrome 54, but certainly not in the context of `destroy()` (we don't have any code that deletes local databases on this server).

Unfortunately, I wasn't able to reproduce it. The only thing I have is the following stacktrace. Sorry for the concatenated file, luckily on this server we don't uglify it:

```
Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at openTransactionSafely (http://beta.gdt.evidenceprime.com/app/javascripts/vendor-1478787482.js:90274:16)
    at startTransaction (http://beta.gdt.evidenceprime.com/app/javascripts/vendor-1478787482.js:90327:21)
    at http://beta.gdt.evidenceprime.com/app/javascripts/vendor-1478787482.js:90317:5
    at done (http://beta.gdt.evidenceprime.com/app/javascripts/vendor-1478787482.js:89813:9)
    at http://beta.gdt.evidenceprime.com/app/javascripts/vendor-1478787482.js:89788:14
    at Array.forEach (native)
    at preprocessAttachments (http://beta.gdt.evidenceprime.com/app/javascripts/vendor-1478787482.js:89782:12)
    at idbBulkDocs (http://beta.gdt.evidenceprime.com/app/javascripts/vendor-1478787482.js:90313:3)
    at PouchDB.idb_bulkDocs [as _bulkDocs] (http://beta.gdt.evidenceprime.com/app/javascripts/vendor-1478787482.js:91085:5)
    at PouchDB.<anonymous> (http://beta.gdt.evidenceprime.com/app/javascripts/vendor-1478787482.js:88946:15)
```

**Comment by chrisortman** [comment] 2016-12-05 23:08
I can reproduce pretty consistently when I manipulate the same database using two different instances of PouchDB

run `ember test --server -m 'Unit | Service | publisher'` on this commit

https://github.com/chrisortman/ember-cms-frontend/commit/f893c77f2987562b2c17b2ad7d33adbc23f05382

**Comment by kiyanovsky** [comment] 2017-04-10 16:19
I run into this error for the first time and seemingly no reason. This is a [screenshot](https://www.screencast.com/t/pTlMqryehNL) of two errors, the first one is DOMException and the second and all next - err:InvalidStateError in bulkDocs(). As far as I can see there were no any DB operations in time of the first exception from my side, except live synchronization.

**Comment by tshad** [comment] 2017-04-13 06:16
I am getting this same problem.  I normally erase the database, but for attachments, this seems to cause me an error.  This normally works fine but at some point, once this starts, it won't seem to fix itself.  There is nothing in the database at the point I am doing this.

My code looks like:
```
   }).then(function (json) {
      return loadCategoriesDDL();

      // TaskImages
   }).then(function () {
      if (DB_TaskImages != null)
         return DB_TaskImages.destroy();
   }).then(function () {                                    <---- I have breakpoints on all the lines around this.
                                                                              When I hit continue It doesn't go the next line
                                                                              It goes to the catch.
      return DB_TaskImages = new PouchDB(DBNAME_TaskImages, { auto_compaction: true });

      // Equipment
   }).then(function () {
```
The error I get is:
code: 11
message:"Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing."
name:"InvalidStateError"
stack:
"Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.↵    at st (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:7:28615)↵    at ke.e._getLocal (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:8:8112)↵    at ke.<anonymous> (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:10:10701)↵    at ke.<anonymous> (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:7:7346)↵    at ke.<anonymous> (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:10:22137)↵    at http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:7:6762↵    at Promise (<anonymous>)↵    at ke.<anonymous> (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:7:6681)↵    at ke.get (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:10:22137)↵    at ke.<anonymous> (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:10:14757)↵    at ke.<anonymous> (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:7:7346)↵    at ke.<anonymous> (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:10:22137)↵    at http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:7:6762↵    at Promise (<anonymous>)↵    at ke.<anonymous> (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:7:6681)↵    at ke.destroy (http://localhost:12531/Scripts/pouchdb-5.4.4.min.js:10:22159)"

What I am doing at this problem is clearing (erasing) all the databases and recreating them.  I destroy the attachment database because for some reason, erasing the datatabase, won't let me add records.  I get an error that says reason: deleted.  If I use destroy, I don't have that problem.  But I am not sure why I am getting this issue.

**Comment by charleskoehl** [comment] 2017-04-25 20:10
i got this error today as well in Google Chrome Version 57.0.2987.133 (64-bit). clicking "clear site data" in dev tools "application" tab with Indexed DB checked didn't fix. had to also restart chrome. so at least in that one case, both were needed

**Comment by mryellow** [comment] 2017-08-07 23:42
> "clear site data"

Just passing by, I find this bookmarklet handy:

`javascript:indexedDB.webkitGetDatabaseNames().onsuccess = function (sender) { for (var x in sender.target.result) { console.log('Delete', sender.target.result[x]); indexedDB.deleteDatabase(sender.target.result[x]); } }`

**Comment by mryellow** [comment] 2017-08-08 00:38
> had to also restart chrome

Appears in my case a reboot was required. Debian KDE Chrome.

Crashed the browser somewhere along the line and had a hidden "wait for script" window I didn't notice until it showed during shutdown.

**Comment by giulioprovasi** [comment] 2017-08-30 07:27
Someone have succeeded in reproducing the bug by using IndexedDB manually ? (Sorry for asking in a PouchDB issue, but haven't found anywhere else) ?

We have the same issue with our application when kept open for a few hours, but with a random reproducibility... and it locks the application, a chrome or sometimes computer reboot

**Comment by muhleder** [comment] 2017-08-30 08:16
We've seen it using IndexedDB via localForage, not in person but we get the error logs crop up from time to time in Sentry.

**Comment by victorbojica** [comment] 2017-11-03 10:40
Any luck on this? Able to reproduce a few times after clearing the site data from Chrome Dev Tools.

**Comment by pptdr** [comment] 2017-11-28 23:18
It is reproducible in chrome browser each time when local db is cleared manually and recreate data   during sync.

**Comment by nshoes** [comment] 2017-12-18 20:44
Any news or word on this? I ran into it a few days ago. At first the error in my console, then in subsequent refreshes, I had no errors. Our app just hung indefinitely. A reboot solved the problem.

**Closed** 2018-02-23 22:27 UTC
Labels: bug, wontfix

**Comment by riterrani** [comment] 2018-06-28 08:32
I am still having the same problem with this code

`db.destroy().then(function (){
   db = new PouchDB('test');
   db.put(...);
});`

**Comment by florianbaer** [comment] 2018-08-16 06:57
I got the same issue with the following code: 

```
return this.$q((resolve) => {
                this.pouchDbService.dropDatabase().then(() => { // wraps db.destroy() as promise
                    this.db = this.pouchDbService.createDatabase(); // wraps create new PouchDB(App.Constants.POUCH_DB_NAME); and return so
                    resolve();
                }).catch(error => {
                    console.error(error);
                    this.$log.error(error);
                });
            });
```
So same behavior as @riterrani 
**PouchDB 6.4.3**

**Comment by LyteFM** [comment] 2018-08-30 12:27
I'm not sure if this is directly related, but I'm happy if it helps. I got a similar error with an Ionic App on Android 8.0.0, Chrome 68.0.3440.91 using PouchDB 6.4.3:
```
DOMException: pouchdb failed to execute 'transaction' on 'idbdatabase': The database connection is closing
   at openTransactionSafely (...)
   at idbAllDocs (...)
   at PouchDB.idb_allDocs (...)
```
The issue appeared after I removed auto-compation from my db:
`myDB = new PouchDB( dbName, {revs_limit: 100, auto_compaction: true})`
and instead called a manual compaction after every sync. Asynchronally, another method queried the Pouch via `myDB.allDocs()`, which sometimes resulted in the above error. It also happened without destroying and re-creating a db, but just returning from background.

After reading https://www.bountysource.com/issues/55221986-error-indexed_db_went_bad-on-reading-from-a-database, I assumed this compaction was responsible, but cannot tell for sure. I reverted back to auto-compaction and could not reproduce the error since that.

If this is expected behaviour, the phrase "compaction is a harmless operation" in the docs is misleading.

**Comment by WillemvdW** [comment] 2020-09-10 18:36
We are experiencing the same where teh error: "InvalidStateError", name: "InvalidStateError", reason: "Failed to execute 'transaction' on 'IDBDatabase' message appears in a situation with a sync from couchdb where teh changes feed fails and the changes feed call times out.
