### ISSUE TITLE
Create directory if it doesn't exists?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5872] opened 2016-11-13 07:23 UTC
Would be nice if PouchDB created the specific directory path if it doesn't already exists.

Currently it fails with `No such file or directory`.

**Comment by nolanlawson** [comment] 2016-11-19 20:38
duplicate of https://github.com/pouchdb/pouchdb/issues/5668

**Closed by nolanlawson** 2016-11-19 20:38 UTC
