### ISSUE TITLE
Fix for #5145 breaks replication against Cloudant/CouchDB 2.0

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#5272] opened 2016-06-03 09:21 UTC
### Environment (Node.js/browser/hybrid app/etc.)

All

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

All

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

HTTP

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Cloudant, CouchDB 2.0

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

The fix for #5145 compares last_seq values from _changes. In Cloudant and CouchDB master, sequence numbers are strings, with an integer and a base64 part. The integer can be ignored (this is for backwards compatibility with CouchDB clients that test for an integer and is meaningless). The base64 part decodes as a list of Erlang tuples of the form `{node(), range(), {integer(), uuid()}}`, the combination of which uniquely identifies a position in a shard copy. The order of those tuples can change for each call to _changes, resulting in different sequence values to represent the same underlying state.

Unfortunately, the sequence value cannot currently be unpacked to a useful structure outside of Erlang, so they must be treated as opaque values and cannot be usefully compared (we can't event test for equality).

We can rethink how to implement the fix in #5145 without depending on last_seq but, until then, I think we need to revert the change or consciously break compatibility with Cloudant/CouchDB master.

**Comment by daleharvey** [comment] 2016-06-03 10:18
I commented on your comment, I shouldnt have missed it especially since I called out couch2 compat in the test, however `last_seq` values are supposed to be able to collate right? it seems like switching `old.last_seq > new.last_seq` should be able to be changed to collage(old.last_seq, new.last_seq)` and work as intended

**Comment by willholley** [comment] 2016-06-03 10:28
@daleharvey I don't believe that fix is safe either - sequence numbers are supposed to be treated as opaque blobs. I wonder whether that test is even required - just testing a branch with an alternative...

**Comment by daleharvey** [comment] 2016-06-03 16:37
Fixed in https://github.com/pouchdb/pouchdb/commit/176808878a116589ec68bb6476a0c75319e92c54

**Closed by daleharvey** 2016-06-03 16:37 UTC
Labels: bug
