### ISSUE TITLE
Replication of documents with many attachments is unstable

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#4963] opened 2016-03-08 12:20 UTC
I have a database which contains map tiles at different zoom levels. All these tiles are stored in a single doc, resulting in a document with around 200 attachments of average 10kb each. My DB stores 2000 documents, of which 50 contain 200 attachments. All others documents hold 0 or 1 attachment of 100kb size. Total DB size is 80mb.

Replicating (parts of) these databases to other databases seems instable, sometimes documents with many attachments are not written to the destination, but no error is raised.

I have tested quite some scenarios, these are my observations: (all against CouchDB 1.6.1 instances)

 - documents with little or no attachments always sync perfectly
 - syncing using the futon interface (couchdb-couchdb) works fine
 - replication from localhost is more stable than a remote host, maybe a slow connection makes the problem more apparent
 - setting `require('http').globalAgent.maxSockets = 10;` increase reliability, which makes me think pouchdb maybe does too many concurrent requests
 - `PouchDB.replicate(fromDB, toDB, {batch_size: 2, batches_limit: 2})` works much more stable than without the extra options.
 - I get the same problems when using `pouchdb-dump-cli`; the dump file will not contain all documents
 - running `pouchdb-dump-cli > dump.data` multiple times for the same db results in different `dump.data` files, which is very weird

My gut feeling is that the replicator fetches all attachments at once, which leads to a massive data transfer peak, which might be unstable. Probably some attachments fail to load, which silently breaks something more downstream.

I don't know where to start debugging. For now I am working with `{batch_size: 2, batches_limit: 2}` which seems most stable.

**Comment by nolanlawson** [comment] 2016-03-10 20:39
Thank you; this is very valuable research! Can you please confirm which browsers/environments you've tested this on? Sounds like Node and LevelDB, but I'm not sure e.g. which Node version, which OS, etc.

Some of the issues you raise are unfortunately not solveable due to CouchDB limitations. For instance, we cannot download attachments using the more efficient `multipart` format because they ship `gzip` and we can't reasonably decode that in JS. However, for uploads it is possible for us to directly upload blobs.

I believe most of these issues could be addressed by #3913, which is on [my personal roadmap](https://gist.github.com/nolanlawson/7953d9aaebbbe8cb382b) but I can't promise when it will get implemented. After that feature is shipped, all attachments should be uploaded/downloaded directly as binary.

That said, we obviously should try to fix the base64 case as well if possible.

**Comment by ermouth** [comment] 2016-03-28 20:48
I had similar issue with 3.3.1 in browser, at least symptoms look very same. 

In brief, opening too many XHR connections simultaneously, replication exhausted all available connection slots, and some requests stayed on hold for too long so they were aborted on timeout.

In my case it was fixed increasing default ajax timeout 100x, right inside PouchDB code.

**Comment by alxndrsn** [comment] 2016-04-01 20:49
We're seeing something similar with pouch `5.3.0` in Chrome browser.  Full discussion at https://github.com/medic/medic-webapp/issues/2134.

In our case we are replicating a db including ~20 docs with one attachment each, ranging in size from 2 to 70KB, on poor internet connections.  This is somewhat speculative, but it seems that if an attachment download fails then pouch does not save the doc, and does not retry the download again.  Restarting the browser will not trigger the download for these failed docs - the local storage must be cleared, and the replication restarted from the beginning.

This is a critical issue for us, so I would greatly appreciate knowing the priority of this for the pouchdb team cc: @nolanlawson.  We will likely work on fixing next week if it's not in your short term plans.

@ermouth if you can share a patch for your fix, or at least info on where the code change you made was, it sounds like this would be very helpful.

**Comment by garethbowen** [comment] 2016-04-03 23:03
It looks like replication ignores any errors returned from the bulk get shim.

1. If the get of the individual doc returns any error, then the [bulkGetShim returns `[{error:err}]`](https://github.com/pouchdb/pouchdb/blob/master/src/deps/bulkGetShim.js#L86).
2. This is ignored by the replicate/getDocs.js which [only returns docs which are `ok`](https://github.com/pouchdb/pouchdb/blob/master/src/replicate/getDocs.js#L54).
3. replicate.js then [writes the successful docs locally and updates the checkpoint](https://github.com/pouchdb/pouchdb/blob/master/src/replicate/replicate.js#L169-L173).

I can't see anywhere in 3 that checks if there are any outstanding docs in the current batch before `finishBatch` is called which writes the checkpoint and moves on to the next batch.

**Comment by garethbowen** [comment] 2016-04-04 03:51
I started to look into writing a test to replicate this and it looks like [one already exists](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js#L2051) however it's currently skipped. When I unskipped it and mocked out the right functions I can reproduce this issue which suggests to me this is a regression of #1240.

I'll try to do some more debugging on this tonight/tomorrow but any help on this would be greatly appreciated. Here's the patch test failing as expected:

```js
    it('(#1240) - get error', function (done) {
      var db = new PouchDB(dbs.name);
      var remote = new PouchDB(dbs.remote);
      // 10 test documents
      var num = 10;
      var docs = [];
      for (var i = 0; i < num; i++) {
        docs.push({
          _id: 'doc_' + i,
          foo: 'bar_' + i,
          // needed to cause the code to fetch using get
          _attachments: {
            text: {
              content_type: 'text\/plain',
              data: "VGhpcyBpcyBhIGJhc2U2NCBlbmNvZGVkIHRleHQ="
            }
          }
        });
      }
      // Initialize remote with test documents
      remote.bulkDocs({ docs: docs }, {}, function (err, results) {
        var bulkGet = remote.bulkGet;
        function first_replicate() {
          remote.bulkGet = function () {
            var getResults = [];
            for (var i = 0; i < docs.length; i++) {
              var doc = docs[i];
              getResults.push({
                id: doc._id,
                docs: [ {
                  ok: {
                    _id: doc._id,
                    foo: doc.foo,
                    _attachments: doc._attachments,
                    _rev: results[i].rev
                  }
                } ]
              });
            }
            // Mock remote.get to fail writing doc_3 (fourth doc)
            getResults[3].docs[0] = { error: new Error('timeout') };
            return Promise.resolve({ results: getResults });
          };
          // Replicate and confirm failure, docs_written and target docs
          db.replicate.from(remote).then(function(result) {
            should.exist(result);
            result.docs_written.should.equal(4);
            function check_docs(id, result) {
              if (!id) {
                second_replicate();
                return;
              }
              db.get(id, function (err, exists) {
                if (exists) {
                  should.not.exist(err);
                } else {
                  should.exist(err);
                }
                check_docs(docs.shift());
              });
            }
            var docs = [
              [
                'doc_0',
                true
              ],
              [
                'doc_1',
                true
              ],
              [
                'doc_2',
                true
              ],
              [
                'doc_3',
                false
              ],
              [
                'doc_4',
                false
              ],
              [
                'doc_5',
                false
              ],
              [
                'doc_6',
                false
              ],
              [
                'doc_7',
                false
              ],
              [
                'doc_8',
                false
              ],
              [
                'doc_9',
                false
              ]
            ];
            check_docs(docs.shift());
          });
        }
        function second_replicate() {
          // Restore remote.bulkGet to original
          remote.bulkGet = bulkGet;
          // Replicate and confirm success, docs_written and target docs
          db.replicate.from(remote, function (err, result) {
            should.not.exist(err);
            should.exist(result);
            result.docs_written.should.equal(6);
            function check_docs(id, exists) {
              if (!id) {
                db.info(function (err, info) {
                  verifyInfo(info, {
                    update_seq: 6,
                    doc_count: 6
                  });
                  done();
                });
                return;
              }
              db.get(id, function (err, result) {
                if (exists) {
                  should.not.exist(err);
                } else {
                  should.exist(err);
                }
                check_docs(docs.shift());
              });
            }
            var docs = [
              [
                'doc_0',
                true
              ],
              [
                'doc_1',
                true
              ],
              [
                'doc_2',
                true
              ],
              [
                'doc_3',
                true
              ],
              [
                'doc_4',
                true
              ],
              [
                'doc_5',
                true
              ],
              [
                'doc_6',
                true
              ],
              [
                'doc_7',
                true
              ],
              [
                'doc_8',
                true
              ],
              [
                'doc_9',
                true
              ]
            ];
            check_docs(docs.shift());
          });
        }
        // Done the test
        first_replicate();
      });
    });
```

**Comment by alxndrsn** [comment] 2016-04-07 16:22
Could this also be related to short timeouts in the `bulkGetShim`?  https://github.com/pouchdb/pouchdb/issues/5042

**Comment by ig3** [comment] 2016-04-13 02:24
In 5.1.0, timeout in ajax called from src.changes() in getChanges() or replicate() returns an error {status:0}. It might be helpful if a timeout error was returned so that timeouts could be distinguished from other errors and handled specifically or, at least, reported specifically as such.

**Comment by ssured** [comment] 2016-04-13 08:39
@ig3: your last comment is quite interesting to me, and maybe is the source of a problem I am having. As I read your comment I understand from you that the changes feed throws an error when te ajax time-outs. The user land scenario would be, open a site using pouchdb on your device, listen for changes, put your device on standby, after a minute start your device again. In that scenario src.changes would throw an 'unknown' error? It might explain a lot of unknown errors I am having in my Rollbar logs. If so, then we should probably investigate in a new issue. Thanks for pointing me in this direction.

**Comment by nolanlawson** [comment] 2016-04-14 12:56
Should be solved by 29a0bcb7477cd0e6b88c00feccbca6fa1ee453ba; please reopen if it's still an issue!

**Closed by nolanlawson** 2016-04-14 12:56 UTC

**Comment by ig3** [comment] 2016-04-14 19:52
@ssured: If ajax is using XMLHttpRequest the timeout aborts the request. Anything that aborts the request before the server returns headers (before readyState === 1) will cause an 'unknown error'.  There are probably other ways to get this error but I don't know what standby does. If it doesn't cause an abort directly, it might cause a timeout.

**Comment by WillemvdW** [comment] 2019-10-14 18:30
> 
> 
> We're seeing something similar with pouch `5.3.0` in Chrome browser. Full discussion at [medic/medic#2134](https://github.com/medic/medic/issues/2134).
> 
> In our case we are replicating a db including ~20 docs with one attachment each, ranging in size from 2 to 70KB, on poor internet connections. This is somewhat speculative, but it seems that if an attachment download fails then pouch does not save the doc, and does not retry the download again. Restarting the browser will not trigger the download for these failed docs - the local storage must be cleared, and the replication restarted from the beginning.
> 
> This is a critical issue for us, so I would greatly appreciate knowing the priority of this for the pouchdb team cc: @nolanlawson. We will likely work on fixing next week if it's not in your short term plans.
> 
> @ermouth if you can share a patch for your fix, or at least info on where the code change you made was, it sounds like this would be very helpful.

Hi, we are experiencing similar issues occationallly with clients on very poor networks where it appears that the replication succeeded but the document was not saved, although the index was updated. Was there any more thoughts about how to catch or patch this?
