### ISSUE TITLE
Feature request: API for querying design document info

### ISSUE THREAD

**Issue by rpiaggio** [pouchdb/pouchdb#6920] opened 2017-12-07 04:35 UTC
### Issue
Allow querying design document's info, ie: http://docs.couchdb.org/en/stable/api/ddoc/common.html#db-design-design-doc-info.

### Info
- Environment: All
- Platform: All
- Adapter: All
- Server: CouchDB/Others?

### Reproduce
Already tried `db.get("_design/id/_info")`, but it doesn't work.

Thank you!

**Comment by daleharvey** [comment] 2017-12-07 14:41
Some of the information (disk size) etc will not be available from the browser context, that combined with us moving more towards pouchdb-find / mango over map reduce means its fairly unlikely we are going to want to implement this

What information were you looking to get / how were you planning to use it?

**Comment by rpiaggio** [comment] 2017-12-07 16:35
We mainly need to access `update_seq`. Comparing it with the DB `info`'s  `update_seq`, we can inform the user of index creation progress. Of course, I wouldn't expect local browser DBs to provide the same information as remote DBs if it's not available.

Also, I wouldn't expect local DBs to be so large as to require this functionality, so being able to use it at least for remote CouchDB DBs would be great.

Thank you, @daleharvey !

**Comment by rpiaggio** [comment] 2017-12-07 19:28
Actually, it make even make more sense to provide a way to invoke `_active_tasks`, at least for remote DBs.

**Comment by avickers** [comment] 2017-12-08 15:47
The issue is the automatic uri encoding done in the http adapter.  It skips the substrings _local/ and _design/ but otherwise encodes all ids.

@rpiaggio One quick and dirty option for you is to create a custom adapter, which is just the http adapter with the automatic encoding removed.

Then I guess the question is whether get requests prefixed with _design need to be encoded at all or if the edge case of those ending in _show should be handled separately.  If Pouch and Couch are beginning to diverge, then maybe Nano becomes a more appropriate library for some things.

**Comment by daleharvey** [comment] 2017-12-09 11:03
So PouchDB has / will only ever support a subset of CouchDB's API, most of the design doc functionality is not in pouchdb and less of it will be in the future, in pouch we try our best to only support things that will be shared by all adapters and dont implement http only stuff

Even if we didn't encode the url and the request managed to work its not a very robust solution, we could easily expect to make assumptions during .get requests that dont hold true for certain apis

Your last point is a good solution I think, if you want to make requests to an api pouchdb doesnt support, make the request directly (you can use nano, but fetch'ing directly would work too)

**Closed by daleharvey** 2017-12-09 11:03 UTC
