### ISSUE TITLE
leveldown is not defined: unable to import leveldown

### ISSUE THREAD

**Issue by rdpascua** [pouchdb/pouchdb#5474] opened 2016-07-15 06:36 UTC
Hi I'm having this error when using electron+webpack+pouchdb, I'm using `leveldb` for my adapter

`webpack.base.conf.js`

```
var path = require('path')
var webpack = require('webpack')
var config = require('../config')
var cssLoaders = require('./css-loaders')
var projectRoot = path.resolve(__dirname, '../')

module.exports = {
  // Note: entry points are added by environment-specific configs.

  output: {
    path: config.build.outputRoot,
    filename: '[name].js'
  },
  // Use target 'node' so that __dirname works properly. We then need
  // to manually specify the electron modules in the ExternalsPlugin
  // since we're not using target 'electron'.
  target: 'node',
  node: {
    __filename: false,
    __dirname: false
  },
  resolve: {
    extensions: ['', '.js', '.vue', '.json', '.node'],
    fallback: [path.join(__dirname, '../node_modules')],
    alias: {
      app: path.resolve(__dirname, '../app')
    }
  },
  resolveLoader: {
    fallback: [path.join(__dirname, '../node_modules')]
  },
  module: {
    noParse: /node_modules\/json-schema\/lib\/validate\.js/,
    preLoaders: [
      {
        test: /\.vue$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /vue-devtools|node_modules/
      }
    ],
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /vue-devtools|node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.html$/,
        loader: 'vue-html'
      },
      {
        test: /\.(png|jpe?g|gif|svg|woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url'
      }
    ]
  },
  plugins: [
    new webpack.ExternalsPlugin('commonjs2', [
      'desktop-capturer',
      'electron',
      'ipc',
      'ipc-renderer',
      'native-image',
      'remote',
      'web-frame',
      'clipboard',
      'crash-reporter',
      'screen',
      'shell',
      'leveldown'
    ]),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    })
  ],
  externals: [
    'leveldown'
  ],
  vue: {
    loaders: cssLoaders()
  },
  eslint: {
    formatter: require('eslint-friendly-formatter')
  }
}
```

`Error`

```
api.js?dffc:9 Error: ReferenceError: leveldown is not defined: unable to import leveldown
    at requireLeveldown (eval at <anonymous> (http://localhost:8080/app.js:1872:2), <anonymous>:4994:12)
    at PouchDB.LevelDownPouch (eval at <anonymous> (http://localhost:8080/app.js:1872:2), <anonymous>:5006:17)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1872:2), <anonymous>:2728:36)
    at new PouchDB (eval at <anonymous> (http://localhost:8080/app.js:1872:2), <anonymous>:2659:17)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:2136:2), <anonymous>:13:15)
    at Object.<anonymous> (http://localhost:8080/app.js:2136:2)
    at __webpack_require__ (http://localhost:8080/app.js:518:30)
    at fn (http://localhost:8080/app.js:49:20)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:2142:2), <anonymous>:7:12)
    at Object.<anonymous> (http://localhost:8080/app.js:2142:2)(anonymous function) @ api.js?dffc:9emitOne @ events.js:101emit @ events.js:188backOff @ index.js?adeb:7654completeReplication @ index.js?adeb:7969abortReplication @ index.js?adeb:7941(anonymous function) @ index.js?adeb:8123
backend.js?64a4:18 backend -> devtools Object {event: "vuex:init", payload: "{"dashboard":{"pageIndex":0,"sidebarToggled":false…},"route":{"path":"","query":null,"params":null}}"}
```

**Comment by nolanlawson** [comment] 2016-07-16 00:13
When you use pouchdb+leveldown in Electron projects, you need to manually rebuild leveldown for Electron. There is a demo and instructions here; please let me know if that helps. https://github.com/nolanlawson/pouchdb-electron

**Comment by rdpascua** [comment] 2016-07-16 00:24
I already rebuilded the `leveldown` using `node-gyp`, I've tried everything but it doesn't work. I tried reading every information related to this issue nothing helps.

**Comment by nolanlawson** [comment] 2016-07-18 16:13
Can you provide a test case to reproduce? Maybe something changed between https://github.com/nolanlawson/pouchdb-electron's version of leveldown and the version you're using. Another possibility is that you just need to `rm -fr node_modules` and try to install again; I know it sucks, but sometimes that works.

**Comment by rdpascua** [comment] 2016-07-18 22:52
I've tried removing `node_modules` and `.npm` for debugging sake. I'll update for the test case

**Comment by singhshashi** [comment] 2016-07-19 09:00
When using webpack, require statements turn into __webpack_require__ and this leads to some issues in resolving some modules. What you need to do is to tell webpack to require('pouchdb') and not __webpack_require__. This can be done by adding the following config to your webpack config file:

```
  externals: {
    'pouchdb':"require('pouchdb')",
  },
```
The issue I was facing was similar where at runtime the error thrown was that leveldown.node could not be found even though it was there.  By adding this, I was able to resolve the issue.

**Comment by rdpascua** [comment] 2016-07-19 09:11
I will try to do this later, will let you know if i have some issue.

**Comment by singhshashi** [comment] 2016-07-19 09:16
Also, webpack has two different targets: 'electron' and 'electron-renderer'. You could use those instead of target 'node'. The require('pouchdb') was used with 'electron-renderer'.

**Comment by rdpascua** [comment] 2016-07-19 09:18
I believe my target platform is `node`

```json
var path = require('path')
var webpack = require('webpack')
var config = require('../config')
var cssLoaders = require('./css-loaders')
var projectRoot = path.resolve(__dirname, '../')

module.exports = {
  // Note: entry points are added by environment-specific configs.

  output: {
    path: config.build.outputRoot,
    filename: '[name].js'
  },
  // Use target 'node' so that __dirname works properly. We then need
  // to manually specify the electron modules in the ExternalsPlugin
  // since we're not using target 'electron'.
  target: 'node',
  node: {
    __filename: false,
    __dirname: false
  },
  resolve: {
    extensions: ['', '.js', '.vue', '.json', '.node'],
    fallback: [path.join(__dirname, '../node_modules')],
    alias: {
      app: path.resolve(__dirname, '../app')
    }
  },
  resolveLoader: {
    fallback: [path.join(__dirname, '../node_modules')]
  },
  module: {
    preLoaders: [
      {
        test: /\.vue$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /vue-devtools|node_modules/
      }
    ],
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /vue-devtools|node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.html$/,
        loader: 'vue-html'
      },
      {
        test: /\.(png|jpe?g|gif|svg|woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url'
      }
    ]
  },
  plugins: [
    new webpack.ExternalsPlugin('commonjs2', [
      'desktop-capturer',
      'electron',
      'ipc',
      'ipc-renderer',
      'native-image',
      'remote',
      'web-frame',
      'clipboard',
      'crash-reporter',
      'screen',
      'shell'
    ]),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    })
  ],
  vue: {
    loaders: cssLoaders()
  },
  eslint: {
    formatter: require('eslint-friendly-formatter')
  }
```

**Comment by daleharvey** [comment] 2016-07-25 11:58
Is https://github.com/pouchdb/pouchdb/issues/5496 any help here?

**Comment by ammar-hasan** [comment] 2016-10-10 07:02
As mentioned by @singhshashi , I was also facing the same problem, when I debugged the application, there were two things
1. As mentioned by @nolanlawson, I had to build the pouchdb using [hello-electron-with-pouchdb](https://github.com/nolanlawson/hello-electron-with-pouchdb) , it solved problem partially, but I had the same issue again.
2. As mentioned by @singhshashi I had to put the following in externals, this resolved the issue because leveldown was using node-bindings, which uses stacktrace to determine filenames, and in webpack this was not working properly, because everything is bundled, so I had to exclude the modules
```
externals: {
    // put your node 3rd party libraries which can't be built with webpack here
    // (mysql, mongodb, and so on..)
    'pouchdb':"pouchdb",
    'leveldown':"leveldown"
  }
```

**Comment by nolanlawson** [comment] 2016-10-23 02:56
If somebody could please modify the hello-electron-with-pouchdb example, that would be great. I have no experience with Electron and so any help is appreciated.

In the meantime I figure we should close this, since it sounds more like an Electron/Webpack issue than a PouchDB issue and there are workarounds.

**Closed by nolanlawson** 2016-10-23 02:56 UTC

**Comment by juliobetta** [comment] 2016-11-07 03:11
I'm using [Electron+React Boilerplate](https://github.com/chentsulin/electron-react-boilerplate) and, thanks to @ammar-hasan, my app is working! However, I spent 3 hours of my life trying to figure out why pouchdb+leveldown was working in development and not in production. It turns out that I forgot to add `pouchdb` as a dependency in `app/package.json`. doh! :confounded: :confounded: :confounded:
