### ISSUE TITLE
sync with live: true triggers "change" events twice

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#4293] opened 2015-09-09 05:38 UTC
```js
var PouchDB = require('pouchdb').defaults({
  // memdown makes no difference, just added for sake of simplicity
  db: require('memdown')
})

var db1 = new PouchDB('db1')
var db2 = new PouchDB('db2')

db1.put({_id: 'a'})

.then(function () {
  return db2.put({_id: 'b'})
})

.then(function () {
  db1.sync(db2, {live: true}).on('change', function (change) {
    console.log(change.direction, change.change.docs)
  })
})
```

Output looks like this

```js
$ node debug.js 
push [ { _id: 'a', _rev: '1-4c355ea809e3720366f3ce63e030039f' } ]
pull [ { _id: 'b', _rev: '1-30da76a9658982ad291add2de458cb7c' } ]
push [ { _id: 'a', _rev: '1-4c355ea809e3720366f3ce63e030039f' } ]
pull [ { _id: 'b', _rev: '1-30da76a9658982ad291add2de458cb7c' } ]
```

WIthout the `live: true` option, it correctly triggers the "change" events only once per document. Is this by design? Or some kind of race condition maybe?

**Comment by daleharvey** [comment] 2015-09-09 09:22
Certainly not by design, just a straight up bug I think

**Comment by Charlotteis** [comment] 2015-09-09 10:15
I poked around a bit: I'm unfamiliar with how everything fits together but I can say with confidence that your journey to fix this may start with this line: https://github.com/pouchdb/pouchdb/blob/master/lib/sync.js#L80

```
  if (opts.live) {
    this.push.on('complete', self.pull.cancel.bind(self.pull));
    this.pull.on('complete', self.push.cancel.bind(self.push));
  }
```

Not a great lot of help, but a start :)

**Comment by nolanlawson** [comment] 2015-09-09 12:27
Mmm yeah if this only occurs with `sync()` but not with `replicate()`, then it's definitely a bug in `sync.js`.

**Comment by daleharvey** [comment] 2015-09-17 11:57
Added a test here, its a bug in `replicate` - https://github.com/pouchdb/pouchdb/pull/4348

**Comment by daleharvey** [comment] 2015-09-17 12:59
Fairly trivial fix - https://github.com/pouchdb/pouchdb/commit/764ba8a1f3b9be807e96c87d8c06bffd30e97c31, however looks like the retry tests are broken somehow (they depend on extra events being fired) and now failing

**Comment by daleharvey** [comment] 2015-09-17 13:25
So the retry test depends on this behaviour, the retry test does rep.on('change', postNewDoc) to post docs in a loop, currently we only fire the change event once the checkpoint has successfully written, if that fails, the batch fails, replication gets retried but the next document is already written so it will fire the empty change event

**Comment by daleharvey** [comment] 2015-09-17 13:27
We can change the behaviour for replication to fire change events before the checkpointer, however that is going to have a knock on effect (the tests fail when I do that)

**Comment by daleharvey** [comment] 2015-09-22 18:40
Fixed in https://github.com/pouchdb/pouchdb/commit/fe4cc24dbe6a93ddc072c7dd3bacaec70120f74d

**Closed by daleharvey** 2015-09-22 18:40 UTC
Labels: bug
