### ISSUE TITLE
Large map function is larger and slower than expected

### ISSUE THREAD

**Issue by akircher** [pouchdb/pouchdb#4618] opened 2015-11-29 20:43 UTC
I have a database of medications that contains ~40,000 documents with this structure

```
{
   "_id": "0002-3229",
   "_rev": "1-ee59686ce7848511d69a3b0e82b1590e",
   "names": [
       "Atomoxetine Hydrochloride 40 Mg"
   ],
   "brand": "Strattera",
   "form": "Oral Capsule",
   "ndc9": "000023229",
   "upc": "00023229",
   "image": "http://pillbox.nlm.nih.gov/assets/large/00002-3229-30_3E1E1F50.jpg",
   "labeler": "Eli Lilly And Company"
}
```

I want to implement a partial word search that works with an autocomplete search box.  My first thought was to use `pouchdb-quick-search` however that does not support partial words and the stemming feature was useless for drug names so it didn't seem to be the right fit.  My second thought was to use `$regex` in `pouchdb-find` but that actually does a full db scan on every query, which was really slow.  

My last option was to implement a `view` to query.  The map function that I wrote for this view is below. The view results in a `pouchdb-mrview` database of ~1,500,000 docs.  As you can see this is reduced somewhat because I require at least 4 letters for partial words.

```
function drugSearch(doc) {
  var names = doc.names.concat([doc.ndc9, doc.upc])
  var str   = doc.ndc9+" "+doc.names.join(", ")+" "+doc.form
  for (var i in names) {
    var name = names[i]
    for (var j=4; j<=name.length; j++) {
      var key = name.slice(0, j)
      emit(key.toLowerCase(), str.split(key))
    }
  }
}
```

This function takes 10-15 minutes on the first query to compile the view.  I am OKAY with this as it is a one time deal.  Once the view compiles the queries run in 50-200ms range which is quite good.  However I have two problems.

(1) The first query after each browser refresh/reload is really slow, 15-25 seconds.  After that first query the view speeds back up again.  This is a very noticeable and recurring delay/aggravation to my users.

(2) Less of a problem, but the database is >1 GB in size according to Chrome's All Cookies and Site Data page.  The size of the DB before the view is ~200MB and with the view it grows to ~1.2GB.  This size seems excessive - even though there are ~1.5M docs - each doc is only something very small like 
```
_doc_id_rev: "5400007337140007-3371::1-cbf31ecd3bb225d52bbc8f18e4ab1e26",
key: "000073371",
value: ["",  " Carvedilol Phosphate 20 Mg Oral Capsule"]
```

Thanks for your help!

Adam

**Comment by nolanlawson** [comment] 2015-12-01 01:19
As a first response, I can tell you that PouchDB secondary indexes are not highly optimized for large amounts of data or large indexes. You may want to try Dexie or YDN-DB instead, especially if you are not using PouchDB's sync capabilities for those 40,000 documents. (PouchDB is optimized for sync, not for indexing... design tradeoffs, yada yada :smiley: ).

As a second response, I'd say this is very surprising:

> The first query after each browser refresh/reload is really slow, 15-25 seconds

Can you profile with an unminified `pouchdb.js` to see what is taking so long? In theory the first query after a reload should be the same as a second, assuming the index is already built.

>  The size of the DB before the view is ~200MB and with the view it grows to ~1.2GB.

If you remove the second arg from your `emit()`, it should store about half as much data, since your `emit()` key and value are the same size (roughly).

**Comment by akircher** [comment] 2015-12-01 05:34
Thanks for the quick thoughtful reply.  I would rather put up with a slow first query than add complexity of a second DB or wrapper just for this one search.  Plus I am hoping adapter specific native secondary indexes will help me eventually!

So I did a profile, but Github won't let me attach that file type.  Here is the best that I can to summarize: it seems that PouchDB is simply taking a very long time to fully load because its counting the index.  The profiler just sits idle from second 2 - second 19.

```
pouchdb-5.1.0.js:9427 2190ms
pouchdb-5.1.0.js:9394 2195ms
pouchdb-5.1.0.js:8470 2235ms
pouchdb-5.1.0.js:8281 2235ms
pouchdb-5.1.0.js:8282 2235ms
pouchdb-5.1.0.js:8222 2235ms
pouchdb-5.1.0.js:8491 2240ms
pouchdb-5.1.0.js:11035 2240ms
pouchdb-5.1.0.js:8222 2240ms
pouchdb-5.1.0.js:8239 2240ms
pouchdb-5.1.0.js:11035 2240ms
pouchdb-5.1.0.js:5979 2240ms
pouchdb-5.1.0.js:832 2240ms
pouchdb-5.1.0.js:5813 2240ms (PouchDB constructor)
pouchdb-5.1.0.js:5841 2240ms
**** 17 second wait ****
pouchdb-5.1.0.js:3462 19120ms (index.count.onsuccess)
pouchdb-5.1.0.js:3407 19120ms (checkSetupComplete)
pouchdb-5.1.0.js:3535 19120ms
pouchdb-5.1.0.js:3514 19120ms (tryCode)
pouchdb-5.1.0.js:5914 19120ms
```
So maybe it’s this code?
```
var index = txn.objectStore(DOC_STORE).index('deletedOrLocal');
index.count(IDBKeyRange.only('0')).onsuccess = function (e) {
        docCount = e.target.result;
        checkSetupComplete();
};
```

**Comment by nolanlawson** [comment] 2015-12-13 19:45
Ah yeah, that count is an optimization that we do in order to be able to quickly deliver `total_rows` when you do an `allDocs()`. However, it could potentially take a long time to calculate, depending on the browser implementation of IndexedDB. Arguably we should be caching that count inside of the database itself, since (in the case of SQLite at least) `COUNT(*)` is not cached. I believe it's not the case in LevelDB/IndexedDB either.

**Comment by nolanlawson** [comment] 2015-12-13 19:46
Out of curiosity, do you see any differences between browsers? Chrome, Firefox, and IE have three different implementations of IndexedDB, so if one is noticeably slower than the other two, we could file an issue on those browsers.

**Comment by akircher** [comment] 2015-12-16 06:41
I can't easily test IE, but Firefox completed the initial search within ~3 seconds.  Looks like a Chrome performance issue.  If we can solve this either through caching the value in the database or the browsers IndexedDB implementations, my users would appreciate it!

**Comment by nolanlawson** [comment] 2015-12-19 18:10
Can you write a small reproducible test case? I understand how happy your users would be, but this is an open-source project, so bugs tend to get fixed more quickly when either 1) users fix it themselves, or 2) they provide small reproducible test cases that make it easy for project maintainers to quickly identify and correct the issue.

BTW, just to confirm - the slowness is *only* in Chrome, and not in IE/Safari/Firefox?

**Comment by ermouth** [comment] 2015-12-24 12:46
@akircher There are two more reasonable approaches for your particular task.

1) Keep entire dataset in RAM, then search is obvious
2) Use two step search. Make index by two first letters only, query it to get raw result and filter it precisely at client side, not DB side.

**Comment by tohagan** [comment] 2015-12-25 13:21
Nolan's full text search engine might also be useful:
- https://github.com/nolanlawson/pouchdb-quick-search

**Comment by daleharvey** [comment] 2016-01-03 15:30
Yup, ultimate solution will be native indexes which we have a bug open for, in the meantime this is somewhat expected and discussed so closing the issue out, cheers

**Closed by daleharvey** 2016-01-03 15:30 UTC
Labels: bug, help wanted
