### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by travbus** [pouchdb/pouchdb#8449] opened 2022-02-15 06:13 UTC
### Issue
I get gobal is not defined error when trying to make a database.    "pouchdb": "^7.2.2", "@types/pouchdb": "^6.4.0", vue with type script.      "allowSyntheticDefaultImports": true. .I followed the website guide. I hope this isn't a huge issue. I'm using chrome and firefox. Maybe its a vite issue.

<img width="807" alt="Screen Shot 2022-02-14 at 11 03 12 PM" src="https://user-images.githubusercontent.com/18337819/154002683-32ae2458-e689-4944-8b18-597e9bf28808.png">
<img width="518" alt="Screen Shot 2022-02-14 at 11 02 26 PM" src="https://user-images.githubusercontent.com/18337819/154002686-fc2094ac-79ef-441b-8fd4-b9f6eef38a37.png">

{
  "name": "vit-quasar",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"

  },
  "dependencies": {
    "@quasar/extras": "^1.12.5",
    "@unocss/reset": "^0.20.4",
    "axios": "^0.24.0",
    "pinia": "^2.0.11",
    "pouchdb": "^7.2.2",
    "quasar": "^2.5.5",
    "velocity-animate": "^1.5.2",
    "vue": "^3.2.31",
    "vue-i18n": "^9.1.9",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@intlify/vite-plugin-vue-i18n": "^3.3.0",
    "@quasar/vite-plugin": "^1.0.4",
    "@types/node": "^17.0.18",
    "@types/pouchdb": "^6.4.0",
    "@vitejs/plugin-vue": "^2.2.0",
    "sass": "1.32.0",
    "typescript": "^4.5.5",
    "unocss": "^0.23.0",
    "vite": "^2.8.2",
    "vite-plugin-pages": "^0.20.2",
    "vite-plugin-vue-layouts": "^0.6.0",
    "vue-tsc": "^0.31.4"
  }
}

### Info
- Environment: (Node.js/browser/hybrid app/etc.). 
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (idb/indexeddb/memory/leveldb/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by pubkey** [comment] 2022-02-21 00:40
Duplicate of https://github.com/pouchdb/pouchdb/issues/7263#issuecomment-453495115

**Closed** 2022-04-19 14:43 UTC
