### ISSUE TITLE
Pouch halts replication with SQLite

### ISSUE THREAD

**Issue by jfspencer** [pouchdb/pouchdb#3548] opened 2015-02-18 23:54 UTC
I am running into an issue using using the SQLite plugin where replication will stop mid sequence without any error. If I use the standard webSQL adapter replication functions normally. I played around with the batch size/limit thinking it was a memory issue. Which didn't resolve the issue, but gave different amounts of replicated data. If using batch_size: 1 , batch_limit: 1, it would get through about 66 requests before it would halting. resulting in 66 docs in the data base. on the high end batch_size:200, batch_limit 10 , it would complete about 14 sequences and grab 800 docs. The total docs to be replicated is 1847.

Any thoughts on causes or how to gather more information?

using pouch 3.3.1
SQLite plugin 1.0.3

**Comment by nolanlawson** [comment] 2015-02-19 00:38
This is probably a bug in the SQLite plugin. Also it would be helpful to know whether you were on iOS or Android. :)

**Comment by jfspencer** [comment] 2015-02-19 00:39
Issue is experienced on iOS. Have not tried android yet.

On Wednesday, February 18, 2015, Nolan Lawson <notifications@github.com>
wrote:

> This is probably a bug in the SQLite plugin. Also it would be helpful to
> know whether you were on iOS or Android. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/3548#issuecomment-74979429>.
>


-- 

Cheers,


James

**Comment by nolanlawson** [comment] 2015-02-19 00:41
Is there any error output? Or is it just a memory leak?

**Comment by survah** [comment] 2015-02-19 07:34
Environment  
=====================
PouchDB - 3.3.1
Cordova - 4.1.2

I am experiencing the same issue; 'The replication stops' . There is no error displayed. My test environment includes the following setup

IOS (Testing on Simulator)
=====================
- Replication stops happening. No error message is displayed

Android (Testing on Google Nexus 7, Android 5.0.1)
=====================
- No issue with replication
- But way slower than WEBSQL

**Comment by nolanlawson** [comment] 2015-02-19 12:24
Can either of you provide a small sample app to reproduce? Then we can file this issue on the SQLite Plugin and see what they think.

AS for Android being way slower than WebSQL; that's a known issue. The SQLite plugin is serializing the JSON requests into strings and then passing that between the Java and JavaScript, which is why is slower.

**Comment by jfspencer** [comment] 2015-02-19 22:52
I'll put one together.

**Comment by jfspencer** [comment] 2015-02-20 06:01
@nolanlawson 
Here is a link to a fully configured app that reproduces the halting replication. 
https://drive.google.com/file/d/0B0-I41uSyatNM0xPQ192OXhHeDA/view

It is an ionic app so npm/ionic dependencies are a given. in an ionic environment you just need to run
    
    ionic build ios
    ionic emulate/run ios
There is a replication address input field and start replication button that fires everything up for you.

All of the pouch events are wired up to re-broadcast in angular. the dashboard controller has hooks setup to handle each event. 

pouch debugging is turned on.

Thanks for your help!

**Comment by nolanlawson** [comment] 2015-02-20 12:55
Yes, please file an issue on the SQLite Plugin, link back to this issue, and if you can provide a fix, that works be amazing! :)

**Comment by mnewmedia** [comment] 2016-03-09 10:54
@jfspencer, @survah still having issues?

**Comment by nolanlawson** [comment] 2016-03-09 18:43
Closing because this is an issue with the SQLite Plugin. For the time being, we do recommend the SQLite Plugin if you can avoid it.

**Closed by nolanlawson** 2016-03-09 18:43 UTC
Labels: enhancement
