### ISSUE TITLE
sync and change listeners fire strange behavior

### ISSUE THREAD

**Issue by Miaaw** [pouchdb/pouchdb#5320] opened 2016-06-09 14:34 UTC
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

I have a pouchdb as local database and couchdb as a remote one, when I try to sync pouchdb content to couchdb I notice that my code is executed twice, and paused and active are emitted too many times.. and a warning message appears 
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

I have spent a lot of time to figure out what's happening without any solution! 
here is my code

         dbLocal.sync(dbRemote, {
           live: true,
            retry: true,
            include_docs:true
         }).on('change', function (change) {
               console.log("sync ");

         }).on('paused', function (info) {
    // replication was paused, usually because of a lost connection
        console.log("Paused "+ info);
         }).on('active', function (info) {
      console.log("Active"+ info);
    // replication was resumed
        }).on('error', function (err) {
         console.log(err);
        });
           dbRemote.changes({
           since: 'now',
           live: true,
           include_docs: true
         }).on('change', function(change) {

             if(change.doc.name=== "myDoc") {
               var link = 'path/to/my/file.php';
               $http.delete(link, {
                                 idf : change.doc.idf
                                 })
               .success(function (res){
                 console.log("deleted----");
                   console.log(res);
               }).error(function (err) {
                 console.log(err);
               });
             }

           }

         }).on('complete', function(info) {
           // changes() was canceled
         }).on('error', function (err) {
           console.log(err);
         });

Please could tell me how can I solve this problem?

**Comment by daleharvey** [comment] 2016-06-10 09:55
@Miaaw Hi, thanks for the report, so in normal usage you should never get the max EventListener problem, that sounds like you are starting multiple `changes` or `sync`'s? You mentioned quite a few problems and none are represented in the code sample, can you maybe start with one error, probably the first one that indicates something is wrong and explain that in full and we can see what is going on? Thanks

**Comment by Miaaw** [comment] 2016-06-10 13:33
Hey @daleharvey , thanx for your reply, well I am trying to do a sync between a puchdb and a couchdb, and I am trying to listen if there are any changes in the chouchdb, if yes, and everything goes well, I send a rest api request.. the code is correct, but the problem is that my code is being executed twice, without any reason! I think that this problem has triggered other problems (max EventListener). 

 I have solved the problem of the max EventListener by raising the number of allowed listeners, but I am afraid of having a real memory leak problem as I am working on  a mobile app..

**Comment by daleharvey** [comment] 2016-06-10 17:37
So I took your code into a runnable demo @ http://paste.pouchdb.com/paste/h3pms8/, this has the same listeners, it does a remote.put 2 seconds into the page loading, for the output I get 

> changes change Object { id: "test", changes: Array[1], doc: Object, seq: 1 }
> sync active Object { direction: "pull" }h3pms8:15:7
> sync change Object { direction: "pull", change: Object }h3pms8:12:7
> sync paused undefined

Which is pretty much what I would expect, and there is no maxlistener problem, can you edit that demo in a way to show the error you are seeing?

**Comment by Miaaw** [comment] 2016-06-11 16:25
Well I think the problem comes from the _sync_, cause the  "Paused" and "Active" messages are appearing two timees each one.

**Comment by daleharvey** [comment] 2016-06-11 16:48
Its hard to rely on the exact number of times `paused` and `active` events fire, in the example they are firing once, I would have expected an extra initial `paused` event, but may be a race in starting to listen for it after it being fired, either way I dont have enough information to know if its a bug you are seeing or expected behaviour / user error, if you could expand on what the actual error is I will look into it, cheers

**Comment by daleharvey** [comment] 2016-06-18 19:25
When it isnt clear what the bug is / if this is actionable I will close out the bug after 2 weeks without of no activity, just pinging in case you want to follow up to clarify the bug

**Comment by daleharvey** [comment] 2016-06-25 15:53
Closing out, if you still have problems / can clarify STR then please reopen, cheers

**Closed by daleharvey** 2016-06-25 15:53 UTC
Labels: bug

**Comment by mbeaudru** [comment] 2016-10-22 22:41
I am encountering the same issue, when I sync my local and remote databases and listen for 'pause', it immediatly fires twice even if the user is online and everything is fine.

Besides, 'pause' seems to have a very strange behaviour and fires in weird situations, such as moving from offline to online 😶 and if I understand this right it is supposed to only fire 'active'.

When I have the time I can try to produce a sample that reproduces this behaviour if necessary. Here is the code that produces this behaviour on my project.

```javascript
    this.sync = this.state.modelDb
      .sync(this.state.modelRemoteDb, { retry: true, live: true })
      .on('change', () => {
        this.getAllLocalModels()
          .then(localModels => {
            const storeAndDbDiffer = !_.isEqual(this.props.models, localModels);
            if (storeAndDbDiffer) {
              this.props.updateModels(localModels);
            }
          });
      })
      .on('paused', (err) => {
        this.notify.addNotification({
          message: 'Impossible to establish sync - your are in offline mode',
          level: 'warning',
          autoDismiss: 10
        });
        console.log(err);
      });
```

I join to this updateModels redux action because it's the only side effect of the above code.

```javascript
export function updateModels() {
  return dispatch => {
    const modelDb = new PouchDB('model-db');

    modelDb.allDocs({ include_docs: true })
      .then(({ rows = [] }) => {
        const order = [];
        const models = rows
          .map(({ doc }) => {
            order.push(doc._id);
            return doc;
          })
          .reduce((prev, next) =>
            Object.assign({}, prev, {
              [`${next._id}`]: next
            })
          , {});

        dispatch({
          type: types.UPDATE_MODELS,
          models,
          order
        });
      });
  };
}
```
