### ISSUE TITLE
Some docs not replicated from remote CouchDB

### ISSUE THREAD

**Issue by noradaiko** [pouchdb/pouchdb#4766] opened 2016-01-09 15:22 UTC
I'm facing a problem in replicating from CouchDB.
All docs can be properly replicated to remote db.
But once removing local db and trying to sync from remote db, some docs are not replicated.
For example, you have 100 docs on the remote db, but synced only 57 docs.
The number of docs synced is randomly changed.
The issue only occurs if the revision of docs is 2 (or larger, I guess).

Here is code to reproduce:
https://gist.github.com/noradaiko/ea55c8a1c835130e8974

And log:
https://gist.github.com/noradaiko/a33fdd14d50a121049cd

PouchDB: 5.1.0
CouchDB: 1.6.1
Node: v5.1.0

Any advice will be appreciated.

**Comment by daleharvey** [comment] 2016-01-09 16:30
Thanks these steps to reproduce are amazing, I am however not able to reproduce, with 1.6.1 and node 5.1.0 I am getting 100 notes consistently every time. Will carry on trying but if you can think of anything else that may be affecting this.

**Comment by daleharvey** [comment] 2016-01-09 17:34
So I was actually testing with node 5.0, with 5.1.0 I cant actually npm install pouchdb, getting `Error: Cannot find module 'inherits'`

@noradaiko What OS are you on and can you test different versions of node?

**Comment by noradaiko** [comment] 2016-01-10 03:44
Thanks for taking your time, that gave me a hint.
It seems that [Dockerized CouchDB](https://github.com/klaemo/docker-couchdb) which I use was causing this issue.
It randomly causes `ECONNRESET` as pouchdb log reports:

```
Sat, 09 Jan 2016 15:16:03 GMT pouchdb:http GET http://localhost:50011/note/note%2F97?revs=true&open_revs=%5B%222-37b1ef978bd6a7dd24a2b3ec17d7f1ba%22%5D
Sat, 09 Jan 2016 15:16:03 GMT pouchdb:http GET http://localhost:50011/note/note%2F98?revs=true&open_revs=%5B%222-8ba1c2d718af612e4da0d94092906a11%22%5D
Sat, 09 Jan 2016 15:16:03 GMT pouchdb:http GET http://localhost:50011/note/note%2F99?revs=true&open_revs=%5B%222-c9ad800c4f7c115cd4019964b88063e0%22%5D
Sat, 09 Jan 2016 15:16:03 GMT pouchdb:api http://localhost:50011/note get error { [Error: connect ECONNRESET 127.0.0.1:50011] status: 400 }
Sat, 09 Jan 2016 15:16:03 GMT pouchdb:api http://localhost:50011/note get error { [Error: connect ECONNRESET 127.0.0.1:50011] status: 400 }
Sat, 09 Jan 2016 15:16:03 GMT pouchdb:api http://localhost:50011/note get error { [Error: connect ECONNRESET 127.0.0.1:50011] status: 400 }
```

All docs are successfully synced with CouchDB installed on ubuntu on other machine.

I'm using node.js on Mac OSX 10.10.5 and Ubuntu 14.04.
I tried also with node 5.4.0, 5.0.0 and 4.1.1 and I didn't see any error like `Error: Cannot find module 'inherits'`. Maybe npm issue?

Anyway, love your great work, thanks!

**Comment by daleharvey** [comment] 2016-01-10 10:23
@noradaiko yeh the `install` was definitely an npm issue, possibly my fault switching between versions. 

We actually use the same Docker CouchDB for our test suite, so I dont think the error is specifically that instance, it may be some problem with the docker network or similiar. But glad you have started getting to the issues and that its not an issue in pouchdb itself, closing this out but if you do find anything pouchdb specific please file again, thanks

**Closed by daleharvey** 2016-01-10 10:23 UTC
Labels: bug
