### ISSUE TITLE
Build issues on 6.3.0 solved when locked to 6.2.0

### ISSUE THREAD

**Issue by hshafy** [pouchdb/pouchdb#6601] opened 2017-07-13 14:28 UTC
### Build issues on 6.3.0 solved when locked to 6.2.0

We got this issue right after the release of 6.3.0 with normal CI build, 6.2.0 was working fine for us, so we locked the version for now, till we investigate further.

```
RROR in ./node_modules/pouchdb/lib/index-browser.js
Module not found: Error: Can't resolve 'lie' in '..../node_modules/pouchdb/lib'
 @ ./node_modules/pouchdb/lib/index-browser.js 5:26-40
 @ ./app/redux/db.js
 @ ./app/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server whatwg-fetch babel-polyfill ./main.js

ERROR in ./node_modules/pouchdb/lib/index-browser.js
Module not found: Error: Can't resolve 'argsarray' in '...../node_modules/pouchdb/lib'
 @ ./node_modules/pouchdb/lib/index-browser.js 6:35-55
 @ ./app/redux/db.js
 @ ./app/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server whatwg-fetch babel-polyfill ./main.js

ERROR in ./node_modules/pouchdb/lib/index-browser.js
Module not found: Error: Can't resolve 'immediate' in '....../node_modules/pouchdb/lib'
 @ ./node_modules/pouchdb/lib/index-browser.js 9:31-51
 @ ./app/redux/db.js
 @ ./app/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server whatwg-fetch babel-polyfill ./main.js

ERROR in ./node_modules/pouchdb/lib/index-browser.js
Module not found: Error: Can't resolve 'spark-md5' in '....../node_modules/pouchdb/lib'
 @ ./node_modules/pouchdb/lib/index-browser.js 12:26-46
 @ ./app/redux/db.js
 @ ./app/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server whatwg-fetch babel-polyfill ./main.js

ERROR in ./node_modules/pouchdb/lib/index-browser.js
Module not found: Error: Can't resolve 'vuvuzela' in '....../node_modules/pouchdb/lib'
 @ ./node_modules/pouchdb/lib/index-browser.js 13:31-50
 @ ./app/redux/db.js
 @ ./app/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server whatwg-fetch babel-polyfill ./main.js

ERROR in ./node_modules/pouchdb/lib/index-browser.js
Module not found: Error: Can't resolve 'uuid/v4' in '....../node_modules/pouchdb/lib'
 @ ./node_modules/pouchdb/lib/index-browser.js 10:25-43
 @ ./app/redux/db.js
 @ ./app/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server whatwg-fetch babel-polyfill ./main.js
 ```

**Comment by daleharvey** [comment] 2017-07-13 16:48
Dupe of https://github.com/pouchdb/pouchdb/issues/6600, thanks

**Closed by daleharvey** 2017-07-13 16:48 UTC
