### ISSUE TITLE
Load more

### ISSUE THREAD

**Issue by injectless** [pouchdb/pouchdb#5318] opened 2016-06-09 11:30 UTC
### **Environment**
Node.js/Hybrid App -> Phonegap & Electron

### **Browser/platform**
Linux for now

### **Adapter**
IndexedDB

### **Plugins**
angular-pouchdb
pouchdb.find
pouchdb.upsert

Hi folks,
I would like to know how can I do something like LIMIT (sql), and load more results when the users clicks a button or scrolls down (this last two I can do it myself), and just append to the div

I know you understand me, if not, something like this..
Result 1
Result 2
Result 3
Load more ...
^ and then..
Result 3
Result 4
Result 6

**Comment by daleharvey** [comment] 2016-06-09 12:16
Nolan wrote a blog post about this @ https://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html, personally

**Comment by daleharvey** [comment] 2016-06-09 12:34
And closing since its not a bug, however if you have any more questions please feel free

**Closed by daleharvey** 2016-06-09 12:34 UTC
