### ISSUE TITLE
Non-uniform attachment loading behaviour

### ISSUE THREAD

**Issue by weiserr** [pouchdb/pouchdb#6166] opened 2017-01-22 17:48 UTC
### Issue
Working with attachments (png images in my case) in the *Electron* renderer process feels rather strange:

* I can save the data in form of a base64 encoded string.
* If loading the image as shown in the [documentation](https://pouchdb.com/guides/attachments.html#image-attachments) the data type returned is an `Uint8Array`.
* If executing the same code as in the [documentation](https://pouchdb.com/guides/attachments.html#image-attachments) with a larget image (>100kb) the returned data type is a `Blob`.
* If loading the object using `db.get(id, { attachments: true, binary: false })` it does not have an effect at all... - I still get either an `Uint8Array` or a `Blob`.

It would be nice if returned attachments would always have the same type. It would be even nicer if the attachments could be returned as base64-encoded strings (enabling simple data *URL* creation) as the *Electron* renderer process is rendering a web browser page.

What do you think?

Cheers, Robert

### Info
- Environment: Electron Renderer Process (Node.js + browser env present)
- Platform: Chromium
- Adapter: IndexedDB
- Server: None

### Reproduce
See the [documentation](https://pouchdb.com/guides/attachments.html#image-attachments) example and run the code in the *Electron* render process.

**Comment by nolanlawson** [comment] 2017-01-23 17:37
Does this only occur in Electron? My hunch is that there is a bug here where certain parts of PouchDB are getting loaded in "browser style" whereas others are getting loaded in "Node style."

One way to check would be to see if the [buffer polyfill](https://github.com/feross/buffer) is in your codebase anywhere. If it is, then there's a misconfiguration in the build that is causing it to be included. Normally this module should never appear in PouchDB unless you're using the in-memory, localstorage, or fruitdown adapters.

I believe under the hood the buffer polyfill uses Uint8Arrays which may explain where they're coming from.

**Comment by nolanlawson** [comment] 2017-01-23 17:38
For the record if you want to be 100% certain then you can use the [pouchdb-browser](https://www.npmjs.com/package/pouchdb-browser) package instead of the regular pouchdb package which explicitly includes the "browser-only" version of the codebase.

**Comment by weiserr** [comment] 2017-01-23 22:09
I haven't tried the code in a browser-only environment - however this should be simple to reconstruct if adapting your [gist](https://gist.github.com/nolanlawson/2a5f98a66c9fe3ae3532).

I've already been using the [pouchdb-browser](https://www.npmjs.com/package/pouchdb-browser) package dependency.

Running a `npm ls --only=production` yields:

	+-- @angular/common@2.1.2                        
	+-- @angular/compiler@2.1.2                      
	+-- @angular/core@2.1.2                          
	+-- @angular/forms@2.1.2                         
	+-- @angular/http@2.1.2                          
	+-- @angular/platform-browser@2.1.2              
	+-- @angular/platform-browser-dynamic@2.1.2      
	+-- @angular/router@3.1.2                        
	+-- blob-util@1.2.1                              
	| +-- blob@0.0.4                                 
	| `-- native-or-lie@1.0.0                        
	+-- core-js@2.4.1                                
	+-- json-loader@0.5.4                            
	+-- pouchdb-browser@6.1.1                        
	| +-- argsarray@0.0.1                            
	| +-- debug@2.6.0                                
	| | `-- ms@0.7.2                                 
	| +-- immediate@3.0.6                            
	| +-- inherits@2.0.3                             
	| +-- lie@3.1.0                                  
	| +-- scope-eval@0.0.3                           
	| +-- spark-md5@3.0.0                            
	| `-- vuvuzela@1.0.3                             
	+-- rxjs@5.0.0-beta.12                           
	| `-- symbol-observable@1.0.4                    
	`-- zone.js@0.6.26                               

> If loading the object using `db.get(id, { attachments: true, binary: false })` it does not have an effect at all... - I still get either an `Uint8Array` or a `Blob`.

...I will need to extend this - besides the effect described above I also get a `Uncaught TypeError: Failed to execute 'readAsBinaryString' on 'FileReader': parameter 1 is not of type 'Blob'.` in the `api._getAttachment(...)`-> `readBlobData(...)`-> `readAsBinaryString(...)` -> `reader.readAsBinaryString(...)` call chain.

**Comment by nolanlawson** [comment] 2017-01-24 02:51
Yup it definitely sounds like `buffer` is getting included in your codebase. Note that `npm ls` might not necessarily list it, because Webpack is what adds it. I assume you're using Webpack?

**Comment by weiserr** [comment] 2017-01-24 18:22
Yeah you're right, I am using Webpack. I will try to figure out how to get hold of the dependencies bundled into the resulting file(s).

**Comment by weiserr** [comment] 2017-01-24 18:50
Dumping the dependency tree by providing the `--json` flag to *Webpack* yields no result if searching for `/buffer/` in the generated file. According to my understanding I should be able to find an entry with a module `name` referencing the `buffer/index.js` file.

**Comment by nolanlawson** [comment] 2017-01-25 17:13
Hmmmm... I would check in the actual JavaScript output file and see if `buffer` is in there. Alternatively can you provide a working repro of the problem? We have seen _many_ issues with Webpack+Electron in the past but honestly we're usually stumped to try to figure it out because it's often a configuration issue and none of the PouchDB core team members are Webpack experts. But a repro always helps! :)

**Comment by weiserr** [comment] 2017-01-25 17:33
Thanks for the input - I will investigate it later on and try to strip down my repo to the essentials in case I don't find any clues.

**Comment by weiserr** [comment] 2017-01-25 21:49
Searching for `buffer` in the generated files yields the same amount independet if building for the web or *Electron*.

However, the problem can be re-created by switching from the `target: 'web'` which is the *Webpack* default to `target: 'electron-renderer'`.

Would it help providing you with a *WebPack* config file and an *Electron* `main.js` file?

**Comment by weiserr** [comment] 2017-01-26 21:41
Building for the `target: web` with *WebPack* and using the `binary: false` option will yield different results depending on where the generated JavaScript is being run - it works with Base64-encoded data in the browser and fails in the *Electron* environment.

**Comment by nolanlawson** [comment] 2017-01-26 21:59
This sounds like an Electron issue rather than a Webpack issue, in that case. I understand Electron has a concept of "Node-like" vs "browser-like" and it seems like something is getting mixed up in this case.

Can you please provide a small sample app to reproduce this issue? None of us on the team are Webpack/Electron experts and so it's really difficult to tell what's happening just from the description. However if we had a sample app that would help a lot. Thanks!

**Comment by weiserr** [comment] 2017-01-30 22:36
So I finally came around trying to re-create the situation by building a vanilla Electron+Webpack environment having your demo code executed. I actually was not able to re-produce it...

Even adding Typescript and Angular2 to the mix did not change the behaviour - all works as supposed to. The main differences I had to my project were some different devDependency versions; most notably the demo project using a more "bleeding edge" Webpack (2.x) version. Sadly I was not able to pinpoint the problem to exactly one component - as you already pointed out it seems / seemed to be a build configuration issue.

For the sake of completness please find the demo-case in the [pouchdb-6166](https://github.com/weiserr/electron-quick-start/tree/pouchdb-6166) branch. I hope it helps you in the future with issues regarding Webpack+Electron. Please let me know if you have some more insights.

Cheers, Robert

**Comment by nolanlawson** [comment] 2017-02-02 02:23
In that case, sounds like this was fixed in Webpack 2. That's good to know; thanks for sharing!

**Closed by nolanlawson** 2017-02-02 02:23 UTC
Labels: bug, needs reproducing

**Comment by W1M0R** [comment] 2019-03-01 10:00
I am experiencing similar issues with `pouchdb-browser` in an Electron BrowserWindow. Here is a description of the problem linked to another issue: https://github.com/pouchdb/pouchdb/issues/7449#issuecomment-468607794
