### ISSUE TITLE
Strange error on console

### ISSUE THREAD

**Issue by ramstein74** [pouchdb/pouchdb#4803] opened 2016-01-18 11:47 UTC
Hello i created an app just to test relication local/remote as written in the docs.
It works. however i see in the console a strange error and i´m worried that it will bite me later in the development of my app.

Please see attached file and let me know if i need to change something.
![image](https://cloud.githubusercontent.com/assets/1210858/12390580/444609fc-bdd9-11e5-8d71-0059e52efaa4.png)

**Comment by nickcolley** [comment] 2016-01-18 15:32
Hey @ramstein74,

Can you let us know what browser, OS and PouchDB version you're using?
Also if you can provide a snippet of your code that reproduces this that'd be great, otherwise it won't be easy to fix this kind of error since it's so vague!

**Comment by nolanlawson** [comment] 2016-01-18 15:55
The "unknown error" is caused by PouchDB hiding the actual original error... it's a really annoying problem, but you'd have to do more intense debugging to figure out what's going on. I've seen it a couple times in a working app. Not sure what it is, but it's probably nothing.

**Comment by nickcolley** [comment] 2016-01-18 16:40
@nolanlawson anyway we can stop PouchDB from hiding errors?

**Comment by daleharvey** [comment] 2016-01-18 22:15
Every time I run into an Unknown Error I tried to fix it to ensure something proper is shown, but quite a lot of the time we just get no information

**Comment by kidwm** [comment] 2016-02-12 11:29
I also encountered this kind of error in my `express-pouchdb` app:
```js
var db = new PouchDB(window.location.origin + '/db/items');
⋯
⋯
componentDidMount() {
		this.update = db.changes({
			since: 'now',
			live: true
		})
		.on('change', this.getItems.bind(this))
		.on('error', function (err) {
			console.log(err);
		});
		this.getItems.call(this);
	}
```
And Firefox gave me this message for this long polling error:
```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

**Comment by nolanlawson** [comment] 2016-02-13 18:48
@kidwm Looks like a different issue. The issue here is that PouchDB is noisily logging "unknown error" errors.

**Comment by kidwm** [comment] 2016-02-15 02:23
@nolanlawson I think they were related since I got the same "unknown error" message in Chrome.

**Comment by mnewmedia** [comment] 2016-02-29 17:06
I'm also back with the `unknown error`:
```js
error: true
message: "Database encountered an unknown error"
name: "unknown_error"
result: Object
doc_write_failures: 0
docs_read: 14493
docs_written: 14493
end_time: Mon Feb 29 2016 16:05:44 GMT+0100 (CET)
errors: Array[1]
last_seq: 24070
ok: false
start_time: Mon Feb 29 2016 16:03:05 GMT+0100 (CET)
status: "aborting"
__proto__: Object
status: 500
__proto__: x
```
**only** with `live-sync` and exactly when the `paused event` should trigger. If i still wait this error comes 18 times and then:
`(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.`

failing request:
`url/_changes?timeout=25000&style=all_docs&feed=longpoll&heartbeat=10000&since=24070&limit=100`

**since version 5.0.0:**
Linux with SSL through HAProxy and basicAuth: `have this error`
Windows without SSL ans basicAuth: `works fine`
initialSync on.change: `only pull`

**before version: 5.0.0**
win & lin: `works fine`
initialSync on.change: `pushes and pulls` (although I don't know why pushes if it's initialSync)

**Comment by mnewmedia** [comment] 2016-03-02 16:20
okey i found out it's because of the nginx proxy. Because PouchDB uses long-polling you also have to setup:
```
proxy_buffering off;
proxy_ignore_client_abort off; // not shure
// maybe needs some more like proxy_read_timeout 3600;
```
Still needs tuning, cause without proxy long_polling goes 25 seconds, an know it goes forever i will test it tomorrow more in-depth.

**Comment by jeffleus** [comment] 2016-03-16 16:08
I am seeing almost the same behavior as you @mnewmedia, except the EventEmitter msg arrives after 10 uncaught errors.  I also identified the failing request to url/_changes...

However, not sure about your follow-on comment about proxy_buffering.  I am syncing between a local PouchDB in an Ionic/PhoneGap app and remote CouchDB on an AWS linux server.  I am not much a linux/aws guy and did the minimum to get a free-tier server running that I could test against.  Is there something I can change on the Couch server to address the issue?

**Comment by mnewmedia** [comment] 2016-03-16 21:54
@jeffleus If you don't use `nginx as a proxy`, you can forget about `proxy_buffering`. But to help you, provide more information and inspect anything and write it down. Try using pouchdb 3.6 and look if it works. If you use couchdb directly, you shout nod have to change anything there.

**Comment by jeffleus** [comment] 2016-03-17 16:27
@mnewmedia, thx for the quick response.  I cloned my repo to a computer at work and do not get the errors.  I will need to profile the error on my other computer in more detail and report back.  It's definitely associated w/ XHR network call

http://couch-db-server:5984/db/_changes?timeout=25000&style=all_docs&**feed=longpoll**&heartbeat=10000&since=193&limit=100

that is part of the .sync().  I notice on my work machine where I don't see the "Uncaught (in promise)" error, that this call does not error out.  And, I can actually see the timeline actively updating every 10s in DevTools on the network tab.  On the "bad" machine, the call errors out and then gets recalled repeating until the emitter error is thrown.  My guess is that it is perhaps specific to that other computer.

I will do some more detailed investigating and report back.

**Comment by nolanlawson** [comment] 2016-05-23 19:53
Closing as a duplicate of https://github.com/pouchdb/pouchdb/issues/5214, please let me know if I misdiagnosed.

**Closed by nolanlawson** 2016-05-23 19:53 UTC
Labels: bug, needs reproducing
