### ISSUE TITLE
PouchDB Get is not working in chrome after some days

### ISSUE THREAD

**Issue by hanuunah** [pouchdb/pouchdb#7165] opened 2018-03-16 14:47 UTC
### Issue
PouchDB Get is not working in chrome after some days.
-Some time works if we run in incognito, 
-Some time it works after clearing temp and cache.
-Even tried debug below code in dev tool, unfortunately it does not throw error.

### Info
- Environment: (browser)
- Platform: (Chrome)
- PouchDB Version - 6.1.2/pouchdb.min.js

### Sample Code

  ``` whenAvailable("PouchDB", function (t) {
    var db = new PouchDB('sample');
    db.get('data1').then(function (doc) {
      db.put({
        _id: 'data1',
        _rev: doc._rev,
        token: 'hello'
      });
    }).catch(function (err) {
      db.put({
        _id: 'data1',
        token: 'hello'
      });
        })      
  });

  function whenAvailable(name, callback) {
    var interval = 10; // ms
    window.setTimeout(function () {
      if (window[name]) {
        callback(window[name]);
      } else {
        window.setTimeout(arguments.callee, interval);
      }
    }, interval);
  }

**Comment by daleharvey** [comment] 2018-03-17 11:45
duplicate of https://github.com/pouchdb/pouchdb/issues/7098

**Closed by daleharvey** 2018-03-17 11:45 UTC
