### ISSUE TITLE
PUTting to a full database hangs

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#4018] opened 2015-07-01 14:25 UTC
## Environment

Android Emulator with platform 4.4.2, API Level 19; both of
* Default browser (Chrome?)
* WebView in java app
* pouch-db 3.6.0

## Observed behaviour

When a database has too much stuff in it, no callback is made from the final call to `db.put()`.

## Expected behaviour

Callback should be called with an error, or doc detailing successful put

## Steps to reproduce:

1. call `db.put()` a lot of times (around 3,500 times with a doc size of approx 2KB)
2. call `db.put()` one more time

Example code at: https://github.com/alxndrsn/pouch-db-capacity-testing/tree/full-pouch-demo

## Extension

If a further `db.put()` call is made while there is one "in progress", the following error is given to callback:

> `"InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing."`

If the page is reloaded, and a `put()` or `drop()` call is made, the following error is received by the callback:

> `{"status":500,"name":"error","message":"unknown"}`

**Comment by alxndrsn** [comment] 2015-07-01 14:57
To reproduce on desktop (Chromium 44.0.2395.0 (64-bit)):

1. `db.put()` until out of device space
2. observe that `db.put()` call has hung
2. free up some space
3. click "add doc" button
4. observe error:

> `InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`

**Comment by alxndrsn** [comment] 2015-07-01 15:01
Seems to be a Chrome issue - with Firefox 38.0.5:

The following error is returned when space runs out on device:

> `{"status":500,"name":"error","message":"unknown"}`

Subsequent `db.put()` calls return:

> `"InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`

**Comment by alxndrsn** [comment] 2015-07-01 15:50
# Safari 8.0.6:

 ## When space runs out on device:

1. This error is reported in the console from `pouchdb-3.6.0.min.js:8:10761`:

> `IndexSizeError: DOM Exception 1: Index or size was negative, or greater than the allowed value.`

2. This error is passed to the callback:

> `{"status":500,"name":"Object","message":"unknown"}`

After freeing space, subsequent calls to `db.put()` work fine.

**Comment by daleharvey** [comment] 2015-07-11 15:40
@alxndrsn Thanks so much for this report, I was worried about how hard this would be to reproduce but you already have a test repo up and running, thats amazing.

Ill take a shot at running those tests / possible getting them running on travis, would you be up for us merging them into pouchdb?

**Comment by alxndrsn** [comment] 2015-07-13 09:05
@daleharvey thanks for looking at this.  Very happy for this to be merged into pouchdb - please let me know if there's anything I can do to help.

**Comment by daleharvey** [comment] 2015-09-20 10:37
Hrm, so testing this in automation is going to be hugely difficult, been running the script to flll up my hard drive but got bored after an hour or so, I can probably point a chrome profile to a much smaller partition but we arent going to be able to do that in our current automation

**Comment by nolanlawson** [comment] 2015-09-20 13:53
I have lots of Android devices that I could fill up to test this. Testing in automation is definitely unreasonable unless Saucelabs is okay with us filling up their hard drives. ;)

For the record, I know for a fact that `idb.js` has try/catch wrappers around everything, but `websql.js` doesn't. So I'm surprised about IndexedDB not returning the callback, but not about WebSQL.

**Comment by daleharvey** [comment] 2015-09-20 14:59
The minumum partition size I can make for osx seems to be 2GB which makes testing this harder, I would like to get manual test up there so we can fix this, verify it, then have them stick around in case we hear of a regression and need to test again

**Comment by daleharvey** [comment] 2015-09-20 15:00
Will probably be easier to do this in an ubuntu vm

**Comment by daleharvey** [comment] 2015-09-20 16:34
So reproduced this in chrome, used dd to generate a file to fill up the disk,https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/idb/blobSupport.js#L27 is running and not firing oncomplete or onerror

**Comment by daleharvey** [comment] 2015-09-20 16:40
So with the above error, I get to a point where it stops responding, I can then no longer open the database (or delete it), which is why the error was in the `blobSupport` check, we done have a `txn.onerror` here which is a problem, but that doesnt even seem to be fired

**Comment by daleharvey** [comment] 2015-09-20 16:41
Sorry I keep closing this by accident

**Comment by daleharvey** [comment] 2015-09-20 17:13
So one thing to do would be to get rid of the `blobSupport` check, that at least lets us open (+delete) the database when it is full, chrome on android at this point is an evergreen browser right? the blob bugs were fixed over a year ago, @nolanlawson you have any opinions on this?

**Comment by nolanlawson** [comment] 2015-09-20 17:48
The blobSupport check is tricky, because it's partially testing for 1) bugs in pre-Chrome 37, which are still swimming around in Kitkat and below (i.e. [75% of Android devices](https://developer.android.com/about/dashboards/index.html)), along with 2) a bug in Chrome 37-42, which probably doesn't affect many Android devices since Lollipop debuted with 37 and is evergreen, now at 45.

But to be honest, I'm hesitant to remove either check, because Google doesn't provide any information about how quickly Lollipop devices are updated, and furthermore there's still weird environments like Crosswalk to deal with. Filling up your entire disk is a super-duper edge case in my opinion, and I'm worried to promote it above a much more common edge case (Chrome 37-43).

If `blobSupport` fails because of a storage error, then won't we report `blobSupport = false` and then move on to the next transaction? I'm not understanding why `blobSupport` is causing an issue here. Can't we just catch the error again later?

**Comment by daleharvey** [comment] 2015-09-20 19:33
There is no error, it goes into the `put` and never comes out, it looks like when we try to write with a full disk

```
var txn = idb.transaction....
var req = txn.objectStore(...).put(...);

req.onsuccess = function () { 
  console.log('I get called totally fine');
};

txn.oncomplete = function() { 
  console.log('I never get called');
};

txn.onerror = function() { 
  console.log('I never get called');
};
```

It looks like the same issue in startup vs writing, so will file against chrome and try to reproduce with idb only, `blobSupport` being problematic here + the fact its warning is continuing to confuse people I would still like to get rid of it, but I will check what compatibility is looking like and do that seperately.

**Comment by daleharvey** [comment] 2015-09-20 22:01
Filed the bug against chrome @ https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=534149

**Comment by daleharvey** [comment] 2015-09-22 08:00
And the bug is closed since I was doing this all wrong, we arent handling the transaction errors properly, should be a simple enough fix, its `txn.onabort` and `req.onerror`

**Comment by alxndrsn** [comment] 2015-09-22 08:20
Thanks for looking at this.

And one tip for filling up your hard disk quickly is to use boot2docker - eats up that space in no time :-)

**Comment by daleharvey** [comment] 2015-09-22 14:14
Fixed in https://github.com/pouchdb/pouchdb/commit/6c14a1a6df52ce5d06c89bd006c3d96c09183bfe

**Closed by daleharvey** 2015-09-22 14:14 UTC
Labels: bug

**Comment by daleharvey** [comment] 2015-09-22 14:15
nice @alxndrsn, I used `dd if=/dev/zero of=filename bs=1 count=0 seek=200K` and just changed it till my hd was at around 95%
