### ISSUE TITLE
Empty attachments in Crosswalk/WebView for Android

### ISSUE THREAD

**Issue by ts1690** [pouchdb/pouchdb#4940] opened 2016-03-01 22:50 UTC
A replication from a remote CouchDB database to local PouchDB in Android device truncates all attachments to zero length.

Test case:

1. CouchDB 1.6.1 on REMOTEIP:5984 with full admin party default
	CORS activated with add-cors-to-couchdb - https://github.com/pouchdb/add-cors-to-couchdb
	Config->http->bind_address to 0.0.0.0 - http://REMOTEIP:5984/_utils/config.html
	A 'test' database with a 'test' document with 'test.jpg' attached.

2. Intel XDK version 2893 - https://software.intel.com/en-us/intel-xdk

3. Android device
	Intel App Preview - https://play.google.com/store/apps/details?id=com.intel.html5tools.apppreview&hl=en

4. PouchDB 5.2.1 - http://pouchdb.com

This Test code is added in Intel XDK blank cordova app in the deviceready event:
```javascript
function doPDBTest()
{
    var ip = '1.2.3.4'; // To remote replication source CouchDB

    // DOM element
    var el = document.getElementById("id_test");

	console.log('==== navigator ====');
    console.log('appName: '+navigator.appName);
	console.log('appVersion: '+navigator.appVersion);
	console.log('platform: '+navigator.platform);
	console.log('userAgent: '+navigator.userAgent);
	console.log('vendor: '+navigator.vendor);

    el.innerHTML+=
        '==== navigator ===='+'<BR/>'
        +'appName: '+navigator.appName+'<BR/>'
        +'appVersion: '+navigator.appVersion+'<BR/>'
        +'platform: '+navigator.platform+'<BR/>'
        +'userAgent: '+navigator.userAgent+'<BR/>'
        +'vendor: '+navigator.vendor+'<BR/>';

    if(window.device)
    {
        console.log('==== window.device ====');
        console.log('cordova: '+window.device.cordova);
        console.log('model: '+window.device.model);
        console.log('platform: '+window.device.platform);
        console.log('uuid: '+window.device.uuid);
        console.log('version: '+window.device.version);
        console.log('manufacturer: '+window.device.manufacturer);
        console.log('isVirtual: '+window.device.isVirtual);
        console.log('serial: '+window.device.serial);

        el.innerHTML+=
            '==== window.device ===='+'<BR/>'
            +'cordova: '+window.device.cordova+'<BR/>'
            +'model: '+window.device.model+'<BR/>'
            +'platform: '+window.device.platform+'<BR/>'
            +'uuid: '+window.device.uuid+'<BR/>'
            +'version: '+window.device.version+'<BR/>'
            +'manufacturer: '+window.device.manufacturer+'<BR/>'
            +'isVirtual: '+window.device.isVirtual+'<BR/>'
            +'serial: '+window.device.serial+'<BR/>';
    }

    PouchDB.debug.enable('*');

	var db_remote = new PouchDB('http://'+ip+':5984/test');

    db_remote.info().then(function(info) {
        el.innerHTML +=
            'db_remote.info'+'<BR/>'
            +JSON.stringify(info)+'<BR/>';
	}).catch(function (err) {
		console.error('db_remote.info',err);
	});

	new PouchDB('test').destroy(function(response) {
        var db_test = new PouchDB('test');

        db_test.info().then(function(info) {
            el.innerHTML +=
                'db_test.info'+'<BR/>'
                +JSON.stringify(info)+'<BR/>';
        }).catch(function (err) {
            console.error('db_test.info',err);
        });

        var replication = db_test.replicate.from(db_remote)
		.on('complete', function (info) {
            console.log('>>>>>>>>>> db_test.replicate.from remote' + ' complete', info);
			getAllDocs(db_test);
		}).on('error', function (err) {
			console.log('>>>>>>>>>> db_test.replicate.from remote' + ' error', err);
        }).catch(function (err) {
            // handle error
            console.log(err);
		});
    });
}

function getAllDocs(db_test)
{
    var el = document.getElementById("id_test");
    db_test.allDocs({include_docs: true}, function(err, res) {
		if(!err) {
            res.rows.forEach(function(element) {
                if(element.doc._attachments) {
                    for(var filename in element.doc._attachments) {
                        db_test.getAttachment(element.doc._id, filename).then(function(blob) {
                            var url = URL.createObjectURL(blob);
console.log('db_test.getDoc url:', url.substring(0,64));

                            var img = document.createElement('img');
                            img.style.height = '100px';
                            img.src = url;
                            el.appendChild(img);

                            setTimeout(function () {
                                URL.revokeObjectURL(url);
                            }, 1000);
                        }).catch(function (err) {
                            // handle error
                            console.error(err);
                        });
                    }
                }
            });
        } else {
            // handle error
            console.log('db_test.allDocs error', err);
        }
	});
}
```

The Intel XDK has four main development tabs for debugging and running apps:

1. EMULATE
2. TEST
3. DEBUG
4. BUILD.

These are the results of the code above running in each mode:

Tab Mode:			Browser:	OS				Adapter		Result
1.	EMULATE			Chrome/38	Android 2.3.2	WebSQL		Success
2.	TEST			Chrome/48	Android 5.0.1	idb:binary	Fail
3.	DEBUG			Chrome/44	Android 5.0.1	idb:binary	Success
4a.	BUILD CROSSWALK	Chrome/38	Android 2.3.2	idb:binary	Fail
4b.	BUILD ANDROID	Chrome/48	Android 5.0.1	idb:binary	Fail

The PouchDB sniffing should use binary Blobs for Chrome >= 43 and fallback to Base64 encoding otherwise. These results clearly show nos. 2 and 4b failing when >= 43 and no. 4a showing binary over base64. I think then there is a little more going on maybe than just incorrect sniffing.

Info below shows the full appVersion and userAgent strings from navigator. Note 4a does *not* show Chrome in the userAgent string.. Or Crosswalk for that matter ..

1. EMULATE
navigator.appVersion: 5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36
navigator.userAgent: Mozilla/5.0 (Linux; U; Android 2.3.2; en-us; Galaxy S Build/GRH78C) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1

2. TEST
navigator.appVersion: 5.0 (Linux; Android 5.0.1; GT-I9505 Build/LRX22C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.106 Mobile Safari/537.36
navigator.userAgent: Mozilla/5.0 (Linux; Android 5.0.1; GT-I9505 Build/LRX22C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.106 Mobile 

3. DEBUG
navigator.appVersion: 5.0 (Linux; Android 5.0.1; GT-I9505 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Crosswalk/15.44.384.7 Mobile Safari/537.36
navigator.userAgent: Mozilla/5.0 (Linux; Android 5.0.1; GT-I9505 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Crosswalk/15.44.384.7 Mobile Safari/537.36

4a. BUILD CROSSWALK
navigator.appVersion: 5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36
navigator.userAgent: Mozilla/5.0 (Linux; U; Android 2.3.2; en-us; Galaxy S Build/GRH78C) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1

4b. BUILD ANDROID
appVersion: 5.0 (Linux; Android 5.0.1; GT-I9505 Build/LRX22C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.106 Mobile Safari/537.36
platform: Linux armv7l
userAgent: Mozilla/5.0 (Linux; Android 5.0.1; GT-I9505 Build/LRX22C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.106 Mobile Safari/537.36

I have a temporary fix in my code for now by just returning ArrayBuffers on Android (see createBlob in pouchdb.js) and then converting them into base64. Not ideal obviously.

**Comment by nolanlawson** [comment] 2016-03-02 14:16
Just to confirm - can you please verify that you _don't_ see this bug if you use the regular WebView rather than Crosswalk? It's nice to confirm whether it's a problem isolated to Crosswalk or not.

**Comment by ts1690** [comment] 2016-03-02 17:21
I _do_ see this bug in regular WebView (4b above)

**Comment by christianjunk** [comment] 2016-04-27 08:39
I am experiencing the same issue. But I am not able to read and convert the blob. I am always getting the following error message:

`Error in Success callbackId: SQLitePlugin966280337 : TypeError: Cannot read property 'length' of null`

**Comment by nolanlawson** [comment] 2016-04-28 22:30
@christianjunk The SQLite Plugin has compatibility issues with PouchDB. Please try [SQLite Plugin 2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) instead.

**Comment by christianjunk** [comment] 2016-04-29 07:56
@nolanlawson Sorry I provided too less information yesterday. I am already using the SQLite Plugin 2. 

```
"name": "cordova-plugin-sqlite-2",
"version": "1.0.3",
"description": "Cordova SQLite Plugin 2"
```

Here is my system information:

```
Cordova CLI: 6.1.1
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3 Build version 7D175
```

Storing and retrieving image attachments is working under all my Apple devices (iOS 9.3.1). But under Android devices (6.0.1) I am experience the problem mentioned above. I had the same problem with the "old" SQLite plugin.

This is the code for retrieving the images from the database:

```javascript
function getAllImagesForFacility(facilityId) {
      var q = $q.defer();

      var images = [];

      _localdb.query('images/by_facility', {key: facilityId, include_docs: true, attachments: true})
        .then(function (docs) {
          images = docs.rows.map(function (row) {
            // Dates are not automatically converted from a string.
            // row.doc.Date = new Date(row.doc.Date);
            return row.doc;
          });

          q.resolve(images);
        }).catch(function (err) {
        console.log(err);
        q.reject(err);
      });

      return q.promise;
    }
```

**Comment by christianjunk** [comment] 2016-04-29 14:23
Today I switched to Cloudant and after that everything is working fine. Don't know what was wrong with my own hosted PouchDB instance?! But it seems that now the problem is solved for me.

**Comment by christianjunk** [comment] 2016-05-02 14:54
I tried debugging the SQlite adapter using Android Studio. When requesting the images on Android I am getting the following error message:

`Window is full: requested allocation 2728249 bytes, free space 2096708 bytes, window size 2097152 bytes`

And after that, these message appear:

```
"Error in Success callbackId: SQLitePlugin1760063941 : TypeError: Cannot read property 'length' of null", source: file:///android_asset/www/cordova.js (312)
"Uncaught TypeError: Cannot read property 'length' of null", source: file:///android_asset/www/cordova.js (314)
```

**Comment by christianjunk** [comment] 2016-05-02 17:13
@nolanlawson It seems that there is no bug in the `cordova-plugin-sqlite-2 code`, but that there is a 2mb size limit for cursors in SQLite on Android:

1. [Cursor size limit in Android SQLiteDatabase](http://stackoverflow.com/questions/5406429/cursor-size-limit-in-android-sqlitedatabase)
2. [Retrieve large blob from Android sqlite database](http://stackoverflow.com/questions/12716859/retrieve-large-blob-from-android-sqlite-database)
3. [Access Large BLOB in Android Sqlite without Cursor] (http://stackoverflow.com/questions/17300407/access-large-blob-in-android-sqlite-without-cursor)

**Comment by nolanlawson** [comment] 2016-05-02 22:35
Hm yeah, this is not something we can easily solve.

If you are storing huge blobs in PouchDB, I would strongly strongly strongly _strongly_ recommend using IndexedDB rather than the SQLite Plugin or WebSQL. IndexedDB has native support for blobs, whereas in WebSQL/SQLite everything has to be serialized, and so even without the 2mb limit you'd run into inefficiencies due to the serialization (WebSQL lacks blob support, and Cordova requires serializing everything into strings anyway when communicating between the WebView and native layer).

Closing because this is really not something we can reasonably solve.

**Closed by nolanlawson** 2016-05-02 22:35 UTC
Labels: bug, help wanted

**Comment by christianjunk** [comment] 2016-05-03 12:30
@nolanlawson Perhaps we should add this info to the documentation and the guide of the attachment API?

**Comment by nolanlawson** [comment] 2016-05-03 15:45
Yes, I would definitely add it as an alert to the attachments guide. It's also briefly touched on in https://pouchdb.com/faq.html#data_types

**Comment by ts1690** [comment] 2016-05-25 08:47
Fast update the intel XDK now uses crosswalk 16 instead of 15 but the problem still persists on android. 

Still using workaround of returning Arraybuffer over blob and converting to base64 on android attachments. Note also since bug issue filed have had to mod putattachment too with same as get attachment.
