### ISSUE TITLE
IDB not working in Mobile Safari

### ISSUE THREAD

**Issue by Ciebiada** [pouchdb/pouchdb#7250] opened 2018-04-30 20:55 UTC
### Issue
I'm using current version of everything:
PouchDB: `6.4.3`
Mobile Safari: `Version/11.1 Safari/605.1.15`

And PouchDB, sadly, doesn't work.
Changing adapter to `WebSQL` makes it work.

Interestingly, it will work in Private (Incognito) mode, and yes I have tried clearing cache and I have tested on two different iPhones.

Errors:
```
[Error] InvalidStateError: Failed to execute 'objectStore' on 'IDBTransaction': The transaction finished.
	objectStore (bundle.js:10906)
	storeMetaDocIfReady (bundle.js:10906)
	(anonymous function) (bundle.js:10922)
	onsuccess (bundle.js:9973)
[Error] Database has a global failure – UnknownError: Error preparing Blob/File data to be stored in object store
UnknownError: Error preparing Blob/File data to be stored in object store
	guardedConsole (bundle.js:5047)
	onabort (bundle.js:10854)
[Error] Error: The error you provided does not contain a stack trace.
	parseError (bundle.js:38418)
	getStackFrames (bundle.js:38311:85)
	crashWithFrames (bundle.js:37975:84)
	rejectionHandler
[Error] Unhandled Promise Rejection: {"status":500,"name":"indexed_db_went_bad","message":"unknown","reason":"UnknownError"}
	(anonymous function)
	promiseReactionJob
```

### Info
- Environment: Mobile Safari
- Platform: iOS
- Adapter: IndexedDB
- Server: No server

### Reproduce
The most basic example like:
```
const db = new PouchDB()
db.put({_id: 'test'})
```
Will not work

**Comment by daleharvey** [comment] 2018-05-02 07:50
Closing as dupe of https://github.com/pouchdb/pouchdb/issues/7057

**Closed by daleharvey** 2018-05-02 07:50 UTC
