### ISSUE TITLE
Unable to use pouchDB 8.0.1 on a Vite 4.1.0 React Typescript + SWC application

### ISSUE THREAD

**Issue by monsieurpigeon** [pouchdb/pouchdb#8607] opened 2023-02-27 10:58 UTC
### Issue
Unable to use pouchDB 8.0.1 on a Vite 4.1.0 React Typescript + SWC application

### Info
- Environment: browser
- Platform: Chrome
- Adapter: indexedDB
- Server: PouchDB Server

### Reproduce
Create a new vite app using react / typescript + SWC, add pouchDB
You should get the following error : `Uncaught ReferenceError: global is not defined`

If you update vite.config.ts and add ```define: {
    global: "window"
  }```
You get a new error : `index-browser.es.js:457 Uncaught TypeError: Class extends value [object Object] is not a constructor or null`

**Comment by monsieurpigeon** [comment] 2023-02-27 11:06
apparently fixed when adding "events" to dependencies
'npm i events'

**Comment by enhariharan** [comment] 2023-03-23 04:14
Hi. Did you get a solution to this problem? I am facing the same issue and created a similar question for this in StackOverflow - https://stackoverflow.com/q/75808603/5447891 

I tried "npm i events" but that did not help. I still get the same error as above - Uncaught TypeError: Class extends value [object Object] is not a constructor or null.

**Comment by ehsanghorbani190** [comment] 2023-11-02 10:51
For those who are seeking an answer for this tedious problem, you first have to add this script tag in your `index.html`:
```html
<script>
	var global = global || window;
</script>
```
Now, install `events` package in your project, and you should be good to go.

There's another way of using pouchdb. You can just install `events` package, and just don't import pouchdb in your JS files, it should work ok.

**Comment by alxndrsn** [comment] 2023-11-07 11:02
> You should get the following error : `Uncaught ReferenceError: global is not defined`

This may be caused by https://github.com/calvinmetcalf/immediate/issues/39.

**Comment by garethbowen** [comment] 2024-01-31 13:44
Fixed by #8849

**Closed by garethbowen** 2024-01-31 13:44 UTC
