### ISSUE TITLE
Convert dates to strings in IndexedDB

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2352] opened 2014-06-05 17:32 UTC
Otherwise things like this (https://github.com/pouchdb/pouchdb/issues/2351) can happen, where the developer tests storing raw Dates in IndexedDB and then it bites them when it doesn't work in CouchDB/WebSQL/LevelDB.

**Comment by daleharvey** [comment] 2015-08-05 12:46
Closing as dupe of https://github.com/pouchdb/pouchdb/issues/4126

**Closed by daleharvey** 2015-08-05 12:46 UTC
Labels: enhancement, help wanted
