### ISSUE TITLE
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by tudordumitriu** [pouchdb/pouchdb#7954] opened 2019-11-18 09:56 UTC
Hi 
We are getting "InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing." when we are trying to get a document, and it happens with a disturbing frequency (once in a day under standard usage - let's say approximately 1000 - 2000 db crud operations a day).
We see it happening on Chrome Desktop and on iOS WkWebVIew Safari (cordova)
The DB is around 5000 docs and it uses replication db.replicate.to and db.replicate.from (live: true, retry: true, checkpoint: false) to keep the data in sync. 
On app startup we delay starting the replication for around 30 seconds just to make sure there the UI runs smoothly.

Any ideas / hints even on how to track or address this would be much appreciated.

**Comment by tudordumitriu** [comment] 2019-11-18 10:36
I did see there is another issue (closed) that's why I decided adding a new one: https://github.com/pouchdb/pouchdb/issues/7412

**Comment by mattjennings** [comment] 2019-12-09 21:07
I've run into this as well, and my current theory is the browser is suspending the IDB connection when it's backgrounded and screws up any active PouchDB instances. Our main browser usage was iOS Safari, and it seemed to happen much more often once iOS 13 came out. We've also seen it on Windows Chrome, though.

Unfortunately, our solution was to move away from PouchDB rather than trying to figure it out because it was also happening much too often and nearly impossible to debug.

If we were going to attempt anything, it was going to be opening new PouchDB instances for data requests and closing them after they were finished so that connections weren't kept open when the browser backgrounded.

**Comment by sureshvv** [comment] 2020-01-15 10:01
@mattjennings you moved away from PouchDB to what? Just curious.

**Comment by mattjennings** [comment] 2020-01-15 16:19
@sureshvv We decided to move to GraphQL with Apollo, and with that we found [apollo-offline](https://www.npmjs.com/package/@wora/apollo-offline) to keep it working offline.

It was not a straight-forward migration at all, but it worked for us.

**Closed** 2020-03-22 16:49 UTC
Labels: wontfix

**Comment by stevenroussey-privicy** [comment] 2020-04-16 15:49
Is this on Safari only?

**Comment by sureshvv** [comment] 2020-04-17 15:19
Chrome - Both Linux & Android

**Comment by cuongthai** [comment] 2020-05-04 06:33
I confirm this also happens randomly on Windows too. Mostly Windows 7, Windows 10 (15%). I can't reproduce it

**Comment by stevenroussey-privicy** [comment] 2020-05-04 19:40
I had noticed that we were using the newest pouchdb plugins but not the newest version of pouchdb itself.

**Comment by tudordumitriu** [comment] 2020-07-25 10:29
Hi
Maybe will help someone

We actually used sqlite adapter for mobile apps (were the idb was failing massively) and I can say we're good now.

options.adapter = 'cordova-sqlite'; (it requires the sqlite plugin install if you're using Cordova/Ionic)
options.iosDatabaseLocation = 'default';
options.androidDatabaseImplementation = 2;

**Comment by anubes19** [comment] 2020-07-26 00:33
Thanks
