### ISSUE TITLE
Update and test with the latest leveldown

### ISSUE THREAD

**Issue by peakji** [pouchdb/pouchdb#6551] opened 2017-06-08 03:42 UTC
### Issue
We've fixed the bug in `leveldown` that may cause a crash while closing db with open iterators: https://github.com/Level/leveldown/issues/194#issuecomment-306686747

However, the `Assertion 'dummy_versions_.next_ == &dummy_versions_' failed` error can be from anywhere in the C++ land, so I'm not sure if PR https://github.com/Level/leveldown/pull/368 solved the PouchDB case.

It'll be great if you could try with the latest master of leveldown, and ping me if the test still fails.

### Info
- Environment: Node.js
- Adapter: LevelDB

**Comment by hubgit** [comment] 2017-06-08 10:19
I can confirm that the `Closing db does not cause a crash if changes cancelled` test no longer crashes, which is great progress.

Unfortunately the "local" version of the test still doesn't pass (unlike the "http" version of the test, which is fine), as the new "iterator has ended" error that's thrown isn't being caught.

**Comment by ralphtheninja** [comment] 2017-07-14 20:20
There's an additional advantage to updating to `leveldown@1.7.2` since it uses `preubild-install` instead of `prebuild --install` which reduced the dependency tree substantially.

@hubgit Is there anything I can do to help with this? It seems we broke something by fixing something else.

**Comment by hubgit** [comment] 2017-07-14 20:28
@ralphtheninja [this](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.changes.js#L2366) is the test that's still failing - I didn't manage to get to the bottom of how to catch the thrown error appropriately.

**Comment by ralphtheninja** [comment] 2017-07-14 23:59
@hubgit What is the command to run all the appropriate tests? Do I need some extra setup with couchdb etc?

**Comment by daleharvey** [comment] 2017-07-15 12:09
`npm test` will run all the tests, `GREP=test.changes.js npm test` will run only that file, you do need couchdb running on localhost:5984, if that is too much of a hassle 

```
npm install -g pouchdb-server
pouchdb-server
```

is an easier version

**Comment by ralphtheninja** [comment] 2017-07-15 17:40
@daleharvey Thanks! I'm in the middle of the bush right now and a huge party, but will hop on this when I'm back home :)

**Comment by hubgit** [comment] 2017-07-22 13:46
Here's what I've been able to surmise so far:

The "Closing db does not cause a crash if changes cancelled" test calls `db.changes`, then asynchronously calls `db.close`.  Closing the database causes `db.changes`' stream reading to get the new "iterator has ended" error, which is reported by Mocha as an "Uncaught Error". Although the test completes successfully, when `done` is called the test has already been closed due to the uncaught error, so Mocha throws a "Cannot set property 'state' of undefined" exception, which is reported as an "Unhandled promise rejection".

There must be somewhere in PouchDB's changes/stream reading code to catch the "iterator has ended" error and handle it, but I haven't been able to work out where.

**Comment by ralphtheninja** [comment] 2017-07-22 14:17
@hubgit Aye, I've gathered as much myself, but have problems understanding the project structure, since all code is built out before on each `npm test`. Any pointers greatly appreciated.

**Comment by ralphtheninja** [comment] 2017-07-22 14:19
I basically want to find out what's going on in `db.close()` to start with. I'm assuming this is a pouchdb specific method that in turn wraps closing of the `leveldown` instance.

**Comment by vweevers** [comment] 2017-07-22 14:22
The `changestream` [here](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-leveldb-core/src/index.js#L1149) doesn't have a listener for an `error` event. That's where you could catch the `iterator had ended` error, I think.

**Comment by daleharvey** [comment] 2017-07-22 16:08
@ralphtheninja yup the pouchdb close is just a wrapper around levels https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-leveldb-core/src/index.js#L1158

**Closed** 2017-07-23 16:42 UTC
