### ISSUE TITLE
3.3–3.6 versions can loose attachments data

### ISSUE THREAD

**Issue by ermouth** [pouchdb/pouchdb#3932] opened 2015-06-06 07:22 UTC
Looks like data loss takes place in this scenario (Chrome 43, Mac):
* create a doc with attachments in 3.2.1
* upgrade to 3.3.1
* read the doc
* put exactly same attachment(s) in the doc as `{content_type:"whatever", data:"base64 string goes here"}`
* add some new attaches
* save the doc 
* from now replication is broken – re-saved attaches has no data / revpos and newly saved have no revpos
* upgrade to 3.6.0
* read the doc with `{attachments:true}`
* save it to another DB

Now *all* attaches of the clone are lost.

Interesting, that MD5 checksums are preserved – they all are different – but `data` returned are empty strings.

Also I experienced accidental attachments loss doing nothing with docs – just upgrading from 3.3 to 3.6. Exact cases are not yet clear.

**Comment by nolanlawson** [comment] 2015-06-06 13:53
Hm, that's weird: there was no IndexedDB migration between 3.2.1 and 3.3.1.

Have you tried upgrading directly from 3.2.1 to 3.6.0?

**Comment by nolanlawson** [comment] 2015-06-06 14:01
Also a reproducible test case would be very helpful.

**Comment by ermouth** [comment] 2015-06-06 14:10
All I can provide right now is remnants, they look like this:

```json
  "css/ptm55f-webfont.ttf": {
   "digest": "md5-SbEzACAvJcCFxzHSFvq0IQ==",
   "content_type": "application/octet-stream",
   "data": ""
  },
  "css/ptm75f-webfont.ttf": {
   "digest": "md5-ICZexyAYJD7Ox4eZxbWdOQ==",
   "content_type": "application/octet-stream",
   "data": ""
  },
  "i/tip-apps.png": {
   "digest": "md5-wtAFDfJRZZCqN3IYGyx4QQ==",
   "content_type": "image/png",
   "data": ""
  },
  "i/tip-db.png": {
   "digest": "md5-clHzg3xV1VRVkSKd4I66Bw==",
   "content_type": "image/png",
   "data": ""
  },
  "i/tip-profile.png": {
   "digest": "md5-V24SYJpSeIkEiYBteC8TuQ==",
   "content_type": "image/png",
   "data": ""
  },
  "i/tip-start.png": {
   "digest": "md5-s/bZ3Or71kFT1zCycfJIIw==",
   "content_type": "image/png",
   "data": ""
  },
  "i/tip-sync.png": {
   "digest": "md5-TGHl6/ss0gx8fhygUOFLmQ==",
   "content_type": "image/png",
   "data": ""
  },
  "i/tip-wait.png": {
   "digest": "md5-Q0hvw1jciZjK+kAn2MbWuw==",
   "content_type": "image/png",
   "data": ""
  }
```

**Comment by nolanlawson** [comment] 2015-06-06 14:23
I'm really sorry about that. We have an insane number of unit tests, but sometimes you just can't catch 'em all.

PouchDB is a non-commercial, unfunded open-source project, and we rely on the generosity and collaboration of the community to keep us honest and prevent bugs from appearing.

**Comment by ermouth** [comment] 2015-06-06 14:40
I can‘t contribute by myself in code – I‘ve tried to in one of early version but discovered I do not clearly understand what impacts what sometimes.

But I can give you an advice. Always test these scenarios (now you do not):

1. Version upgrade from several previous version__s__
2. Couch inbetween
* Old ver <-> Couch <-> New ver
* New ver <-> Couch, with doc update on server <-> New ver

It‘s not the first time I experiense data loss, but it‘s the first time, when it is so silent, massive and severe.

Also I think it‘s reasonable to think about safety procedures – DB must not destroy user‘s data. Even if exist a slightest risk – do not release.

**Comment by nolanlawson** [comment] 2015-06-06 15:33
Our tests already take ~5 hours to run on Travis; I think it would be unfeasible to add the kind of test you describe. But I would love it if you made that test yourself, and hosted it on your own server! :) You could even run it for every commit on PouchDB, which would be a great "canary in the coalmine."

Also in general I believe this particular failure can be captured within our unit tests. I suspect it has something to do with "revpos" and some very particular combination of factors that causes CouchDB to not send the attachment.

> I do not clearly understand what impacts what sometimes.

If you are ever interested in contributing, I would be happy to personally walk you through the codebase. :) It is really not so complicated. I am available via IRC, Skype, Google Hangouts, whatever.

When I got started on this project 2 years ago, I barely knew JavaScript, but Dale and Calvin were very helpful in coaching me and helping me understand stuff. I would be happy to pay that forward!

**Comment by ermouth** [comment] 2015-06-06 16:34
Let me be harsh, sorry in advance. Nothing personal.

>  I think it would be unfeasible to add the kind of test you describe

This consideration is definitely wrong. PouchDB only exist and popular because CouchDB exist. There are a lot of other DBs on top of IDB/WebSQL, and they have very little or no value.

If you do not test most natural and straightforward scenario arguing “It already takes 5 hours” – hm, I think you missing what testing is. And what database is. And what term “software release” is.

I think you are too overworked playing with plugins, default settings modifications, gates, accelerations and so on. All this experiments have very little value if your DB can destroy data in common scenarios – __because first and main intention of PouchDB is to store data__. If DB loose data silently – it‘s just not a DB.

DB must not destroy users‘ data on any possible input – since it is intended to store and persist them. If it needs 5 hours of automated testing before release – let it take 5 hours. If it needs 50 – let it take 50. Or do not label it “DB release”.

< /harsh off >

I surely can not say you what to do – we all making a lot of work to provide free software, and believe me, I know what it means very good and deeply respect your efforts. If you could notice there were no single word blaming you. 

To add – all this shit might be much less painful if I had previous revisions, but they were killed by autocompact. Thats why you better keep autocompaction off by default.

> It is really not so complicated

It is, and you know it. I do review code of new releases time to time – and definitely see that you fight complexity.

> I would be happy to personally walk you through the codebase

Thank you. It looks like I need to start doing it – I‘ll try to find a day or two in July or August, right now I can‘t since I need to sleep sometimes )

**Comment by daleharvey** [comment] 2015-06-06 16:54
@ermouth It may be lost in translation or subtlety, but saying people do not understand what testing etc is not "harsh" its rude and this isnt a place to be either.

You are right that if that is the test we need then it is the test we need, but before we worry about what type of testing would have prevented this we need to find out what "this" is

**Comment by ermouth** [comment] 2015-06-06 17:00
@daleharvey I‘ve already spent 18 hours recovering data from the thing you accidentally named ‘DB release’, and I‘m only half way from full recovery. So if it looks rude – ok, let it be rude.

**Comment by daleharvey** [comment] 2015-06-06 17:09
@ermouth I am sorry you are fustrated but no, being rude will not be tolerated as a part of the process here.

Now it looks like Nolan has been trying to reproduce this, im gonna give it a shot with the steps you have given in https://github.com/pouchdb/pouchdb/issues/3932#issue-85716486, can you check for certain since you are in chrome whether the data has gone or not, given there has been no migrations in the period over those 2 releases it doesnt seem like a data loss from inside pouchdb is possible, either things are not being replicated properly, things arent being read back out properly, or somehow the browser has managed to lose data in its own migration.

**Comment by nolanlawson** [comment] 2015-06-06 17:39
> let it take 5 hours. If it needs 50 – let it take 50

Long-running tests slow down how fast we can write code. See point 2 in [7 habits of highly defective testing](http://damienkatz.net/2014/11/7_habits_of_highly_defective_testing.html).

> I think you are too overworked playing with plugins, default settings modifications, gates, accelerations and so on.

I also write blog posts, answer questions on StackOverflow, respond to GitHub issues, review pull requests, respond to questions on IRC/Twitter/Google Groups, etc. PouchDB is a full-time job for me, and I do not get paid for it, and my employer (rightfully) expects me to do this stuff in non-office hours.

So since my benefits from this project are purely psychological, it is very hurtful to read issues like this. Not only because you lost data, but because you are frustrated over losing data and have expressed it by criticizing the way we run the project. Believe me, I am angered that I let this bug slip through and negatively affect you. I try to hold PouchDB to a higher standard than that. If I can offer an excuse, it would be: "Go ahead and use another browser database library that is more robust and better-tested." Spoiler alert: you won't find one.

Anyway, let's keep the discussion constructive and work on fixing the problem. If you could write a reproducible test case, that would be marvelous and would save us a lot of time. In the meantime, please avoid saying hurtful things that make me wonder if I should find another hobby.

**Comment by ermouth** [comment] 2015-06-06 18:01
Pointing me I‘m rude changes nothing in the fact PouchDB 3.6 swallows attachments and your existing test couldn‘t catch it.

If you don‘t like to hear your tests are not enough good – you surely can reflect it telling ‘Go ahead and use another DB’, but it changes nothing, tests are not enough good.

If you don‘t like to hear that changing default settings in the manner that can reduce safety is not the right way – don‘t be stubborn, just don‘t change these default settings. Nobody asks for it.

If you do not like to hear advices, where to focus to make you DB reliable – well, kill me or ban, or leave the project.

You may say I‘m rude or harsh or ferocious or barbarious or whatever – it‘s not intentional. I‘m not native English speaker and my directness comes up with territory I live. Nothing personal.

Again, sorry.

Constructive part is that now I‘m trying to reproduce exact steps that produce data loss and think I can provide Gist in nearly an hour or two.

**Comment by ermouth** [comment] 2015-06-06 18:39
Well, thats it. All steps are performed from console.
Each single step starts with //****

```javascript
// "Wlpa" is base64 "ZZZ"


// **** Step 1

var db = PouchDB("testb");
db.put({_id:"test1", type:"XX", name:"Test1",_attachments:{"1.txt":{content_type:"text/plain", data:"Wlpa"}}});

// **** Next 
// sync to CouchDB 1.6.1


// **** Next

var doc; db.get("test1", {attachments:true})
.then(function(a){console.log(a); doc=a;});
// I see revpos:undefined


// **** Next 
// I uploaded the same file under name 2.txt into CouchDB
// and replicated doc back to Pouch

var doc; db.get("test1", {attachments:true})
.then(function(a){console.log(a); doc=a;});
// Now I see revpos:0 for 1.txt 
// and revpos:2 for 2.txt


// **** Next

doc._attachments = {
"1.txt":{content_type:"text/plain", data:"Wlpa"},
"2.txt":{content_type:"text/plain", data:"Wlpa"}
};
db.put(doc);

// **** Next

var doc; db.get("test1", {attachments:true})
.then(function(a){console.log(a); doc=a;});
// I see revpos:undefined for both files


// **** Next

db.put(doc);

// **** Next
// close tab and wait several seconds (~15 is enough)


// **** Next
// open tab again
// force replication to Couch
// See all attachments now has zero length

var db = PouchDB("testb");
var doc; db.get("test1", {attachments:true})
.then(function(a){console.log(a); doc=a;});

// attachments now has no data
```

**Comment by nolanlawson** [comment] 2015-06-06 19:10
Cool, I will try to write a unit test to reproduce, and then I will fix it.

**Comment by ermouth** [comment] 2015-06-06 19:34
Thank you.

If you are interested in how to plan/build/test/analyze/ship/support complex reliable system, please take a time and read MIL-STD-499B “System Emgineering” (1993 editon, 70 pages). Can send you PDF if you‘re interested, very nice document, best I ever read.

Again, sorry, if I offended you somehow. It was not intentional.

**Comment by nolanlawson** [comment] 2015-06-06 19:45
@ermouth Are you compacting at all? I can reproduce the issue where `revpos: undefined` shows up (and this becomes `revpos: 0` for both attachments in the remote Couch), but I cannot get it to lose the data in either remote or local. It is always `"Wlpa"`.

**Comment by ermouth** [comment] 2015-06-06 19:55
No autocompaction, PouchDB 3.6.0 uglified. Also DB was not compacted manually during intermediate steps.

**Comment by nolanlawson** [comment] 2015-06-06 19:58
^ Here is my attempt to write a test. I still can't reproduce, but maybe it's because it has something to do with closing the tab and waiting 15 seconds. I can't imagine what difference that that would make, though, and it would be impossible to reproduce in our unit tests.

**Comment by nolanlawson** [comment] 2015-06-06 19:59
Also what does "force replication to Couch" mean? Can you hop onto IRC to explain how to repro this?

**Comment by ermouth** [comment] 2015-06-06 20:06
I do not use IRC for security considerations, sorry. ermouth @skype or @Gtalk

**Comment by ermouth** [comment] 2015-06-07 10:07
@nolanlawson did you try to reproduce an issue from console, closing tab in the middle? if not, do you plan to?

**Comment by daleharvey** [comment] 2015-06-07 11:17
Trying to reproduce from the steps in https://github.com/pouchdb/pouchdb/issues/3932#issuecomment-109631249, this is on pouchdb.com 

```
var db = PouchDB("testb");
undefined
db.put({_id:"test1", type:"XX", name:"Test1",_attachments:{"1.txt":{content_type:"text/plain", data:"Wlpa"}}});

Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
db.sync('http://127.0.0.1:5984/testing/');
o {canceled: false, push: s, pull: s, _events: Object}
pouchdb.min.js:9 GET http://127.0.0.1:5984/testing/?_nonce=1433673153554 404 (Object Not Found)i @ pouchdb.min.js:9t.exports @ pouchdb.min.js:9r @ pouchdb.min.js:9n @ pouchdb.min.js:7c @ pouchdb.min.js:7(anonymous function) @ pouchdb.min.js:9i @ pouchdb.min.js:9u @ pouchdb.min.js:9r @ pouchdb.min.js:9f.sync @ pouchdb.min.js:9(anonymous function) @ VM256:2InjectedScript._evaluateOn @ VM69:895InjectedScript._evaluateAndWrap @ VM69:828InjectedScript.evaluate @ VM69:694
pouchdb.min.js:9 The above 404 is totally normal. PouchDB is just detecting if the remote DB exists.
pouchdb.min.js:9 GET http://127.0.0.1:5984/testing/_local/rA2HZgYrJduwgVC.oZX47g%3D%3D?_nonce=1433673153611 404 (Object Not Found)i @ pouchdb.min.js:9t.exports @ pouchdb.min.js:9r @ pouchdb.min.js:9n @ pouchdb.min.js:7(anonymous function) @ pouchdb.min.js:7(anonymous function) @ pouchdb.min.js:10(anonymous function) @ pouchdb.min.js:10(anonymous function) @ pouchdb.min.js:10(anonymous function) @ pouchdb.min.js:10(anonymous function) @ pouchdb.min.js:10o.getCheckpoint @ pouchdb.min.js:8A @ pouchdb.min.js:9c @ pouchdb.min.js:9(anonymous function) @ pouchdb.min.js:9
pouchdb.min.js:9 GET http://127.0.0.1:5984/testing/_local/rA2HZgYrJduwgVC.oZX47g%3D%3D?_nonce=1433673153684 404 (Object Not Found)i @ pouchdb.min.js:9t.exports @ pouchdb.min.js:9r @ pouchdb.min.js:9n @ pouchdb.min.js:7(anonymous function) @ pouchdb.min.js:7(anonymous function) @ pouchdb.min.js:10(anonymous function) @ pouchdb.min.js:10(anonymous function) @ pouchdb.min.js:10(anonymous function) @ pouchdb.min.js:10(anonymous function) @ pouchdb.min.js:10r @ pouchdb.min.js:8o.updateTarget @ pouchdb.min.js:8o.writeCheckpoint @ pouchdb.min.js:8v @ pouchdb.min.js:9
pouchdb.min.js:9 The above 404 is totally normal. PouchDB is just checking if a remote checkpoint exists.
var doc; db.get("test1", {attachments:true})
.then(function(a){console.log(a); doc=a;});
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
VM260:3 Object {type: "XX", name: "Test1", _attachments: Object, _id: "test1", _rev: "1-3092f409ac5d7fb90a5e0f17e8d19bcc"}_attachments: Object1.txt: Objectcontent_type: "text/plain"data: "Wlpa"digest: "md5-B0UGSRi0lpPMpk1rahPSig=="__proto__: Object__proto__: Object_id: "test1"_rev: "1-3092f409ac5d7fb90a5e0f17e8d19bcc"name: "Test1"type: "XX"__proto__: Object
```

Not seeing revpos:undefined, what version are you doing those console tests with?

**Comment by ermouth** [comment] 2015-06-07 11:32
3.6.0. 
https://github.com/pouchdb/pouchdb/issues/3932#issuecomment-109643252

**Comment by nolanlawson** [comment] 2015-06-07 16:38
@daleharvey If you use Node rather than Chrome, you won't see `revpos: undefined`, but it's definitely there if you follow @ermouth's steps. That's fixed in master.

However I could not reproduce the data loss, and yes @ermouth I did try your steps with closing the tab, but I did not succeed. The "Wlpa" is still there on both attachments, in both the remote and local databases.

**Comment by daleharvey** [comment] 2015-06-07 17:02
I was doing it in chrome, visiting pouchdb.com in the console and with CouchDB running 1.6.0 at localhost:5984

```
> var db = new PouchDB('newtest');
undefined

> db.put({_id:"test1", type:"XX", name:"Test1",_attachments:{"1.txt":{content_type:"text/plain", data:"Wlpa"}}});
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}

> db.sync('http://127.0.0.1:5984/newtest');
....

> var doc; db.get("test1", {attachments:true}).then(function(a){console.log(JSON.stringify(a)); doc=a;});
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
{"type":"XX","name":"Test1","_attachments":{"1.txt":{"digest":"md5-B0UGSRi0lpPMpk1rahPSig==","content_type":"text/plain","data":"Wlpa"}},"_id":"test1","_rev":"1-d0dfb854f0bba2d2c6800410908796c7"}

**Comment by nolanlawson** [comment] 2015-06-07 17:28
@daleharvey 

1) Download this HTML file: https://gist.github.com/nolanlawson/f0dd3e35ba908df691bb
2) Run `python -m SimpleHTTPServer 8888`
3) Follow the steps

You'll see this in the console:

![screenshot 2015-06-07 13 28 06](https://cloud.githubusercontent.com/assets/283842/8025145/168fe88c-0d19-11e5-8b2e-4d13ca3f5f54.png)

Notice that the data ("Wlpa") is still there. However, the local doc has `revpos: undefined`.

**Comment by nolanlawson** [comment] 2015-06-07 17:30
@ermouth That html file ^ follows your steps exactly and does not reproduce the error. If you could, please modify the html file so that it reproduces the error.

**Comment by ermouth** [comment] 2015-06-07 18:45
@nolanlawson did you try to reproduce it using console and Futon step by step? __if you did not, please, just spend 5 minutes and try.__

I won‘t run any code until you try steps exactly, uploading file using Futon. It worth 5 minutes, much less, then you spent writing your htmls.

You asked me to give you steps how to reproduce – I gave them to you, but you just trying to play around.

**Comment by ermouth** [comment] 2015-06-07 19:06
@nolanlawson addition. If you can‘t reproduce even performing sequence step by step, then I think I should create sterile environment and add all possibly impacting factors one by one, combing them in all possible ways. 

It would take enormous effort surely since this approach have combinatorial complexity, and I don‘t want to until I try all other less complex ways.

**Comment by daleharvey** [comment] 2015-06-07 20:03
@ermouth Its abundantly clear both of us have spent far more than 5 minutes trying to reproduce this and neither of us have been able to with the steps you have given us. I gave you you very precise example @ https://github.com/pouchdb/pouchdb/issues/3932#issuecomment-109772916 of following your steps and did not start getting at the same issue, Nolan has obviously spent far more time trying to interpret your very vague bug report and has not been able to reproduce.

You can follow up and provide more information to help us debug it, or you can try to do so yourself. Either way again I am reminding you that you can only do so here if you promise to be civil which you are still not being. Absolutely nobody owes you their time and every bit of work that people are doing to help you diagnose this issue you should at the very least be thankful for.

**Comment by daleharvey** [comment] 2015-06-07 20:11
> Notice that the data ("Wlpa") is still there. However, the local doc has revpos: undefined.

Yup getting revpos: undefined in both firefox and chrome

**Comment by ermouth** [comment] 2015-06-07 20:18
@daleharvey what I see, is playing around. If the term ‘playing around’ insults you – well... I just do not know, how to express more precisely what you are doing. No even bit of sorry in this case.

In your comment:
* I see dots like ..... – I do not understand what they mean
* I do not see was Futon used or not
* I see that you could not reproduce `undefined` that is clearly reproducible.

These three points mean that term ‘precise’ definitely can not be used here. So please put off your arrogance, it‘s just annoying.

I asked very simple and direct questionseveral times and did not get an answer. So I‘m asking again – __did you repeat all steps exactly? Without cheats, HTMLs, emulations and so on?__

NB: Testing with localhost is not good for various reasons, you better use you subnet IP for example, not 127.0.0.1.

**Comment by daleharvey** [comment] 2015-06-07 20:33
Yes, when someone is spending their precious time attempting to help you and you tell them they are 'playing around' it is plainly rude, there isnt a way to say it in a non rude way because it is by definition rude. again nobody owes you any of their time.

I gave you a direct answer, I opened up pouchdb.com in Chrome 34, I typed in the 4 commands that you started to describe @ https://github.com/pouchdb/pouchdb/issues/3932#issuecomment-109631249, then it gave me the output @ https://github.com/pouchdb/pouchdb/issues/3932#issuecomment-109772916. I did not get revpos:undefined, which you indicated in your comment you were seeing so there was obviously something missing to reproduce the bug. Nolan has managed to get a lot further diagnosing it with https://gist.github.com/nolanlawson/f0dd3e35ba908df691bb, so if you want to find the cause of this bug I would suggest looking into it and replying in a civil manner

**Comment by ermouth** [comment] 2015-06-07 20:59
@daleharvey I‘m spending __my__ precious time solving problems possibly caused by the library from __your__ repo. And I definitely saw no help, when I had to repair manually 50+Mb of lost data, and I couldn‘t repair about 10% – they are lost forever. Repair took more than 30 hours of very unpleasant work, and in parallel I was to look for reproducible recipe for you and Nolan, finding out what could cause the loss.

If you do not like to investigate and solve the problem with you lib – well, I definitely do not insist, since right now I see very little value in all the words you said.

And yes, thank you for your lessons of English, I just opened vocabulary and see that ‘to play around’ term has not only insulting meaning, so if you were offended – look for the reason inside you head, not in my words. 

And I see now, that you finally _could_ reproduce `undefined`, so there is nothing more to discuss.

Now I‘m asking the question again: __did you repeat all steps exactly? Without cheats, HTMLs, emulations and so on?__

NB. The 34th release of Chrome is very old, update. (May be you just mis-typed).

**Comment by nolanlawson** [comment] 2015-06-07 21:00
@ermouth I tried it again just now, following your directions exactly, using `localhost` and Futon to upload the attachment. I'm using CouchDB 1.6.1, PouchDB 3.6.0 minified, and Chrome. Same result: "Wlpa" is still there.

This is why we need actual working code, not English descriptions. And yeah, Dale is right; your attitude is not persuading me that I should spend any more of my time this weekend working on this.

**Comment by ermouth** [comment] 2015-06-07 21:02
Ok.

**Comment by willholley** [comment] 2015-06-09 06:37
@ermouth  I know this ticket has been closed but I'm also trying (and failing) to reproduce this problem using console and Futon. Could you please clarify a few points in your reproduction steps:

1. When you say  "sync from CouchDB 1.6.1, sync to CouchDB 1.6.1" is this a db.sync(remote) call in PouchDB or something else?
2. When you say "See all attachments now has zero length" is this observed in PouchDB or Futon?
3. Are you able to reproduce this problem using an empty database? How about against Cloudant (to rule out any problems with your CouchDB instance)?

Finally, it would be very helpful to get a request trace during your reproduction of the error. Chrome can save an XHR from the Network tab in developer tools - you may need to clear out any authentication details before posting it to GitHub.

**Comment by jhs** [comment] 2015-06-09 08:36
@ermouth, I know how frustrating it can be to lose data and to struggle to recover. And yes, the worst bugs can be very painful to experience yet very difficult to reproduce. Hang in there!

Not to hijack this thread, but I would like to discuss some sort of worst-case backup/restore tool. As I use and think about PouchDB, I feel like, it is a superb achievement, but it is still young. A prudent engineer may wish to make a full copy of PouchDB. (No, a replica is not a backup.)

I am also very interested in PouchDB plugins. I am thinking of a backup/restore plugin (nothing official, just an insurance policy for those who want it).

@ermouth, if you could go back in time, what kind of backup/restore tool would have helped you? For me, I use PouchDB with Node.js, so I would perhaps want a backup that is a text file with JSON, plus attachments as plain files in the file system. That way, in a worst-case scenario, I could manually restore the data from the very accessible backup data. Have you got any thoughts? Perhaps for those who use PouchDB in a browser, something that streams a backup to a server, or S3 or something?

**Comment by daleharvey** [comment] 2015-06-09 08:44
Ermouth has been blocked from replying, we will try to resolve that out of github but in the meantime probably best not to ping him in the thread. We have reopened the investigation in https://github.com/pouchdb/pouchdb/issues/3942

@jhs you may want to look at https://github.com/nolanlawson/pouchdb-dump-cli

**Comment by jhs** [comment] 2015-06-09 08:45
Love it. Thanks.

**Closed by daleharvey** 2015-06-09 08:44 UTC
