### ISSUE TITLE
`PouchDB.sync` doesn't seem to emit anything when username/password is incorrect

### ISSUE THREAD

**Issue by chrisfosterelli** [pouchdb/pouchdb#4761] opened 2016-01-07 23:19 UTC
I'm using the following code:

```javascript
let src = /* local PouchDB */
let dst = /* remote CouchDB URL */
PouchDB.sync(src, dst)
.on('denied', handleErr)
.on('error', handleErr)
.on('complete', () => console.log('complete'))

function handleErr(err) {
  let msg = 'Could not sync with remote CouchDB:'
  console.error(msg, err.message)
}
```

If the username and password of the `dst` URL is invalid, I can see CouchDB issue a 401 error but I see a "complete" message on the client. No changes are propagated to the actual remote database.

**Comment by nolanlawson** [comment] 2016-01-10 22:33
Which version of CouchDB?

**Comment by chrisfosterelli** [comment] 2016-01-11 02:25
@nolanlawson 1.6.1

**Comment by nolanlawson** [comment] 2016-01-15 02:25
We need better testing around the case of a non-admin-party CouchDB. Maybe this bug will be a good start, especially now that we are using Docker in Travis to run CouchDB.

**Comment by ahaith** [comment] 2016-02-12 13:36
I'm encountering this also. It seems to be happening because 401s are ignored in case they arise from attempting to replicate design docs. See PR #2243. 

Changing to only screen out 403s works for my purposes, but presumably this would cause issues when replicating dbs which contain design docs.

**Comment by nolanlawson** [comment] 2016-05-20 00:06
duplicate of https://github.com/pouchdb/pouchdb/issues/5172

**Closed by nolanlawson** 2016-05-20 00:06 UTC
Labels: bug
