### ISSUE TITLE
npm install pouchdb --save fails if directory name has space

### ISSUE THREAD

**Issue by gpathak18** [pouchdb/pouchdb#6786] opened 2017-10-10 02:38 UTC
### Issue
npm install --save pouchdb fails

### Info
- Environment: NodeJS 8.5
- Platform: MacOS

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.
Create NodeJS project in a directory on your mac that has 'space' in the name:

example - User/abc/project/my project/package.json

now install pocuhdb using 'npm install pocudb --save'

The command fails and produces following - 

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.5.0 install script.

Now 'rename' the directory and remove space, (in example above - User/abc/project/myproject/) and try the command again, installation completes without error.

**Comment by pubkey** [comment] 2017-10-11 20:26
I think this is not a pouchdb-problem but a leveldb-problem.
Can you check if `npm i leveldown --save` works in your folder?

**Comment by gpathak18** [comment] 2017-10-12 02:06
I thought the same but 'npm i leveldown --save' command is successful, only 'npm install pocudb --save' fails. I just tried this on my machine again.

**Comment by pubkey** [comment] 2017-10-12 08:10
Ok. I tested this on linux but there it works.
Can someone with windows reproduce this?

**Comment by karlwestin** [comment] 2017-10-22 22:19
I took a quick look to reproduce on macosx 10.11.6
Seems to be dependent on node/npm combination

| Node version  | Npm version | Install succeeds/fails |
| ------------- | ------------- | ------------- |
| 8.5.0 | 5.5.1 | **fail** |
| 6.11.4 | 3.10.10 | **success** |
| 6.11.4 | 5.5.1 | **success** |

Some observations
- Just like @gpathak18 says, `npm install --save leveldown` works, while `npm install --save pouchdb` fails. 
- Other packages that have leveldown as dependency for example `flash-store` **succeeds** :(

Anyone have any ideas where we can look further on this?

**Comment by westphalen** [comment] 2017-12-10 14:50
+1 Have this problem as well.
NPM: `5.5.1`
Node: `8.9.1`
PouchDB: `^6.3.4`

**Comment by daleharvey** [comment] 2018-01-26 12:44
I would give `npm install --save level` a shot, its not only leveldown, either way the fact that it is both dependent on npm versions and all errors point to level says that this is a level bug that we cant do anything about inside pouchdb so closing out, cheers

**Closed by daleharvey** 2018-01-26 12:44 UTC

**Comment by Annoraaq** [comment] 2019-04-15 13:50
The bug might be originating in leveldown but it leads to PouchDB not running. So I am not sure if it is optimal to close this issue.
