### ISSUE TITLE
Saving and invalid attachment causes sync to fail

### ISSUE THREAD

**Issue by syntithenai** [pouchdb/pouchdb#2876] opened 2014-10-16 00:28 UTC
If I save an attachment inline and fail to include the digest attribute. The attachment happily saves but subsequent sync operations cause an error.
Uncaught DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
If I use the websql adapter I get the error
Uncaught IndexSizeError: Failed to execute 'item' on 'SQLResultSetRowList': The index provided (0) is greater than or equal to the maximum bound (0).

If I load the record and attachment and just update the data so that the digest, revpos etc attributes are present when I save the record (with inline attachment) the world is good.

It seem to be that there is a bug in being able to save attachments when there is insufficient meta data.

**Comment by daleharvey** [comment] 2015-09-08 14:57
@syntithenai If you are able to give us any hep reproducing or stilling seeing this could you reopen, otherwise this has been open a year without STR so closing out, thanks

**Comment by simonaberry** [comment] 2015-11-22 06:04
I have managed to replicate the same error :

1. uploaded a Docx file using a HTML input of type file -> saved to `fileInputVal`
2. put attachment to pouchdb

```
db.putAttachment('templ/doc',templFilename,templateDocRev, fileInputVal,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
```

i am still a newbie at blobs, buffers, ecoded strings, etc etc... so suspect what I did above was actually wrong (still trying to get my head around it) - but despite my stupidity I don't think that that my mistake should lead to the document becoming unusable ??

error message is  : `Uncaught DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.`

and my datastore looks like this 
 ```
_attachments: {,…}
StratByRole.docx: {digest: "md5-zifDeTdaeoheLEqOmHCxqA==",…}
content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
digest: "md5-zifDeTdaeoheLEqOmHCxqA=="
length: 16035
revpos: 0
stub: true

StratScorecard.docx: {content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"}
content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

StratSummary.docx: {digest: "md5-dDlPcXml87QaMEYFhyFsVQ==",…}
content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
digest: "md5-dDlPcXml87QaMEYFhyFsVQ=="
length: 15153
revpos: 0
stub: true
_doc_id_rev: "templ/doc::4-80ceeb333b73b6b2ee6cb8d9f954de3e"
```

its the 'StratScorecard.docx' attachemnt that was added incorrectly - as you can see there is no digest, length, revpos or stub info...

**Comment by nolanlawson** [comment] 2015-11-22 22:44
Can you please provide an HTML page that reproduces this error? I'm not sure what's causing it, but it seems like it might be a bug in PouchDB.

**Comment by simonaberry** [comment] 2015-11-23 05:10
http://plnkr.co/edit/R2uGLISmDNHUFudyjqWr

in trying to recreate the bug, I realised that  
- document with attachments must exist already, error does not occur if creating a new doc/attachment
- if the doc has a single attachment, then Pouch catches the problematic request  and gives a 'Some query argument is invalid' 500 error
- as per example, if you do a putAttachement on to a doc that has multiple attachments && do it *twice* (seems to work ok first time) - you get the malformed document in the attachments

after typing this all up, I ran my plunkr one last time and the bug did not happen again (although it did occur initially in the plunkr), so it must be an occasional occurrence ??  Either way, I hope the the plunkr provides some sort of help....

I also just remembered that the original bug was linked to a pouchdb that is sync'ed. And my real pouchdb (i.e. not the plunkr) is a sync'ed one. It may help you to reproduce the bug if you set up the db to sync.

**Comment by nolanlawson** [comment] 2015-12-13 23:45
So the plunkr does not reproduce the issue? Keep in mind that, if you need to `sync()` in order to reproduce the bug, you don't actually need CouchDB - you can sync between two local PouchDBs.

Closing unless we can get a test case that reproduces the issue. Sorry, but we just cannot solve it using the information provided.

**Closed by nolanlawson** 2015-12-13 23:45 UTC
Labels: bug

**Comment by injectless** [comment] 2016-07-11 04:41
it happens when you try to return the attachment:
```
  getfile: function(id, file){
            db.get(id, {attachments: true}).then(function(doc) {
              return doc;
          }).then(function(here) {
            return db.getAttachment(here.id, file, here._rev);
          }).catch(function(err){
            console.log("error :(");
            console.log(err);
          });
          }, 
```

This is what I get:
**_DOMException: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
    at Error (native)_**

To put an attachment, I use:
```
 db.get(id).then(function(doc) {
            var buf = new Buffer(base64, 'base64'); 
            console.log(doc)
            //tried also with buf instead of base64 var
             db.putAttachment(doc._id, 'cover.png', doc._rev, base64, 'text/plain').then(function(res) {
                  console.log(res);
              }).catch(function(err){ return console.log(err); });
           }).catch(function(err){ return console.log(err); });
```

Now, the return of the db.get actually shows the attachment there, like so:
![screenshot_2016-07-11_01-40-40](https://cloud.githubusercontent.com/assets/12424545/16720045/8346c048-4708-11e6-8ae6-ad6d00539c37.png)

This is really weird

**Comment by nolanlawson** [comment] 2016-07-11 15:24
Hi @injectless, thanks for letting us know! If you can consistently reproduce this error, could you please open a new issue with a reproducible test case? Looking at your code and screenshots, I'm not sure how to reproduce, because it seems to be that all of your code is well-represented in our test suite.

OTOH I do notice in your code that you say `here.id` instead of `here._id`; maybe that's the source of the bug?

**Comment by llunn** [comment] 2020-09-01 17:46
@nolanlawson I realize this issue is almost over 4 years old, but wanted to add the cause and solution for this error as I experienced it, in case other people find themselves reading this.  I'm working within the context of an Ember app, so (partially) access databases through ember-pouch, but also directly through PouchDB.

In my case, this was caused by a call to `allDocs` using an array that contained an element equal to `undefined` for the `keys` params.  Interestingly, the `undefined` element was added to the array using `find` and passing it an null id, which returned all records in the database.  This document did not contain an attribute that was expected (but not checked for), resulting in an undefined value being injected into aforementioned array.

Solution was to obviously fix this logic problem in my projects codebase.  Seems obvious to not pass `undefined` as an id to retrieve, but it seems like PouchDB is happy to serve that request and return **ALL** documents.  Seems like unintended behaviour to me, but that is for you to decide I suppose.  Note that this is different than passing `null`, which rejects with a useful error.
