### ISSUE TITLE
Attachment corruption when upgrading PouchDB from pre-promises version to 4.*

### ISSUE THREAD

**Issue by enquora** [pouchdb/pouchdb#4371] opened 2015-09-28 16:50 UTC
Have seen two instances of attachments store becoming corrupted when updating from pre-promises version to 4.*

Attachment references incorrectly over-written, some attachments deleted.

**Comment by nolanlawson** [comment] 2015-09-28 19:13
A test case to reproduce would be very helpful. :) Which platform are you seeing this on?

**Comment by enquora** [comment] 2015-09-28 19:21
Windows, Firefox
OS X, Firefox

**Comment by daleharvey** [comment] 2015-10-05 13:37
Heh, what version did we implement the Promise API, @enquora any specifics about what version you were based on? cheers

**Comment by daleharvey** [comment] 2015-10-12 13:01
Put a basic test case up and not seeing any issues between upgrading from 1.1.0 to latest, would need more information to reproduce this @enquora, cheers

```
<!doctype html>
<html lang="en">
  <meta charset="utf-8">
  <title>My Paste</title>
  <script src="//cdn.jsdelivr.net/pouchdb/1.1.0/pouchdb.js"></script>
  <script>
    new PouchDB('testingupdate', function (err, db) {
      console.log('err', db);
      var doc = {
        "_id": "doc",
        "title": "Legendary Hearts",
        "_attachments": {
          "att.txt": {
            "content_type": "text/plain",
            "data": "TGVnZW5kYXJ5IGhlYXJ0cywgdGVhciB1cyBhbGwgYXBhcnQKTWFrZS" +
              "BvdXIgZW1vdGlvbnMgYmxlZWQsIGNyeWluZyBvdXQgaW4gbmVlZA=="
          }
        }
      };
      db.put(doc, function (err, result) {
        console.log('yay', result);
        console.log(err);
      });
    });
  </script>
</html>
```

```
<!doctype html>
<html lang="en">
  <meta charset="utf-8">
  <title>My Paste</title>
  <script src="http://cdn.jsdelivr.net/pouchdb/latest/pouchdb.js"></script>
  <script>
    var db = new PouchDB('testingupdate');
    db.getAttachment('doc', 'att.txt').then(function(doc) {
      console.log(doc.type);

      var myReader = new FileReader();
      myReader.onload = function(event){
        console.log(JSON.stringify(myReader.result));
      };
      myReader.readAsText(doc);
    });
  </script>
</html>
```

**Comment by daleharvey** [comment] 2016-01-03 18:14
Closed as unable to reproduce

**Closed by daleharvey** 2016-01-03 18:14 UTC
Labels: enhancement
