### ISSUE TITLE
PouchDB not building if Webpack target is set to electron

### ISSUE THREAD

**Issue by kobens** [pouchdb/pouchdb#5911] opened 2016-11-21 14:46 UTC
### Issue
I'm not entirely sure this is an issue with PouchDB, but I tried adding the pouchdb package to my Electron app and it didn't go well. 

Webpack threw me the error when I tried bundling the js (using Webpack):
`76:22 Critical dependency: the request of a dependency is an expression`

I found two workarounds:
1. remove `target: 'electron'` from my `webpack.config.js`
2. add `/lie\.js$|\/leveldown\//` to `module.target` in `webpack.config.js`

The first one is not an option since I need to access some electron specific modules. The second seems to work but it isn't documented anywhere and I had to dig around to find it #3647

### Info
- Environment: Electron
- Platform: macOS

### Reproduce
Clone [this repo](https://github.com/kobens/electron-pouchdb), run `yarn`, remove [this line](https://github.com/kobens/electron-pouchdb/blob/d14fdf070f7c81981218d39ef648d1c9faafe29c/webpack.config.js#L14), and run `yarn build`

**Comment by nolanlawson** [comment] 2016-11-21 17:54
We’ve seen this issue reported many times by Webpack/Electron users and I’ve always wondered how to fix it. No one on the PouchDB core team is very familiar with Webpack or Electron but it seems that there is a very complicated amount of configuration required to get Webpack to work properly. I’m not sure if there is anything PouchDB can do here.

The main issue (as far as I can tell) is that PouchDB can either be used Node-style (using leveldown) or browser-style (using IndexedDB/WebSQL). Also leveldown must be recompiled in Electron to work properly.

One possible solution is to use the packages pouchdb-node or pouchdb-browser and therefore explicitly state which one you are using. But I wonder if there’s something more PouchDB can do.

**Comment by nolanlawson** [comment] 2016-11-21 18:03
Are you trying to use PouchDB in the Node style or in the browser style? Also why did `/lie\.js$|\/leveldown\//` fix it for you? What happened when you removed `target: 'electron'`?

**Comment by kobens** [comment] 2016-11-21 18:23
I don't know why the noParse line fixed it found it here https://github.com/pouchdb/pouchdb/issues/3647

Removing `target: 'electron'` fixes the issue but then you can't import electron modules (like fs I think).

I tried using pouchdb-browser but got the same error.

**Comment by nolanlawson** [comment] 2016-11-22 16:57
Are you trying to use PouchDB in a Node style or in a browser style? If you're using Electron I'll assume you want to use it in the Node style so that it runs on a background thread and uses native LevelDB.

If that's the case, then ignoring leveldown would be the wrong approach; you would need to recompile leveldown for Electron. I don't know what the standard Electron+Webpack approach is for that, but I could ask around. As for why you need to ignore `lie`, that confuses me as well because it's just a Promise polyfill.

**Comment by kobens** [comment] 2016-11-23 09:18
If I use it Node style, then I guess I don't have to import pouchdb directly in the renderer script (bundled by Webpack).

Requiring from the main process works without changing the Webpack config, so I can have this somewhere in my renderer script:
```js
const PouchDB = require('electron').remote.require('pouchdb')
const db = new PouchDB('DB');
db.info().then(function (result) {
  console.log(result)
}).catch(function (err) {
  console.log(err);
});
```

This however gives me a version mismatch error, but that must be a different issue altogether:
`Error: Module version mismatch. Expected 50, got 51. This generally implies that leveldown was built with a different version of node than that which is running now.  You may try fully removing and reinstalling PouchDB or leveldown to resolve.`

**Comment by nolanlawson** [comment] 2016-11-23 16:45
The version mismatch error can usually be fixed by reinstalling leveldown, e.g. as in this demo https://github.com/nolanlawson/pouchdb-electron

My understanding is that this is the "proper" way to use native modules in electron.

**Comment by nolanlawson** [comment] 2016-12-14 04:24
I can no longer reproduce. Seems this was fixed in either Webpack or Electron. Please reopen if I'm wrong about this.

**Closed by nolanlawson** 2016-12-14 04:24 UTC
Labels: bug, has test case, help wanted
