### ISSUE TITLE
(possible bug?) views are regenerating on each page load

### ISSUE THREAD

**Issue by dryajov** [pouchdb/pouchdb#4857] opened 2016-01-30 20:49 UTC
I've been seeing what I believe is weird behavior with views being regenerated on each page load (pouch in the browser). According to an earlier conversation with @nolanlawson on slack, this should not happen. I followed his advices and made sure that the data was not being altered between page loads, and from what I can tell it is not. 

What I've done so far to make sure data is not changing, is attach a `change` handler to the DB to monitor it. The app is also designed in such a way that data only changes through user interaction or replication from a remote db. For this tests I've disabled replication all together and I also made sure that I didn't interact with the app in such a way that it would update or add any new documents. I've also made sure that the change sequence doesn't change using the browser fauxton plugin. 

So far the behavior is pretty consistent, the view seems to be regenerated on each page refresh when that view is first queried, even with the `stale` param being set to either 'update_after' or 'ok'. After the page loads, subsequent queries are considerably faster, but this behavior makes the app startup seem pretty slow.

Here is the console capture from two consecutive runs:

First run:
[pouchdb_onpageload.txt](https://github.com/pouchdb/pouchdb/files/110989/pouchdb_onpageload.txt)

Second run:
[pagedb_onpageload1.txt](https://github.com/pouchdb/pouchdb/files/110990/pagedb_onpageload1.txt)

Again, as far as I understand, this is not the expected behavior, and if it is, it would be useful to be able to control it with a flag - I don't mind having to regenerate the view every so ofter, but I should be able to control when it happens.

**Comment by nolanlawson** [comment] 2016-01-30 21:23
Hey @dryajov, this is very helpful information, but I think we would need tests to reproduce rather than the logs, which are rather verbose and hard to discern. Any chance you can provide a reproducible test case?

**Comment by dryajov** [comment] 2016-01-30 22:24
Sure, I'll put together a sample project ASAP.

**Comment by ermouth** [comment] 2016-01-31 20:38
@dryajov Do you pass map/reduce functions as a query param or have them stored in a design doc?

**Comment by dryajov** [comment] 2016-02-02 22:18
@ermouth  They are stored in a design doc

**Comment by dryajov** [comment] 2016-02-02 22:31
So, I havent been able to reproduce this outside of my app. I wonder what I might be doing that would cause this behavior. Basically, refreshing the page, causes the view to trigger the change event every time. It doesn't seem to matter if its a fresh db with completely new data, or its data that has been replicated from a remote. 

I've been trying to debug this, but being new to the code and not knowing what the criteria to trigger the change event is, I'm not getting too far. At this point, I believe that, in order to move forward troubleshooting the issue, I'd need to get a bit more acquainted with the internals of pouch and how it determines changes in general (and for IDB in particular, although this seem to happen with websql as well), so if there are any pointers to tickets discussing the implementation of the change stream/feed, or general suggestions of what to look for when stepping through the code, that should be pretty helpful.

Also, I should point out that once that page has loaded, I don't see the change event trigger any more, it happens exclusively after/on page load and the first time I run the query, which makes me wonder if it's got something to do with when/how I'm loading things (race condition of some sort?).

**Comment by daleharvey** [comment] 2016-05-27 11:52
Closing as a dupe, its the same issue and the other has a test case with it, cheers for reporting https://github.com/pouchdb/pouchdb/issues/4967

**Closed by daleharvey** 2016-05-27 11:52 UTC
Labels: bug, needs reproducing
