### ISSUE TITLE
Live Sync + window.location.reload throws unhandled exception

### ISSUE THREAD

**Issue by mrzor** [pouchdb/pouchdb#3847] opened 2015-05-15 19:42 UTC
Title should say it all.

I gisted a workaround (in coffee) : https://gist.github.com/mrzor/8d0d12be413e873682b8 
And there is a jsfiddle that reproduces the error : http://jsfiddle.net/mrzor/51ps6qza/2/

Catch it with your devtools / pause on exceptions.
No need to "pause on caught exception" as this one appears uncaught despite the fact that `.on('error', ...)` is set.

**Comment by nolanlawson** [comment] 2015-05-16 21:55
Hmm, since this isn't really something we can fix in PouchDB itself (I think it would be odd for a library to take it upon itself to add a global listener to `window`), maybe we should just document it in `errors.md` (common errors)? E.g. it seems this is enough to fix it:

```js
window.addEventListener("beforeunload", function(e) {
  sync.cancel()
});
```

**Comment by nolanlawson** [comment] 2015-05-16 21:55
Or maybe we should just add the global listener.

**Comment by mrzor** [comment] 2015-05-16 22:52
I cannot think of any downsides to PouchDB adding the global listener itself.

I can imagine other issues arising from this. They might also share the "non impactful" nature of this one - I believe that this issue is not data-threatening.

No further comment on this, the choice is mostly yours. I can submit a documentation PR if you'd rather go the other route. To add the event handler to window, you probably know best how to do that in a sane way.

**Comment by nolanlawson** [comment] 2015-05-16 23:08
Nah, I think you're right that it's best to attach it to the window.

**Comment by nolanlawson** [comment] 2015-05-17 16:43
So I actually cannot reproduce your error when I try to do it outside of jsfiddle.

To be honest I always discourage people from using jsbin/jsfiddle/whatever, because there is usually so much going on on the page that it distracts from the issue itself. E.g. your example doesn't work in Firefox, because jsfiddle doesn't support Firefox IndexedDB for some reason.

The one I prefer is bl.ocks.org, because it's just a normal HTML page, so I made one: http://bl.ocks.org/nolanlawson/raw/3171ab7eb855d00f4272/

**Comment by nolanlawson** [comment] 2015-05-17 16:59
@mrzor I created a pull request that you are free to try out. I have no idea if it will work or not, because I cannot reproduce: https://github.com/pouchdb/pouchdb/pull/3856

**Comment by daleharvey** [comment] 2015-09-08 11:19
I can reproduce, however ios/safari doesnt do page beforeunload and I think its best to avoid adding any code that runs beforeunload as its somewhat intrusive. If we were to do this I think it would likely be better do silently fail replication if we know beforeunload has fired than to actively kill it. (we could add a single event in prequest or something that just returns a 'browser reloaded' error or some such.

Its virtually impossible to test this though, and its not a bug that will cause problems to users, just possibly confusing.

**Comment by daleharvey** [comment] 2015-10-21 15:44
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/4442

**Closed by daleharvey** 2015-10-21 15:44 UTC
Labels: enhancement
