### ISSUE TITLE
DB Connection closed on Chrome: Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by srsgores** [pouchdb/pouchdb#3277] opened 2014-12-27 06:27 UTC
Using latest Chrome (``39.0.2171.95 m``), I get the following error when attempting to retrieve ``all_docs`` from a given database:

```
Error while processing route: admin.manage-posts.index Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
 at Error (native)
    at allDocsQuery (http://``localhost``:4200/assets/vendor.js:95274:27)
    at http://``localhost``:4200/assets/vendor.js:95392:7
    at countDocs (http://``localhost``:4200/assets/vendor.js:95362:14)
    at PouchDB.idb_allDocs [as _allDocs] (http://``localhost``:4200/assets/vendor.js:95381:5)
    at PouchDB.<anonymous> (http://``localhost``:4200/assets/vendor.js:93284:15)
    at PouchDB.<anonymous> (http://``localhost``:4200/assets/vendor.js:100661:21)
    at PouchDB.<anonymous> (http://``localhost``:4200/assets/vendor.js:101000:18)
    at http://``localhost``:4200/assets/vendor.js:100597:21
    at PouchDB.<anonymous> (http://``localhost``:4200/assets/vendor.js:100584:19)
```

The error occurs [here](https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/idb/idb.js#L414), in the file ``adapters/idb/idb.js``.

Even after clearing IndexDB, the error persists (even in latest Chrome canary).

However, on the latest FireFox, this error does not occur.

This is as per my discussion on IRC with @nolanlawson 

Using Windows 8.1 x64.

Thanks in advance for fixing

**Comment by nolanlawson** [comment] 2015-02-07 18:54
duplicate of https://github.com/pouchdb/pouchdb/issues/3415

**Closed by nolanlawson** 2015-02-07 18:54 UTC

**Comment by cdaringe** [comment] 2015-08-12 06:06
```js
z = new PouchDB('z');
z.destroy()
    .then(function() {
        return z.post({test: 'doc'});
    })
    .catch(function(err) {
        console.error(err.message); // Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    })
```

in my case, it was user error
