### ISSUE TITLE
Removing conflicting revision doesn't sync from local to remote

### ISSUE THREAD

**Issue by cschwarz** [pouchdb/pouchdb#3179] opened 2014-12-14 22:28 UTC
It works from remote to local.

I'm opening a PR with a failing test replicating the issue.

**Comment by cschwarz** [comment] 2015-01-07 20:58
I have updated pouchdb to 3.2.1 and still have the same problem, even though the test works fine now. I could not reproduce it in a unit test, but I have isolated the issue in a jsbin.

http://jsbin.com/fahigagumu/1/

Maybe it is also a mistake in the way I resolve the conflict.

**Comment by nolanlawson** [comment] 2015-02-07 20:23
OK, so it looks like we've finally found a bug due to our non-deterministic rev-generation. I have some tests that reproduce the error.

**Comment by nolanlawson** [comment] 2015-02-07 20:48
Actually, there are two issues at play here: 1) live sync, which is breaking where non-live sync succeeds, and 2) duplicate docs, which are hashed to the same rev in CouchDB but not PouchDB.

**Comment by nolanlawson** [comment] 2015-02-07 23:35
Found a fix.

**Comment by daleharvey** [comment] 2015-02-09 12:31
Fixed in https://github.com/pouchdb/pouchdb/commit/572539869b1595e579c53c71a7f55b0cfa27cdb2

**Closed by daleharvey** 2015-02-09 12:31 UTC
