### ISSUE TITLE
Error: Invalid Adapter in Chrome

### ISSUE THREAD

**Issue by cquillen2003** [pouchdb/pouchdb#5386] opened 2016-06-21 22:37 UTC
### Environment (Node.js/browser/hybrid app/etc.)

Browser

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome Version 51.0.2704.103 (64-bit)
Mac OS X El Capitan

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

Not specified, but Chrome is using WebSQL for some reason.

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Cloudant

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Calling PouchDB.sync(myDB, CloudantURL) is not causing checkpoint requests.  Subsequent query using pouchdb-find causes the following error:

Error: Invalid Adapter(…)

**Comment by tropperstyle** [comment] 2016-06-22 02:53
I have the same issue after upgrading to PouchDB latest.

`Unhandled rejection Error: Adapter is missing`

Here is my init:
```
new PouchDB('somedb', {
  auto_compaction: true,    // Only store latest records
  location: 2,       // Do not backup to iCloud
  adapter: 'websql' // Force adapter for SQLite plugin
});
```

I use cordova-sqlite-storage, and `sqlitePlugin` is globally defined. Downgrading to PouchDB 5.3.2 resolves the issue. I did not check other versions prior to 5.4.4 - so not sure when exactly it was introduced.

**Comment by nolanlawson** [comment] 2016-06-22 15:00
Sounds like these are two separate issues. @tropperstyle can you confirm that you're on 5.4.4? Also can either of you provide a test case? (E.g. a sample Cordova app or web page that reproduces the issue.)

**Comment by nolanlawson** [comment] 2016-06-22 15:12
Another helpful thing would be a full stacktrace, or at least a screenshot of one.

**Comment by cquillen2003** [comment] 2016-06-22 18:14
@nolanlawson Here's a sample Ionic 2 app that reproduces the 'Invalid Adapter' error:

https://github.com/cquillen2003/testPouch

No error in Firefox, only in Chrome.

**Comment by cquillen2003** [comment] 2016-06-22 18:24
I find strange behavior in the Ionic 2 sample app above:

The Create & Sync operation works correctly after trying once, then refreshing the page/app, the trying again.  The database is a WebSQL database, which is surprising in Chrome.

**Comment by nolanlawson** [comment] 2016-06-25 23:14
@cquillen2003 How do I run your code? Keep in mind I don't know Ionic 2 very well.

**Comment by nolanlawson** [comment] 2016-06-26 22:50
@cquillen2003 OK, I installed ionic beta CLI (`npm install -g ionic@beta`), did `ionic serve`, opened the app in Chrome 51, and clicked the "Create & Sync Pouch" button. However, everything seems to work fine and there's no error.

@tropperstyle You almost certainly have an unrelated issue, since your issue is with SQLite Plugin and @cquillen2003's is with Chrome. Do you have a test to reproduce?

**Comment by tropperstyle** [comment] 2016-06-26 23:13
I am away for the weekend, but I will put together a minimal case to reproduce and open a new issue when I get back. Thanks

**Comment by dharders** [comment] 2016-07-01 23:35
@tropperstyle Your issue is fixed now (Merged PR #5423, background #5417), just need to wait for next release...

**Comment by daleharvey** [comment] 2016-07-07 12:46
So we havent heard back about the original error and this issue is confused with the other thats being fixed, if you are still seeing having a problem, please reopen or open a new issue with steps for us to reproduce, thanks

**Closed by daleharvey** 2016-07-07 12:46 UTC
Labels: bug, has test case, needs reproducing

**Comment by chmelevskij** [comment] 2020-03-27 07:58
I know this is closed, but had similar issue when trying to use pouchDB in chrome extension. This happened because I was porting web page version to extension so was using something like this:
```javascript
var db = new PouchDB({
    name: window.location.origin + "userdb-some-id",
    auth: undefined
  });
```
To initialise the db. So, in the context of extenstion `window.location.origin` is `chrome-extension://somerandomgiberish`.

Don't know much about ionic, but my guess it is running in similar context, hence the `chrome-extension` bit. But if someone else stumbles on this just make sure you pass in the right url for remote db.
