### ISSUE TITLE
webkit, Failed to open indexDB

### ISSUE THREAD

**Issue by 7demo** [pouchdb/pouchdb#5448] opened 2016-07-07 09:18 UTC
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

My workmate had made a client app with ["CEF"](https://bitbucket.org/chromiumembedded/cef) . I got the version:

```--- 5.0(Windows NT 6.2; WOW64) AppleWebkit/537.36(KHTML, Like Gecko) Chrome/45.0.2454.101 Safari/537.36```

When i run the code:

```var room = new PouchDB('room');```

 I got : 

```{
    "__opts":{},
    "prefix":"_pouch_",
    "_events":{},
    "taskqueue":{
        "isReady":false,
        "failed":{
             "status":500,
             "name":"indexed_db_went_bad",
             "message":"unknown",
             "error":true,
             "reason":"Failed to open indexDB, are you in private browersing mode?"
              ........
         } 
    }
}```


Then i knew the doc:https://pouchdb.com/errors.html#throwing_invalidstateerror
Howerver , I think my bower is a webkit. Can give me some tips?

**Comment by nickcolley** [comment] 2016-07-07 09:20
Hey @7demo do you have an code example to reproduce this error?

**Comment by daleharvey** [comment] 2016-07-07 11:05
We have had bugs mentioning CEF before, I think if you are building a CEF app you need to do specific work to ensure indexeddb functions correctly and the error is pretty certainly indexeddb isnt properly functioning in the browserlike client, not to do with pouchdb itself so closing out, but if you have other questions or find there is something pouchdb could do to help here please feel free to say / reopen

**Closed by daleharvey** 2016-07-07 11:05 UTC

**Comment by 7demo** [comment] 2016-07-07 11:19
Now,  i put the project in the github. the url:[https://github.com/7demo/pouchdb-test](https://github.com/7demo/pouchdb-test)

 After download, this app must run in the windows pc. This app is a clent app by  C++ with cef. The html/js/css can run in it.  In fact , it read the 'main.html' after run the 'OnlineStuClient.exe'.  You can edit the code in the 'main.html', then you can see the change after click the text "重连" or  reopen 'OnlineStuClient.exe'

**Comment by nolanlawson** [comment] 2016-07-07 14:56
@7demo How do you run this project? Also yeah, most likely it's because IndexedDB is disabled in CEF. You might want to try Electron or Node.js instead.

**Comment by 7demo** [comment] 2016-07-08 02:22
Download the preject , click  'OnlineStuClient.exe'.  

I has tried Electron and nw.js .Saddly, i have to use CEF. I will try some other method.

Thanks.
