### ISSUE TITLE
Question: intercept AJAX requests globally

### ISSUE THREAD

**Issue by pavel** [pouchdb/pouchdb#5722] opened 2016-09-27 19:54 UTC
### Question
How to intercept AJAX requests made to a remove CouchDB instance by Pouch globally?
For example handle `401` response globally to redirect a user to a login page.
I tried to find this in docs with no luck.

### Info
- Environment: browser
- Platform: desktop
- Server: Remote CouchDB

**Comment by nolanlawson** [comment] 2016-09-29 13:04
This seems to be a duplicate of #5607 and/or #5322; please reopen if those issues don't address your concern.

**Closed by nolanlawson** 2016-09-29 13:04 UTC
