### ISSUE TITLE
revpos:undefined

### ISSUE THREAD

**Issue by ermouth** [pouchdb/pouchdb#3930] opened 2015-06-06 03:09 UTC
When saving attachments emitted in doc as base64, and then reading doc with `{attachments:true}`  revpos has `undefined` value.

Pouch 3.6.0, IDB, Chrome 43, Mac.

To mention – in Pouch 3.3.1 there is no revpos at all in this case, that effectively breaks replication.

**Comment by nolanlawson** [comment] 2015-06-06 13:55
We don't use revpos at all. I don't understand what the problem is here. Can you provide a live test case to reproduce?

**Comment by nolanlawson** [comment] 2015-06-06 13:58
This seems to be caused by `utils.pick` not checking if the source object has the key or not. This should be fixed in master. [3.6.0 version](https://github.com/pouchdb/pouchdb/blob/849fd7ae440824c46d3219c90dea4e49caf08693/lib/utils.js#L46-L54) and [master version](https://github.com/pouchdb/pouchdb/blob/39da6013d74685189fcdf5bc2c617db5b76e88bd/lib/utils.js#L46-L54)

**Comment by nolanlawson** [comment] 2015-06-06 13:59
Can you try http://pouchtest.com/nightly and see if that fixes your issue? If so, we can do a hot release.

**Comment by ermouth** [comment] 2015-06-06 14:24
> We don't use revpos at all

CouchDB use revpos – and send it. So anything you‘ve created/replicated to CouchDB has revpos. And I see `revpos` in all docs, that were synced from Couch.

**Comment by nolanlawson** [comment] 2015-06-06 14:28
Hm, maybe this is the key to the problem. Maybe we shouldnt' be storing revpos at all, since CouchDB is using it to avoid syncing attachments.

**Comment by ermouth** [comment] 2015-06-06 14:52
I do not know you should or you should not – it requires investigations. But I clearly know, that when we had revpos:0 – everything was just fine.

And if CouchDB uses it – and you use CouchDB sync protocol – you better use it also, or have some reasonable shim/placeholder.

**Comment by ermouth** [comment] 2015-06-06 15:26
Also take in account, that there can exist software, that somehow relies on presence of `revpos` – since it existed in previous versions.

**Comment by nolanlawson** [comment] 2015-06-06 15:58
Did you ever use the CouchDB replicator? Our own replicator ignores revpos, so I think this might only come up if you use CouchDB replication.

**Comment by ermouth** [comment] 2015-06-06 16:38
> Did you ever use the CouchDB replicator
On server? Yes, surely. I can‘t replicate between CouchDB instances without it.

**Closed** 2015-06-07 21:03 UTC

**Comment by jo** [comment] 2016-04-05 16:11
Just a note that `revpos:0` leads to problems whith cbl replicator: https://github.com/couchbase/couchbase-lite-ios/issues/1200

**Comment by jo** [comment] 2016-04-06 11:07
Relevant: https://github.com/pouchdb/pouchdb/issues/2709
