### ISSUE TITLE
Start seriously tracking performance

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2417] opened 2014-06-24 04:37 UTC
I see three problems with the way we're currently testing performance:

* We're not testing WebSQL performance in Travis (phantomjs)
* The Firefox tests are so slow that they time out before finishing the `temp-views` test, which is probably our most useful test since it's so slow and it tests multiple things at once (get/put/bulkDocs/allDocs)
* We're not looking at the performance delta when we :+1: a PR.

I have a lot of performance improvements waiting in the wings, but I'd like to be more diligent about measuring the performance gains or losses before we approve them.  Most of the time I'm just running the tests manually on my own machine, but what if I forget to clear out the browser cache between tests? There's probably other stuff that can go wrong too.

Also, in an ideal world we'd be testing Chrome and IE performance, but I don't know how reasonable it is to do that in saucelabs.

**Comment by daleharvey** [comment] 2015-10-06 21:33
Closing as dupe of https://github.com/pouchdb/pouchdb/issues/4152

**Closed by daleharvey** 2015-10-06 21:33 UTC
Labels: enhancement, tests
