### ISSUE TITLE
unknown_error: Database encountered an unknown error

### ISSUE THREAD

**Issue by ceremcem** [pouchdb/pouchdb#5414] opened 2016-06-29 19:01 UTC
### Environment (Node.js/browser/hybrid app/etc.)

This is a browser application 

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Linux/Iceweasel

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

adapter: idb

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Couchbase 

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I can't know what is happening, since the error message is not helpful.

**Comment by nolanlawson** [comment] 2016-06-30 00:33
Thanks for the issue, but this is probably not enough information to figure out what the problem is. E.g. which version of Iceweasel? What are you doing to cause the problem? What is the problem exactly? Do you have a stacktrace or screenshot?

**Comment by daleharvey** [comment] 2016-06-30 13:15
Usually error messages along arent helpful enough to diagnose the issue, its a matter of describing what you are doing to trigger the problem in a way that hopefully we can follow and get the same problem that helps find the root cause. Cheers

**Comment by daleharvey** [comment] 2016-07-08 15:19
So this is unactionable as it is, closing out, if you can give us any guidance on how to see the bug you are seeing please reopen with steps to reproduce, thanks

**Closed by daleharvey** 2016-07-08 15:19 UTC
Labels: bug, needs reproducing

**Comment by ceremcem** [comment] 2016-07-08 17:10
I don't use Elixir, but I like the idea: https://twitter.com/josevalim/status/621933537009246208

The error message doesn't even point that the error is related to my last actions on source code... Would you consider changing that line with an appropriate error message, so we can debug happily?
