### ISSUE TITLE
Sorting example from docs throws an error

### ISSUE THREAD

**Issue by lukechilds** [pouchdb/pouchdb#7206] opened 2018-04-03 01:21 UTC
### Issue
In [the docs](https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-find) it mentions that "sorted fields also have to be selected in the selector" and gives the example:

```js
db.find({
  selector: {
    debut: {'$exists': true}
  },
  sort: [{debut: 'desc'}]
});
```

However for me, using `{$exists: true}` results in `Error: Cannot sort on field(s) "date" when using the default index` however using `{$gt: true}` works.

Not sure if this is an error in the docs or the code, but either way, it's quite confusing.

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: IndexedDB
- Plugin: PouchDB Find

### Reproduce

```js
const db = new PouchDB('test-sort', {adapter: 'idb'});

await db.createIndex({index: {fields: ['date']}});

await db.post({date: Date.now()});
await db.post({date: Date.now()});
await db.post({date: Date.now()});

const result = await db.find({
	selector: {
		date: {$gt: true},
	},
	sort: [{date: 'asc'}],
});
// => {docs: Array(3)}

const result = await db.find({
	selector: {
		date: {$exists: true},
	},
	sort: [{date: 'asc'}],
});
// => Error: Cannot sort on field(s) "date" when using the default index
```

**Comment by garrensmith** [comment] 2018-05-31 08:05
This is confusing but correct behaviour. PouchDB-Find cannot use `exists: true` on an index. Rather use something like:

```
const result = await db.find({
	selector: {
		date: {$gt: null},
	},
	sort: [{date: 'asc'}],
});
```

This is something we can definitely improve in the future.

**Comment by lukechilds** [comment] 2018-05-31 08:30
That should probably be clarified in the docs here: https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-find#sorting

**Comment by iosfitness** [comment] 2018-05-31 12:52
@lukechilds  I'm doing the same. But it seems the sort doesn't work when we have a different type of records in alldocs.
For eg. In my case, I have a list of inspections, list of attachment, list of inspectable objects, etc

**Comment by garrensmith** [comment] 2018-05-31 13:50
@iosfitness can you give an example of your code

**Comment by daleharvey** [comment] 2018-06-30 21:39
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/6266, same issue

**Closed by daleharvey** 2018-06-30 21:39 UTC
Labels: pouchdb-find
