### ISSUE TITLE
404 on remote DB's URL parent breaks replication

### ISSUE THREAD

**Issue by nickcmaynard** [pouchdb/pouchdb#4036] opened 2015-07-08 10:25 UTC
In a change since 3.4.0, we're seeing some issues with replication.

* DB A at `http://host/context_root/db`.
* Replication from A to another DB.

When it starts the replication, PouchDB does an initial query against `http://host/context_root`.  If this 404s, the replication stops/fails.  In our app, our reverse-proxy setup doesn't forward the base `context_root`, so we see a 404.

In 3.4.0, this wasn't a problem - the DB replication carried on (and worked).

**Comment by daleharvey** [comment] 2015-07-11 15:53
Hrm yup we should fall back from this without problem

**Comment by daleharvey** [comment] 2015-08-04 19:59
Closing as dupe of https://github.com/pouchdb/pouchdb/issues/4094

**Closed by daleharvey** 2015-08-04 19:59 UTC
