### ISSUE TITLE
Cannot handle 401 error with sync gateway 1.2.1 and pouchdb ( rev. ef1db28 ) using sync method

### ISSUE THREAD

**Issue by agsv83** [pouchdb/pouchdb#5966] opened 2016-11-30 12:07 UTC
First of all, this is a duplicate of https://github.com/pouchdb/pouchdb/issues/5607

I have commented the issue and a workaround here: https://github.com/pouchdb/pouchdb/issues/5607

I dont know if your where aware of those comments.

### Issue
It is not possible to catch the 401 error using sync and the sync_gateway.

### Info
- Environment: browser + pouchdb ( rev. https://github.com/pouchdb/pouchdb/commit/ef1db281fdea6524aa85f1cefa1550efa8d9e3c3  )
- Platform: Chrome
- Adapter: the default pouchdb uses
- Server: CouchDB + Sync gateway 1.2.1

### Reproduce
- Create a user session on the gateway
- Use the cookie on the browser and start using pouchdb with the gateway
- Destroy that user session with the gateway rest api
- Pouch sync method fails catching the 401 error

**Comment by nolanlawson** [comment] 2016-12-02 10:13
Closing as a duplicate of https://github.com/pouchdb/pouchdb/issues/5607#issuecomment-263229959, thank you for the additional information though

**Closed by nolanlawson** 2016-12-02 10:13 UTC
