### ISSUE TITLE
PouchDB.plugin() resets defaults

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#6053] opened 2016-12-22 06:51 UTC
### Issue

I would expect `PouchDB.plugin()` to return the original constructor including defaults, but it removes the defaults from the constructor

### Reproduce

```js
var MyPouch = PouchDB.defaults({foo: 'bar'})
var MyPouch2 = MyPouch.plugin({foo: function () {}})
MyPouch.__defaults
// {foo: "bar"}
MyPouch2.__defaults
// undefined
```

I know that setting `MyPouch2` makes no difference here, but it’s still an unexpected behavior

**Comment by kartikagarwal1993** [comment] 2017-01-19 18:09
Going through the code I found this comment.
https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/setup.js#L86. 
Which indicates that the issue is related to Issue #5922 . Are these two issues same?

**Comment by nolanlawson** [comment] 2017-01-20 02:08
They're related but not exactly the same. The bug here is that `MyPouch` and `MyPouch2` should be exactly the same objects with exactly the same `__defaults`. I'm not sure why it changes...

**Comment by kartikagarwal1993** [comment] 2017-01-26 09:54
Hey, In the PouchDB.defaults function on the following code https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/setup.js#L55.

I added following lines before `return PouchDB`
```
if(this.__defaults){
    PouchDB.__defaults = assign({}, this.__defaults);
}

```

The function now looks like 
```
PouchDB.plugin = function (obj) {
  if (typeof obj === 'function') { // function style for plugins
    obj(PouchDB);
  } else if (typeof obj !== 'object' || Object.keys(obj).length === 0){
    throw new Error('Invalid plugin: got \"' + obj + '\", expected an object or a function');
  } else {
    Object.keys(obj).forEach(function (id) { // object style for plugins
      PouchDB.prototype[id] = obj[id];
    });
  }
  if(this.__defaults){
    PouchDB.__defaults = assign({}, this.__defaults);
  }
  return PouchDB;
};
```

Is this a reasonable way to solve the following bug?

**Comment by nolanlawson** [comment] 2017-01-27 17:36
It seems like it may solve it? I'm not sure; you'd need to write a test case and then see if it fails before the fix but succeeds after. :)

My workflow for this feature would be:

1. Write a test case in `test.basics.js`, ensure it fails
2. Write the fix
3. Re-run the test, ensure it passes

You can run particular tests by doing e.g. `GREP=name-of-test npm test`. Let me know if that helps!

**Comment by kartikagarwal1993** [comment] 2017-01-27 17:56
Yes, that helps. Now I know that its the right direction to move towards. Will update you further after the test cases are done. Thanks!

**Comment by nolanlawson** [comment] 2017-02-05 23:57
fixed in https://github.com/pouchdb/pouchdb/pull/6196

**Closed by nolanlawson** 2017-02-05 23:57 UTC
Labels: bug, has test case, help wanted
