### ISSUE TITLE
PouchDB Crashes on iOS after several memory warnings.

### ISSUE THREAD

**Issue by thedracle** [pouchdb/pouchdb#4632] opened 2015-12-03 22:45 UTC
Doing a large sync, of maybe 12k documents, causes increasing memory usage which never seems to be cleaned up.

Prior to a sync, there will be ~200MB used, and this will increase to ~450MB. After Pouch stops, it never seems to reclaim this memory, and often during a sync iOS will stop the application.

**Comment by thedracle** [comment] 2015-12-04 23:29
There seems to be a memory leak with Pouch. After syncing a large database, the memory profile gradually climbs, and never seems to reduce.

Subsequent syncs of other collections will eventually crash the application.

We have tried websql as a driver, sqlite, and this behavior seems entirely independent of the driver we are using.

**Comment by thedracle** [comment] 2015-12-05 00:51
Platform Details:
iOS 9.1
UIWebView

Here is a screenshot of the memory leak issue:
![leakscreenshot](https://cloud.githubusercontent.com/assets/1301817/11604853/62aceb60-9aaf-11e5-952c-d476a9d5a2a7.png)

This is produced by replicating a database, and after it finishes, all of the memory it allocated seems to be indefinitely retained.

**Comment by nolanlawson** [comment] 2015-12-05 21:44
Can you reproduce this with the FruitDOWN adapter? It would be nice to figure out if this is a bug in the `websql` adapter (used by both WebSQL and SQLite Plugin) or in PouchDB itself. Also do you see it on any other browsers/platforms?

**Comment by thedracle** [comment] 2015-12-05 23:45
As far as I am aware, the FruitDown adapter will not work on UIWebView because it doesn't support IndexDB. We can use WKWebView, but it has the issue that if a location.reload() occurs, all of the permanent storage (LocalStorage/IndexDB/WebSQL) seems to get temporarily wiped until the Application is restarted.

I can test it against WKWebView though with FruitDown to determine if it's an issue with the websql adapter specifically.

**Comment by thedracle** [comment] 2015-12-06 19:21
I noticed you commented on https://github.com/axemclion/IndexedDBShim. 

Is it possible to use this with UIWebView + FruitDown in a stable way? It looks like there is an issue setting to window.indexDB, but I could work around that with the driver itself.

In the meantime I will try to figure out if the websql adapter in particular is the source of the issue (I suppose because this is the common link between using sqlite and websql directly), via WKWebView.

**Comment by thedracle** [comment] 2015-12-07 22:02
Using the IndexDB shim + Fruitdown has a similar result, only since it is much much slower, it happens over a very long duration of time.

<img width="770" alt="screen shot 2015-12-07 at 3 01 32 pm" src="https://cloud.githubusercontent.com/assets/1301817/11641083/7af13230-9cf3-11e5-8a67-c1b1cbedbfcc.png">

**Comment by robwithhair** [comment] 2016-01-15 00:30
I'm experiencing this same bug on iOS during replication of large data from device to server.  Using pouch with sqlite plugin.

**Comment by nolanlawson** [comment] 2016-01-15 01:49
If it happens with both FruitDOWN, the SQLite Plugin, and WebSQL, then it seems like a bug in PouchDB. Probably we have a memory leak somewhere, which presumably should also occur in other browsers if it occurs with all these adapters.

**Comment by mnewmedia** [comment] 2016-03-07 16:25
I don't understand this stuff but defintily something wrong here.
Sometimes i clicked on collect garbage, then it whent a bit down.

<img width="1757" alt="bildschirmfoto 2016-03-07 um 16 43 25" src="https://cloud.githubusercontent.com/assets/2413156/13574340/f8b9a404-e483-11e5-8395-6c3f545c30f0.png">

**Comment by robwithhair** [comment] 2016-04-07 15:07
Any news on this issue?  We've got guys in production using pouch in the field and they're effectively unable to work at the moment.  I'm sanity checking all my code and I'm sure I'm doing everything correctly.

**Comment by nolanlawson** [comment] 2016-04-07 15:41
@robwithhair Are you using the SQLite Plugin or the normal app? And is this only on iOS?

I admit I've been trying to solve SQLite Plugin problems recently, and haven't been attacking this particular issue per se.

**Comment by robwithhair** [comment] 2016-04-07 15:43
Hi @nolanlawson I'm using the SQLite Plugin as our DB is fairly large.  I've only seen the bug in iOS but it may exist elsewhere.  thedracle above was using IndexDB shim + Fruitdown however from his above posts.

**Comment by robwithhair** [comment] 2016-04-07 16:00
Doesn't seem to be to do with event listeners, because I just removed them and I am still experiencing the issue using.

```
var options = {                                                                                                                                                                                                                                                                                                                                              
      batch_size: 1,                                                                                                                                                                                                                                                                                                                                           
      batches_limit: 1,                                                                                                                                                                                                                                                                                                                                        
      timeout: 60000 * 10                                                                                                                                                                                                                                                                                                                                      
};                                                                                                                                                                                                                                                                                                                                                           
global.currentReplication = db.sync(databaseUrl, options);
```

`currentReplication.cancel()` stops the increase in memory usage but doesn't clear the memory.  Neither does `currentReplication.removeAllListeners()` or `delete currentReplication`.

**Comment by thedracle** [comment] 2016-04-07 16:02
We tested with IndexDB + Fruitdown, and with the SQLlite driver, with both UIWebView and WKWebview.

All had similar memory leak results. We eventually had to abandon ship with PouchDB and move to EJDBKit with a Cordova Wrapper.

It is working very efficiently and fast without any memory issues.

I think it would make a good backend for PouchDB on iOS.

**Comment by robwithhair** [comment] 2016-04-07 16:10
@thedracle ok, I'm panicking now!  I hope there's a solution cos we've got all these guys in the field with data on devices they can't sync up. 

The weird thing is that when I hit the refresh button in safari inspector for iOS 
![image](https://cloud.githubusercontent.com/assets/6692245/14358100/7ca4ced4-fce3-11e5-9980-a8d7e0d6ac16.png)
it doesn't free the memory either!  That would suggest to me that it is either safari caching, or the objective C cordova side which is filling up the ram.

**Comment by robwithhair** [comment] 2016-04-07 16:19
@nolanlawson, I was using your project https://github.com/nolanlawson/sqlite-plugin-fork in order to get larger capacity on iOS.  I see you've got a project https://github.com/nolanlawson/sqlite-plugin-2, could this be a replacement?  How is progress going with this project?

**Comment by thedracle** [comment] 2016-04-07 16:27
So, all signs seemed to point to the core of PouchDB since the behavior remained the same regardless of which driver we used.

One workaround/hack that seemed to work better with SQLLite was to basically generate a PouchDB file by syncing the database until it finished without crashing, download that file off the device, and publish it out to S3 zipped, and then use simple HTTP/GET to pull it down, and dump it onto the local device.

Subsequent syncs will be much smaller- and it seemed to mostly work (with sometimes intermittent crashes related to another bug.)

**Comment by nolanlawson** [comment] 2016-05-20 00:08
I believe this issue still needs a reproducible test case, if anyone can please provide it.

@robwithhair that project is done now: https://github.com/nolanlawson/cordova-plugin-sqlite-2

**Comment by mnewmedia** [comment] 2016-06-04 13:03
cordova-plugin-sqlite-2 makes all faster but memory problems are still here. Once i found out my Database had a fragmention of 97% and i runned a compaction on the server the memory did go from 500 to 120. So I believe it's something with the revisions. 

@nolanlawson you need a github project for reproducing? I already have an old one just need to update everything. Will come back when i did it.

**Comment by nolanlawson** [comment] 2016-06-12 15:59
Anything to reproduce would be helpful, yeah. I've marked this as "needs reproducing."

**Comment by olexme** [comment] 2016-06-24 11:46
We observe memory leaks during the sync process as well, however it is the most visible when the documents have any bigger inline attachment included. I’ve just prepared very simple cordova app with PouchDB lib only which shows the issue. The project uses cordova-plugin-sqlite-2 but without it the leaks were also observed. 
Here is the cordova project  https://github.com/olexme/pouchdb-cordova, and here the required backend server https://github.com/olexme/pouchdb-server. @nolanlawson I hope you will be able to reproduce the issue. For now i focused on iOS (v.9.3.2 on iPhone 6). See README for steps.

**Comment by nolanlawson** [comment] 2016-06-24 15:03
I'll try to look at it when I get a chance. Thank you for the test case!

**Comment by nolanlawson** [comment] 2016-06-26 02:29
Thanks for the test; looks like I should have a fix assuming this passes our test suite ^.

**Comment by daleharvey** [comment] 2016-06-27 08:49
Fixed in https://github.com/pouchdb/pouchdb/commit/52201f1307f8ab116fd04cabff01686ab2a060c5

**Comment by olexme** [comment] 2016-06-27 11:49
I’ve just tested the build based the master branch and can say that the fix improved the sync operation a lot but isn’t perfect. Earlier I couldn’t sync 20 the same exemplary docs with one attachment = 1,6MB. Right now I’m able to sync up to 348 docs before the app crashes so the progress is big. Anyway we can still observe huge memory peaks when the batch contains more docs so I had to limit batch_size to 4, and with batches_limit=1 I was able to sync 348 docs before memory usage reached 500MB on iPhone 6 which means the app crash. Here is how memory grew during that sync process.
![memory_growth](https://cloud.githubusercontent.com/assets/5081537/16378716/b20756f4-3c6d-11e6-8bbe-d36bd76b6edf.png)

**Comment by olexme** [comment] 2016-06-27 12:09
Regardless of the fix I’m wondering, if it is possible to set the batch_limit for the specific type of documents only or for attachments only. This is because setting batch_limit allows to avoid memory peaks which can crash the app but overall slows down the sync significantly. We don’t have all type of docs with attachments so being able to put limits only for specific type of docs could be helpful.
Thanks in advance for help.

**Comment by nolanlawson** [comment] 2016-06-27 14:52
@olexme Could you please open up a new issue with this data? We can always try to improve memory usage, but this thread is very long already and so it's easy to lose track.

Keep in mind, though, that in your example you have a 500kB picture of a cat, so if you are doing `bulkDocs()` with that cat 20 times, that's going to create a lot of memory pressure no matter what. We can try to limit memory usage, but asking the user to batch their documents based on expected size is not unreasonable here.

As for batching on attachment-ful documents vs attachment-less documents, it's not something we're curruently planning.

**Comment by mnewmedia** [comment] 2016-08-20 09:02
This issue never got really solved for me using ionic 1 / cordova. The memory did grow ever while syncing. But now ionic released a new version of [wkwebview](https://github.com/driftyco/cordova-plugin-wkwebview-engine) which resolved the memory leak for me. I thought that will never be possible but yeah! finnaly!  Wooooh! If you guys wanna try it you also must use this [pouchdb-adapter-sqlite](https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite).

But the replication in the new `wkwebview` was about 25% slower.

Just wanted to notify others having the same issue.

**Comment by CatchSandeepVaid** [comment] 2016-09-01 10:23
Hi mnewmedia,
Can you please describe your usecase (how many docs to sync, their size etc., ios version etc.) where you were facing memory leaks before and it got solved using ionic wkwebview and pouchdb-adapter-sqlite as for my usecase it still didnt worked.

I used ionic wkwebview with pouchdb-adapter-sqlite and tried to sync (few videos each of 30 mb each). I saw memory leak (on wkwebview- i think it memory increase shows in "Other processes" instead of showing that under my process). It gave me a memory warning in xcode's console. 

Moreover i think there are many other issues in wkwebview and my app doesnt work on it properly.  
In my app, i have few videos (each of size 30mb) stored in pouchdb (on ipad) and i sync them with my couchdb server when internet connection is available but during this sync memory leaks.

Moreover ionic team said their wkwebview plugin is in beta and not ready for production use.

**Comment by mnewmedia** [comment] 2016-09-01 10:57
I use it like:
- no attachments (no videos, no images)
- size of single doc 20-100kb
- 10'444 docs -> almost all are rev 8-12
- db size showing in fauxton 5.6mb
- ioinc, cordova
- IOS 9.3.x  on iPad
- Sync duration around 100 seconds in uiwebview

I'm unshure but AFAIK there is IOS10 comming with new indexeddb stuff, maybe this will resolve our issues.

**Comment by CatchSandeepVaid** [comment] 2016-09-07 07:26
@nolanlawson - As @olexme said, the memory leak is still there. I am facing the same issue. As suggested by you, i have also opened a new issue regarding this. [](https://github.com/pouchdb/pouchdb/issues/5646).  Can you please help us resolving this issue.

**Comment by mnewmedia** [comment] 2016-12-15 18:54
Hi all ios-ler although this is closed, it's still a problem for many of us. Even with wkwebview and without attachments, if the device has not enough memory it still crashes. Just wanted to notify you that I found a cordova plugin for couchdb from cloudant. I didn't test it, but it sounds promising have a look [here](https://github.com/cloudant/sync-cordova-plugin).

The saddest part of it is, that it's not anymore pouchdb, and I really really liked pouchdb ;)

**Comment by nolanlawson** [comment] 2016-12-15 18:58
Is there still a repro for this? And I understand you're frustrated but PouchDB is maintained by volunteers so we're all just trying to do what we can. Simple repros help a lot.

**Comment by mnewmedia** [comment] 2016-12-15 19:05
omg, you misunderstood me, is my english so bad? haha. I'm not frustrated, It's just it still crashes. And I meant I'm really am sad to move a bit away from pouchdb ;) I really love you all and it's incredible what you all are doing.

I don't have a repro right now, but theres also nothing big needed to repro, just create a big db and start replication and it will crash on devices with not enough memory in UIWebView. In WKWebview I'm unshure what is causing it because Xcode shows only about 50mb RAM used, whats not much at all but still memory warning will appear in console and it will crash.

**Comment by nolanlawson** [comment] 2016-12-15 19:07
> theres also nothing big needed

What seems simple for a PouchDB user to reproduce may take several hours or days for a PouchDB contributor to reproduce. :)

Honestly I have dozens of open-source projects with hundreds of people asking me for help. If I can just `git clone path-to-repo && npm install && cordova run ios` to reproduce then that makes it much more likely that I'll have time to look into it and be able to solve it.

**Comment by mnewmedia** [comment] 2016-12-15 19:10
I will update an old one give me some time.

**Comment by mnewmedia** [comment] 2016-12-20 12:42
Ok i found out it's because of documents which went too big (7000 lines long), but anyway the memory grows as you sync. Even I would remove the big docs and add instead thousand of small ones.
[repro](https://github.com/mnewmedia/testApp)

PouchDB really improved the memory growing in recent versions! But it's still a bit there, maybe it's also not your fault and a leak in apple stuff?

Whatever I will ever love you, the pouchdb team, and pouchdb itself 😛.

**Comment by samhibberd** [comment] 2017-09-07 19:42
Hi all, we are currently running into these issues on a live app, as our dataset has grown the more the impact. Utilising WKWebview helped but we are still seeing hugh memory usage. 

Can anyone suggest any sources that might help? 

If not I think it would it be best to open a new issue? 

Many thanks.

**Closed** 2017-12-06 15:33 UTC
Labels: bug, has test case, wontfix

**Comment by zspitzer** [comment] 2019-02-07 14:27
if PouchDB is using openCursor with indexedDB, it will leak memory on Webkit/Safari/iOS

the workaround is to use getAll instead

https://bugs.webkit.org/show_bug.cgi?id=193504
