### ISSUE TITLE
PouchDB problem in integration tests with Jasmine

### ISSUE THREAD

**Issue by Sturgelose** [pouchdb/pouchdb#4657] opened 2015-12-15 00:22 UTC
Hi,

I have been working during the last 2 weeks non stop to find a way to do integration tests of my service and PouchDB (5.1 and 5.0). At the moment I have properly working code which runs and has all error handlings ready for production. However, I want to create some tests in order to make sure that everything keeps allright in the future.

My project is an AngularJS project.
I've set up Karma/Jasmine + PhantomJS/Chrome (I've been using this two browsers to debug the problem).
In order to make everything properly, I added as well the es5-shim package and the blob-shim. Mostly I based all my work in the tests I found in [angular-pouchdb](https://github.com/angular-pouchdb/angular-pouchdb/blob/master/test/api.js) repository. Using them it works properly fine. 

However now it starts the tricky part: if I create a new service, which uses promises (I'm fetching info from $http and pushing it using promises to pouchdb), if I run the service manually, directly in the browser, it works fine. However, running it through the tests it always gets stuck. I have exactly the same problem described in this stackoverflow post: http://stackoverflow.com/questions/26328200/how-do-i-resolve-a-q-when-promise-in-unit-tests

So in sum, I have an structure like this:

$http (is used by) -> MyServiceUnderTest (saves info into)-> angular-pouchdb -> PouchDB

So the code is something as simple (I'm writing it a bit fast as I'm doing some abstraction. If needed I can write the whole proper code or upload it to a repository). And it works perfectly when ran in the browser!!!

```
$http.get(url)
.then(function(response) {
    return $q.when(pouchDB.post(response.data)); // I don't use the when but is already implemented by angular-pouchdb, so I add it here for explanation
})
.finally(done);
```
However, this gets stuck in testing.I'm using `done` (async support) from jasmine to make sure that the test waits until the end of the asyncalls and it doesn't stop before.

I've tried using $q.when wrapping the PouchDB promises and also using angular-pouchdb in order to use something from the community and more tested. However, after several days of debugging I kinda figured out the root of the problem.

Seems that there is some kind of misssynchronization between the ticks in angular's $q and PouchDB's lie (or at least this is what I've been able to deduce, as I'm not an expert in Angular, but I've become more wise in this after 2 weeks of research nonstop). The only way I found it to call $rootScope.digest() or $rootScope.apply().
However, seems that one call does nothing and I have to call it several times in order to make PouchDB keep on processing. So the only way I found to fix this (which looks awful and works whenever it wants) is to first flush the httpBackend `$httpBackend.flush()` and then call repeatedly non stop every 30 ms `$rootScope.apply()`, which somehow makes the async engine of PouchDB to keep on moving.

```
      refreshIntervalId = setInterval(function() {
        $rootscope.$apply();
      }, 30);
```

However, this makes all the test to run really slow and even timeout (it takes like 20 seconds somehow...). Also it gets more complicated as in the real code, the logic is more complicated and I have to flusch http in the middle and.. well, that this is hell.

Is there any advice or way on how to fix this? Seriously, I have only found messages of people with the same problem and they couldn't come up with the solution for this.
Also, making a mockup of the pouchDB module, it's a bit out of hands. I can't (and I don't wanna if possible) to have to write so many answers and behaviours to replicate what PouchDB does.

Thanks a lot in advance! And, well, sorry for the long post!

**Comment by mlegenhausen** [comment] 2015-12-15 16:33
The problem is the switch between native promises and what angular is doing. I had the same problem the last day and tried the same approach but it seems not practical.

I would not recommend to use pouch directly. The angular way would be to mock pouchdb away and run your code in a synchronous way by calling `$rootScope.$apply`.

Your example would look like this:

```js
beforeEach(module(function ($provide) {
  $provide.value('pouchDB', jasmine.createSpyObj('pouchDB', ['post']));
});

beforeEach(inject(function ($injector) {
  pouchDB = $injector.get('pouchDB');
 // TODO: Configure your $httpBackend
});

it('should run', function () {
  pouchDB.post.and.returnValue($q.when(someData));

  $http.get(url).then(function (response) {
    return pouchDB.post(response.data);
  });

  $httpBackend.flush();
  $rootScope.$apply();

  expect(pouchDB.post).toHaveBeenCalled();
});

```

This code seems async, but is converted in synchronize code by `angular-mock`.

**Comment by Sturgelose** [comment] 2015-12-15 19:45
@mlegenhausen , thanks a lot! I've been trying this. The idea looks nice, but I have a problem, and it's that, this same service starts the database, and calls pouchDB().
Also, this service does put and find (from pouchdb-find repo), which I can replace with the jasmine spy, but it's with different variables each time, and it should give different results... I found out I can try with `.and.callFake(fn)` method from jasmine, but well, seems I'll have lot of handmade things to write in order to cover all the different possibilities.

I was thinking if was possible to replace lie, the async scheduler from PouchDB for $q, so this way PouchDB would be running in exactly the same system. Got some hints from this piece of code I found:
```
beforeEach(function () {
    module('Module', function ($provide) {
        $provide.value('$q', Q); 
    });
});
```
I'd write `lie` instead of `$q` and `$q` instead of `Q`. However, haven't found out how to load $q before this so I can set is as an input....

**Comment by Sturgelose** [comment] 2015-12-15 19:50
By the way, the actual code I have is:
**SectionServ test**
```
'use strict';

describe('module: main, service: Section', function () {

  // load the service's module
  beforeEach(module('main'));
  // load all the templates to prevent unexpected $http requests from ui-router
  beforeEach(module('ngHtml2Js'));

  beforeEach(module(function ($provide) {
    $provide.value('pouchDB', jasmine.createSpyObj('pouchDB', ['post']));
  }));

  var pouchDB;
  var sectionJson;
  var $httpBackend;
  var $rootScope;
  var Section;
  var Config;
  var $q;
  beforeEach(inject(function ($injector) {
    pouchDB = $injector.get('pouchDB');
    pouchDB.post.and.returnValue($q.when('somedata'));
    $httpBackend = $injector.get('$httpBackend');
    $rootScope = $injector.get('$rootScope');
    Section = $injector.get('Section');
    Config = $injector.get('Config');
    $q = $injector.get('$q');

    // Load fixtures
    fixture.setBase('test/karma/fixtures');
    sectionJson = fixture.load('json/section-list.json');

    $httpBackend
      .expectGET(Config.ENV.CALLHOME_SECTION_URL).respond(200, sectionJson);
  }));

  describe('.getSection', function () {

    it('should fetch all sections', function (done) {

      pouchDB.post.and.returnValue($q.when('123'));
      var sectionA = sectionJson[0];

      Section.getSection('SectionA')
        .then(function (answerSection) {
          // Check the expects here....

          // End the test
          done();
        });

      $httpBackend.flush();
    });

  });

});

```

And Section uses pouchDB and does some puts and finds in order to check if I need to update the database depending on the info I get from the http request. So in sum, I'm just caching data offline inside pouchDB

**Comment by mlegenhausen** [comment] 2015-12-15 20:05
If possible I would test with the real pouchdb too, to get original results from pouchdb. I will try out the `Q` approach tomorrow maybe I can find out something how to get this working.

**Comment by nolanlawson** [comment] 2015-12-15 20:13
> The problem is the switch between native promises and what angular is doing.

So in that case, shouldn't `$q.when()` work fine? It takes PouchDB's promises as input and outputs Angualr-style `$q` promises, so it should play nice with Angular.

FWIW, I have many many repos where I test PouchDB using Mocha (using the built-in promise support), and I've never needed to do any fancy conversion of promises.

My guess is that the underlying issue has something to do with mocking `$http` (which automatically does the rootScope.apply and stuff) vs not mocking PouchDB. Can't you do something like this?

```js
it('should do a thing', function (done) {
  db.post({}).then(function () {
    $rootScope.$apply();
    // put your assertions in here
  }).finally(done);
});
```

?

If that doesn't work, then I recommend eliminating PouchDB from your tests until you have established a working system for testing asynchronous promises. For instance, you could do something very simple like:

```js
it('should do a thing', function (done) {
  $q.when(new Promise(function (resolve) {
    setTimeout(resolve, 5000);
  })).then(function () {
    // do some assertions...
    return new Promise(function (resolve) {
      setTimeout(resolve, 5000);
    });
  }).then(function () {
    // do some more...
  }).finally(done);
});
```

**Comment by Sturgelose** [comment] 2015-12-15 20:29
@nolanlawson, what I found out is that if I don't merge two kind of promises of PouchDB and $q (- I don't return a $q.when enclosed pouchdb to $q -), even if I have an $http request or anything else, this works.

The problem comes when I have a `return $q.when(PouchDB Promise)` that returns to a $q promise processor.

And yes, $q.when works prefectly fine running the app as usual. However running it as a test using Jasmine just gets stuck...

I'll try to see if I can set up my environment with Mocha, maybe it's only something problematic with Jasmine...

> My guess is that the underlying issue has something to do with mocking $http (which automatically does the rootScope.apply and stuff) vs not mocking PouchDB. 

Not here: I'm using angular-pouchdb and it should also apply the rootScope.apply automatically.... (at least according to the documentation)

**Comment by mlegenhausen** [comment] 2015-12-15 20:33
@nolanlawson I tryed your example in my jasmine test setup. It never finishes. Do you included angular-mocks?

**Comment by Sturgelose** [comment] 2015-12-15 20:42
I have added: 
1. All my bower files:
```
{
  "dependencies": {
    "ionic": "~1.1.0",
    "angular": "~1.4.5",
    "angular-animate": "~1.4.5",
    "angular-sanitize": "~1.4.5",
    "angular-ui-router": "~0.2.15",
    "ngCordova": "~0.1.17-alpha",
    "angular-dynamic-locale": "~0.1.27",
    "angular-translate": "~2.8.1",
    "angular-translate-loader-static-files": "~2.8.1",
    "angular-localForage": "~1.2.3",
    "angular-pouchdb": "~4.0.0",
    "pouchdb-find": "~0.8.0"
  },
  "devDependencies": {
    "angular-mocks": "~1.4.5"
```
2. and all this:
```
files: bowerFiles.concat([
      // shims for PouchDB testing
      'node_modules/tlvince-blob-shim/Blob.js',
      // other
      'app/!(bower_components)/**/*.js',
      // test
      'test/karma/**/*.js',
      {
        pattern: 'test/karma/fixtures/**/*'
      },
      // templates
      'app/**/templates/*.html'
    ]),
```

I'm using https://github.com/mwaylabs/generator-m-ionic for scaffolding and it automatizes to include all the bower libraries I have.

**Comment by mlegenhausen** [comment] 2015-12-15 20:51
OK I tested a little bit the problem is definitely angular. The problem seems to be that every resolved promise is tight to angulars digest cycle. So the example from @nolanlawson needs round about 3 perfect timed digest cycles. That why it is working with some interval digests. It simply resolves the promise chain step by step.

The adjusted test could look lile:

```js
const intervalId = setInterval($rootScope.$digest, 1);

$q.when(new Promise(function (resolve) {
	console.log('1');
	setTimeout(resolve, 0);
}))
.then(function () {
	console.log('2')
// do some assertions...
	return new Promise(function (resolve) {
		console.log('3')
		setTimeout(resolve, 0);
	});
})
.then(function () {
	console.log('4')
	// do some more...
}).finally(() => {
	clearTimeout(intervalId);
	done();
});
```

**Comment by Sturgelose** [comment] 2015-12-15 20:57
@mlegenhausen , if you check in my first post, my way was to setup a refresh every 30ms. Every time it goes inside I have 3 async in the list of the scope (I'm debugging with WebStorm). And well, if you count I'm doing like 4 gets and 4 posts, if you want to make this calls precise enough, it's a total mess...

``` javascript
refreshIntervalId = setInterval(function() {
        $rootscope.$apply();
      }, 30);
```

**Comment by Sturgelose** [comment] 2015-12-16 11:34
Hey, some update here. I tried with Mocha+Chai, and I see the same issue...
I uploaded my code up to here: https://github.com/Sturgelose/angularjs-testingwithpouch
(develop branch is jasmine, and there is another one with mocha)
You can run the tests with `gulp karma` and it's ready for WebStorm.

I know that maybe the code is not the best as I'm still learning, but it works fine if ran without tests...

**Comment by mlegenhausen** [comment] 2015-12-18 13:35
Maybe this ticket is interesting: https://github.com/angular/angular.js/issues/12533#issuecomment-129262925
Cause when we are able to replace `$q`, `$timeout` and `$interval` with the native browser implementations from angular we can go on and use the async jasmine unit testing.

**Comment by nolanlawson** [comment] 2015-12-19 18:03
> OK I tested a little bit the problem is definitely angular.

I see that in your test there is no reference to PouchDB (only Promises), and you are still able to reproduce the error. So I can assume that the issue is indeed Angular. I'll close this issue unless you still think there's something PouchDB should do here.

**Closed by nolanlawson** 2015-12-19 18:03 UTC

**Comment by Sturgelose** [comment] 2015-12-20 11:07
@nolanlawson, just in case, the reference to PouchDB is in DBManager service in app/main/services.
