### ISSUE TITLE
putAttachment fails for authenticated HTTP requests

### ISSUE THREAD

**Issue by MattCollins84** [pouchdb/pouchdb#6132] opened 2017-01-11 13:46 UTC
### Issue
When calling putAttachment to write to a remote HTTP CouchDB/Cloudant database that requires authentication, the request fails with a 403 Not Authorized despite the correct credentials being provided.

I have traced this to the authentication information not being passed in the headers when making the request.

### Info
- Environment: Node.js
- Platform: OS X
- Adapter: HTTP
- Server: CouchDB & Cloudant

### Reproduce
Here is the code I used to reproduce the issue:

````js
var PouchDB = require('pouchdb');
PouchDB.debug.enable("*");

var remote = new PouchDB('http://admin:admin@localhost:5984/att');

var ATT_TXT = new Buffer('abc').toString('base64');

remote.putAttachment('mydoc', 'att.txt', ATT_TXT, 'text/plain')
.then(function(data) {
  console.log('success', data)
}).catch(function(e) {
  console.log('error', e);
});
````

This works on 6.1.0 but fails on 6.1.1

**Comment by willholley** [comment] 2017-01-20 19:13
This looks to be caused by b325846d (#6012). This change means that user-provided headers [overwrite](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L171) the defaults instead of being merged with them. This will show up anywhere we explicitly provide a `headers` field in ajax options - `putAttachments` is one instance of this.

**Closed** 2017-01-21 18:35 UTC
Labels: bug
