### ISSUE TITLE
Give clear error when writing to a stale db handle

### ISSUE THREAD

**Issue by devfelipereis** [pouchdb/pouchdb#4134] opened 2015-08-07 17:10 UTC
I'm new with pouchdb and I have a situation where I destroy my database and then I create it again. The issue is that I can delete, but when I try to re-create, it gives me an error. 

I'm using "angular-pouchdb" with cordova and I'm testing with Chrome Version 44.0.2403.130 (64-bit).

DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

Someone know why I got this error? Thanks!

**Comment by daleharvey** [comment] 2015-08-08 09:10
Similiar to https://github.com/pouchdb/pouchdb/issues/4135 this looks like a situation we tests an awful lot and havent yet seen, any help to reproduce (a broken test case) would be helpful, thanks

**Comment by nolanlawson** [comment] 2015-08-08 17:36
Are you using map/reduce? (`query()`?) Are you waiting for the callback/promise on `destroy()` before re-creating? As @daleharvey says, our unit tests destroy/recreate a database between every test, and this issue doesn't come up.

**Comment by devfelipereis** [comment] 2015-08-09 20:35
I'm just doing something like this:

LocalDB.destroy().then(function(){ //and here I'm executing a LocalDB.put() })

I don't know if I'm doing right. I'm still a beginner.

**Comment by nolanlawson** [comment] 2015-08-09 20:48
hm, I think you need to call `new PouchDB()` between the `destroy()` and `put()`.

**Comment by devfelipereis** [comment] 2015-08-11 13:50
@nolanlawson I'm using "angular-pouchdb" and I have a service that returns:

return new pouchDB('localdb', {auto_compaction: true});

Every time I call a service, this instance is returned. It's a singleton instance. As I said, I'm a beginner.. but I was thinking... could be this singleton instance a issue here? Cause this instance will have the information that the database was deleted? If I destroy the database, close the app and open it again, all works fine.

**Comment by daleharvey** [comment] 2015-08-11 14:09
So I am very surprised, but this used to work in 3.4.0, it looks to have broken in 3.5.0 but really it should never have worked, if you `destroy()` a database you need to create a new handle to write to it again

**Comment by nolanlawson** [comment] 2015-08-11 14:10
@devfelipereis Services in Angular are only created once (i.e. singletons), so yes, that is your problem. You will probably need an Angular factory instead of a service.

If you `destroy()` a PouchDB object then you can never use that same object again. You can however create a new PouchDB with the same name.

**Comment by devfelipereis** [comment] 2015-08-11 17:20
@daleharvey and @nolanlawson Thanks for your reply! I'll try a factory to check if it works.

**Comment by daleharvey** [comment] 2015-10-06 21:40
Closing as a dupe - https://github.com/pouchdb/pouchdb/issues/4339

**Closed by daleharvey** 2015-10-06 21:40 UTC
Labels: enhancement
