### ISSUE TITLE
Live replication replicates 1 doc, then 1 again, then batch_size

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3824] opened 2015-05-10 18:57 UTC
As mentioned here: https://github.com/pouchdb/pouchdb/issues/2940#issuecomment-63135931.

This is a longstanding issue that we're all aware of (I used to see it in the NPM Browser - "replicated 1", "replicated 2", then "replicated 502", etc).

For some reason it's never had its own issue, but now it does.

**Comment by olafura** [comment] 2015-08-13 18:44
We are talking about thousands of request on a very small dataset.

Last time I was here I wrote my own library :)

It looks like I have to tackle this at the source. I don't see why we can't do an initial _all_docs or use the filter specified and then the rest of the code.

I doubt that half an hour is enough for the sync to finish, for my case. I'm up to around 6000 request going on 17 mins. On 215 documents, which are small, except a couple of design documents. The databases are under a MB, without compaction. I'm up to 6.6 MB of traffic from the replication.

**Comment by olafura** [comment] 2015-08-13 18:48
PouchDB is a very effective DDoS tool :D

**Comment by kxepal** [comment] 2015-08-13 18:49
couch_replicator does the same, but it's by design. Workers doesn't wait while they read whole batch_size from changes queue manager, but read everything available up to the batch_size and starts works with that. 

At the replication start, changes reader is not able to physically read changes for at least one batch size when workers are started to request the changes. However, when workers comes on second time for changes, they almost always reads whole batch unless connection with changes feed reader is slow enough.

**Comment by kxepal** [comment] 2015-08-13 18:52
Simple mitigation could be start replication workers with a small delay, but this doesn't solves the issue in general, when remote changes feed is on slow connection or reader had read all the changes and the update rate on source is not enough to fill the batch size quickly.

**Comment by olafura** [comment] 2015-08-13 19:06
@kxepal The problem is that browsers generally don't like this kind of behaviour, so each one of thoses calls is messing with the other calls. http://www.browserscope.org/?category=network

I've tried forcing the timeout to something higher because the just timeout after 10s.

For me perfect replication should be for the server so conditional and not the browser.

**Comment by olafura** [comment] 2015-08-13 19:09
I'm up to 17000 request and 17 MB transferred and 43 minutes and the bulk of the documents haven't been transferred.

**Comment by kxepal** [comment] 2015-08-13 19:17
@olafura I think here, is problem is so big, better to use some composite algorithm. For instance:
- let worker not process changes until it read at least batch_size/2 of them;
- force to process all that worker had read (if any) after 3s timeout;

But such fix will come with the price that replicator won't replicate documents ASAP, especially when changes feed reader starts listen only for the new updates.

**Comment by olafura** [comment] 2015-08-13 20:12
@kxepal I think I'm going to look into websockets, I think it might be the only solution.

**Comment by kxepal** [comment] 2015-08-13 20:20
@olafura websocket are suddenly not available on CouchDB, so I don't count them as the solution for now. But indeed, that's the right way to go.

**Comment by daleharvey** [comment] 2015-08-13 20:23
There are several issues relating to replication performance so I think it would be good to open a new thread for this.

You said you mentioned you have a small dataset (assuming a large amount of deleted items) how about creating a filter that only replicated deleted items after the replication has started, you can ignore all the ones that come before it?

**Comment by olafura** [comment] 2015-08-13 20:38
@kxepal I'm doing some tests with socket-pouch just now playing around with it, but I think Elixir plug should work. I spent recently half a day debugging a problem with my erlang validate_doc_update function[1],  so I think some time Elixir is going to be a welcome place :)

@daleharvey I think it has more to do with it being split up in multiple databases.

[1] some with fabric:update_doc user_ctx and some with a problem I nailed down to me using {OldDoc} which doesn't work with new documents like I was creating with the function so I had to do some overload of anonymous functions. And of course that I have to return 1 :)

**Comment by nolanlawson** [comment] 2015-08-14 15:33
@olafura I'm concerned with PouchDB/CouchDB replication performance as well. Currently there are a few solutions you can try:

* https://github.com/nolanlawson/pouchdb-load
* https://github.com/nolanlawson/pouchdb-replication-stream and associated community of plugins
* https://github.com/nolanlawson/socket-pouch

Hopefully in there you should be able to find some solution that works for your current stack. :)

**Comment by bbenezech** [comment] 2015-12-22 22:30
@nolanlawson Sorry to bump this thread abruptly out of nowhere, but I think this issue is causing a lot of damage to the PouchDB project and should be addressed .

- It makes replication a lot harder to comprehend when looking at the network tab, especially for beginners.
- It sends 3 times to many requests for every replication when changes count is < 4, which is often.
- It looks really nasty, to be honest :no_good: 

This bug is making me feel uncomfortable each time I stumble upon it.
I retro-engineered a replication endpoint (the "dumb" one), and I feel I cannot call it done until this issue is closed. :confetti_ball: 

You stalled last may nearly there, saying `replicate.js` needed a refactoring. Is it still the case today?
I wish I could help with a PR, but that would probably be a waste of both our time.
Maybe if you reopen a branch with that fix I can try to make tests pass? Would you accept it without a proper refactoring of `replicate.js`? Do you think it is accessible to a first time contributor?

**Comment by daleharvey** [comment] 2015-12-23 12:02
If you had a fix for this without refactoring `replicate.js` then all other things being the same it would definitely be welcome. Its not the cleanest part of the code base but as long as you are familiar with JavaScript this should be accessible and via IRC or on here would be totally happy to help out.

I would expect a naive implementation to write one document then start filling up the batch size, its strange that it does 1, then 1 then batch size, I think before fixing anything it needs to be understood exactly why that is happening. 

As for your worries, I havent been considering this a bug at all just a possible improvement, at the most it could cause 2 extra http requests since it only occurs at the start of a replication.

**Comment by nolanlawson** [comment] 2015-12-24 01:00
One thing about this bug: it occurred to me recently that it actually serves a purpose: during live replication, there's no way to determine whether we're "up to date" except to send a non-live `_changes` request for a single doc. Think of it as a ping.

However, there's no reason to do two requests for one doc. We could just do one.

**Comment by daleharvey** [comment] 2016-01-16 13:17
Fixed in https://github.com/pouchdb/pouchdb/commit/f3a72ea84c951a815f8dd7a002fb11aa17b82543

**Closed by daleharvey** 2016-01-16 13:17 UTC
Labels: enhancement
