### ISSUE TITLE
getAttachement doesn't return the type

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#3946] opened 2015-06-09 16:10 UTC
getAttachment doesn't return the type in the blob response when getting an attachment (I tried application/pdf).

version 3.6.0
Browser: Chrome

**Comment by natcohen** [comment] 2015-06-09 18:45
It seems that it's not the getAttachment function but rather the update of the browser DB... when I updated to 3.6.0, the type disappeared. When I tried to rollback to 3.5.0, the DB still didn't have the types. I had to delete the database and recreate it under the 3.5.0 version.

**Comment by nolanlawson** [comment] 2015-06-09 19:38
Can you provide a test to reproduce please? Also I'm not sure what you mean by "doesn't return the type." You mean `blob.type` is not correct, or `attachment.content_type` is not correct...?

**Comment by nolanlawson** [comment] 2015-06-09 19:42
To be fair, it just occurred to me that we don't actually test the blob content types anywhere, since we don't get them in Node (only in the browser). I think it would be reasonable to add these tests to the current test suite, maybe hidden behind a flag like `if (inBrowser) {`.

**Comment by natcohen** [comment] 2015-06-09 20:47
The blob.type is empty...

Put a pdf file in your couchdb, sync pouchdb and get the file with getAttachment. The blob response won't have type. It broke from 3.5.0 to 3.6.0

**Comment by nolanlawson** [comment] 2015-06-10 01:57
Sorry, I cannot reproduce. Please see https://github.com/pouchdb/pouchdb/pull/3948

Can you please offer a live test case? An `index.html` file using a local CouchDB at `localhost:5984` would be fine.

**Comment by natcohen** [comment] 2015-06-10 14:10
Well, I simply use the following to get the file:
    
    var pouch = new PouchDB('transport', {size: 50});
    pouch.replicate.to('http://127.0.0.1:5984/transport', {live: true});
    pouch.replicate.from('http://127.0.0.1:5984/transport', {live: true});
    
    pouch.getAttachment(docid, name, function(err, res){
        console.log(res);
    })

It returns a blob with correct data and size but with type = ""

**Comment by nolanlawson** [comment] 2015-06-10 16:03
@natcohen Is there any way you could provide a live test case? I don't have access to your CouchDB, so I cannot test your particular case. :)

**Comment by nolanlawson** [comment] 2015-06-15 03:15
Please provide more details if this is an issue. Also feel free to try the nightly. :)

**Comment by natcohen** [comment] 2015-06-16 15:26
@nolanlawson 
Sorry, I was away for few days... 

I made a mistake, it doesn't occur when I add the pdf through CouchDB but when I generate it with PDFkit and add it through PouchDB. Here is the procedure to reproduce it:
- Create a pdf using PDFkit (http://pdfkit.org/)
- Add it to your PouchDB using (pouch.putAttachment(id, name, rev, doc, 'application/pdf');)
- Get your attachment and check the type of the blob (it is empty)

The problem seems to come from putAttachment rather than getAttachment...

**Comment by nolanlawson** [comment] 2015-06-16 18:59
@natcohen I'm sorry, that's still not enough information to reproduce. (E.g. what is `doc`?) Is there any way you can create a live site to demonstrate? Can you supply your own PDF?

**Comment by natcohen** [comment] 2015-06-16 21:14
I made a plunker here (http://plnkr.co/edit/VIRpKefTlS9aA4TBFMsg?p=preview) and found the problem... This plunker works but as soon as I write: `var pdfBlob = new Blob([pdfBuffer.buffer]);` instead of `var pdfBlob = new Blob([pdfBuffer.buffer], {type:'application/pdf'});` I lose the type...

It worked in 3.5.0 without `{type:'application/pdf'}` specified. Is it a bug or an intended behavior? If it is intended, why would I need to specify the type twice (once in the blob and the second when I add the attachment to the DB)?

**Comment by nolanlawson** [comment] 2015-06-18 03:15
Blobs need to have a type attached, or else the type doesn't get saved. We save the Blob directly into IndexedDB, so that's why that happens.

The reason there's redundancy in having a type on the Blob as well as a `content_type` on the attachment metadata is because `Buffer`s in Node have no type, so in the browser we have to be redundant. In general, you shouldn't depend on this behavior and should put the type on both. I think our documentation is wrong in this regard, because in some places it shows examples of creating Blobs without types.

**Comment by nolanlawson** [comment] 2015-06-18 03:15
Gonna close this, since we figured out what's up. I think the docs need to be fixed; I'll do that now.

**Closed** 2015-06-18 03:16 UTC

**Comment by nolanlawson** [comment] 2015-06-18 03:34
BTW I should explain: the reason we are doing it this way is because 3.6.0 eliminated redundant conversion between different binary formats. So now when you give a blob to PouchDB, it is stored directly as-is with no expensive conversion process. It's a performance optimization. :)
