### ISSUE TITLE
websql by-sequence table sometimes stores deleted flag from wrong rev

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#3646] opened 2015-03-17 18:43 UTC
We are having a problem where replication-to-WebSQL winds up with too many documents, while IndexedDB works fine. Once this happens replication will never result in the remote and local databases containing the same number of documents. The following demo shows the same problem, but with pouchdb-load instead of pouchdb-bulk-get.

https://github.com/dholth/pouchdb-websql-bug

Instead, WebSQL should wind up with the same number of documents as IndexedDB and should not care if an older dump is loaded into the database first.

**Comment by dholth** [comment] 2015-03-18 12:59
When I get() one of the extra documents from the websql database, it has _deleted:true

**Comment by dholth** [comment] 2015-03-18 14:19
It looks like when the deleted document is added, PouchMerge.winningRev changes the rev's deleted state to false by thinking a different rev is the winner, when it leafs.sort() by (a.deleted !== b.deleted).

**Comment by nolanlawson** [comment] 2015-03-18 15:11
Yeah, I can guess what might be causing this. It's probably due to how deleted revisions are treated in WebSQL under the hood. So the bug is probably in [websql.js](https://github.com/pouchdb/pouchdb/blob/7a7d0310afcc6cfca0509e36d75986f6ce62d313/lib/adapters/websql/websql.js).

I'll try to get around to this the next weekend (been slammed recently). If you're in a hurry to get this fixed, it would save some time if you could convert your test case to an integration test that fails in WebSQL but succeeds in IndexedDB. If it were me, I would probably start with a test [like this one](https://github.com/pouchdb/pouchdb/blob/7a7d0310afcc6cfca0509e36d75986f6ce62d313/tests/integration/test.replication.js#L766-L834), and figure out what docs I have to load using `bulkDocs()` with `new_edits=false` (which is what `pouchdb-load` does) in order to reproduce the bug.

**Comment by dholth** [comment] 2015-03-19 15:40
At first glance it looks like changing line 107 of websql-bulk-docs.js from
```
var deletedInt = deleted ? 1 : 0;
```
to
```
var deletedInt = docInfo.metadata.deleted ? 1 : 0;
```
fixes the problem. The by-sequence table was writing the deleted flag from a different rev to the table.

**Comment by dholth** [comment] 2015-03-19 17:38
Additional analysis to figure out if we can avoid passing the wrong deleted flag to the function would be desirable of course, but this change seems to solve exactly the websql bug.

**Comment by nolanlawson** [comment] 2015-03-20 05:09
This fix looks correct, but it will just need a test before we can merge it. :)

**Comment by nolanlawson** [comment] 2015-03-21 14:42
I can reproduce now. There was just a bug in the test due to not cleaning up the database before/after the test.

**Comment by daleharvey** [comment] 2015-04-03 11:54
Awesome, thanks for the test @dholth 

Fixed in https://github.com/pouchdb/pouchdb/commit/a7b7c89bfbf3befa5276ef93685098cb47d9e9ea

**Closed by daleharvey** 2015-04-03 11:54 UTC
