### ISSUE TITLE
No information of requested id  in callback of "get" Request.

### ISSUE THREAD

**Issue by ZeroNine00** [pouchdb/pouchdb#5749] opened 2016-10-03 17:43 UTC
### Issue
No Information of requested id  in callback of "get" Request.

### Reproduce
We must check if String exist in the pouchdb . The problem is we have 50 positions and we must check for all this positions if the material number exist in the pouchdb. 
So we do a loop over the positions and in there we are doing a "get" requests with key and have callback function. 

The problem is that we have no opportunity in the callback function to see for which request the callback was . And so we have chance to show a proper message to the end user.

BR

**Comment by daleharvey** [comment] 2016-10-04 09:42
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/5490

**Closed by daleharvey** 2016-10-04 09:42 UTC
