### ISSUE TITLE
Replication: fetching attaches separately vs inlined

### ISSUE THREAD

**Issue by ermouth** [pouchdb/pouchdb#5367] opened 2016-06-18 11:40 UTC
Since it‘s not an issue, but a question, I‘ve discarded a template, sorry.

Upgrading from 3.3 to 5.4, I‘ve discovered, that now Pouch fetches attaches using separate requests. It‘s nice, since it reduces possibility of timeout on docs with lot of large attaches, also it reduces traffic.

Although, since Pouch does not check integrity of an attach received, any unreported error during transmission can have destructive effect.

If we, for example, have misconfigured proxy or rewrite in front of Couch, direct request to an attach may cause any answer but attach itself. This response will be stored in Pouch and then replicated back to Couch (if user changes doc in Pouch, surely).

Initial attach is totally destroyed in this case. Example isn‘t taken from thin air – I‘ve discovered it testing real configuration with rewrites. Also I know proxies, configured to add cache-control header to all images, and it may also break intended behavior.

So is there any way to fetch docs during sync in prev versions style? I mean an option or something to enforce Pouch 5.4+ make only application/json requests and fetch docs with attaches inlined?

**Comment by daleharvey** [comment] 2016-06-18 12:00
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/3913

**Closed by daleharvey** 2016-06-18 12:00 UTC
