### ISSUE TITLE
Cookie credentials remote db ignored

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [pouchdb/pouchdb#7018] opened 2018-01-17 09:12 UTC
_Reposting #6683 since it has been closed by mistake. This is still an issue. I can’t reopen it… So:_

### Issue
I have an electron app, I managed to login to couchdb with cookie auth.
I also manage to retrieve the correct session. I used the `fetch` api so far to handle the requests.
For cookie storage in electron I use `electron-cookies` and this is working, if I do a get request with `credentials: 'include'` and `'withCredentials' : true` options it makes the request with the cookie.
Whenever a user is created a corresponding database is created too with the new user being the admin of the database. So far so good.

However, if I try to connect to the remote DB with PouchDB this does not work, I get an `unauthorized`.

My guess is that the authentification cookie is ignored somehow.

I tried it the normal way:
```
remoteDB = new PouchDB('http://somecorrecturl/userDBName');
```
and also like this:
```
remoteDB = new PouchDB('http://somecorrecturl/userDBName', {
    ajax: {
      method: 'POST',
      mode: 'cors',
      headers: {
        'Content-Type': 'application/json',
        'withCredentials' : true
      },
      credentials: 'include',
      withCredentials: true,
    }
  });
```
without success.

Note: "userDBName" is a user database that can only be accessed by that logged in user. In my frontend the user is logged in via cookie. I still get permission denied. The cookie seems ignored when trying to sync or to put documents:

```
localDB.sync(remoteDB, {live: true, retry: true}).on('error', console.log.bind(console));
``` 

Will fail. Also

```
var doc = {
        "_id": "mittens",
        "name": "Mittens",
        "occupation": "kitten",
        "age": 3,
        "hobbies": [
          "playing with balls of yarn",
          "chasing laser pointers",
          "lookin' hella cute"
        ]
      };
remoteDB.put(doc);
```

Also fails because `unauthorized`

Is there some special option I have to include? Using the `fetch api` for example I had to add `credentials: 'include'` before it would use the cookie.

Doing the exact same thing with the same auth-cookie but using postman works.
So my bet is that the cookie is ignored by pouchdb.

### Info
- Environment: Node.js / Electron
- Platform: Chromium / Electron
- Adapter: PouchDB
- Server: CouchDB

Thank you for your help!

**Comment by ptitjes** [comment] 2018-01-17 10:51
@ThibaultJanBeyer I'd like to work on that, but maybe you could provide an example project ?

**Comment by daleharvey** [comment] 2018-01-18 16:22
Closed as a dupe of https://github.com/pouchdb/pouchdb/issues/7022, which I think will be closed as a dupe of other WIP issues

**Closed by daleharvey** 2018-01-18 16:22 UTC

**Comment by ThibaultJanBeyer** [comment] 2018-06-16 07:17
@daleharvey This is still not fixed. Please re-open.

**Comment by ptitjes** [comment] 2018-06-16 11:47
@ThibaultJanBeyer In 7.0, it is expected that you use the `fetch` provided by PouchDB or that you provide it with a `fetch` implementation that you want.

I requested you before a test project with `pouchdb`, `electron` and `electron-cookies` as you use them, as I might like to look into you problem...

**Comment by adrienverge** [comment] 2018-08-21 09:58
A custom `fetch` implementation should not be required for basic usage.

In 7.0.0 cookies are not sent, but this should be fixed by https://github.com/pouchdb/pouchdb/pull/7395 (not released yet).

**Comment by ThibaultJanBeyer** [comment] 2018-08-21 13:37
Okay nice, looking forward for that release. Any ideas when it will happen? Thank

**Comment by adrienverge** [comment] 2018-08-21 14:00
I don't know, but in the meantime you can apply the following patch to your repository: 
[0001-pouchdb-fetch-with-credentials.patch](https://github.com/pouchdb/pouchdb/files/2306554/0001-pouchdb-fetch-with-credentials.patch.txt).
