### ISSUE TITLE
PouchDB query does not return doc with latest revision when Cloudant DB is recreated

### ISSUE THREAD

**Issue by sagarkm** [pouchdb/pouchdb#5516] opened 2016-07-31 15:14 UTC
PouchDB once synced with remote CloudantDb and the sequence went beyong 10K.
Now due to unavoidable circumstances we flushed the remote Cloudant Db and recreated with the exact same doc but only thing all doc now have seq=1-xxxx
Now any changes done on Cloudant does bring the updated document with seq=1 or 2 or smaller nos and Pouch DB shows multiple docs with seq=1-xxx (the newer doc) as well with seq=1-yyy (older replicated copy).

But the issue is when we query the PouchDB for any _id it returns the one with highest seq=10K something, and not the one iwht 1-xxx.

I'm using PouchDB v5.4.5 in hybrid Ionic App.

Issue persists on all browsers and I am using the WebSQL adapter, but think this would occur using any adapter

Net Trace: calls _changes API 
https://xxx.cloudant.com/sm_db/_changes?timeout=55000&style=all_docs&heartbeat=10000&since=3828-g1AAAAOreJy10cEOwUAQANClgm9wQMS5WXar2xN_ws7uSiPVJm2d-RPEQXwFf8Kf1NoWVw57mclsJvOyMxFCqB06Eg0liCRVMwljV60zEfI0zzAeuSJKNpLHuRurPNLddY6gVxTFKnRAV521fmtNKCHBmP445j8P-jrC9EPWLobEygOPcjvk7EXOv-TJkJRTDP7EDrl4kdvvYpuG9ITEIO38Mm7oiHY6aXVfsV3Dcl_RJZMW2UPJXqsFnw3LAsKFBIvsrWTvFXs0rM-AQuBbZB8l-77twLCEEMYU_nHa6gm7PSkz

Response :

``` json
{"results":[
{"seq":"553-g1AAAAL0eJyl0ksOgjAQBuBGTdBTaIxrUoqUspKbaKctQYI14bHWm-hN9CZ6E2xloexQNjPJZPJN8mdyhNA0HUu0kiCOhYolEFcdSpHyoiox9lyRH2vJdeVqVeVme8QRzJumydIxRwczcCjFlHiRRLNaS5XstZK_ibAwFTYd1OeMcOYPQGOLbjsojrwkomQAurPoqYPCGtMwCP5H9cRUdDbNuJevXEXIEhYOha8tfPvAUcAEUG8ofG_hh4WdNxxwUMTm24v65-azvWnjBzNctr_i-4wp3FPLXsF06yg","id":"bases_769","changes":[{"rev":"1-ab82650daaf2d984945754be29c429c8"}]},
{"seq":"16-g1AAAALxeJyl0EsOgjAQBuBGTNBT6MI1KUXaspKbaF8ECZSEx1pvojfRm-hNsMBC2SFsZpLJ5PuTPwUArGJLgp3kIi9UKDlyVFaKmBVVCaHriDSvJdOVo1WVmu8FA3zTNE0SWwxk5mBjDDFyAwnWtZYqOmsl_xP51kx-GKAeo4hRbwYatuhxgMLAjQKMZqCnFr0MUL6HmPj-dFQvzQRXs4x7--lVEBpRMhe-9_DjCwc-FRy7c-FnD79a2O5gn3GF2n5HUVMy331mV_-6y0SCCMLISCr5ADvj62w","id":"users_152619","changes":[{"rev":"3-0b3e3ad87856f6c443881fa3172cdbf2"}]}
],
"last_seq":"16-g1AAAALxeJyl0EsOgjAQBuBGTNBT6MI1KUXaspKbaF8ECZSEx1pvojfRm-hNsMBC2SFsZpLJ5PuTPwUArGJLgp3kIi9UKDlyVFaKmBVVCaHriDSvJdOVo1WVmu8FA3zTNE0SWwxk5mBjDDFyAwnWtZYqOmsl_xP51kx-GKAeo4hRbwYatuhxgMLAjQKMZqCnFr0MUL6HmPj-dFQvzQRXs4x7--lVEBpRMhe-9_DjCwc-FRy7c-FnD79a2O5gn3GF2n5HUVMy331mV_-6y0SCCMLISCr5ADvj62w","pending":0}
```

**Comment by nolanlawson** [comment] 2016-07-31 18:07
I wonder if this is related to the fact that we can't create `_local` documents in Cloudant? If your Cloudant is locked down such that users can't create `_local` documents, then yes, we'll be helpless if the remote database gets destroyed/recreated because the client has no way to know.

**Comment by willholley** [comment] 2016-08-01 11:35
This sounds like expected behaviour. When a document is conflicted, PouchDB/CouchDB will choose the non-deleted revision with the longest history - in this case the 10K rev. Your best bet is probably to delete the local database and re-sync but if that's not possible, you'll need to delete the old revisions from your local PouchDB copies.

Bear in mind that you need to be careful about replicating those deletions back to Cloudant. If you do replicate back to Cloudant, you'll likely generate lots of conflicts which will impact replication performance. As mentioned above, a better solution would be to delete the local PouchDB database and replicate everything from Cloudant into an empty database.

**Comment by sagarkm** [comment] 2016-08-03 22:53
Thanks correct @nolanlawson. In this case the DB on the Cloudant is read only. When I see network trace, I do see failed attempts to POST _bulk_docs with _local endpoints and those are unauthorized by Cloudant due to invalid API key.

And I do want to delete the Local PouchDb and recreate anytime the Remote CloudantDB is destroyed. But the question is how do I detect that the remote DB was destroyed and a new version od DB with the same name has is now up.

Also I read sometime back, that there are some issues with sync to/from cloudant as Cloudant uses alpha-numeric revs and PouchDb for some reaons uses numeric. This that true?

**Comment by willholley** [comment] 2016-08-04 08:19
@sagarkm with Cloudant, you can assign your API key `reader` and `replicator` permissions which will allow it to write checkpoints but otherwise be read only.

Regarding detecting whether the remote db was destroyed, the only reliable way I can think of is to maintain a metadata document in the Cloudant database (e.g. containing a database version/timestamp) that your application tests.

> Also I read sometime back, that there are some issues with sync to/from cloudant as Cloudant uses alpha-numeric revs and PouchDb for some reaons uses numeric. This that true?

Those issues have been fixed for a while and we test PouchDB's continuous integration tests against CouchDB 2.0 (which also uses string-based sequence numbers). In general, it's good not to assume that sequence numbers are integers/incremental as that is an implementation-specific detail rather than a requirement of the sync protocol.

**Comment by sagarkm** [comment] 2016-08-04 13:09
@willholley  The API key has been assigned reader and replicator permissions but still the POST to _bulk_docs/_local fails as it needs writer permission (I guess)
Thanks for the suggestion of maintaining a metadata doc. I was thinking of the same. Your suggestion validates my thoughts.

**Comment by willholley** [comment] 2016-08-04 13:17
@sagarkm replicator permissions should allow writing checkpoints. When you say the request to `_bulk_docs/_local` do you mean there is a request to `https://myaccount.cloudant.com/somedb/_bulk_docs/_local`? If so, that isn't a valid URL...

**Comment by daleharvey** [comment] 2016-08-04 14:28
It sounds possibly like the checkpoint permissions allow `POST _local` but not `POST /bulk_docs` with the content `{id: '_local/id'}` ?

**Comment by willholley** [comment] 2016-08-04 14:39
wow @daleharvey - looks like you're correct. `PUT _local/id` works but `POST _local/id` via `_bulk_docs` OR `/db` doesn't. I'll file a bug.

**Comment by willholley** [comment] 2016-08-04 15:03
I wonder given the issues with Couchbase as well whether we should just `PUT` checkpoints again. I'm not optimistic this will get fixed in Cloudant any time soon as it appears non-trivial (authorization currently just looks at the URL requeste; this would require inspecting the body) and the current solution works for other replicators.

**Comment by nolanlawson** [comment] 2016-08-06 22:44
I agree with @willholley. It was a nice simplification to the pouchdb-adapter-http codebase to assume _bulk_docs everywhere, but the buggy behavior in Couchbase/Cloudant isn't worth saving a few hundred bytes imo.

**Comment by sagarkm** [comment] 2016-08-10 17:19
@willholley Randomly while the live sync is on I see network call:
GET https://xxx.cloudant.com/some_db/_local/wbq8QguFTSXqyiOPUx_c.w%3D%3D?
That fails with 404

Then immediately next network call is:
POST https://xxx.cloudant.com/some_db/_bulk_docs
That fails with 403 and below data:
{"error":"forbidden","reason":"_writer access is required for this request"}

Also some random call:
POST https://xxx.cloudant.com/some_DB/_bulk_get?revs=true
That fails with 403 and below data:
{"error":"forbidden","reason":"_writer access is required for this request"}

Hope this helps.
When is the next version of PouchDB expected?
How can I get the nightly build of Pouchdb.js?

**Comment by nolanlawson** [comment] 2016-08-11 02:00
```
git clone https://github.com/pouchdb/pouchdb.git
cd pouchdb
npm install
```

Then grab `packages/pouchdb/dist/pouchdb.js`; that's the latest build. :)

**Comment by willholley** [comment] 2016-08-11 12:12
@sagarkm those calls are expected.

    GET https://xxx.cloudant.com/some_db/_local/wbq8QguFTSXqyiOPUx_c.w%3D%3D?

is PouchDB looking for an existing replication checkpoint

    POST https://xxx.cloudant.com/some_db/_bulk_docs

is failing because the user does not have write permissions on the source database (required for PouchDB to write checkpoints)

    POST https://xxx.cloudant.com/some_DB/_bulk_get?revs=true

is likely failing because the cluster your account is on does not support the _bulk_get endpoint (though this one can be easily fixed by moving to a different cluster).

The nightly/next release isn't going to help until https://github.com/pouchdb/pouchdb/pull/5455 or some other fix is merged.

**Comment by sagarkm** [comment] 2016-08-12 10:40
Thanks @willholley and @nolanlawson 
Cloudant API keys are created only with _reader and _replicator permissions. They do not have _writter permission.
So in case of READ ONLY replication, pouch would not be able to store replication checkpoints on remote source db?
So does it imply that in case of replication of READ ONLY DBs, if for some reason replication breaks, the client (PouchDB) would restart the downloading all docs and ignore the ones already written and then write the remains docs that were missing?

If so the replication time would be very high in poor network like Mobile 3G.
Or am I missing something?

**Comment by willholley** [comment] 2016-08-12 10:49
@sagarkm if checkpoints don't get written, PouchDB will rescan the remote _changes from the beginning on every sync. It won't download the document content if it already exists locally but it will have to check that and so sync will take longer.

**Closed** 2017-12-06 21:31 UTC
Labels: bug, needs reproducing, wontfix
