### ISSUE TITLE
db.type() impredictible behavior regression (5.2.0) 

### ISSUE THREAD

**Issue by bbenezech** [pouchdb/pouchdb#4788] opened 2016-01-14 19:15 UTC
Tested in latest chrome:

With PouchDB 5.2.0
```javascript
console.log(new PouchDB('1').type());
console.log(new PouchDB('2').type());
>> idb
>> Uncaught TypeError: (intermediate value).type is not a function(…)
```

A setTimeout to display `db2.type()` (sometime 0, sometime more) fixes it.
It worked as expected with 5.1.0

Tell me how I can help.

**Comment by nolanlawson** [comment] 2016-01-15 02:10
Interesting bug! Seems to be due to removing `type` from the prototype (it was marked as dead code by Istanbul).

Presumably we need to add it back to `adapter.js`. Here's [where it used to live](https://github.com/pouchdb/pouchdb/blob/57923d6c088f52adcc785f1dad693227fb209396/lib/adapter.js#L750-L753). It's probably easy enough to just add that code back in, but a slam-dunk would also be to add a test to `test.basics.js` that catches this bug.

**Comment by nickcolley** [comment] 2016-01-15 09:14
Should .type() be deprecated in favour of .info()?

**Comment by bbenezech** [comment] 2016-01-15 11:02
@nolanlawson Thanks for reviewing.
You may want to warn users in pouchdb-find's readme, since it tries to read `.type()` with `.getIndexes()`
It fails reliably when I instantiate/set up indices on my second collection.
I'll stay with 5.1.0 until `.type()` is moved back to `adapter.js`.

I can't express how much I love you guys for maintaining PouchDB, thanks a lot, really!

**Comment by nolanlawson** [comment] 2016-01-16 23:23
@nickcolley It's basically undocumented; it's one of those weird edge cases where it's widely used by plugins (naughty me), but probably should not exist or should be made official.

**Comment by bbenezech** [comment] 2016-01-17 12:51
I can't reproduce the issue in `test.basics.js`. (it is using the `leveldb` adapter, maybe not impacted?)

`.type()` is already covered there:

https://github.com/pouchdb/pouchdb/blob/b933b9847c1855e65d26e8bca9fb9c250e853b5b/tests/integration/test.basics.js#L1041-L1044

I don't get the async chicken and egg story with `adapter/type/_type` through `adpater.info()`
I guess moving `.type()` back would fix the issue, but it doesn't make much sense to me :D

Your call.

**Comment by nolanlawson** [comment] 2016-01-17 15:06
@bbenezech I can reproduce your issue in the browser using the code you provided above. That code would be perfectly fine for a unit test; in fact you can simplify by it by using the same db name for both PouchDB objects and using the `dbs.name` from the test file (i.e. re-using the same name, so that additional databases aren't unnecessarily created by the test). So the test would look like this:

```js
new PouchDB(dbs.name).type().should.be.a('function');
new PouchDB(dbs.name).type().should.be.a('function');
```

I'm going to mark this as a good first patch, because it seems like it should be pretty easy to solve. I don't know why re-adding the old `type()` function works, but if it fixes the test, then let's do it and figure out why it works later. :)

**Comment by nolanlawson** [comment] 2016-01-17 15:09
To fix this bug:

1. check out the PouchDB source code
2. run `npm install` and `npm run dev`
3. open up the integration tests in a browser
4. modify `test.basics.js` to add a new test as described above
5. add `?grep=name_of_test_you_just_wrote` to the URL bar to search for the test you just wrote
6. confirm that it fails
7. fix `adapter.js` as described above until it no longer fails

**Comment by bbenezech** [comment] 2016-01-18 09:31
Ok, I can reproduce with

```javascript
new PouchDB(dbs.name).type.should.be.a('function') // works (leveldb)
new PouchDB(dbs.name, { adapter: 'idb' }).type.should.be.a('function') // fails
new PouchDB(dbs.name, { adapter: 'websql' }).type.should.be.a('function') // fails
```

@nolanlawson How can I test this cleanly?

**Comment by daleharvey** [comment] 2016-01-18 09:47
@bbenezech if you follow @nolanlawson's guide then it looks like that test should fail in the browser (without needing `adapter:idb` as they are automatically used in the browser)

**Comment by daleharvey** [comment] 2016-01-18 22:11
Fixed in https://github.com/pouchdb/pouchdb/commit/7f2321b47ad69ca4214b0f6f03866a03dc21c587

**Closed by daleharvey** 2016-01-18 22:11 UTC
Labels: bug, first timers only, help wanted
