### ISSUE TITLE
Losing data when migrating from 5.4.5 in Cordova SQLite (2) plugin

### ISSUE THREAD

**Issue by Bouzmine** [pouchdb/pouchdb#5753] opened 2016-10-05 12:46 UTC
### Issue

Everything is lost during the migration to the PouchDB 6.0.6 + plugin
### Info
- Environment: hybrid app
- Platform: iOS
- Adapter: WebSQL
### Reproduce

Migrate from 5.4.5 to 6.0.6 on a project using SQLite 2 plugin and see the data losses

**Comment by nolanlawson** [comment] 2016-10-25 01:00
Can you provide a reproducible test case? Based on the description I don't understand what's going on.

If you are using the SQLite 2 plugin then I'm guessing what's going is that you need to use the new https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite plugin; note that this was a breaking change in 6.x: https://pouchdb.com/2016/09/05/pouchdb-6.0.0.html

**Comment by nolanlawson** [comment] 2016-12-18 23:34
Closing because this needs a test case, please reopen if you have one!

**Closed** 2016-12-18 23:34 UTC
