### ISSUE TITLE
IDBObjectStore: An object could not be cloned (Ember.js integration)

### ISSUE THREAD

**Issue by jfgirard** [pouchdb/pouchdb#2158] opened 2014-05-05 20:15 UTC
I just gave a try to 2.2.0.  With WebSQL, its working great.  But with IndexedDb (Chrome and FF),  if i insert a document and `query()` it, i receive this error:

Uncaught DataCloneError: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned. pouchdb.js:2140

I still use the "old" query way, passing along the map function.

It fails on `docInfo.data` with value:

     Object {value: Object, _id: "5542014-05-05T19:57:35.812Z4E1D619FA-C497-146F-     A636-8BAAEADF6F6F31", _rev: "1-28a58b028db3af911ec118c3aa8cd4a4", _doc_id_rev:      "5542014-05-05T19:57:35.812Z4E1D619FA-C497-146F-A…EADF6F6F31::1-28a58b028db3af911ec118c3aa8cd4a4"}
     _doc_id_rev: "5542014-05-05T19:57:35.812Z4E1D619FA-C497-146F-A636-   8BAAEADF6F6F31::1-28a58b028db3af911ec118c3aa8cd4a4"
     _id: "5542014-05-05T19:57:35.812Z4E1D619FA-C497-146F-A636-8BAAEADF6F6F31"
     _rev: "1-28a58b028db3af911ec118c3aa8cd4a4"
     value: Object
     id: "E1D619FA-C497-146F-A636-8BAAEADF6F6F"
     key: Array[1]
     0: "2014-05-05T19:57:35.812Z"
     ....

Using allDocs({include_docs:true}) works fine.

**Comment by ronyrun** [comment] 2015-02-27 16:26
I also currently get that error : 

Error: Uncaught DataCloneError: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned. Script: file:///android_asset/www/lib/pouchdb/dist/pouchdb.js Line: 2192 Column: 29 StackTrace: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned. debug.js:5window.onerror

I'm implementing pouchDB on cordova / IonicFramework  with Crosswalk.
OS: Windows 8.1
Node Version: v0.12.0
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.11
Latest Ionic version: 1.0.0-beta.14  (released 2014-12-15)

**Comment by nolanlawson** [comment] 2015-02-28 06:07
Are you using Ember.js? Can you provide a live reproducible test case?

**Comment by ronyrun** [comment] 2015-02-28 18:15
Hi Nolan,
I'm using AngularJS.

It's a basic ionic app with crosswalk implemented.

**Comment by acdcjunior** [comment] 2015-02-28 18:34
@ronyrun Did you check the plunker in [my comment](https://github.com/pouchdb/pouchdb/issues/2158#issuecomment-66921293)? I was using angular as well. The solution (it is shown in a comment in the plunker) was to use `angular.extend()` before `.put()`ting.

**Comment by nolanlawson** [comment] 2015-02-28 22:17
@acdcjunior This is probably happening because some library is extending the global Object prototype. Is Angular doing that somewhere?

**Comment by nolanlawson** [comment] 2015-03-02 17:12
Reopening because this is now an issue with Angular.

So this seems to be a running gag with IndexedDB and the various JavaScript frameworks that monkey around with the global prototype. We can fix it pretty easily by just taking the nuclear option and doing a structured clone in `idb.js`. I'm going to revive that topic, because I think the performance hit will be minimal, but the benefits are pretty good:

1) no more worrying about weird cloning
2) Dates work the same across all adapters, so no more surprises if you test in Chrome and then discover different results in WebSQL/CouchDB/LevelDB.

I already wrote a fix in 6c6d95af626ad37fbeb2f79e6cc23352e184fabf, with a test and everything. We could easily rebase that on master.

**Comment by acdcjunior** [comment] 2015-03-02 21:51
@nolanlawson I don't really know if Angular extends the global Object prototype, I don't know it that well. In that example plunkr, the problem seemed to be about the (`movie`) object's prototype, yeah. Anyway, you already seem to have a handle on it, great, then!

**Comment by nolanlawson** [comment] 2015-03-03 02:17
@acdcjunior I checked your plunkr. Sorry for not giving you feedback earlier.

The problem is actually not with Angular, and in fact my "fix" doesn't fix it. The problem is that the object you are trying to save looks like this:

```js
{title: "Rambo", year: 2009, genre: "Action", getTitle: function, _doc_id_rev: "1::2-4627fd86dff4602c56be5ddca8d99a1a"}
```

You cannot save a PouchDB object with a function on it. You can only save normal objects. If you are ever unsure, you can run:

```js
JSON.parse(JSON.stringify(myObject))
```

before storing.

Closing this issue. Sorry to take so long to correctly diagnose your problem. :(

**Closed by nolanlawson** 2015-03-03 02:17 UTC

**Comment by acdcjunior** [comment] 2015-03-03 22:17
@nolanlawson Not a problem at all. I've been using that `angular.extend({}, objectWithFunctions)` workaround and will continue to use it. The addition of the info to the docs was a great move. Cheers.

**Comment by tobkle** [comment] 2015-05-27 19:03
Confirming @acdcjunior 's workaround with 
<code>angular.extend({}, objectWithFunctions)</code>
This helped me fixing this IDB Error as well. Thanks a lot!

**Comment by webnoob** [comment] 2016-10-21 23:27
I just want to tag something on to this as I've been experiencing this same issue. I've added date_created fields against my objects using moment.js. If you do `myField = moment('DD/MM/YYYY')` then make sure you don't forget the `.toString()` call at the end otherwise the moment js instance will be passed through and trigger this issue.

**Comment by nolanlawson** [comment] 2016-10-24 00:33
You cannot store custom objects in IndexedDB. Sorry about that; best bet is to ensure that `JSON.parse(JSON.stringify(obj))` produces the same object.
