### ISSUE TITLE
Issues on Android 4.1.2

### ISSUE THREAD

**Issue by Heshyo** [pouchdb/pouchdb#4584] opened 2015-11-17 01:45 UTC
Since we started using PouchDB (quite some time ago actually), our Phonegap app doesn't run anymore on one of our device, with Android version 4.1.2. When we started using the SQLite plugin I tried the app again, but it still doesn't work. We're using PouchDB 4.0.3, so I tried with the latest 5.1 but with no luck. Also there's really not much in our logs nor in PouchDB logs. It's as if things just hang.

We're using the 'websql' adapter ('idb' is not available).

Has anyone noticed errors on 4.1.2? It works well on 4.2.2, 4.4.x, 5.x.

I don't know if there's a test page that I could load in the default browser, or inside a Phonegap app, to test things.

FYI I also just tested using CrossWalk 1.4 and everything works perfectly.

**Comment by nolanlawson** [comment] 2015-11-20 13:45
Hm, I've run the PouchDB test suite in 4.1.2 and there were no issues. What kinds of problems are you running into? Do you have an error log? Does the error occur *with* the SQLite Plugin or *without* it? (For the record, we are aware of SQLite Plugin issues and I don't really recommend it anymore over WebSQL/IndexedDB.)

BTW for the record, Crosswalk is *awesome* because it gives you the latest version of Chromium for all Android 4.0+ devices. Not only will Chromium be more standards-compliant, but your app will very likely run faster, too!

**Comment by Heshyo** [comment] 2015-11-23 01:34
I have the issue with and without the SQLite plugin. Actually at first we weren't using the SQLite plugin, until we reached the quota limit on iOS.

I'm not exactly sure what the problem is. After launching the app, it just looks like it hangs.

I enabled the debug log for Pouch and dumped the logcat: [Wiko_noSQLite.txt](https://github.com/pouchdb/pouchdb/files/41230/Wiko_noSQLite.txt) I'm not seeing anything obvious in it.

Maybe there's a limit on the number of open databases?

I remember I had issues with IE. We always cache the databases so that we only do ```new PouchDB``` once per database, but sometimes we had issues. So now in some places of the code (eg when doing a ```bulkDocs```), if we get an error we force the ```new PouchDB``` and redo the action. That simple trick has fixed the IE issue. I thought we may have something similar here so I forced the ```new PouchDB``` all the time. Unfortunately things still don't work: [Wiko_noSQLite_noDBCaching.txt](https://github.com/pouchdb/pouchdb/files/41236/Wiko_noSQLite_noDBCaching.txt)

When doing those tests I got a weird error, but it may have nothing to do with Pouch: [strangeError.txt](https://github.com/pouchdb/pouchdb/files/41237/strangeError.txt)

**Comment by Heshyo** [comment] 2015-11-23 02:39
As for CrossWalk, it's really great but it makes my app crash on some devices. On one of the 1st releases it crashed on 3 devices. With the latest release it crashes on 2 devices which are low end ones, with 512MB of RAM only. Maybe the additional memory required by CrossWalk is the culprit.

**Comment by nolanlawson** [comment] 2015-12-13 02:56
In general, the most useful errors are the ones that come from the JavaScript console. It's painful, but you can use something like WEINRE to inspect a running Android 4.1.2 WebView and see what the crash is. I admit that combing through your 260KB log file is not easy. I tried, but I'm not seeing anything from the console in it.

**Comment by nolanlawson** [comment] 2015-12-13 02:57
I'm going to close this unless more details can be provided, because as-is I wouldn't even know where to start with fixing it, since there are no steps to reproduce or error messages (aside from the huge dump files).

**Closed by nolanlawson** 2015-12-13 02:57 UTC

**Comment by Heshyo** [comment] 2015-12-13 05:32
@nolanlawson I understand. I also never saw anything useful either in the console logs nor in the catlog dumps. I mostly asked here to see if anyone had also encountered issues on 4.1.2. Maybe someday I'll try to spend time on it.
