### ISSUE TITLE
IndexedDB DOMException is thrown in case of an uncaught exception

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3812] opened 2015-05-08 12:17 UTC
It seems anytime you get a 404 missing, you can end up with IndexedDB DOMExceptions, which are a great way to create a red herring to distract you from the real problem:

```
"{"status":404,"name":"not_found","message":"missing"}"
"InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing."
"Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Error (native)
    at 7.exports.openTransactionSafely (http://localhost:8989/pouchdb-3.5.0.js:2723:16)
    at startTransaction (http://localhost:8989/pouchdb-3.5.0.js:2161:21)
    at http://localhost:8989/pouchdb-3.5.0.js:2151:5
    at done (http://localhost:8989/pouchdb-3.5.0.js:9103:9)
    at http://localhost:8989/pouchdb-3.5.0.js:9078:14
    at Array.forEach (native)
    at Object.preprocessAttachments (http://localhost:8989/pouchdb-3.5.0.js:9072:12)
    at idbBulkDocs (http://localhost:8989/pouchdb-3.5.0.js:2147:9)
    at PouchDB.idb_bulkDocs [as _bulkDocs] (http://localhost:8989/pouchdb-3.5.0.js:3016:5)"
```

**Comment by nolanlawson** [comment] 2015-05-08 12:29
This is weird; I can only reproduce this when I'm using huge documents.

**Comment by nolanlawson** [comment] 2015-05-08 12:33
Might be related to the size: 

```
"Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing."
"InvalidStateError"
INDEX_SIZE_ERR: 1
```

**Comment by daleharvey** [comment] 2015-10-05 11:48
Do you remember how huge? taking a look at reproducing this now

**Comment by daleharvey** [comment] 2015-11-14 01:19
Few months, hasnt been reported and cant reproduce, closing some of these old ones out, please reopen if there is indication this is still a bug

**Closed by daleharvey** 2015-11-14 01:19 UTC
Labels: bug
