### ISSUE TITLE
db.info() never resolves when low on disk space on Chromium (QuotaExceededError)

### ISSUE THREAD

**Issue by sigmike** [pouchdb/pouchdb#6817] opened 2017-10-30 11:29 UTC
### Issue

When low on disk space Chromium refuses to make the first transaction when `db.info()` is called and the promise is never fulfilled or rejected (so we don't get any error message).

Apparently it happens when there's less than 1% available on the disk.

Adding an `onerror` handler on the transaction actually makes the error displayed on the console (but the promise is still not rejected). I made the change on the compiled files so I'm not sure where it is in the source code, but I think it's [there](https://github.com/pouchdb/pouchdb/blob/01ba42da361cf2925cf12a81a8417935c66667f2/packages/node_modules/pouchdb-adapter-idb/src/index.js#L754). Adding `txn.onabort = function() {}` just before this line makes the `idb.onabort` called with the actual error (a `DOMException` with the name `QuotaExceededError`).

### Info
- Environment: Browser
- Platform: Chromium 59, Linux
- Adapter: IndexedDB
- Server: N/A

### Reproduce

* Make your system have less than 1% of available disk space
* Go to http://jsbin.com/dodepuxawe/edit?js,console with Chromium (Chrome probably works too)
* Click "Run". If the problem is reproduced you should not have "fulfilled" in the console.

**Comment by webnoob** [comment] 2017-11-03 20:06
I can second this. I've just been running into an issue on Chrome locally and have been banging my head against a wall. Turns out, I have less than 1% disk space and I get no message to say what's wrong:

I trigger replication manually and call the following code (console logs are for debugging).

When I have 1% disk space, I don't see anything except `Begin Replication`.

```
console.log('Begin Replication...')
this.getLocalDb().then(function (localDb) {
	localDb.sync(liveDb, {
	  live: false,
	  retry: false,
	  batch_size: 500
	}).on('paused', function (info) {
	  // console.log('PAUSE')
	  // console.log(info)
	}).on('change', function (info) {
	  console.log('Replication Change Found:')
	  console.log(info)
	  typeof this.onSyncUpdateProgressCallback === 'function' && this.onSyncUpdateProgressCallback(info)
	}).on('complete', function (info) {
	  console.log('Replication Complete:')
	  console.log(info)
	  var requiresReload = info.pull.docs_written > 0 || info.pull.docs_read > 0 || info.push.docs_written > 0 || info.push.docs_read > 0
	  if (requiresReload) {
		typeof this.onSyncCompleteCallback === 'function' && this.onSyncCompleteCallback(info)
	  } else {
		typeof this.onNoSyncRequiredCallback === 'function' && this.onNoSyncRequiredCallback(info)
	  }
	  resolve(info)
	}).on('error', function (err) {
	  console.log('Replication Error:::')
	  console.log(err)
	  if (err.message === 'getCheckpoint rejected with ') {
		// Don't need to resolve anything here as we resolved it above and nothing will have
		// changed as no connection is available.
		console.log('No live connection available, return local (without sync).')
	  } else {
		typeof this.onSyncErrorCallback === 'function' && this.onSyncErrorCallback(err)
		reject(err)
	  }
	}.bind(this))
  }.bind(this))
}.bind(this))
```

**Comment by webnoob** [comment] 2018-01-03 15:27
This is still an issue and is something that would be good to have some info on.

**Comment by daleharvey** [comment] 2018-01-15 14:42
Closing as dupe of https://github.com/pouchdb/pouchdb/issues/6954

**Closed by daleharvey** 2018-01-15 14:42 UTC
