### ISSUE TITLE
Issues in Internet Explorer (not working at all/no errors/no warnings/nothing)

### ISSUE THREAD

**Issue by lordgreg** [pouchdb/pouchdb#4377] opened 2015-09-29 13:02 UTC
Hi. We're currently having some serious issues getting PouchDB to run properly on Internet Explorer 10 or 11. The description of codeflow bottom works without any problems in Chrome, Chrome Canary, Firefox or Safari (or as cordova project on iOS or Android). It is pure IE problem which we cannot resolve.

1. data info is stored in JSON file (approx 1MB size)
2. read the file using normal $http procedure by angular
3. loop through elements from JSON and store them locally using PouchDB. 
4. It takes approx. 20 seconds because of complexity of data, but once this is done, we can load data on next refresh directly using PouchDB. 

The problem in Internet Explorer however is, that we are not getting ANY error using any catch block, any console output or anything similar. Console.log stays empty. No warnings, no errors.

Weird thing however, we found a way that this feature sometimes works in IE:
1. clear local data/cache in IE. 
2. close IE
3. open it and open your site with PouchDB usage
4. warning will appear that your app is exceeding data limit and if you want to allow it. if you press yes and wait 2 minutes, it will work.
5. if you now reopen IE it won't work anymore (no output)
6. if you refresh the page right away, it won't work anymore.

There is just one usecase where i've found a similar problem form someone, here: http://stackoverflow.com/questions/14717739/storage-limit-for-indexeddb-on-ie10

To extend my problem a bit, here's the code:
1. First, we wait for all promises to complete
```
    // preload data and setup databases
    $q.all([ProductFinder.loadProducts(), ProductFinder.loadAnswerMappings(), QuestionService.init(), UserBrochureService.init(), CountryService.init(), Imprint.loadImprint()])
    .then(function () {
      ...
```
2. We define each PouchDB like this:
```
  this.init = function () {
    /*globals PouchDB*/
    productsDB = new PouchDB('products');
    mappingDB = new PouchDB('mappings');
  };
  this.init();
```

3. Each function above (point 1) starts its own PouchDB loading/saving like this:
```
  this.loadProducts = function () {
    if (this.products.loaded) {
      return $q.when(this.products.loaded);
    }
    var that = this;
    return $http.get('main/assets/resources/products.json')
    .then(function (result) {
      that.products.loaded = true;
      var products = result.data;
      return productsDB.get('products-settings')
      .then(function (settings) {
        if (settings.version !== result.data.version) {

          // delete old database to avoid document conflicts
          return productsDB.destroy().then(function () {
            // create new instance of deleted productsDB
            that.init();
            // when data is retrieved from file, we save all products to db
            return saveProductsToDatabase(products, {
              version: '0.0.1',
              createDate: new Date().getTime()
            });
          }).catch(function (error) {
            $log.log(error);
          });
        }
      }).catch(function () {
        return saveProductsToDatabase(products, {
          version: '0.0.1',
          createDate: new Date().getTime()
        });
      });
    });
  };
```
4. `saveProductsToDatabase` is function, which starts loading:
```
  var saveProductsToDatabase = function (products, settings) {
    angular.forEach(products, function (item) {
      item._id = item.uuid;
    });
    return $q.when(productsDB.bulkDocs(products)
    .then(function () {
      productsDB.put({
        version: settings.version,
        createDate: settings.createDate
      }, 'products-settings');
    }).catch(function (err) {
      $log.log(err);
    })
    .then(function () {
      return productsDB.createIndex({
        index: {
          fields: ['uuid']
        }
      }).catch(function (err) {
        // ouch, an error
        $log.log(err);
      });
    }));
  };
```
5. The implementation, as said, works without any problems in other browsers. Also, if we remove some promise requests and we only wait for few:
From:
```
    $q.all([ProductFinder.loadProducts(), ProductFinder.loadAnswerMappings(), QuestionService.init(), UserBrochureService.init(), CountryService.init(), Imprint.loadImprint()])
```
to 
```
    $q.all([QuestionService.init(), UserBrochureService.init(), CountryService.init(), Imprint.loadImprint()])
```
or to
```
    $q.all([ProductFinder.loadProducts(), ProductFinder.loadAnswerMappings(), QuestionService.init()])
```
it will work. But with all requests (6 files to parse and save to db), it won't. 

File sizes are:
```
answer_products.json = 550KB
countries = 18KB
product_groups = 291B
products = 121KB
question = 26KB
```

Talking with Dale on IRC channel, he suggested I should pull his commit and try with nightly version. So I did, enabled extra debug and here is extra results at the end, that never ends:
```
ouchdb:api mappings-mrview-9ac5a0de5e3cd19cfd70b926e79f33d9 +13msget_local/lastSeq 
 pouchdb:api mappings-mrview-9ac5a0de5e3cd19cfd70b926e79f33d9 +6msgetsuccess[object Object] 
 pouchdb:api mappings-mrview-9ac5a0de5e3cd19cfd70b926e79f33d9 +9msbulkDocs[object Object] 
 pouchdb:api mappings-mrview-9ac5a0de5e3cd19cfd70b926e79f33d9 +56msbulkDocssuccess[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] 
 pouchdb:api mappings-mrview-9ac5a0de5e3cd19cfd70b926e79f33d9 +6msallDocs[object Object] 
 pouchdb:api mappings-mrview-9ac5a0de5e3cd19cfd70b926e79f33d9 +1msallDocssuccess[object Object] 
 engine.io-client:socket writing ping packet - expecting pong within 60000ms +5s 
 engine.io-client:socket flushing 1 packets in socket +0ms 
 engine.io-client:socket socket receive: type "pong", data "undefined" +10ms 
 engine.io-client:socket writing ping packet - expecting pong within 60000ms +5s 
 engine.io-client:socket flushing 1 packets in socket +0ms 
 engine.io-client:socket socket receive: type "pong", data "undefined" +1ms 
 engine.io-client:socket writing ping packet - expecting pong within 60000ms +5s 
 engine.io-client:socket flushing 1 packets in socket +0ms 
 engine.io-client:socket socket receive: type "pong", data "undefined" +2ms 
 engine.io-client:socket writing ping packet - expecting pong within 60000ms +5s 
 engine.io-client:socket flushing 1 packets in socket +1ms 
 engine.io-client:socket socket receive: type "pong", data "undefined" +8ms 
 engine.io-client:socket writing ping packet - expecting pong within 60000ms +5s 
 engine.io-client:socket flushing 1 packets in socket +0ms 
 engine.io-client:socket socket receive: type "pong", data "undefined" +2ms 
 engine.io-client:socket writing ping packet - expecting pong within 60000ms +5s 
 engine.io-client:socket flushing 1 packets in socket +0ms 
 engine.io-client:socket socket receive: type "pong", data "undefined" +16ms 
```

Can I get some info about specific problem (if there is any?) or if you need more info, please tell me what do you need, I'll try to copy/paste as many info as possible.

Thank you developers! :+1:

**Comment by nolanlawson** [comment] 2015-09-30 03:16
So you're not going to like this answer, but in my experience IE/Edge just has one of the most unstable implementations of IndexedDB (weird behavior, crashes, inconsistencies). I've filed [several bugs](https://connect.microsoft.com/IE/SearchResults.aspx?UserHandle=Nolan%20Lawson) on them over the years and they haven't made any progress yet (not a single bug closed).

We've written a TON of workarounds in PouchDB to avoid various IE bugs, but basically we're at a state right now where we can only be sure that our tests all pass, however, at the edges (e.g. inserting a large amount of data, like you are doing), you're probably going to run into issues.

Describing your setup is helpful, but what would be most helpful (for both us and the IE/Edge team) is a small HTML page to reproduce your results. My guess is that you can reproduce it by just inserting a lot of data.

And you're in luck, because I actually wrote a tool this weekend to insert a lot of data into IndexedDB/LocalStorage/WebSQL using various methods. I'm sure if you open it in IE10 you will be able to simulate your crashes with just a few clicks (I haven't tried IE10 yet): http://nolanlawson.github.io/database-comparison/

If not, like I said, please write a reproducible test case and (ideally!) file it on Microsoft's bug tracker. They haven't made much progress, but I do believe they're listening. And if enough of us whine and provide incontrovertible evidence of their bugs, they might even get around to fixing them. :)

**Comment by nolanlawson** [comment] 2015-09-30 03:26
Do you see this issue in Edge or only IE 10/11?

**Comment by nolanlawson** [comment] 2015-09-30 03:32
OK, I just tried database-comparison in IE 10 and all I saw was this cool "page is not responding" message after I inserted too much data. Dunno if it's related to your issue

![screenshot](https://cloud.githubusercontent.com/assets/283842/10183834/5360259a-6702-11e5-8e00-505ee9f45694.png)

**Comment by nolanlawson** [comment] 2015-09-30 03:34
Also another answer you may or may not like: PouchDB does add overhead due to its sync-optimized schema. That means that it stores more data under the hood for the same number of documents than something like Dexie or LocalForage. So if you are not using PouchDB sync, you may be better off using Dexie/LocalForage.

**Comment by daleharvey** [comment] 2015-10-05 12:40
@lordgreg So yeh, not responding sounds like you are hitting the quota limit and getting stuck, the main thing is are definitely catching all the errors locally? (ie could there be a `put.then` that doesnt have a catch. 

Master should have fixed the problem of pouchdb not responding when hitting the quota limit, I have been using https://github.com/pouchdb/pouchdb/blob/master/tests/capacity/index.html to test that and should hopefully be easy enough for you to check it as well.

**Comment by lordgreg** [comment] 2015-10-05 13:27
Hi @nolanlawson and @daleharvey and thank you both for replying. As Dale already suggested using his commit last week when we discussed over IRC, we found out, that it actually works. I was still testing nightlies last week and got mixed results. I'm not giving a full review here just yet but I can tell that sometimes, when I refresh the page with developer console opened, the stuff breaks itself and I start getting Corrupt DB errors. Since we're also using LiveReload on the page, when I update my code and the LiveReload hits in, the db also gets corrupted. But in most other cases, it works. So far, better as with latest stable. I still have to load/reload the page few 100 or 1000 times to test everything properly. 

I am not sure now, @daleharvey if you did some more changes to the code or not, so I don't know if I should pick another nightly or not. Please also be aware that when using latest hash commit in bower, I get no pouchdb.min.js or pouchdb.js. I have to get these manually hitting another command later. This is kind of a struggle since I wanted to use the specific commit hash in bower on our Jenkins server that is generating code but I cannot do that, since he won't get any js in that download.

I will post more updates in a week or two when our team tests the site through and through. 

Until then, thank you very much for your kindness and replies. :+1:

**Comment by SevTho** [comment] 2015-11-23 14:34
Hi (this is the same project @lordgreg was working on). We are currently facing some issues with PouchDB 5.0 on Internet Explorer 11. Whenever a user opens our webapp for the first time or empties the cache PouchDB crashes and shows the following error: Database has a global failure UnknownError. After reloading the page everything is fine. We tried to break down our problem in small steps, this is what we got:

1. Open the Page
--> Sometimes it works straight up
--> Sometimes it fails to open the page and shows the error: Database has a global failure UnknownError
--> Sometimes it shows the error: Failed to open indexedDB, are you in private browsing mode? (however this happens really rarely)
2. Reload the Page
--> Everything works fine

We dont know where the error is coming from or how we could fix it.

Many thanks for your help! :thumbsup:

**Comment by ffle** [comment] 2015-11-25 18:26
Tried the tutorial following nolanlawson's get started video. When using IE 11 in windows 7, it encountered error in app.js
var db = new PouchDB('todos');	
'PouchDB' is undefined
It kind of worked in Chrome and Firefox except it failed to load the base.css file.

**Comment by lordgreg** [comment] 2015-11-25 18:33
@ffle actually this has nothing to do with our problem but, you could add PouchDB in globals or .eslintrc

**Comment by nolanlawson** [comment] 2015-12-13 19:55
IE seems to have some serious stability issues, especially involving race conditions and data corruption. I've filed [this issue](https://connect.microsoft.com/IE/feedback/details/1009247/indexeddb-gets-corrupted-and-stops-responding) on them, but got very little feedback.

Since I don't have much experience in this domain, my advice to @lordgreg/@ffe/@SevTho/etc. would be to find a reproducible test case and file it on the Microsoft Connect page. PouchDB can't do much here except cross our fingers and hope it doesn't crash.

It may sometimes feel like browser vendors are off in some ivory tower, deaf to our complaints, but in fact they do listen. It's just that they have a million things on their plate at any given time, and they have to prioritize the things that are easily fixable. So they're much more likely to address these sorts of issues if we can help them out by providing reproducible test cases.

I'm closing this issue because I don't think there's anything PouchDB can do.

**Closed by nolanlawson** 2015-12-13 19:55 UTC
Labels: bug
