### ISSUE TITLE
Getting Started Guide not Creating Database in Chrome

### ISSUE THREAD

**Issue by srsudar** [pouchdb/pouchdb#3780] opened 2015-05-02 06:17 UTC
I'm trying to follow the instructions in the [getting started guide](http://pouchdb.com/getting-started.html) and I'm not able to get it running in Chrome. The call `var db = new PouchDB('todo');` doesn't affect the IndexedDB in the resources tab. I've tried downloading the master and known working versions, which tell me "There was a problem syncing" under the TODO list.

The same demo functions correctly in Firefox.

Am I missing something in configuration? Should it not work in Chrome by default? Any other ideas?

**Comment by nolanlawson** [comment] 2015-05-02 18:31
"There was a problem syncing" is just the user-facing error in the interface. What error do you see in the console? Or do you see an error in the network tab?

The "getting start" guide worked fine for me in Chrome, as I demonstrated in that Youtube video. :)

**Comment by srsudar** [comment] 2015-05-02 18:45
Yeah, I saw that in the video, which makes me especially confused.

When I try to run the functioning app, I see `Uncaught TypeError: Cannot read property 'rows' of undefined` at `app.js` line 38.

More interestingly, when I try `var db = new PouchDB('test')`, I get no output.

`db.put({_id: '12345', data: 'foo'});` gives me an `AbortError` with a status 500.

**Comment by nolanlawson** [comment] 2015-05-02 22:33
Hm, try blowing away your local data and trying again. Unfortunately sometimes Chrome/Firefox have some inconsistent IndexedDB behavior that only seems to be solved by a complete wipe. :( I use [this Chrome extension](https://chrome.google.com/webstore/detail/clearbrowserdata/apehfighfmpoieeniallefdeibodgmmb) constantly.

**Comment by srsudar** [comment] 2015-05-03 01:21
That extension didn't do it for me, but opening in an incognito window did. So I'm not sure what has gone wrong, but it appears to be on my end.

**Comment by nolanlawson** [comment] 2015-05-03 13:55
That's really odd. Which version of chrome are you using? Did you try Chromium/Canary as an alternative?

**Comment by srsudar** [comment] 2015-05-07 15:29
I am on Version 42.0.2311.135 (64-bit). I did not try Chomium/Canary, just
the incognito window. My lab does development that includes purging w3sql
database purging from time to time, so I wouldn't be surprised if I had
somehow gotten my databases into a weird state. I'm surprised pouch wasn't
giving me errors, though.

**Comment by nolanlawson** [comment] 2015-05-08 02:49
Oh wait, I missed the fact that you were using an incognito window. PouchDB often fails in private/incognito mode because browsers either disallow IndexedDB or just write to it but don't let you read from it. Not sure what Chrome does.

**Comment by srsudar** [comment] 2015-05-08 02:51
Oh crazy! I was trying to say that it WORKED in incognito, and that was the
only thing I tried other than a normal browsing session in the version of
Chrome I listed above.

**Comment by daleharvey** [comment] 2015-07-11 15:53
Yup it looks like chrome does actually let you write indexeddb in incognito and likely wipes it out, but yeh sounds like you hit a weird state in chrome which we cant do anything about until we get a reproducable profile so closing this out, cheers

**Closed by daleharvey** 2015-07-11 15:53 UTC
