### ISSUE TITLE
Feature Request Check if db is accessible

### ISSUE THREAD

**Issue by desertzebra** [pouchdb/pouchdb#2683] opened 2014-08-25 17:30 UTC
Considering [IndexedDb access errors](https://github.com/pouchdb/pouchdb/issues/2572), is there a check/test during init that checks if the Db is accessible? e.g. When I run a file in FF's private mode or as a local file(rather than through a webserver) pouchDb can tell me that it is not possible for it to access the Db, rather than failing silently or throwing an unknown error. I haven't tested it on any other environment so I am not sure what the results would be there.

**Comment by daleharvey** [comment] 2015-07-07 12:35
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/4010

**Closed by daleharvey** 2015-07-07 12:35 UTC
