### ISSUE TITLE
PouchDB custom build

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4449] opened 2015-10-10 15:51 UTC
I think our build has gotten a bit too big (~47KB). There's nothing we can reasonably remove without removing serious functionality, though.

So I would like to create a custom build. You should be able to build a PouchDB that is missing:

* idb
* websql
* migrations
* http
* sync/replicate
* mapreduce

I think this is technically possible both with a browserifable script and a web UI builder. So the web UI builder would both allow you to download a file and display a browserifiable file that would probably look like this:

```js
var PouchDB = require('pouchdb/custom/pouchdb');
require('pouchdb/custom/idb');
// no websql
require('pouchdb/custom/mapreduce');
// no http
// no migrations
// no replicate/sync
module.exports = PouchDB;
```

I'll take a stab at it this weekend.

**Comment by nickcolley** [comment] 2015-10-10 17:15
We could think about https://github.com/pouchdb/pouchdb/issues/4199 alongside this.

**Comment by daleharvey** [comment] 2015-10-12 13:12
So I think a custom build is a nice thing to offer to users, however I do not think it is a solution for having to large a distribution. I would still like to make sure we have a "this is pouchdb" distribution that has sensible defaults for most users while being as small as possible.

**Comment by nolanlawson** [comment] 2015-10-12 14:13
I wish we could make it smaller, but aside from removing stuff for edge cases (vuvuzela, websql, blob shims), the only big win I see would be from using rollup, which means switching to ES6 modules: https://github.com/nolanlawson/rollup-comparison.

I consider this more of a stopgap while our build is too big; also a good transitional step. E.g. when we drop WebSQL support, that will just mean that the "this is pouchdb" distribution will lose the "require websql" line from its custom build.

**Comment by nolanlawson** [comment] 2016-01-01 19:32
Just investigated, and unfortunately Rollup and tree-shaking don't help us out much here: https://github.com/nolanlawson/test-tree-shaking

I think the best solution is to basically ask users to write their own `index.js` and exclude what they don't want. It's the simplest to support.

**Comment by nickcolley** [comment] 2016-01-25 14:17
:+1: for having our normal builds plus the instructions to build their one index.js

**Comment by kidwm** [comment] 2016-02-12 07:55
@nolanlawson is it possible to release an ES Modules build like Redux did ?
BTW, I tried to bundle my pouchdb app but always failed with these setting:
```
plugins: [
		babel({
			"presets": ["es2015-rollup"]
		}),
		nodeResolve({
			jsnext: true,
			main: true
		}),
		commonjs({
			include: 'node_modules/**'
		})
	]
```

**Comment by nolanlawson** [comment] 2016-02-13 17:36
It's unfortunately not possible because the `PouchDB` object is a non-static object. ES6 module tree-shaking works best for static functions.

**Comment by daleharvey** [comment] 2016-05-10 22:39
Dupe of https://github.com/pouchdb/pouchdb/issues/5128

**Closed by daleharvey** 2016-05-10 22:39 UTC
Labels: enhancement
