### ISSUE TITLE
How can we detect if a document is in conflict using PouchDB.find?

### ISSUE THREAD

**Issue by kgathuru** [pouchdb/pouchdb#6821] opened 2017-11-02 16:28 UTC
### Issue
db.allDocs and db.get both have an option for including conflicts ({conflicts: true}) However, pouch db find does not. Now that our project has moved all data loading responsibilities to pouchDb.find, we have no way to tell if the documents have errors or not.

How can we detect if a document is in conflict using PouchDB.find?

### Info
- Environment: (browser)
- framework: Angular2+
- Server: (CouchDB)

**Comment by afinne** [comment] 2017-11-03 15:52
This might be mis-information, but I seem to recall that resolving issues in PouchDB might not be the best idea due to... something how it generates... something. 

Instead issue resolving could be performed when talking directly to CouchDB, not to a replicated PouchDB. 

I'm really sorry that I don't have anything concrete at the moment.

**Comment by kgathuru** [comment] 2018-01-09 15:29
I have added this issue as a feature request in https://github.com/pouchdb/pouchdb/issues/6996

**Comment by daleharvey** [comment] 2018-01-15 12:46
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/6996

**Closed by daleharvey** 2018-01-15 12:46 UTC
