### ISSUE TITLE
Webpack+Electron error: define cannot be used indirect

### ISSUE THREAD

**Issue by Nishanth2** [pouchdb/pouchdb#5676] opened 2016-09-12 02:47 UTC
### Issue
Using Pouchdb-browser or Pouchdb-node or Pouchdb ,,

Getting The same Error 
Uncaught Error: define cannot be used indirect amd-define.js:1

I am using Electron + Anuglar 2+ webpack 1.13.2

btw I am just a newbie here ,

Is there Any solution for it ?

**Comment by nickcolley** [comment] 2016-09-12 08:57
Hey @Nishanth2 😄 

Can you supply an example of the code you're using? Thanks!

**Comment by nolanlawson** [comment] 2016-09-13 01:05
This looks like a duplicate of https://github.com/pouchdb/pouchdb/issues/5312, which was closed because we couldn't find a reproducible test case.

Last time I recall I spent an hour or two trying to track this down. Seemed like a Webpack/Electron bug, but I could never figure it out. :confused:

**Comment by Nishanth2** [comment] 2016-09-13 09:25
![amd define error](https://cloud.githubusercontent.com/assets/2277794/18468474/cbd9f1ea-79c1-11e6-9160-d9e6afc731dd.jpg)

Hi, This is the error I was getting when i Use Pouchdb or Pouch browser or pouch node ,
and i am using older version of electron 1.2.0, and angular Rc5

and I Found 2 New boilerplate for Electron  with  Angular Rc6 ..

**Comment by Nishanth2** [comment] 2016-09-13 09:30
using The Following Repo  
https://github.com/PLYoung/electron-angular2

 i am Getting Different Error ... 
![cookie_error](https://cloud.githubusercontent.com/assets/2277794/18468715/c5a86cba-79c2-11e6-908b-3159b5fa5f12.jpg)

**Comment by Nishanth2** [comment] 2016-09-13 09:40
And I Found  1 More  Repo 
 **Actually   Worked Like a MAGIC !** 
https://github.com/bertofer/angular2-electron 

![epic works](https://cloud.githubusercontent.com/assets/2277794/18468796/27774754-79c3-11e6-83be-58bccae5530e.jpg)

But with some Following Warning  in the console 
![works_with_warning](https://cloud.githubusercontent.com/assets/2277794/18468817/41f7d5f8-79c3-11e6-8c3b-d7404cb07e18.jpg)

And One More strange thing  to me ,  i installed using npm pouchdb, only
but it uses leveldb adapter  not indexdb ,
,
Only problem with this repo is Livereload is not working it's related to electron connect maybe ,

Actually  i was using  Angularfire2   only  But   For this app itz need Must Offline features  and  i Found Pouchdb   ..  
Just Need TO test the async  and live sync to couchdb now >>

And Thank  You .......... Finally magic works :+1:

**Comment by nolanlawson** [comment] 2016-09-13 15:54
The error you're seeing in https://github.com/pouchdb/pouchdb/issues/5676#issuecomment-246626834 is due to webpack trying to bundle `leveldown` which requires a package.json despite the fact that this breaks in webpack unless you're using the json-loader. However this bug only occurs in the first place becuase somehow you are bundling pouchdb-node instead of pouchdb-browser.

In any case, it sounds like you found a good fix, so should we close this issue?

**Comment by Nishanth2** [comment] 2016-09-13 21:30
@nolanlawson  Yes You can Close this issue .. Thank You :)

**Comment by Nishanth2** [comment] 2016-09-13 22:59
@nolanlawson  leveldb Adapter not working ... Only Pouchdb-browser working !!

Using require('pouchdb) I can't get the database values and it shows the following erros
![leveldb_error](https://cloud.githubusercontent.com/assets/2277794/18494406/9232d750-7a33-11e6-8a5e-c80ac619e390.jpg)

Using require ('pouchdb-browser) .. I can get the values and it's working !
![pouch_browser](https://cloud.githubusercontent.com/assets/2277794/18494425/ac539cc8-7a33-11e6-9c51-2abfa77ffbcd.jpg)

Pouchdb-browser stores data in the browser indexdb
apart from that is there any advantage using pouchdb-leveldb or just the same like pouchdb-browser in performance wise ,
Anyway ...
@nolanlawson  **Atleast  pouchdb-browser working  ..**

Yes You can Close the thread .. Thank You :)

**Comment by Nishanth2** [comment] 2016-09-14 02:54
@nolanlawson  i am using the following tutorial for livesync and async update on dom wtihout refreshing the page,
http://www.joshmorony.com/offline-syncing-in-ionic-2-with-pouchdb-couchdb/

But the problem is  I am Getting memory leak detected error whenever i routing the page,
example from page A to B !  home -> about   or about  -> home,
![memoryleak](https://cloud.githubusercontent.com/assets/2277794/18498356/75ddec6e-7a53-11e6-8c07-5a828a9118f2.jpg)

And Async is not working   ,  i mean whenever i update the couch db database manually the dom is not updating  i need to refresh the page manually  to  see the changes !,

Updating the Couchdb Manually screenshot
![beforereload](https://cloud.githubusercontent.com/assets/2277794/18498502/7d7ed90a-7a54-11e6-97a8-91586f1e615a.jpg)

After reloading the page screenshot .
![after reload](https://cloud.githubusercontent.com/assets/2277794/18498516/90585d6c-7a54-11e6-970c-b6757a4bce61.jpg)


**@nolanlawson   Is it possible to Use  Angular2 with pocuhdb  + couchdb  + electron ?.

looks like i am stucked now :cry:**

**Comment by nolanlawson** [comment] 2016-09-15 01:30
The reason the memory leak happens is because of adding too many event listeners. You can increase the limit, but most likely you have some kind of leak in your code because most normal usage of PouchDB shouldn't cause the number of listeners to exceed 10. Please see the FAQs: https://pouchdb.com/errors.html#event_emitter_limit

**Comment by nolanlawson** [comment] 2016-09-15 01:31
Also yes it is slightly more efficient to use the leveldb adapter in Electron instead of the websql/idb adapter, but it probably doesn't make an enormous difference.

**Closed by nolanlawson** 2016-09-15 01:30 UTC
Labels: bug, needs reproducing
