### ISSUE TITLE
Sync broken

### ISSUE THREAD

**Issue by AlpineTech** [pouchdb/pouchdb#5392] opened 2016-06-23 13:29 UTC
Version:
1) PouchDB 5.0
2) CouchDB 1.6.1

Devices:
1) four Android tablets, all up to date with updates
2) one IOS tablet, also up to date

Adapters:
1) WebSQL on Android
2) default on IOS

Server:
1) CouchDB on Amazon Linux instance

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

We recently started field trials of Fuels Measure (http://fieldmeasures.org/product/fuels-measure/) a mobile app on Android and IOS which depends on PouchDB  5.0 and CouchDB 1.6.1.  After collecting 344 documents on five devices (four Android tablets and one IOS tablet) out in the field I then attempted to sync the documents on those with a CouchDB database on the server.  All of the devices were set to replicate up the same database, but down from a different database.  To do this I connected all of the devices to our high-speed wifi at the office and then started the app on each device.  At first I received only about 80 documents in the CouchDB database.  Next, I shut down the app on each device and restarted it.  Each time, I noticed about 2 documents were replicated up to the server per device.  I repeated this on all the devices until I finally achieved replication of 216 documents up to the database.  However, the server application still failed to function properly because of the missing documents still left on the device. I checked the error logs on each device and confirmed there were no error messages from PouchDB.  I also created a special build of the mobile app which put the PouchDB sync call in a "setInterval" loop to re-call the sync every 5 minutes.  That did nothing to solve the issue.  Here are some additional notes:

1) Some of the documents in the PouchDB database contain small thumbnail base64 images (150px x 150px).  These base64 images are embedded in the documents, not attached.  Some of those images are getting replicated up to the server.

2) Here are the options:

 var opts = {
            continuous: true,
            complete: syncComplete,
            onChange: syncChange
        };        

3) The syncComplete and syncChange functions are not getting called.

4) I will attach the main js code file to this issue.

**Comment by AlpineTech** [comment] 2016-06-23 13:30
[fdcModel.zip](https://github.com/pouchdb/pouchdb/files/330042/fdcModel.zip)

**Comment by seigel** [comment] 2016-06-30 04:03
Have you tried adding 
```
retry: true
```
to your opts and moving the complete and change to 

```
replicationReference.on("change", function (info) {
...
});

```
type hook ups?

Was there a bug with attachments or am I thinking CouchbaseLite?

**Comment by AlpineTech** [comment] 2016-06-30 12:57
Thank you for the suggestion.  I've since upgraded to version 5.4.4, added
that retry option and so far the issue has not occurred again.

On Wed, Jun 29, 2016 at 10:03 PM, James Seigel <notifications@github.com>
wrote:

> Have you tried adding
>
> retry: true
>
> to your opts and moving the complete and change to
>
> replicationReference.on("change", function (info) {
> ...
> });
>
>
> type hook ups?
>
> Was there a bug with attachments or am I thinking CouchbaseLite?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/5392#issuecomment-229554244>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASxBvHcxk_haqR-aOcYwCMQQWeTnZmmGks5qQ0ACgaJpZM4I8z1B>
> .
>



-- 
<http://www.alpinetechsolutions.com>
http://www.alpinetechsolutions.com

**Comment by nickcolley** [comment] 2016-06-30 13:09
Thanks a lot for raising @AlpineTech, going to close this out since it looks like you've got the issue resolved.

Please re-open if this is not the case and the issue is still present.

Thanks 👍  🎉

**Closed by nickcolley** 2016-06-30 13:09 UTC
Labels: bug, has test case
