### ISSUE TITLE
Adding "active_only" which is a couchbase sync gateway feature

### ISSUE THREAD

**Issue by mjosephd** [pouchdb/pouchdb#6513] opened 2017-05-18 13:25 UTC
### Issue
This is not an issue but merely posted to get pouchdb maintainers opinion on adding a new flag which is exclusive to couchbase sync gateway. Since the maintainers are mainly focused on the couchdb compatibility the question is if we would be able to work on this change would the maintainers accept the PR for this then.

The Couchbase Sync Gateway `_changes` API has a flag called `active_only` which is described as the following.

> Default is false. When true, the changes response doesn't include either deleted documents, or notification for documents that the user no longer has access to.

While this is couchbase specific I believe it would benefit the apps for which we are using pouchdb and sync gateway together.

The use case is as the following
If an existing user installs an application on a new device the user gets all deleted documents and notification documents in the initial sync, and in our particular use case there can be many command type documents which aren't entity but throw away documents. So when an existing user syncs on a new device there are many thousands of unwanted deleted and removed documents. It would be great if we can ignore all of this in the change feed.

The high level proposal would be the following, add a parameter json to the "changes" code

1) `active_only` which will look like, where if the given `active_only` value is not null it implies that it is true by default, and then `load_active_only_false_on_initial_sync` can be used to state if it is constant or only ignore non active documents in the initial sync (this is just off the top of my head, we could come up with something better)

```
active_only: {
  load_active_only_false_on_initial_sync: true/false
}
```

2) Then check in the case of `load_active_only_false_on_initial_sync` being true we check if the sequence is null, if the sequence number given is null it is because it is the initial sync. Then for that `_changes` call only we add the `active_only` flag so deleted and removed documents will be ignored on the initial sync then.

**Comment by mjosephd** [comment] 2017-05-18 13:25
I am assuming this is a decision @nolanlawson and @daleharvey needs to take.

**Comment by nolanlawson** [comment] 2017-05-24 02:29
Hm, my first question is whether or not this could be solved in a plugin, e.g. by forking `pouchdb-replication`. If so, then that's where it should probably go.

The second question is what the actual code would look like; if it's a fairly small change then it's probably not a big deal to add to core, but if not then yeah it'd be best to make external to the project. So the first step would be a PR (including documentation changes) to see what this would look like. :smiley:

**Comment by mjosephd** [comment] 2017-05-24 09:00
Could you be kind enough to link me to the pouchdb-replication repository, a quick search showed me this npm link https://www.npmjs.com/package/pouchdb-replication, however it seems to point to the main pouchdb github repository.

Will have a look if I can use it as a plugin before submitting a PR for consideration.

**Comment by daleharvey** [comment] 2017-05-24 09:10
Sorry meant to update this as we discussed it on IRC, pretty much the same conclusion though would be best done outside the pouchdb repo, this could entirely be done with https://github.com/pouchdb/pouchdb/issues/5322 (including the workaround that can be done now, and the supported version when it lands)

**Comment by daleharvey** [comment] 2017-06-04 08:52
Closing as dupe of https://github.com/pouchdb/pouchdb/issues/5322

**Closed by daleharvey** 2017-06-04 08:52 UTC
