### ISSUE TITLE
Migrate away from "legacy" sublevel

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4294] opened 2015-09-09 11:49 UTC
So when I upgraded levelup/leveldown/sublevel (https://github.com/pouchdb/pouchdb/pull/4236), and specifically updated sublevel from v5 to v6, I had to [enable "legacy" mode](https://github.com/pouchdb/pouchdb/blob/8fd74079cb799d47a2a7679a7ed74d9c0c1aeacc/lib/adapters/leveldb/index.js#L4) in order to make sure we didn't break people with existing databases created using the LevelDB adapter.

There is [sublevel-migrate](https://github.com/calvinmetcalf/sublevel-migrate) written by our own @calvinmetcalf, so we can use it to migrate from old to new, but such a change will have to be added to [migrate.js](https://github.com/pouchdb/pouchdb/blob/8fd74079cb799d47a2a7679a7ed74d9c0c1aeacc/lib/deps/migrate.js), and ideally, we would add a new [migration test](https://github.com/pouchdb/pouchdb/blob/8fd74079cb799d47a2a7679a7ed74d9c0c1aeacc/tests/integration/test.migration.js). I also wonder what the performance implication will be of migrating a large-ish database, so I think it's worth measuring.

**Comment by daleharvey** [comment] 2015-10-21 15:51
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/4337, if we migrate away from it, no need to update

**Closed by daleharvey** 2015-10-21 15:51 UTC
Labels: help wanted
