### ISSUE TITLE
Enhancement Request: Trying to "mirror changes in a non-Pouch structure" is just ugly )-:

### ISSUE THREAD

**Issue by hepiyellow** [pouchdb/pouchdb#5725] opened 2016-09-27 22:12 UTC
Hi,

I quoted in the title from [changes documentation](https://pouchdb.com/guides/changes.html),
and just wanted to add that when a document is deleted then the document is not included (when include_docs is true), this makes it even harder to do such mirroring.
It forces me to store the document IDs in my non-Pouch structure so I can figure out which document was deleted.

When using multiple types of documents, I don't really use the couchDB document ID as my identifier (in the non-Pouch mirror). I use another document field as a key (and a field for the type)

**Why is the document not included? can it be changed?**

About not being able to distinguish from a new document and a modified one, that's not such a big problem because I can check if it exists by the key.

**Comment by nolanlawson** [comment] 2016-09-29 13:02
We follow the CouchDB convention on this. It could be that we do something incorrectly – when you merely add `_deleted: true` and then `put()`, it should retain all document fields. However I don't know if this document is included when you call `changes()` with `include_docs: true`.

If we differ from CouchDB's behavaior, then that's a bug, else I agree it's a bit unergonomic but the best thing would be to open an issue on CouchDB to change their implementation, then we can see if we can align without breaking the ecosystem. :)

**Comment by nolanlawson** [comment] 2016-10-24 02:17
Closing, please reopen as necessary. Seems to me that this is not a bug but rather just how CouchDB works though, although I could be mistaken

**Closed by nolanlawson** 2016-10-24 02:17 UTC
Labels: enhancement
