### ISSUE TITLE
PouchDB // CouchDB sync failed ONLY when revisions exist

### ISSUE THREAD

**Issue by Davidx7** [pouchdb/pouchdb#4012] opened 2015-06-29 11:42 UTC
CouchDB server 1.5.0
PouchDB 3.6.0 + Couchbase Lite 1.0.0 --> ```pouchDB(couchURL/dbName)```
Use: Cordova

Sync fails when revisions exist. 
When adding new documents to a db, one or more, then sync using ```pouchdb.replicate.to(remoteDB)``` everything works fine ```to``` and ```from``` no issues

Once any change is applied to the local pouchdb, of any kind, value, array, object, and a revision is created, in local db everything still displays fine, but sync fails with the message 

```Failed to load resource: the server responded with a status of 404 (Not found) http://localhost:5984/assets/01140?revs=true&open_revs=[%222-61078e66a072db33153ec38d2e80d984%22]&_nonce=1435575761494```

The revision _id ```2-61078e66a072db33153ec38d2e80d984``` is correct, or any other _rev after

If there is more than 1 revision, the link will show ```open_revs=[%223-{rest_of_rev_id}%22]```
-------
NOTE: the _rev that always gives the error, is the main one. It is not a passed _rev, it's the current, valid object. Fetching it locally will NOT cause errors. 
-------
Removing the object, using ```pouchDb.remove(docId)``` does NOT fix the sync problem. It still persists.  

CRUD code is working without any issues in local environment, the only problem is ```replicate.to()```

-------------------------------------------
This error of course triggers another error in Couchbase Lite because PouchDB is asking for something that doesn't exist

```error: true
message: "missing"
name: "not_found"
reason: "Router unable to route request to do_GET_Documentjava.lang.reflect.InvocationTargetException"```

**Comment by Davidx7** [comment] 2015-06-30 12:37
Looks like the same problem as here ::  #4008

**Comment by daleharvey** [comment] 2015-07-06 17:16
Yeh given the symptoms it may be the same, I have a patch up @ https://github.com/pouchdb/pouchdb/pull/4030

Going to close as a dupe of https://github.com/pouchdb/pouchdb/issues/4008 to keep discussion in one place

**Closed by daleharvey** 2015-07-06 17:16 UTC
