### ISSUE TITLE
PouchDB throw "Error: adapter is missing" on Windows Phone with Cordova

### ISSUE THREAD

**Issue by brunoravanhani** [pouchdb/pouchdb#4571] opened 2015-11-13 21:03 UTC
Hi, I'm trying to open the database on Windows 10 Mobile, but it throws the error "Adapter is missing" .Is there something that can help me? I'm using cordova.

**Comment by daleharvey** [comment] 2015-11-14 00:38
Yup there are some more details in a previously reported bug, closing as a dupe of https://github.com/pouchdb/pouchdb/issues/4062

**Closed by daleharvey** 2015-11-14 00:38 UTC
