### ISSUE TITLE
Mismatching checkpoints causes replication to start over from change 0

### ISSUE THREAD

**Issue by karlwestin** [pouchdb/pouchdb#3999] opened 2015-06-24 11:34 UTC
Trying to give a little bit of background to explain the issue:

We're replicating from a 'central', relatively well connected CouchDB, to a PouchDB embeddded in a Cordova app, that is running on android tablets. Those tablets are sometimes offline, sometimes running on very bad connections (think 50 kbps, 0.5-1s latency, some packet loss). Because of the bad connections, we're using very small `batch_size` (less than the number of outstanding requests the browser can have) to avoid timeouts. 

The scenario i describe below represents a replication of data from the central server, to the mobile device. Central = Source, Mobile = Target

In the screenshot here, you see PouchDB reading the replication last_sequence number from central, 3945, right after, it starts reading changes from last_seq 0. 
![http://i.imgur.com/n04z260.png](http://i.imgur.com/n04z260.png)

What happens is that the [comparison of replication state on Central/Mobile disagrees](https://github.com/pouchdb/pouchdb/blob/269e236faf302a4065267f2d0f5d17bc67b38c10/lib/replicate/checkpointer.js#L71), and therefore, returns to 0.

```
if (collate(targetDoc.last_seq, sourceDoc.last_seq) === 0) {
  return sourceDoc.last_seq;
}
return 0;
```

### Where does this difference come from?

When a replication batch is done, we PUT a checkpoint, first on Mobile (Target) then on Central (Source). If the PUT on Central fails, Mobile and Central will have different opinions on the state of replications. We have tried a solution where the PUT on Central would be retried 5x before failing, and if it fails, Mobile would roll back to its previous check point. The problem with this seems to be that when a PUT fails, Pouch can't know if the write failed, or if the write succeeded and we didnt get the response. So it seems half the time, a rollback is correct, and half the time the checkpoint shouldnt be rolled back. 

### Why is this a problem?

Unfortunately 'catching up with the changes', like pouch does now can be pretty slow for us. The problem is worse by the catch-up being non-deterministic. A device can spend an hour or two catching up on checkpoints, just to slip and go back to 0 just before it was time to read docs. (The central DB in our case has a sequence number around 20k, with batch_size 5 that takes a while). I understand that the main problem here is that our connection sucks, but it would be helpful to reach a solution where we can leave a device syncing over night, and know that it will not fall back to 0 again.

### Proposed solution

It seems from my very superficial understanding of the problem, that just choosing the smallest sequence number (i.e. if Central has 2200 and Target has 2204) would be good enough. But I know there are many aspects that i've missed. I also don't know how the CouchDB 2.0 last_seq arrays are gonna look. Therefore i'd like to ask for feedback on this suggestion before implementing a patch

**Comment by janl** [comment] 2015-06-24 20:57
I pointed the replication@couchdb.apache.org list to this issue in hopes to get some more advice from there.

**Comment by kxepal** [comment] 2015-06-24 21:07
Well, the fast fix that will helps here is to reimplement [couch_replicator algorith](https://github.com/apache/couchdb-couch-replicator/blob/master/src/couch_replicator.erl#L863-L906) which respects both checkpoints on source and targets and seeks any common point within replication log.

PouchDB here had implemented the very first step of this comparison that assumes that both source and target checkpoints are in sync which is very positive case.

**Comment by ermouth** [comment] 2015-06-25 02:18
I faced the problem about year ago when Pouch had no ability to memoize checkpoints. In cloudwall.me the problem is solved explicitly outside Pouch in this way:
* there is a proxy method for replication on top of Pouch;
* after succesful replication __to__ external URL this proxy fetches local DB seq and memoizes it to localStorage;
* after successful replication __from__ external DB it fetches remote DB seq and also memoizes it to localStorage;
* next time replication requested this shim first retrieves memoized seq and adds {since:lastMemoizedSeq} to Pouch sync request;
* if no memoized checkpoint found, replication starts with `{since:0}`.

Important note: local DB `.destroy` must be also proxied to ensure checkpoints memoized in localStorage are deleted on DB destroy. It‘s important since DB can be re-created – and if we had not delete our custom checkpoints, custom replicator skips old external docs on first replication.

**Comment by karlwestin** [comment] 2015-06-25 12:52
Thank you so much for your comments! I will attempt to implement those and report back next week!

**Comment by kocolosk** [comment] 2015-06-26 21:47
Yeah, that's annoying for sure. CouchDB addresses this problem by storing and analyzing a history of checkpoints; if the latest checkpoint information in the checkpoint docs on the source and target does not match we'll start looking for a common ancestor in the history of each, and start from that sequence instead of 0 if we find it:

https://github.com/apache/couchdb-couch-replicator/blob/9d010d/src/couch_replicator.erl#L863-L906

The internal replication employed between replicas in a CouchDB 2.0 cluster actually gets even smarter and instead of storing the last N checkpoints it keeps a distribution of checkpoints with exponentially decreasing granularity as you move back in time. @davisp and I worked this one and came up with a nice method for bucketing the checkpoints; it's some pretty dense Erlang but well-documented:

https://github.com/apache/couchdb-mem3/blob/3f229b27/src/mem3_rpc.erl#L153-L257

**Comment by kocolosk** [comment] 2015-06-26 21:52
I can't speak to the concurrency control in PouchDB itself but in the case of replication *from* an external DB @ermouth's technique has the potential to skip updates. Requesting the sequence of the remote database after the replication completes is no good; you need to request it *before* triggering the replication as any updates that occur to the external DB while the replication is running will not necessarily be included in that replication execution. Make sense?

**Comment by ermouth** [comment] 2015-06-26 22:08
@kocolosk you are right in your point – I just described algorithm in bit incorrect way. After replication finished, Pouch returns `last_seq` retrieved. I save this `last_seq` value, not the value retrieved using _info request – so in my case no skip occurs.

@karlwestin please, take it in mind implementing your solution. See https://github.com/ermouth/cloudwall/blob/master/sys/cw.js#L2165 – it can help a little.

**Comment by kocolosk** [comment] 2015-06-27 00:43
Ah, very good - if you have access to `last_seq` that's the optimal value to use.

**Comment by karlwestin** [comment] 2015-06-30 16:31
Cool, i did a little attempt to port the erlang from @kxepal's comment here https://gist.github.com/karlwestin/9e6bf87b897b18cda700 but i really like the idea of phasing out history in couchdb 2.0. Gonna look at that one as well!

**Comment by daleharvey** [comment] 2015-07-16 09:09
Fixed in https://github.com/pouchdb/pouchdb/commit/9de0faa21378812e89b9c82dc1b6950f9868bcd2

**Closed by daleharvey** 2015-07-16 09:09 UTC

**Comment by jo** [comment] 2015-07-16 09:12
very cool!
