### ISSUE TITLE
Using blobutil

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/pouchdb#4408] opened 2015-10-04 22:22 UTC
Hello Support,

We want to include blobutil in our code but when we do this the code handling is not in the right order.
The console.log tells us first the line '2' is logged and then '1'. And also we get an error message.'Document update conflict'.
When we delete the 'blobUtil.imgSrcToBlob .....' line the code handling seems to be in the right order.
Can you advise how to use blobUtil in this context?

```
db.get('profilePicture')
	.then(function (doc) {
	console.log("1");
	console.log(doc);
	localStorage.rev = doc._rev;
	console.log(localStorage.rev);
	})
	blobUtil.imgSrcToBlob('http://my-personaltrainer.nl' + localStorage.profilePictureUrl)
	.then(function (blob) {
		console.log("2");
		return db.putAttachment('profilePicture', 'profilePicture.png', localStorage.rev, blob, 'image/png');
	})

```

Kind regards,
Mario

**Comment by nolanlawson** [comment] 2015-10-04 23:56
So it seems like you might be struggling to understand how to order things using promises. Can I recommend [this blog post](http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html), which a lot of people have told me helped make sense of promise for them?

Namely your code should probably look more like this:

```js
db.get('profilePicture').then(function (doc) {
  console.log("1");
  console.log(doc);
  localStorage.rev = doc._rev;
  console.log(localStorage.rev);
  return blobUtil.imgSrcToBlob('http://my-personaltrainer.nl' + localStorage.profilePictureUrl);
}).then(function (blob) {
  console.log("2");
  return db.putAttachment('profilePicture', 'profilePicture.png', localStorage.rev, blob, 'image/png');
}).catch(console.log.bind(console));
```

**Comment by MarioVanDenEijnde** [comment] 2015-10-05 09:00
Hello Nolan,

Thanks. That worked. But now I have got another issue:
I create a blob but that is not recognized as base64 ("Attachments need to be base64 encoded")
According to the tutorial this should work or am I wrong?: http://bl.ocks.org/nolanlawson/edaf09b84185418a55d9

```
.then(function (doc) {
localStorage.rev = doc._rev;
localStorage.myBlob = blobUtil.imgSrcToBlob('http://my-personaltrainer.nl' + localStorage.profilePictureUrl);
console.log(localStorage.myBlob);
})
.then(function (blob) {
	return db.putAttachment('profilePicture', 'profilePicture.png', localStorage.rev, localStorage.myBlob, 'image/png');
})

```
Please advise,

Kind regards,
Mario

**Comment by daleharvey** [comment] 2015-10-05 12:21
@MarioVanDenEijnde that code has the same problem previously pointed out

```
  return blobUtil.imgSrcToBlob('http://my-personaltrainer.nl' + localStorage.profilePictureUrl);
}).then(function (blob) {
```
vs
```
  localStorage.myBlob = blobUtil.imgSrcToBlob('http://my-personaltrainer.nl' + localStorage.profilePictureUrl);
  console.log(localStorage.myBlob);
}).then(function (blob) {
```

Also just a note, this isnt 'Support', happy to answer questions, but its a little nicer to not be addressed that way, thanks. 

Closing this out as it is not a bug, happy to answer questions however you really should read up on promises and how async code works in javascript since these are are not pouchdb specific issues

**Closed by daleharvey** 2015-10-05 12:21 UTC

**Comment by MarioVanDenEijnde** [comment] 2015-10-05 13:58
Hello Dale,

I certainly don't want to sound unfriendly. Rather would like to show my appreciation on your help. Just did not know how to call you in general instead of your direct names.
It seems understanding the use of promises still has some pitfalls for me.

Thank you very much.

Kind regards,
Mario

**Comment by nolanlawson** [comment] 2015-10-05 16:30
@MarioVanDenEijnde The Slack/IRC channels (scroll to the bottom of pouchdb.com for links) are a great way to get help from the community! :)

**Comment by nolanlawson** [comment] 2015-10-05 16:31
Also I've been told that some people literally sat down with my article for like 2-3 days just to figure everything out. Maybe I should make a YouTube video?
