### ISSUE TITLE
When db size is large, adding documents hangs

### ISSUE THREAD

**Issue by JakeChampion** [pouchdb/pouchdb#3519] opened 2015-02-09 16:20 UTC
I have a database that is storing music tracks as documents and the actual music blob as an attachment.

The size of all the attachments in the database is currently 840.289MB. If I try and add another document the promise returned when adding that document never resolves.

After freeing up the hard drive space by deleting some files, I could add a few more documents but I soon reach the same issue.

**Comment by nolanlawson** [comment] 2015-02-09 16:25
Which browser? Which adapter?

**Comment by JakeChampion** [comment] 2015-02-09 16:27
Google Chrome Canary, adapter would be IndexedDB I believe

**Comment by nolanlawson** [comment] 2015-02-09 18:40
Can you try some other browsers? Or WebSQL? Would be interested to see where the error is coming from.

You may also be hitting a limit on your own machine; if you free up disk space, Chrome might let you store more.

**Comment by JakeChampion** [comment] 2015-02-09 20:23
I can try some other browsers sure. I think it is hitting the limit Chrome has set, however, shouldn't that lead to an error being thrown if that is the case?

**Comment by nolanlawson** [comment] 2015-02-09 20:47
TBH we haven't standardized that yet across the PouchDB API. It could very well throw a sync error that is silently lost. It's something we haven't tackled yet.

**Comment by daleharvey** [comment] 2015-07-22 09:41
Closing as a dupe of #4018 since that has a lot of investigation in it

**Closed by daleharvey** 2015-07-22 09:41 UTC
