### ISSUE TITLE
Better handling of live replication and changes requests

### ISSUE THREAD

**Issue by garethbowen** [pouchdb/pouchdb#4541] opened 2015-11-04 01:18 UTC
I'm using replication with `{ live:true }` over http which makes a request for the `_changes` feed with the following parameters:

Parameter | Value
-------------- | ----------
timeout | 25000
feed | longpoll
heartbeat | 10000
style | all_docs
filter | my_filter
since | 5195
limit | 100
_nonce | 1446598600731

Then exactly 30 seconds later that request gets cancelled and I get this error in the console:

```
Uncaught (in promise) e {status: 500, name: "unknown_error", message: "Database encountered an unknown error", error: true, result: Object}
```

In the couchdb [changes docs](https://couchdb.readthedocs.org/en/1.6.1/api/database/changes.html) it says

> heartbeat ... Overrides any timeout to keep the feed alive indefinitely.

I think what's happening here is the `timeout` parameter is being ignored by couch and the request is being kept alive until it's killed by pouch at 30 seconds. I guess this is the desired behaviour but there are a few things that could be done to improve this.

1. Catch the "unknown error" so it doesn't look like a bug.
2. Don't send the timeout parameter if it'll be ignored. This is very minor but makes the request easier to understand.
3. Don't cancel the request if using a heartbeat. The whole point of the heartbeat is to keep the connection alive so cancelling it manually seems counterproductive.

This applies to both the replication and changes apis.

**Comment by daleharvey** [comment] 2015-11-04 10:35
So when I tested this I seen it work as I (and you) expected, the heartbeat triggered `xhr.onProgress` which reset the timer and requests would happen infinitely - https://github.com/pouchdb/pouchdb/blob/master/lib/deps/ajax/request-browser.js#L155

What browser are you seeing this in?

**Comment by garethbowen** [comment] 2015-11-04 19:26
I can replicate with Chromium 45 and Firefox 41. I've looked at the code a little more and I think you're right, specifying a timeout on the changes feed will work. I'm still stuck with replication because of #4540 .

I think the low priority points 1 and 2 still stand. Another potential improvement is for changes and replication apis to not use the default the timeout when doing live replication. This will help it work as expected out of the box.

**Comment by daleharvey** [comment] 2015-11-14 01:09
So I believe you may be seeing https://github.com/pouchdb/pouchdb/issues/4560 with this issue, it looks like we do have problems with our heartbeat detection code, little confused at how it looked to be working for me before but will be investigating, closing as a dupe of that to keep track of things

**Closed by daleharvey** 2015-11-14 01:09 UTC
Labels: enhancement
