### ISSUE TITLE
Deprecate db.put(doc, id, rev)

### ISSUE THREAD

**Issue by fade2g** [pouchdb/pouchdb#5154] opened 2016-05-11 18:52 UTC
My way of updating a document is like this:

Make a get, then put the new document with the _rev value from the document from get call. If the get call returns no document, make a put without _rev (obvisouly).

```javascript
 function addDoc() {
      db.get(designDoc._id)
        .then(function(originalDoc) {
          return db.put(designDoc, designDoc._id, originalDoc._rev);
        })
        .catch(function(err) {
          if (err.status === 404) {
            return db.put(designDoc);
          } else {
            console.log('Error while updating design document:' + err);
          }
        });
    }
```
When executing this, I get the error message "invalid rev format". Experimenting, I realised, that I should not supply a value for ID, i.e. `return db.put(designDoc, undefined, originalDoc._rev);`.

I think that the error message is quite misleading and should be changed to indicate, that supplying an _id in the document AND in the put call is wrong. Possibliy, updating the documentation at https://pouchdb.com/api.html#create_document with hints on not using both values would be good as well.

See my plnkr http://plnkr.co/edit/QSpI1X?p=preview

**Comment by daleharvey** [comment] 2016-05-11 21:25
So yeh this is the same issue as https://github.com/pouchdb/pouchdb/issues/2344, to be honest I find any other variation on `db.put(doc)` super confusing. I think we may want to remove it 

The `put(id, rev, doc)` was done as motivation for pouch / couchdb to support values other than json, so we could `put(id, rev, new Blob())` etc, but that has never actually happened. 

For you I would suggest using `db.put(doc)`, for us I think we may want to deprecated `db.put(id, rev, doc)`

**Comment by daleharvey** [comment] 2016-05-18 09:51
ok, I would like to deprecate this, basically a long time ago we thought about the ability to store arbitrary data in Couch / PouchDB, not only json. We prematurely implemented some API changes to start supporting that including `db.put(id, rev, data)`, however we have found this to have confusing behaviour (as in this bug), the code to implement it is fairly nasty (https://github.com/pouchdb/pouchdb/blob/master/src/adapter.js#L217). Will put a PR in to put a deprecation notice in the code whenever it is used

**Comment by nolanlawson** [comment] 2016-05-19 14:48
I totally agree. I only use `db.put(doc)`, it aligns it with `db.post(doc)`, and I think it makes a lot more sense conceptually. I'm +1 for deprecating.

**Comment by navarrojava** [comment] 2016-05-19 15:33
I totally Agree Too!
I would find interesting also that the db.post()  accept the _id parameter, and if it receives not generate a random UUID but use what he received as a parameter and persists the object.
And db.put() not need _rev, and return error if the _id not exist of course.

**Comment by fade2g** [comment] 2016-05-22 08:39
As I'm totally new to pouchDB (I cannot judge, how complicated the current PUT implementation is) and I think, that consistency is a good thing, I would like to agree to make PUT and POST the same.

But on the other hand, PUT and POST are not the same thing: POST creates a new record, PUT updates an existing one. POST can never have a _rev property, where PUT must have one.

The case what I was trying to do (as a newbie) was to realise an upsert call (see my [question on stackoverflow](http://stackoverflow.com/questions/37036673/pouchdb-update-design-document-gives-invalid-rev-format-error). So it would be quite convenien to overload some properties on a given document with the non-business-logic-properties _rev and (possibly the ID) (as ID can be business logic or just some technical ID).

So I would not say, that I totally agree with depreacting the put methods optional parameters.

**Comment by daleharvey** [comment] 2016-05-22 20:50
The differing semantics between `put` and `post` will remain (put will fail without an id), the issue is that `put` has a confusing syntax that isnt consistent with the rest of our API. You can still do the exact functionality, just with `doc._rev = newRev` instead of `db.put(doc, newRev)`

**Comment by navarrojava** [comment] 2016-05-23 14:00
And the idea of the post to accept an ID, proceed? I think it would be a good idea, because when eui want to persist with something id generated locally, will not need to use PUT to create, but the POST, following the REST concept.

something like:

```
  ...
if (!doc._id) {
    doc ["_id"] = new UUID();
}
 ...
```

**Comment by nolanlawson** [comment] 2016-05-23 16:59
`post()` already accepts an `_id`. If you provide an `_id` then it's the same as `put()`.

**Comment by nolanlawson** [comment] 2016-05-24 03:40
deprecated in https://github.com/pouchdb/pouchdb/pull/5173

**Comment by daleharvey** [comment] 2016-06-02 07:47
Lets keep this open so we remember to actually remove it

**Comment by daleharvey** [comment] 2016-06-18 21:43
Fixed in https://github.com/pouchdb/pouchdb/commit/d38f8690ece454809530d9fe0480e5a343336c6b

**Closed by daleharvey** 2016-06-18 21:43 UTC
Labels: enhancement
