### ISSUE TITLE
"Invalid value for property _rev" when _id is in both the document and specified as a parameter to put

### ISSUE THREAD

**Issue by mtford90** [pouchdb/pouchdb#2570] opened 2014-08-06 08:27 UTC
Hi there,

Minor issue here but not behaviour that I expected and left me scratching my head for a while. If I specify `_id` in both the document and as a param to `put` I receive the error:  

```
invalid value for property '_rev'
```

e.g:
```
var pouch = new PouchDB('db');
pouch.put({'name':'michael', '_id': '5'}, '5').then(undefined, function (err) {
     dump(err);
});
```

The error doesn't make sense to me. I would have expected this to either have complained that it's specified twice or accepted it due to both being the same.

Let me know if this is down to a misunderstanding on my part.

This is using PouchDB v2.2.3.

Cheers!

**Comment by daleharvey** [comment] 2015-07-12 16:06
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/2344

**Closed by daleharvey** 2015-07-12 16:06 UTC
