### ISSUE TITLE
Support for CommonJS modules

### ISSUE THREAD

**Issue by shimaore** [pouchdb/pouchdb#973] opened 2013-10-26 17:15 UTC
The way I read the code for `mapreduce.js` it seems that PouchDB does not currently support [CommonJS module](http://wiki.apache.org/couchdb/CommonJS_Modules) (only `emit` is supported, `require` is not supported).

This would be a nice feature to add; in the meantime this could be listed under `CouchDB differences` in `docs/faq.md`.

**Comment by marten-de-vries** [comment] 2015-01-02 11:37
This is a duplicate of pouchdb/mapreduce#220. Leaving open for the documentation part though.

**Comment by daleharvey** [comment] 2015-07-06 17:19
I think https://github.com/pouchdb/mapreduce/issues/220 covers any of the use cases people have been motivated to work on, this is an old issue with not a lot of traction, I think ultimately we want pouchdb-find over map/reduce to be the primary query interface so gonna close this out

**Closed by daleharvey** 2015-07-06 17:19 UTC
