### ISSUE TITLE
Native secondary indexes

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2280] opened 2014-05-22 21:59 UTC
A good point was made recently in [a Google Groups question](https://groups.google.com/forum/#!topic/pouchdb/z9ZLd1XKaCA) about the performance of persistent map/reduce.  Basically what it boils down to is that view-building is pretty painfully slow.

My gut feeling is that, while unversioned local docs and/or faster auto-compaction could help, the real root of the problem is just having to run a function over every document in the database, in JavaScript.  This is kind of a waste, though, for the average case of map/reduce functions, which is where you just want an index on a single field.

WebSQL and IndexedDB both support secondary indexes natively, so I'm wondering if we couldn't add a backdoor to have map functions with native C performance.  This could have some limitations - e.g. the field must be a simple string/boolean/integer, it has to be directly accessible from the document without any fancy JS operations, etc. - but I think it's pretty much the only way we could make view-building appreciably faster.

Of course it would require writing adapter-specific code, which could get hairy, but the tradeoff in terms of the performance boost may be worth it.

**Comment by daleharvey** [comment] 2015-07-20 13:19
Gonna close as a dupe of https://github.com/pouchdb/pouchdb/issues/3775

**Closed by daleharvey** 2015-07-20 13:19 UTC
Labels: performance
