### ISSUE TITLE
Getting Started with PouchDB

### ISSUE THREAD

**Issue by ceremcem** [pouchdb/pouchdb#5399] opened 2016-06-24 16:36 UTC
Well, it's not going well... The only [example code](https://github.com/nickcolley/getting-started-todo/issues/3) is not working. Independently of that example, I could manage to put some test documents and get all of them from database, that's all: 

```
update-view = (...x) ->
    console.log "Change detected! : ", x
    db.allDocs {include_docs: true, descending: true}, (err, doc) ->
        console.log "Docs: ", doc

db = new PouchDB \mydb
remote = 'https://MYUSER:MYPASS@MYUSER.cloudant.com/MYDB'
opts =
    continuous: yes
    on-change: update-view

db.replicate.to remote, opts
db.replicate.from remote, opts

user-id = 5
get-new-id = ->
    timestamp = new Date!get-time! .to-string 16
    "#{user-id}-#{timestamp}"

products =
    _id: get-new-id!
    title: \products
    product-list:
        * name: \cake
          unit: \piece
          best-served: \cold
        * name: \water
          unit: \kg
          best-served: \hot


db.put products, (err, result) ->
    if not err
        console.log "success!"
    console.log "result: ", result
```

Second step is getting a view value: 

```
$ curl https://MYUSER:MYPASS@MYUSER.cloudant.com/MYDB/_design/getTitles/_view/new-view
{"total_rows":7,"offset":0,"rows":[
{"id":"5-1557feee287","key":"5-1557feee287","value":"domates"},
{"id":"5-1557ff6c0b3","key":"5-1557ff6c0b3","value":"domates"},
{"id":"5-1557ff854f8","key":"5-1557ff854f8","value":"domates"},
{"id":"5-1557fffff92","key":"5-1557fffff92","value":"domates"},
{"id":"5-1558000c0d5","key":"5-1558000c0d5","value":"domates"},
{"id":"5-1558000f067","key":"5-1558000f067","value":"domates"},
{"id":"5-15582153a32","key":"5-15582153a32","value":"domates"}
]}
```

I can't figure out how to get this result via PouchDB. 

Isn't there any example for such a startup?

**Comment by nolanlawson** [comment] 2016-06-25 15:03
The sample code is out of date, and is using PouchDB 3.2.0. I'll issue a PR on that repo to fix it.

**Comment by nolanlawson** [comment] 2016-06-25 15:06
The sample code is working for me. I also opened a PR: https://github.com/nickcolley/getting-started-todo/pull/4

Try:

    git clone --branch update-pouchdb https://github.com/nolanlawson/getting-started-todo.git
    cd getting-started-todo
    python -m SimpleHTTPServer 9000
    # open up localhost:9000 in a browser

**Comment by nolanlawson** [comment] 2016-06-25 15:07
As for your sample code, I'm not really understanding your question... what is the result you expect compared to what you're seeing? Also you may want to try the Slack channel instead of GitHub if you want more one-on-one help: http://slack.pouchdb.com/

**Comment by ceremcem** [comment] 2016-06-26 11:14
Rather than being directy related with the actual question, the code above was all I could get about pouchdb from examples, API and Google. 

The actual question part was "how can I get a view's result via PouchDB", and here is the answer I could find out: 

```
db.query 'getTitles/new-view', (err, res) ->
    console.log "getting titles: ", res
```

**Comment by daleharvey** [comment] 2016-06-27 09:06
This is documented @ https://pouchdb.com/api.html#query_database, Cheers for the reminder to update the getting started, closing this out as not a bug but if you have any more questions feel free, thank you

**Closed by daleharvey** 2016-06-27 09:06 UTC

**Comment by ceremcem** [comment] 2016-06-28 13:38
Thank you for your help. I think I may provide a fresh feedback as a new noSql user.
