### ISSUE TITLE
Running viewCleanup directly after multiple databases are created fails

### ISSUE THREAD

**Issue by juhasuni** [pouchdb/pouchdb#4841] opened 2016-01-27 10:36 UTC
Simple test to reproduce the issue:
```javascript
var barDb = new PouchDB('bar');
var fooDb = new PouchDB('foo');
fooDb.viewCleanup();
```

This fails with error `db.type is not a function` on Chrome. It looks like some adapter-specific part of database API is not completely initialized.

Tested with PouchDB `5.2.0` and both `Chrome`and `Universal Windows Platform / Windows 10`. This issue does not seem to be present in earlier versions of PouchDB.

To overcome this issue, you must listen to `created` event for all created databases and perform additional operations only after that. I think that this problem is not related to just `viewCleanup` but other operations may fail as well.

**Comment by nickcolley** [comment] 2016-01-27 10:39
Hey @juhasuni 

Looks like this problem might be fixed once this lands: https://github.com/pouchdb/pouchdb/pull/4804

Could you try using the master branch of PouchDB and see if you can reproduce this issue?

**Comment by juhasuni** [comment] 2016-01-27 12:53
Yes, I can confirm that this has been fixed in both master and PouchDB's latest nightly build.

It looks like this is a duplicate with #4788

**Comment by nolanlawson** [comment] 2016-01-27 19:26
Closing as a dup, thanks for reporting. We'll get out an update soon.

**Closed by nolanlawson** 2016-01-27 19:26 UTC
