### ISSUE TITLE
No error -> name and reason -> message for validation errors

### ISSUE THREAD

**Issue by marten-de-vries** [pouchdb/pouchdb#4670] opened 2015-12-19 18:47 UTC
This pouchdb-validation test started failing at some point (currenly skipped because of this bug):
https://github.com/pouchdb/pouchdb-validation/pull/5/files#diff-fb0d18ca230e188e02029b32dbb851d8R28

It was also reported as a separate bug report: https://github.com/pouchdb/pouchdb-validation/issues/4

To reproduce:
Make a design doc (ES6 notation):
```javascript
{
	_id: '_design/test',
	validate_doc_update: `function (newDoc, oldDoc, userCtx, secObj) {
		if (newDoc._id !== "test") {
			throw({forbidden: "only a document named 'test' is allowed."});
		}
	}`
}
```

Now making a doc not named test will make couchdb return the following (from a quick Futon test):
```javascript
{"error":"forbidden","reason":"only a document named 'test' is allowed."}
```

PouchDB gives the following:
```javascript
{ [forbidden: Forbidden by design doc validate_doc_update function]
  status: 403,
  name: 'forbidden',
  message: 'Forbidden by design doc validate_doc_update function',
  error: true,
  reason: 'only a document named \'test\' is allowed.' }
```

What I'd expect for consistency (**and** what it was, the pouchdb-validation test suite checked for it):
```javascript
{
status: 403,
name: 'forbidden',
message: 'only a document named \'test\' is allowed.',
error: true
}
```

**Comment by marten-de-vries** [comment] 2015-12-19 18:54
Probably related: https://github.com/pouchdb/pouchdb/blob/fab33221c80c01b9eeee2f6ad63fa97b88f54888/lib/deps/errors.js#L137

**Comment by nolanlawson** [comment] 2016-05-23 19:53
Closing as a duplicate of https://github.com/pouchdb/pouchdb/issues/5214, please let me know if I misdiagnosed.

**Closed by nolanlawson** 2016-05-23 19:53 UTC
Labels: bug, has test case
