### ISSUE TITLE
Should guard all usages of `console`

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5225] opened 2016-05-26 00:07 UTC
Android in pre-Kitkat doesn't support `console` in a web worker. We still have plenty of unguarded usages of `console`, leading to problems like https://github.com/nolanlawson/worker-pouch/issues/16.

My recommended guard is e.g. `typeof console !== 'undefined' && 'info' in console` (or `warn` or whatever).

Unfortunately we can't really test this because Saucelabs <4.4 isn't reliable, but we can at least manually fix it.

**Comment by schultyy** [comment] 2016-05-27 18:42
I don't have an Android device at hand but I would be in to work on that.

**Comment by daleharvey** [comment] 2016-05-27 18:51
Feel free to work on this without an android device, an idea to test this may be

```
if (process.env.NO_CONSOLE) { 
  delete global.console;
}
``` in https://github.com/pouchdb/pouchdb/blob/master/tests/integration/node.setup.js, then run the tests with `NO_CONSOLE=1 npm test`, if they fail then thats all the testing that should be needed

**Comment by daleharvey** [comment] 2016-05-27 18:55
hrm I just tried that and it doesnt work since mocha tries to use the console :(, either way feel free to work on it and we can discuss / figure out if there is any way to reasonably test it, something like this may not strictly require tests

**Comment by schultyy** [comment] 2016-05-27 19:03
Alright, will do.

**Comment by schultyy** [comment] 2016-05-27 20:53
Does it make sense to have some sort of `console` mock to test if the guard works?

**Comment by daleharvey** [comment] 2016-06-02 07:57
The problem is things outside PouchDB are also using the console and its hard to differentiate, thats pretty much with what I was thinking with `delete window.console`. To be honest this sound mostly like one of those issues we fix and it just stays fixed, we will just be mindful of console's in reviews and it should be fine, but if you can think of a test that works it would be even better :)

Fixed in https://github.com/pouchdb/pouchdb/commit/16030b896769abfe39798291c73078f412fbfddc

**Closed by daleharvey** 2016-06-02 07:57 UTC
Labels: bug, first timers only, help wanted
