### ISSUE TITLE
confusing error message when remote database is deleted while attachment put operation

### ISSUE THREAD

**Issue by lucidNTR** [pouchdb/pouchdb#5104] opened 2016-04-27 14:13 UTC
To reproduce:
- use pouchdb as client library to remote couchdb.
- create database 'test'
- create document 'test'
- upload ~10 MB attachment with pouchdb put command and nodejs filebuffer object
- while upload in progress delete the remote database with futon
- pouchdb does not throw a reasonable error that helps finding the cause eg. 'database deleted while request in progress' but throws error  MISSING_BULK_DOCS for some reason

**Comment by zaccolley** [comment] 2016-04-27 14:31
What is the scenario in which this would happen? What's the use case?

Using a database for each users perhaps?

**Comment by lucidNTR** [comment] 2016-04-28 12:56
we encountered this in the following scenario:
- integration tests automatically create and delete databases (after tests are done) and test a feature that uploads an attachment
- error in the integration test leads to deletion of the databases before the final callback is called.
- because of the misleading error message it took way longer than necessary to find the problem

**Comment by nolanlawson** [comment] 2016-04-28 14:53
I agree we should have a friendlier error, although throwing an error is indeed the correct behavior here.

**Comment by lucidNTR** [comment] 2016-04-28 18:24
hey nolan, its not that throwing an errror or the friendlyness is the issue, the only problem is that its the wrong error. :-)

**Comment by nolanlawson** [comment] 2016-05-23 19:53
Closing as a duplicate of https://github.com/pouchdb/pouchdb/issues/5214, please let me know if I misdiagnosed.

**Closed by nolanlawson** 2016-05-23 19:53 UTC
Labels: enhancement, has test case, help wanted
