### ISSUE TITLE
[nodejs] memleak when creating PouchDB instance

### ISSUE THREAD

**Issue by shimaore** [pouchdb/pouchdb#4868] opened 2016-02-04 14:37 UTC
I am seeing the issue in production with slightly more complicated code (the memleak is obvious after 30 minutes but the databases are all different and using the `http` adapter, etc.), but here is a simple example that also exhibits the issue:

```
var PouchDB, debug, dgram, heapUsed, socket;
dgram = require('dgram');
PouchDB = require('pouchdb');
debug = (require('debug'))('test');
heapUsed = null;
socket = dgram.createSocket('udp4');
socket.on('message', function(msg, rinfo) {
  var db;
  debug("Received " + msg.length + " bytes from " + rinfo.address + ":" + rinfo.port);
  db = new PouchDB('goodluck');
  return db.info(function(info) {
    var last_heapUsed, memory;
    memory = process.memoryUsage();
    last_heapUsed = heapUsed;
    heapUsed = memory.heapUsed;
    return debug('info', last_heapUsed != null ? heapUsed - last_heapUsed : null);
  });
});
socket.bind(7124);
```

I then run `while true; do echo ping | nc -u -w 1 127.0.0.1 7124; done` in a shell to trigger the `message` handler.

Forcing a `gc()` call for each message (using `--expose_gc --expose_gc_as=gc`):
- There is no leak if I remove the `new PouchDB...` code. (The difference is '0' after about 6-7 iterations.)
- The leak is about the same size with or without the call to `info()`.
- The leak is about 2 to 3ko with nodejs 5.4.1 or 5.5.0, about 10 to 14ko with nodejs 4.2.1 or 4.2.6.

I'm obviously not sure this might be a PouchDB issue, but I'm at a loss to analyze where the issue might come from (I've done some runs with [`heapdump`](https://www.npmjs.com/package/heapdump) but it apparently doesn't work when `--expose_gc` is active).

**Comment by nolanlawson** [comment] 2016-02-10 17:12
Creating a `new PouchDB()` multiple times without ever destroying it will almost certainly cause a memory leak. The simplest solution is to just cache the `PouchDB` object; I'm not sure we can even fix this without some kind of `close()` API or something (which we sorta have, but it's undocumented), since we cannot "know" that you are no longer interested in the `PouchDB` object and that we can therefore release all the EventEmitters that get attached to it.

I'd say it makes more sense for us to avoid an explicit `close()` API and simply tell people that they need to avoid needlessly creating lots of PouchDB objects. Let me know if that fixes your issue, though - if not, then it's definitely a bug. Thanks! :)

**Comment by shimaore** [comment] 2016-02-11 09:54
@nolanlawson This is inside a voicemail (VoIP) application (a long-lived Node.js app), only using the `http` adapter. The code uses common instances of PouchDB to access shared databases. The `new PouchDB()` instances are used to access each user's private voicemail database stored on a CouchDB server (following the *one DB per user* pattern); there's no replication or `destroy()` calls on these; these PouchDB instances are short-lived and the end of use is clearly defined.

This could definitely make use of a `close()` API, although an alternative could be a `no_common_references` option that would prevent global references and document which events / behaviors would become unavailable in that case (apparently shared handling of `destroy()`).

If I read the code correctly it seems that in the current code,

    db.emit('destroyed')

should be sufficient to prevent the memleak in itself?

**Comment by nolanlawson** [comment] 2016-02-11 19:17
Yes, destroying the database should clear up any memory leaks. But I don't see you destroying anywhere in your code...?

**Comment by shimaore** [comment] 2016-02-12 09:24
@nolanlawson Ah, I see what you mean. The databases in production are CouchDB databases used through the `http` adapter so they shouldn't be destroyed.
Hmmm maybe the `close() / no_common_references` piece should be specific to the `http` adapter then?

**Comment by nolanlawson** [comment] 2016-02-13 17:35
OK, I think I understand better what the issue is, then. Maybe we do need an official `close()` API after all.

**Comment by daleharvey** [comment] 2016-06-20 12:32
hrm, so I modified this so its a little to get it to run in our test suite more easily

```
var PouchDB = require('pouchdb');
var heapUsed = null;

setInterval(function () {

  global.gc();

  //var db = new PouchDB('goodluck');

  var memory = process.memoryUsage();
  var last_heapUsed = heapUsed;
  heapUsed = memory.heapUsed;

  if (last_heapUsed !== null) {
    console.log('difference is', heapUsed - last_heapUsed);
  }

  //db.close();

}, 1000);
```

Commented out the difference is 0 fairly quickly, uncommented its constantly rising (even with .emit(destroyed) as far as I can tell)

**Comment by mlegenhausen** [comment] 2016-10-10 12:42
Even after calling `close()` I can still see memory draining. This is important for memory constrained environments, where I need to handle hundreds of databases and haven't the resources to cache all pouch instances.

**Comment by daleharvey** [comment] 2016-10-10 12:55
If you were able to expose the memory leak using the test format I started working on that would be great, from that we could have a test to ensure its fixed and isnt regressed

**Comment by shimaore** [comment] 2016-10-16 19:51
+1... After upgrading from 5.4.5 to 6.0.6 last week and replacing `.emit('destroyed')` with `.close()` the problem is back. (I tested 6.0.7 and same result; not unexpected based on the changelog.)

I'll try & re-test tomorrow (I have a strong incentive to do so since otherwise I have to manually restart the processes manually every night ;D )

**Comment by shimaore** [comment] 2016-10-17 12:14
FWIW in production on servers that don't exhaust memory I see the RSS size fall back to normal during light load (around 11pm), then go back up during the day, etc.

I wonder whether there is a chance I might be overwhelming Node.js' garbage collector under load, and how to test whether this is the case. (I can start with forcing `global.gc()` every hour to see what happens. And if that's the case, the next question would be how to reduce the pressure on the GC.)

**Comment by shimaore** [comment] 2016-10-17 15:24
@daleharvey were you ever able to get 8b136fa6a531d4c61278d3a8a96820cadf8c9b4b to succeed? I've ran various versions of the `gc() / new PouchDB() / db.close() or db.destroy()` loop and I always end up with some kind of leak, even when using the same database over and over again, whether using leveldown or the server. 
(I tested using https://github.com/shimaore/pouchdb/commit/10c9a5f0daf83a68ed5fa7bfc1912b57e149682e and node 6.8.1)

**Comment by shimaore** [comment] 2016-10-18 10:30
More data:
- production graph showing the difference between 5.4.5 with `emit('destroyed')` (slow leak) and 6.0.7 with `close()`

    ![freeswitch_node_memory-month](https://cloud.githubusercontent.com/assets/55340/19473425/e7edfde2-952b-11e6-99c7-3bd19f96214d.png)

- I tried to use both `close()` and `emit('destroyed')` on 6.0.7 and the behavior is the same (fast memleak);
- I [compared](https://github.com/shimaore/test-pouchdb-memleak) tests (with 6.0.7) with the http adapter and a dummy adapter; the [leak](https://travis-ci.org/shimaore/test-pouchdb-memleak/jobs/168569385) is in the adapter, not pouchdb-core. (This also means there's probably a different memleak in the leveldown adapter as well.)

**Comment by mlegenhausen** [comment] 2016-10-18 12:37
Same constallation where the memory leak was produced in our system. `pouchdb-core` and `pouchdb-adapter-http`.

**Comment by shimaore** [comment] 2016-10-19 10:06
The leak in pouchdb-core is in [constructor.js / `prepareForDestruction`](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/constructor.js#L26) where the `onConstructorDestroyed` function leaks every PouchDB instance created, as far as I can tell. ([I documented the discovery process.](https://github.com/shimaore/test-pouchdb-memleak/commit/5bc67cfe2849a52fd5aeedbaa7bb50e1088b8668))

I'll try to use the same steps to see if I can figure the (larger) leak involved with the `http` adapter.

**Comment by shimaore** [comment] 2016-10-19 10:49
It's the [recording of the `onConstructorDestroyed` callback in the destruction listeners](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/constructor.js#L37) that creates the leak, not the callback itself.

Shouldn't `close()` remove the callback from `destructionListeners`?

**Comment by shimaore** [comment] 2016-10-24 23:24
Alright, got a usable test framework underway in [shimaore:memleak-test](https://github.com/pouchdb/pouchdb/compare/master...shimaore:memleak-test).

Test shows the problem in pouchdb-core persists with my patch applied, btw. I'll keep looking into this. (I'm still trying to get this fixed first before I move on to the issue in the http adapter.)

@daleharvey or @nolanlawson I would appreciate any hints as to how I'm supposed to integrate the new test file in the test suite (I assume we don't want to run the entire suite with `--expose-gc`?).

**Comment by daleharvey** [comment] 2016-10-25 09:52
So looking at your branch, thats pretty much ideal however I would put the test file under `tests/memleak` to distinguish tests that need run under `-gc`

**Comment by shimaore** [comment] 2016-10-28 05:58
While working on that latest PR, I observed something extremely odd.

The tests report differently based on the order they are ran (inside the same mocha JS source file); I can easily repeat this with the `http` test, but other (simpler) tests also exhibit the behavior.
Tests ran earlier will succeed; tests ran later in the test suite will fail / leak more memory. Same code, same version of Node.js, same versions of dependencies, etc. Just moving the code around makes each test leak more or less memory; I can make the `http` test succeed just by putting it first, fail by putting it last. This is repeatable across runs.

Not sure what to make of it.

**Comment by shimaore** [comment] 2016-10-28 14:02
I [modified the destruction-listener code](https://github.com/shimaore/pouchdb/commit/cf5c9bd63e53a619f1f62a3ad4c9a841cacd8b39) so that the destruction listener(s) are always removed when `close()` is called. (I'm assuming that one would call either `close()` or `destroy()` but not both on the same PouchDB instance, since both are final.) This appears to have fixed the issue with the leveldown adapter.

I'm still struggling with the http adapter, heap dumps aren't collaborating: there is no major leak of closure, objects, etc. The dumps show lots of `code deopt data`, `code relocation info`, `source position data` and `function scope data` entries are created and never removed, so I can tell functions are leaked and moved around, especially in event and `setTimeout` callbacks (but I'm surprised no closures appears in the dev tool). Looking in the code I see for example that `request` tends to use `on` instead of `once` even for events that may only occur once; but a lot of references point to Node.js internals as well so this isn't trivial. (Would appreciate any guidance here!)

I'll keep trying to poke at things, but it has been hit & miss (mostly miss) so far.

**Comment by nolanlawson** [comment] 2016-11-20 16:12
Reopening because we had to revert this in #5901, see https://github.com/pouchdb/pouchdb/pull/5834#issuecomment-261787244

**Comment by nolanlawson** [comment] 2016-11-20 16:12
So basically we would need to figure out why it broke in Safari and then fix it

**Comment by shimaore** [comment] 2016-11-25 11:28
Errors for failed tests in https://travis-ci.org/pouchdb/pouchdb/builds/176740704
> "before each" hook for "should emit closed even when destroyed (async #2)"
> "before each" hook for "test unref for coverage"
> "before each" hook for "should emit closed even when destroyed (async #2)"

**Comment by shimaore** [comment] 2016-11-25 11:39
Yes indeed. `testUtils.cleanup` calls `new PouchDB(db).destroy` which will fail if the goal of the previous test was to test `destroy`.

I'll move the tests I added to a separate test source file so that I can make the `destroy` in `before each` optional.

**Comment by daleharvey** [comment] 2017-05-22 14:36
Merged in https://github.com/pouchdb/pouchdb/commit/96a5dfc5ec0ffefa26b3983ba6ec9a68beeb2173

**Closed by daleharvey** 2017-05-22 14:36 UTC
Labels: enhancement, needs reproducing
