### ISSUE TITLE
Can't create databases in iOS 10 on Safari or Chrome

### ISSUE THREAD

**Issue by rdwoodring** [pouchdb/pouchdb#7057] opened 2018-01-30 15:23 UTC
### Issue
Can't create PouchDB on iOS10 Safari or Chrome

### Info
- Environment: (Browser)
- Platform: (iOS - Chrome 63.0.3239.73 and Safari)
- Adapter: (IndexedDB (letting PouchDB choose))
- PouchDB Version: 6.4.2

### Reproduce
1. Have a page that includes PouchDB 6.4.2
2. Add some code to create a database
3. Hit the page from an iOS 10 device in Safari or Chrome

### Expected Result
The database should be created using the IndexedDB adapter.

### Actual Result
The database is not created and the following error is logged:

Database has a global failure
message: An unknown error occurred within Indexed Database
name: UnknownError

Failed to open indexedDB, are you in private browsing mode?

objectStore@[native code] i@pouchdb-6.4.2.min.js:7:83327 e@pouchdb-6.4.2.min.js:7:89900 onupgradeneeded@pouchdb-6.4.2.min.js:7:89906

### Test Case
https://attractive-brand.glitch.me/

**Comment by Daniel-mumms** [comment] 2018-01-30 20:55
I can confirm the same problem on an iOS 11.2.5 device. However if using private/incognito browsing, I do not get the error, and PouchDB seems to be created normally.

**Comment by SteffenDE** [comment] 2018-01-31 14:36
I can confirm this on iOS 11.2.2, PouchDB 6.4.2.
It doesn't happen on every page load, but if it doesn't happen the creation of the PouchDB database seems to hang.

**Comment by htejwani** [comment] 2018-02-01 10:02
Using PouchDB 6.4.2 in an iOS app, I get the same error. The database is created fine but the sync fails with this error after a download of around 50-100 MB.

InvalidStateError: Failed to execute 'objectStore' on 'IDBTransaction': The transaction finished.

**Comment by daleharvey** [comment] 2018-02-04 15:25
> The database is created fine but the sync fails with this error after a download of around 50-100 MB. 

mobile safari has had a 50MB limit with websql, would expect some similiar limit to be implemented for indexeddb. This isnt the same as the reported bug

The ios tests are currently fully passing using indexeddb on 8.4, would be good to figure out exactly where the error is here

**Comment by rdwoodring** [comment] 2018-02-04 15:59
This does indeed seem different than what I'm encountering. Also, I'm pretty sure that ios doesn't enforce the 50mb limit on indexeddb. I don't have access to an ios device to verify at the moment, but the limits can be easily checked here: https://demo.agektmr.com/storage/ I'm fairly certain I've gotten an iOS 10.x device up to at least 1.6gb on indexeddb.

**Comment by marcoturi** [comment] 2018-02-04 16:58
Steps to reproduce:
- Open http://jsbin.com/pocoqajofu/edit?js,console on Chrome 63-64.
- Be sure to have 'idb' as adapter, an press run -> You will see info from the console log.
- Now put the browser in simulation mode, and pick an iOS device. Press run -> Nothing happen.

**Comment by rdwoodring** [comment] 2018-02-04 17:01
I had some luck using Vorlon.js to remotely debug my iOS device and get an error message/stack trace as mentioned in the original ticket. Don't know if that's something that might help track this down as well.

**Comment by mattjennings** [comment] 2018-02-05 04:15
I'm also getting the "Database has a global failure" error with iOS 11.2.5 on Safari, pouchdb v6.4.3.

![screen shot 2018-02-04 at 10 09 33 pm](https://user-images.githubusercontent.com/8703090/35788039-2a4dd030-09f8-11e8-9255-ff4cb8cf6c98.png)

**Comment by MichaelBoselowitz** [comment] 2018-02-06 16:26
Same issue here. iOS 11.2.2 PouchDB v6.4.3.
<img width="1005" alt="screen shot 2018-02-06 at 11 22 53" src="https://user-images.githubusercontent.com/1891495/35870652-314233ac-0b30-11e8-980b-ac862d96a472.png">

Having debug mode turned on didn't reveal anything notable. I can also report that this doesn't seem to be an issue in the iOS simulator, only on devices.

**Comment by daleharvey** [comment] 2018-02-06 16:28
> Having debug mode turned on didn't reveal anything notable. 
> I can also report that this doesn't seem to be an issue in the iOS simulator, only on devices.

This is going to be hard for me to debug, I dont have an ios device

**Comment by SteffenDE** [comment] 2018-02-06 17:01
Well, for me it seems like the idb adapter is completely unusable in MobileSafari, as simply creating the db hangs using 6.4.3 or fails when trying to put a document.
For now I think we'll have to revert to using WebSQL if MobileSafari is used. IndexedDB works fine for me in Safari on macOS though.

**Comment by MichaelBoselowitz** [comment] 2018-02-06 17:14
> For now I think we'll have to revert to using WebSQL if MobileSafari is used. IndexedDB works fine for me in Safari on macOS though.

I've come to this conclusion as well. WebSQL does indeed still work on iOS 11. If I have a few spare cycles, I'll see if I can debug this any further, but in the meantime I think I will have to progress by forcing the WebSQL adapter on iOS,

**Comment by mattjennings** [comment] 2018-02-06 21:24
I can add that it works on an iOS 11.2 simulator. 

> mobile safari has had a 50MB limit with websql, would expect some similiar limit to be implemented for indexeddb. This isnt the same as the reported bug

On the iOS simulator, I was able to save 5-10 revisions of 4 different 33mb json documents using the idb adapter with no storage issues. So, it _seems_ that there's no storage limit when using the idb adapter.

**Comment by rdwoodring** [comment] 2018-02-06 21:27
@mattjennings I believe that is correct. That was the use case (no limit) for the fruitdown adapter pre-pouchdb 6.4.x

**Comment by daleharvey** [comment] 2018-02-07 18:41
If anyone could get a stack trace using the non minified version of pouch that would help

**Comment by SteffenDE** [comment] 2018-02-07 20:19
![bildschirmfoto 2018-02-07 um 21 17 33](https://user-images.githubusercontent.com/4116351/35939444-71aec6f4-0c4c-11e8-9a51-4ebcb21ed941.png)
![bildschirmfoto 2018-02-07 um 21 17 53](https://user-images.githubusercontent.com/4116351/35939445-7419b49e-0c4c-11e8-9b77-7eea55aa1963.png)

Used [this page](https://s3.eu-central-1.amazonaws.com/steffend/public/pouchdb_error.html) for testing.

**Comment by daleharvey** [comment] 2018-02-08 12:28
So it looks like safari is closing the transaction during our startup checks, a thing that may be worth checking is commenting out https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-idb/src/index.js#L768 and setting docCount = 0 at https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-idb/src/index.js#L722, not the correct fix but will help figure out where the error is, it may be that safari just closes the transaction due to https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-idb/src/countDocs.js#L6

**Comment by rdwoodring** [comment] 2018-02-11 20:16
I'm on paternity leave for the next week and won't have access to an ios device, but I might be able to give it a shot when I get back if no one else has tried it before

**Comment by rdwoodring** [comment] 2018-02-22 20:37
Looks like I am still getting the same error:

Database has a global failure
message: An unknown error occurred within Indexed Database
name: UnknownError

Just to clarify, these are the changes made:

commented out this code at line 768 to this:
```
// countDocs(txn, function (count) {
//   docCount = count;
//   storeMetaDocIfReady();
// });
```

and assigned 0 to docCount at line 722:
`var docCount = 0;`

**Comment by cmer4** [comment] 2018-02-24 03:04
Same here. Not sure how WebSQL can be "deprecated" if iOS mobile is not addressed;(

**Comment by keniasalazarm** [comment] 2018-03-18 23:41
https://github.com/pouchdb/pouchdb/issues/7057#issuecomment-361731045

As Daniel-mumms said, when using private/incognito browsing on IOS it works because it uses local storage instead of PouchDB. For regular Safari (Macs) PouchDB works.

**Comment by adueck** [comment] 2018-03-19 13:33
@keniasalazarm I tried it on Safari on a new MacBook Pro and it only works for a few minutes/queries, and then stops. IOS only works in incognito mode, but then there is no offline/persistent storage.

**Comment by WorldMaker** [comment] 2018-03-23 16:25
I've recently had this problem come up and it seems a strange regression in the way that things seemed to work fine last week and yet it started failing this week "all of a sudden". (Plus of course the peculiar Apple "love" in that things work just fine in the simulator, but not real devices.) I'm trying to figure out the variables that changed in between, and I'm getting pressure that I need solutions ASAP.

@daleharvey Looking at the code I've got a terrible itch now that there is an definitely at least one race condition here. There are two possible paths to `storeMetaDocIfReady` and two possible paths to `CompleteSetup`, and combinatorially at least four different orders through that maze those can be called. That one of these paths starts in `txn.oncomplete` and who knows how many different ways the platform could call that event, I'm getting some shivers there. The one particular line that stands out to me then here is:

https://github.com/pouchdb/pouchdb/blob/7c0988c0ae6b773e2a81554b1b49ffe74471ce97/packages/node_modules/pouchdb-adapter-idb/src/index.js#L783

I don't think that's the direct cause of the problem here, but it smells to me in setting that flag in an event where it isn't guaranteed to be accurate. That is, shouldn't it be on the put request's `onsuccess` in `storeMetaDocIfReady` instead?

I'm going to keep digging, but that was the first sore thumb I stumbled upon.

**Comment by WorldMaker** [comment] 2018-03-23 17:07
Difference between working and broken versions on my end appears to be a possible regression in `pouchdb-core` between 6.1.11 and 6.1.12, looking at version changes in my package-lock.json file. Now for the chore in a monorepo in tracking down specific changes without version specific tags to help and seeing if they apply to the problem at hand.

**Comment by daleharvey** [comment] 2018-03-23 18:16
> That is, shouldn't it be on the put request's onsuccess in storeMetaDocIfReady instead

I dont think so, was a large and very hard to find problem in previous versions of pouch, the process of storing isnt finished until the transaction is complete, assuming it is onsuccess causes a lot of hard to diagnose issues.

It looks a lot from reports that the blob support check causes the fail, I would definitely try with that removed and see if the situation improves, the blob support code does need the transaction to stay open over a microtask which safari could be breaking here

**Comment by WorldMaker** [comment] 2018-03-23 19:06
@daleharvey Maybe there should be an intermediate flag though to at least make sure the put was even tried?

**Comment by WorldMaker** [comment] 2018-03-23 19:11
Hmm, why is the blob support check using the same transaction?

**Comment by WorldMaker** [comment] 2018-03-23 19:21
IndexedDB transactions use implicit commits? That is horrifying. This "parallel" approach to three different uses of the same transaction seems doomed by design to edge conditions in that case. The IndexedDB docs I'm reading seem to only indicate it is only obligated to work in the case of serial operations (and in most cases any parallel attempts may only be serial anyway).

It does look like you need an intermediate flag in that case to make sure that the put was even called by the time the transaction completes (and open a new transaction if not?).

**Comment by daleharvey** [comment] 2018-03-24 09:01
> Hmm, why is the blob support check using the same transaction?

because we have a transaction there / its open, fast than making a new one and just as reliable

> It does look like you need an intermediate flag in that case to make 
> sure that the put was even called by the time the transaction 
> completes (and open a new transaction if not?).

In a compliant browser that isnt needed, new promise is a microtask and should guarantee to run directly after the first `.put`, certainly way before `onsuccess` which will keep the transaction open, this code has been running fine for years in the other browsers, it is not doomed by design

However this code is supporting a 3 year old evergreen browser so not 100% sure its needed anymore, if someone wanted to make a PR removing the blobsupport check we could see what CI says about it

**Comment by jamft** [comment] 2018-04-03 02:54
I have the same issue as well on iOS 10.3.2 and 10.3.3 as well, pouchDB 6.4.3 does not synchronize. It doesn't even save anything locally. But when I switch to privacy mode in safari then it works no problem.
I was wondering if there is a new pouch.js file to address this. Thanks.

**Comment by lifaon74** [comment] 2018-04-09 08:40
In fact after inspection, (ipad pro, ios 11.3, safari 11) it seems safari on ios doesn't support blob store in idb. BUT it supports arraybuffer. So the conversion could be easily done.

**Comment by platov** [comment] 2018-04-11 12:27
I had same error `Failed to open indexedDB, are you in private browsing mode?` twice in random moments in Android Chrome 65 WebView =(

**Comment by jamft** [comment] 2018-04-11 13:13
It works in privacy mode in both Safari as well as Chrome, but not in normal browsing mode. 
As I understand it, pouchDB uses a different database backend when it runs in privacy mode, or perhaps no database at all. This is on iOS 10.10 so the issue is not limited to 11.
It does work on an older Android V5 tablet that I have, and it does work on the MacOS desktop across all browsers. Just on in iOS. And I can't really ask users to view my webpages in privacy mode, so I can't really use pouchDB, which is sad, because it's cool.
I don't use blobs. This is the vanilla toDo example given on the pouchDB website, no modifications at all, so it only has a text field.

**Comment by daleharvey** [comment] 2018-04-11 13:16
pouchdb doesnt using a different backend when in private browsing mode, private browsing mode is supposed to be opaque to us however in firefox it will fail

**Comment by Novelz** [comment] 2018-04-12 10:04
Hi there, same problem here with the idb adapter on iOS 11.
Setting the adapter to 'websql' seems to fix the problem of saving data, but it's just a dirty fix.

**Comment by jamft** [comment] 2018-04-14 06:55
Thank you for the heads-up, Novelz. I would like to try that. Unfortunately, the link to pouchdb.websql.js is returning a 404, both full as well as minimized. All the other adapters are there but the websql adapter is missing.
It's a bit unfortunate. The whole point of pouchDB is that it's supposed to be simple and universal, but if it does not run on iOS then that is not very universal.

**Comment by Novelz** [comment] 2018-04-14 08:38
Jamft if you are using a Pouchdb version < 7.0 then you should good to go as the adapter is already available in the core of pouchdb.
But you will probably run into the space issue of websql in iOS.

**Comment by jamft** [comment] 2018-04-14 14:28
I am using PouchDB 6.4.3 and this is the problem I am getting. 
Doing some more reading, I have added the pouchdb.fruitdown.js adapter, but it's doesn't seem to be working either.
It says: "If you need to support IndexedDB in Apple browsers (which PouchDB normally does not support due to instability), then you can use FruitDOWN, which works over all IndexedDB implementations at the expense of using a much smaller part of the IndexedDB API and therefore being slower and less efficient."

From the same page: "PouchDB attempts to provide a consistent API that "just works" across every browser and JavaScript environment, and in most cases, you can just use the defaults."

I am left scratching my head a bit ...

**Comment by rdwoodring** [comment] 2018-04-14 14:31
Pretty sure fruitdown is no longer maintained and Will be going away at some point (7.0?)

**Comment by jamft** [comment] 2018-04-14 14:40
This is straight from the PouchDB website, and there is no indication of it being retired.

Now I am really confused. Is there actually a hope that PouchDB will work as it says it would. I am getting a feeling I should just abandon it if it can't be relied on to work on iOS, which is pretty well half the mobile devices out there that are actually being used.

**Comment by SteffenDE** [comment] 2018-04-14 17:03
Currently, the only way I can use PouchDB reliably on iOS is by using v6.4.1, as WebSQL support was removed in the newer releases.
https://unpkg.com/pouchdb@6.4.1/dist/pouchdb.min.js works fine for me in every browser.
I am wondering why this issue is still open. Removing WebSQL support clearly wasn’t the right choice when IndexedDB does not work reliably in MobileSafari. So why is [this](https://github.com/pouchdb/pouchdb/commit/179660996893cd3e13897aa9c3a7f10880a69393) still not reverted?

**Comment by daleharvey** [comment] 2018-04-15 11:54
WebSQL was not removed in recent releases as explained in https://pouchdb.com/2018/01/23/pouchdb-6.4.2.html, the default adapter was changed to indexeddb

Its not clear that indexedDB cannot work in mobile safari, there are intermittent bugs being reported here which need fixed, if we cant fix them we will maintain WebSQL support and this issue is blocking us doing a release without websql, but either help fix them or wait for the release, the misinformation and opinions without research do not help

**Comment by SteffenDE** [comment] 2018-04-15 12:39
Okay, thank you for clarifying this, but still this means for PouchDB to work on iOS I need to manually specify `{ adapter: "websql" }`, right? So for still using IndexedDB on Safari on macOS I would need to change my code and add some User-Agent hacks to see if we're running on iOS or not.
Even if WebSQL isn't removed (for now), having IndexedDB as default in Safari is a breaking change for anyone trusting PouchDB to automatically select the right adapter...

> but either help fix them or wait for the release

I really like PouchDB, but having no experience at all with neither IndexedDB nor WebSQL, I can only wait for someone to get to the bottom of this issue :/

**Comment by lifaon74** [comment] 2018-04-16 09:58
Here is the version 6.4.3 that is changed a little to support ios:
[pouchdb.zip](https://github.com/pouchdb/pouchdb/files/1914766/pouchdb.zip)

**Comment by jamft** [comment] 2018-04-16 14:18
Wow! It works!!! Thank you, lifaon74!!!
Dale: Whatever lifaon74 did resolves the problem. Now pouchDB works on my 10.3.2, for both Chrome as well as Safari. Yay!!!

**Comment by coolalpaca** [comment] 2018-04-16 16:44
@lifaon74 What did you manage to change to make it work? We've been anxiously waiting someone to crack the code as well...

**Comment by lifaon74** [comment] 2018-04-16 16:57
See comment upper.
In checkBlobSupport I put
```js
var iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
    if (iOS) {
      resolve(false);
    } else {
...
```
And I rewrite a little the `hasFecth`. This is a quickfix. It's far from perfection.

**Comment by adueck** [comment] 2018-04-17 21:02
Thanks @lifaon74 !
Do you want to put those changes in a pull request?

**Comment by ssured** [comment] 2018-04-18 08:07
I made a quick diff of the pouchdb.zip @lifaon74 sent, see https://www.diffchecker.com/713L2657. Thanks @lifaon74!

**Comment by lifaon74** [comment] 2018-04-18 12:15
@adueck, @ssured please don't commit my changes. It's a fast fix ! By default the blob test of pouchdb is really bad because it doesn't properly handle errors (which fail silently on IOS...). A proper test should:

1. Create a new database wrapped around a promise (error => reject)
2. In the `onupgrateneeded`: create a new store
3. Create a new readwrite  transaction wrapped around a promise (error => reject, complete => resolve) and put a document of type Blob in the previous store.
3. If the database or the transaction get an error => reject, if the `put` fail => reject

If Blob are not supprted (rejected promise), the same test should be done for ArrayBuffer. If ArrayBuffer are not supported, use base64 string.

**Comment by jamft** [comment] 2018-04-18 23:37
I think you guys did a fantastic job, thank you so much for fixing this problem in the short term, and I am looking forward for the changes, once they have been formalized, to be rolled into the next version.
Thanks!

**Comment by daleharvey** [comment] 2018-05-15 15:49
ok, so finally got the CI issues fixed and managed to run the full test suite on an actual device (thank you Jan / Hoodie) and ... full test suite passes fine

The device I have access to is 11.2, will try the 6.4.2 release version, otherwise anyone got any suggestions on how to reproduce?

**Comment by akowald** [comment] 2018-05-15 16:08
How strange.. it shouldn't be hard to reproduce. Calling info() on a new database does it for me. My device is iphone 8+ w/ ios 11.3.1 and using 6.4.3. I've had the same error in previous ios versions.

**Comment by daleharvey** [comment] 2018-05-16 08:34
So I managed to get failures using 11.3 and pouchdb 6.4.2, but none on master no matter what version. Its not that surprising we have a good test suite and browser manufacturers rarely break stuff 'that' badly, its almost always a more naunced problem.

Could people go to https://gem-crystal.glitch.me/ on ios, press run code and tell me if you see `Sync Complete!` and what version you are running? it would be hugely helpful (if it fails and you can post your logs that would be extra helpful) cheers

**Comment by htejwani** [comment] 2018-05-16 08:42
With Pouch 6.4.2. The database is created fine but the sync fails with this error after a download of around 50-100 MB.
InvalidStateError: Failed to execute 'objectStore' on 'IDBTransaction': The transaction finished.

I have attachments (Images/Videos) in the data to be synced. That could be causing the problem.

**Comment by daleharvey** [comment] 2018-05-16 08:47
As i said before that is a different bug, please avoid talking about other bugs and confusing the issue in this bug

**Comment by jareware** [comment] 2018-05-16 08:56
Got to `Sync Complete!` without issues on iOS 11.3.1 and

    Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1

with only this in console:

![screen shot 2018-05-16 at 11 52 11](https://user-images.githubusercontent.com/560055/40106898-a0d6a352-58ff-11e8-9d2a-0014b2514e8d.png)

**Comment by akowald** [comment] 2018-05-16 13:28
I got `Sync Complete!` as well, but that test site is running 7.0.0-prerelease. Could you let me know which branch to checkout for 6.4.3 and I'll give it another go. Sorry for pestering you but I cannot use 7 in prod, too unstable atm.

**Comment by mattjennings** [comment] 2018-05-16 17:28
Got to `Sync Complete` with same console as @jareware. iOS 11.3.1 on an iPhone 8

**Comment by ssured** [comment] 2018-05-17 07:15
Got Sync complete on iPad 11.4 public beta

**Comment by daleharvey** [comment] 2018-05-18 09:35
@rdwoodring or anyone else able to see any errors here?

**Comment by rdwoodring** [comment] 2018-05-18 09:45
I'll give it a whirl when I get into the office and can grab an ios device there. Sorry I didn't get a chance sooner. Updates to follow...

**Comment by johanbuys** [comment] 2018-05-21 08:34
iPad Pro
Using browser: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
Creating Databases
Posting Document
Syncing Data
Sync Complete!

I have the same issue on 6.4.3: Database has a global failure
UnknownError: Error preparing Blob/File data to be stored in object store

**Comment by daleharvey** [comment] 2018-05-21 10:17
ok so as far as I can tell we are all fixed here, if you can reproduce any fatal bug opening databases on an iphone with the latest version of pouchdb, speak now or forever hold your peace (not really, we can still fix it later)

**Closed** 2018-05-22 09:08 UTC

**Comment by daordonez11** [comment] 2020-10-09 14:51
Hello @daleharvey I've found a way of reproducing again this issue with iOS 14.0.1 and Pouchdb 7.1.1 copying the fix of @lifaon74 I made it work but I don't see i t officially and I don't see any PR or change done in 7.1.1+ versions. It is still "Error preparing Blob/File data to be stored in object store" do you want me to open a new issue explaining steps and other details? Or should I just use the new indexeddb adapter?
