### ISSUE TITLE
Issue storing and retrieving video files

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2909] opened 2014-10-21 15:15 UTC
http://goo.gl/W05hbq

http://stackoverflow.com/q/26425718/680742

**Comment by daleharvey** [comment] 2015-09-08 15:57
So I also cant reproduce, I did a working demo that mostly follows the steps you did @ http://paste.pouchdb.com/paste/o8w00a/ and havent had a problem, it may be an issue with the video files or your server setup, if you are still seeing issues or need help please feel free to file a new bug, but closing as working

**Closed by daleharvey** 2015-09-08 15:57 UTC
Labels: bug
