### ISSUE TITLE
Pouchdb attachments

### ISSUE THREAD

**Issue by jabina** [pouchdb/pouchdb#6638] opened 2017-07-21 18:48 UTC
### Issue
Write the description of the issue here

I have  documents with attachments... Sometimes pouchDB with attachments works really good. Sometimes it's not working -->(Mobile creates document that goes to syncgateway, pouchDB reads the changes from sync gateway and update the information to third party software). I am not really sending the attachment to third party, how to ignore these attachments in PouchDB. 

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.

**Comment by willholley** [comment] 2017-07-24 08:56
@jabina PouchDB compatibility with Couchbase Sync Gateway is patchy (nobody is actively maintaining Couchbase compatibility). Are you able to create a reproducible test case against CouchDB?

**Comment by daleharvey** [comment] 2017-07-24 10:04
Yup sync gateway is not supported, happy to take patches but not tracking issues, closing due to https://github.com/pouchdb/pouchdb/issues/5820

**Closed by daleharvey** 2017-07-24 10:04 UTC
