### ISSUE TITLE
Query about syncing deleted documents

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#4233] opened 2015-08-30 21:21 UTC
I had a query to understand exactly what happens when syncing deleted documents. If a document is marked as delete in CouchDB (Cloudant) what exactly does PouchDB sync?  I know that Couchdb does not really delete documents (until purge is called) but in a unpurged CouchDB does Pouch Sync everything? Is there a way to tell Pouch not to sync deleted documents?

**Comment by hrishiballal** [comment] 2015-08-30 21:38
I guess what I am asking is if there is a document with a large amount of data (5MB) in it and if I delete it in couchdb, what is synced in pouch? Just a tombstone that the id is deleted or the entire document and the tombstone?

**Comment by nolanlawson** [comment] 2015-08-30 22:02
If you delete a large document from database A and then replicate it to database B, then database B will only receive the tombstone. On the other hand, A will still have the large, old revision, which you can remove via compaction.

**Comment by daleharvey** [comment] 2015-09-03 14:02
And answered, if you have any more questions feel free to ask, but closing this issue out as its not a bug, cheers :)

**Closed by daleharvey** 2015-09-03 14:02 UTC

**Comment by CatchSandeepVaid** [comment] 2017-08-17 12:37
I observed if i delete a document ("deleted"=true") in couchdb and try to sync, it (not even tombstone) doesnt gets replicated to pouchdb. Is this a bug?

**Comment by CatchSandeepVaid** [comment] 2017-10-03 13:11
@nolanlawson - Will the tombstone be replicated from couchdb to pouchdb? I observed its not getting replicated and this may be the desired behaviour: My scenario is as follows:
Mobile 1 -> In case of conflict, i delete the conflicting revision (say 2-x) by using delete() API. This internally creates a new revision(say 3-x) as {"_id":"myId" , "_rev":"3-x", "_deleted":true} & we are referring to tombstone. Then the user does sync to couchdb. 

Mobile2 -> He syncs the data. He doesnt get _rev=3x. 

Is this the desired behaviour?
