### ISSUE TITLE
Firefox 54.0.1 throws error "Failed to open indexedDB, are you in private browsing mode?"

### ISSUE THREAD

**Issue by polarity** [pouchdb/pouchdb#6644] opened 2017-07-25 15:11 UTC
### Issue
Opening Database in Firefox 54.0.1 throws error "Failed to open indexedDB, are you in private browsing mode?" What im doing wrong here?

### Info
- Environment: Firefox 54.0.1
- Platform: OS X Yosemite 10.10.5
- Adapter: Indexed DB

### Reproduce
go to pouchdb.com, open console, type "new PouchDB('test')

![pouchdb the javascript database that syncs](https://user-images.githubusercontent.com/147424/28579127-05595950-715c-11e7-9776-ac7204c9d16e.jpg)

**Comment by maxalmonte14** [comment] 2017-08-26 22:03
I have the same issue, with 55.0.2 (64-bits) in Linux Mint 18 (based on Ubuntu 16.04), I don't have an idea why this is happening.

**Comment by honzajerabek** [comment] 2017-08-27 16:33
Same here, found around 30 users popping-up in my bug tracker, having this issue - went through them and they were all desktop operating systems and always Firefox 54 or 55

**Comment by maxalmonte14** [comment] 2017-08-28 12:52
I solved the problem changing some Firefox configuration. I had enabled the option "don't remember history", I just disable it and it works!

**Comment by fabiand** [comment] 2017-10-09 09:48
Any fix? I'm hitting this with hubpress

**Comment by jovankrunic** [comment] 2017-10-11 14:49
Same issue.

Info

Environment: Firefox ESR 52.4.0
Platform: Ubuntu 16.04

**Comment by wgrhstf** [comment] 2017-10-13 05:11
Same Problem on electron 1.8.1 Project. So Chromium is affected as well.

**Comment by jtlindsey** [comment] 2017-11-28 21:22
I've seen this same problem on Linux and OSX when more than one instance of the application using pouchdb is open on same workstation (other instance might be open in Chrome/Firefox in another work-space or in a hidden or minimized window).

**Comment by hans-helmut** [comment] 2017-12-06 21:43
Seems to be a problem with different versions of Firefox using the same profile. It was working for me with Firefox 52.5.0, but not with 57.0.1. After renameing ~/.mozilla and starting Firefox 57 first, it works, but when starting Firefox 52 again, the problem is back. My used OS is Linux, I tested pouchdb 6.3.4.

**Comment by daleharvey** [comment] 2018-01-15 12:45
Firefox most definitely doesnt support downgrading profiles, you can only open a profile with a firefox the same or newer version that created it, this will cause fairly obscure errors (should be getting fixed in firefox soon where you will be warned). Seeing https://github.com/localForage/localForage/issues/691 also having profile version issues and no other reproducable issues (working in 54 + 55 for me fine)

If anyone is still having issues could they describe how to reproduce without any downgrading firefox profiles and I will take another look, cheers

**Closed by daleharvey** 2018-01-15 12:45 UTC

**Comment by iworldoftravel** [comment] 2018-01-30 01:20
This happened to me on Windows 10 fresh install while following the tutorial. I didn't do anything with profiles.
